import { Chapter } from '@/lib/types';

/**
 * Kapitelstruktur des Moduls Konsumentenverhalten,
 * extrahiert aus dem hochgeladenen PDF (Studiengang Online-Marketing).
 */
export const chapters: Chapter[] = [
  {
    id: 'k1',
    index: 1,
    title: 'Einführung in das Konsumentenverhalten',
    subchapters: ['Begriffe und Entwicklung', 'Ziele des Konsumentenverhaltens', 'Konsum & Konsumenten'],
    keyIdeas: [
      'Konsumentenverhalten ist das Verhalten beim Kauf oder Konsum wirtschaftlicher Güter; im engeren Sinn das beobachtbare äußere Verhalten, im weiteren Sinn auch materielle und immaterielle Güter (z. B. Kino, Arzt, Wahl).',
      'Die wissenschaftliche Betrachtung begann in den 1920ern; etabliert wurde die Forschung nach dem 2. Weltkrieg mit dem Wandel vom Verkäufer- zum Käufermarkt – Folge war professionelles Marketing.',
      'Hauptziel: Konsumentenverhalten positiv im Sinne des eigenen Unternehmens beeinflussen – was, warum, wann, wie, wie oft und wo kauft der Kunde.',
      'Utilitaristischer Konsum stellt den praktischen Nutzen in den Vordergrund (z. B. familienfreundliches Auto), hedonistischer Konsum Fantasie und Emotionen (z. B. Sportwagen); Schnittmengen sind möglich.',
      'Als Konsument gilt, wer mindestens eine der Entscheidungsformen ausübt: Kaufentscheidung treffen, bezahlen oder konsumieren.',
    ],
    pdfPages: '1',
  },
  {
    id: 'k2',
    index: 2,
    title: 'Modelle des Konsumentenverhaltens',
    subchapters: ['Modellansätze (S-R / S-O-R)', 'Modellarten (Total-, Partial-, Phasenmodelle)', 'Determinanten des Konsumentenverhaltens'],
    keyIdeas: [
      'Behaviorismus erklärt Verhalten nur über Reize und Reaktionen (S-R-Modell); innere Prozesse bleiben unbeachtet – die Person ist eine „Black Box“.',
      'Der Neobehaviorismus ergänzt die Introspektion: S-O-R-Modell mit Stimulus, Organismus, Response; innere Prozesse werden als intervenierende Variablen berücksichtigt, sind aber nicht direkt beobachtbar.',
      'Stimuli wirken aus der Umwelt; marketingdominante Reize lassen sich in die 4 Ps unterteilen (Price, Product, Place, Promotion). Die Response ist direkt messbar (z. B. Verweildauer am POS, Kaufmenge, Cross-Buyings).',
      'Totalmodelle erklären das Verhalten ganzheitlich (didaktisch wertvoll, praktisch schwer anwendbar), Partialmodelle fokussieren einzelne Aspekte (praxistauglich, aber limitiert), Phasenmodelle teilen den Kaufprozess zeitlich ein (Vorkauf-, Kauf-, Nachkaufphase).',
      'Determinanten sind psychische, soziale, persönliche oder kulturelle Faktoren zur Erklärung des Konsumentenverhaltens; psychische Vorgänge laufen über aktivierende und kognitive Prozesse mit Innen- und Außenreizen.',
    ],
    pdfPages: '1–3',
  },
  {
    id: 'k3',
    index: 3,
    title: 'Aktivierung (Aktivierende Prozesse)',
    subchapters: ['Grundlagen der Aktivierung', 'Aktivierung des Konsumenten', 'Elaboration-Likelihood-Modell', 'Überzeugungsstrategien (Cialdini)'],
    keyIdeas: [
      'Aktivierung ist die Grunddimension aller Antriebsprozesse und macht Menschen leistungsbereit und -fähig; ohne Aktivierung kein Verhalten.',
      'Phasische Aktivierung ist zeitlich begrenzt und ermöglicht Fokus auf relevante Reize (Aufmerksamkeit); tonische Aktivierung betrifft längere Zeitintervalle und allgemeine Wachheit. Für das Marketing ist vor allem die phasische relevant.',
      'Die Lambda-Hypothese beschreibt den Zusammenhang von Aktivierung und Leistung mit einem optimalen Bereich; Überaktivierung ist selten, Unteraktivierung häufig.',
      'Aktivierende Stimuli werden in affektive (emotionale), physische und kognitive unterteilt; irritierende Reize und Schockwerbung können einen Bumerang-Effekt auslösen.',
      'Das Elaboration-Likelihood-Modell beschreibt zwei Überzeugungswege: den zentralen Weg über Fakten und Argumente (nachhaltige Einstellungsänderung) und den peripheren Weg über Hinweisreize wie Bilder, Musik, Testimonials (fragilere Änderung).',
      'Cialdinis sechs Überzeugungsstrategien: Reziprozität, Verpflichtung/Konsistenz, soziale Bewährtheit, Gefallen, Autorität, Verknappung.',
    ],
    pdfPages: '4–7',
  },
  {
    id: 'k4',
    index: 4,
    title: 'Emotionen, Motivation & Einstellung',
    subchapters: ['Emotionen', 'Motivation & Maslow', 'Einstellung (ABC-Modell)'],
    keyIdeas: [
      'Emotionen sind innere Erregungsvorgänge, die subjektiv als angenehm oder unangenehm erlebt werden; vier Dimensionen: Erregung, Richtung, Qualität, subjektives Bewusstsein.',
      'Basisemotionen sind angeboren (Izard: 10, u. a. Interesse, Freude, Überraschung; Plutchik: 8); Emotionen verbessern im Marketing die Informationsaufnahme und dienen als USP (Erlebnismarketing).',
      'Motivation ist Emotion mit Zielorientierung; Motive sind latente Zustände, Bedürfnisse gefühlte Mangelzustände, Triebe genetisch bedingte Motive ohne kognitive Komponente. Primäre Motive sind angeboren, sekundäre erlernt; intrinsisch von innen, extrinsisch von außen.',
      'Die Maslow-Pyramide ordnet Bedürfnisse in 5 Ebenen (physiologisch, Sicherheit, sozial, Wertschätzung, Selbstverwirklichung); Ebenen 1–3 sind Defizitbedürfnisse, Selbstverwirklichung ist unstillbar. Für Marketing sind Motive mittlerer Reichweite relevanter.',
      'Einstellung ist Motivation mit kognitiver Gegenstandsbeurteilung – das komplexeste und zeitlich stabilste Verhaltenskonstrukt. Das ABC-Modell zerlegt sie in Affekt, Behavior (Verhalten) und Cognition.',
      'Abgrenzungen: Meinung = verbalisierte Einstellung, Überzeugung = persistente kognitive Grundlage, Präferenz = relativierte Einstellung, Image = objektbezogener Analogbegriff, Vorurteile = schlecht begründete rigide Einstellungen.',
      'Die Verhaltenskonstrukte bauen aufeinander auf: Aktivierung → Emotion → Motivation → Einstellung (steigende zeitliche Beständigkeit und Komplexität).',
    ],
    pdfPages: '7–10',
  },
  {
    id: 'k5',
    index: 5,
    title: 'Kognitiver Prozess',
    subchapters: ['Kognition und Gedächtnis (Dreispeichermodell)', 'Lernen durch Konditionierung & kognitives Lernen'],
    keyIdeas: [
      'Das Dreispeichermodell (modales Gedächtnismodell) beschreibt Informationsaufnahme, -verarbeitung und -speicherung: sensorischer Speicher (Millisekunden), Kurzzeit-/Arbeitsspeicher (Minuten, Kapazität 7±2 Chunks, optimal 3–4) und Langzeitspeicher (quasi unbegrenzt, lebenslang).',
      'Nur Reize, die die Aufmerksamkeitsschwelle passieren, gelangen in den Kurzzeitspeicher; nicht weitergeleitete Eindrücke verblassen. Das Hirn speichert Informationen vor allem in Form von Geschichten.',
      'Lernen ist eine erfahrungsbedingte, relativ konsistente Verhaltensänderung – erklärt durch behavioristische (Konditionierung) und kognitive Lerntheorien.',
      'Klassische Konditionierung: Ein neutraler Stimulus wird mit einem bereits gelernten Reiz-Reaktions-Muster verknüpft (Pawlow); in der Werbung durch emotionales Aufladen von Marken. Instrumentelle (operante) Konditionierung: Lernen durch Verstärkung (Belohnung/Strafe) – wichtig für Habitualisierung und Internalisierung.',
      'Stimulusgeneralisierung: gleiche Reaktion auf ähnliche Reize (z. B. neue Kollektion ähnlicher Produkte); Reizdiskriminierung: unterschiedliche Reaktion – Abgrenzung von der Konkurrenz.',
      'Kognitives Lernen bildet oder modifiziert Wissenseinheiten (Schemata/semantische Netzwerke); hohe Verarbeitungstiefe steigert Gedächtnisleistung, aber auch kritische Auseinandersetzung.',
    ],
    pdfPages: '10–12',
  },
  {
    id: 'k6',
    index: 6,
    title: 'Weitere Einflüsse auf das Konsumentenverhalten',
    subchapters: ['Persönliche Einflussgrößen', 'Soziale Einflussgrößen', 'Kulturelle Einflussgrößen', 'Digitale Einflussgrößen'],
    keyIdeas: [
      'Die Persönlichkeit bildet den Grundrahmen für aktivierende Prozesse; Selbstkonzepttheorie: Motive, Gefühle, Werte, Wissen und Ziele bestimmen die Persönlichkeit. Das Big-Five-Modell umfasst Extraversion, Verträglichkeit, Gewissenhaftigkeit, Neurotizismus und Offenheit.',
      'Involvement ist der Grad der Beteiligung an der Informationsverarbeitung: low (z. B. Einwegfeuerzeug) vs. high (z. B. Photovoltaikanlage).',
      'Soziale Gruppen: primäre (Familie) und sekundäre Gruppen (Vereine, Parteien); Fremd-/Referenzgruppen prägen Verhalten stark, Meinungsführer beeinflussen Kaufentscheidungen über Mund-zu-Mund-Propaganda.',
      'Rollen im Kaufentscheidungsprozess: Initiator, Beeinflusser, Entscheider, Käufer, Nutzer.',
      'Lebensstil = individuelle/kollektive Orientierung an Werten und Zielen; Segmentierungsansätze: Sinus-Milieus, VALS-II, AIO-Konzept (Activities, Interests, Opinions). Kaufentscheidungen im Haushalt: autokratisch oder synkratisch.',
      'Kulturelle Einflussgrößen (soziale Schicht, Kultur, Subkultur) sind die schwächsten Einflussgrößen; Hofstedes Kulturdimensionen (u. a. Machtdistanz, Unsicherheitsvermeidung); Ethnomarketing passt den Marketing-Mix an ethnische Minderheiten an.',
      'Digitale Einflussgrößen gewinnen an Bedeutung; Microtargeting = Profilanalyse für individuelle Zielansprache.',
    ],
    pdfPages: '12–15',
  },
  {
    id: 'k7',
    index: 7,
    title: 'Der Kaufprozess',
    subchapters: ['Arten der Kaufentscheidung', 'Vorkaufphase', 'Kaufphase (POS)', 'Nachkauf-/Nutzungsphase', 'Methoden zur Preisbestimmung'],
    keyIdeas: [
      'Kaufentscheidungen werden nach Involvement unterteilt: impulsiv (Reiz ohne Kognition), habitualisiert (Gewohnheit, „Autopilot“), limitiert (Auswahl aus Alternativen mit vorhandenem Wissen) und extensiv (starke Informationssuche, hohes Involvement).',
      'Vorkaufphase: Zentral ist die Problemerkenntnis (Abweichung von Soll- und Istzustand) – über Bedarf oder Gelegenheiten; danach Informationssuche (intern/extern) und Evaluation von Alternativen.',
      'Evoked Set = Menge der bekannten Alternativen; Consideration Set = engere Auswahl daraus. Steigt das Risiko, steigen Dauer und Intensität der Evaluation.',
      'Kaufphase: Alternativenidentifikation → Intentionsentwicklung → Kauf; zwischen Intention und Kauf wirken Reize beschleunigend oder bremsend. Der POS wird über Verkaufsraumgestaltung, Verkaufsgespräch, Verbundkäufe/Cross-Buyings und Services optimiert.',
      'Nachkaufphase: Konsum → Evaluierung → ggf. Beschwerde → Entsorgung; wichtigste Phase für langfristige Kundenbeziehungen. Beschwerde = subjektiv empfundene Schädigung (nicht Reklamation).',
      'Preisbestimmung: direkte Methoden (Gabor-Granger: 5 Preispunkte + Kaufbereitschaftsskala; Van-Westendorp/Price-Sensitivity-Meter: 4 Preisfragen, Schnittpunkte ergeben Preisunter- und -obergrenze) und indirekte Methoden (Vickrey-Auktion, Conjoint-Analyse).',
      'Gebrochene Preise (10,99) wirken durch den Primacy-Effekt günstiger als runde.',
    ],
    pdfPages: '15–20',
  },
  {
    id: 'k8',
    index: 8,
    title: 'Vom Kunden zur Kundenorientierung und zum Kundenwert',
    subchapters: ['Kundenorientierung & Kundenzufriedenheit', 'Kundenbindung & Kundenwert'],
    keyIdeas: [
      'Die Erfolgskette der Kundenorientierung: Kundenorientierung → Kundenzufriedenheit → Kundenbindung → Kundenwert, moderiert durch unternehmensexterne und -interne Faktoren.',
      'Kundenzufriedenheit wirkt über Wiederkäufe, Cross-Buyings, geringere Preissensibilität und positive Mund-zu-Mund-Propaganda auf den Unternehmenserfolg.',
      'Nachkaufdissonanzen sind Störgefühle/Zweifel nach dem Kauf; Unternehmen sollten proaktiv handeln (Rückgaberecht, gratulierendes Begleitmaterial). Beschwerdemanagement nutzt Beschwerden als Chance.',
      'Zu viel Service kann schaden („Overservicing“ – der Kunde fühlt sich zu sehr umsorgt).',
      'Kundenbindung = positive Einstellung zur Bereitschaft künftiger Transaktionen; Formen: bedingte Loyalität (freiwillig), oberflächliche Loyalität (reine Wiederkäufer/Zwang wie Abos), Commitment (langfristige Bindung mit hoher Unzufriedenheitstoleranz).',
      'Ebenen der Kundenbindung: Organisations-/Unternehmensebene (B2B), Personenebene (Dienstleistungen), Leistungsebene (Konsumgüter).',
      'Variety Seeking: Kunden wechseln bei niedrigem Involvement trotz Zufriedenheit aus Streben nach Abwechslung.',
      'Kundenwert aus Unternehmenssicht: Beitrag des Kunden zu monetären und nicht-monetären Zielen; aus Nachfragersicht: Leistungswert, Markenwert, Beziehungswert.',
    ],
    pdfPages: '20–23',
  },
  {
    id: 'k9',
    index: 9,
    title: 'Konsumentenverhalten auf Dienstleistungsmärkten',
    subchapters: ['Kaufentscheidungsprozess bei Dienstleistungen', 'Service-Erfolgskette', 'Marktsegmentierung auf Dienstleistungsmärkten'],
    keyIdeas: [
      'Dienstleistungen haben drei Dimensionen: Potenzial-, Prozess- und Ergebnisdimension; die 4 Ls typologisieren Leistungen nach Integration, Interaktion, Individualisierung und Immaterialität (Mass Services, Professional Services, Speciality Services).',
      'Konsumphasenmodell: Vorkonsum-, Konsum- und Nachkonsumphase; die Beurteilungsproblematik (Qualität vor dem Kauf schwer einschätzbar) prägt die Vorkonsumphase – Sucheigenschaften, Vertrauen und Kostenvoranschläge helfen.',
      'In der Konsumphase gilt oft „Never change a running system“; je mehr wahrgenommene Kontrolle der Kunde im Interaktionsprozess hat, desto besser die Bewertung.',
      'Die Service-Erfolgskette: Aktivitäten des Dienstleistungsmarketings → psychologische Wirkungen (Zufriedenheit, Image, Qualitätswahrnehmung, Beziehungsqualität, Commitment, Risikowahrnehmung) → Verhaltenswirkungen (Bindung, Wiederkauf, Weiterempfehlung, Zusatzkauf) → ökonomischer Erfolg.',
      'Qualitätswahrnehmung ähnelt der Kundenzufriedenheit, ist aber globaler; Dreiecksverhältnis: Kunde, Dienstleister und Konkurrenz beeinflussen die Dienstleistungsqualität.',
      'Beim Dienstleistungserwerb ist das gefühlte Risiko höher als bei Sachgütern → proaktive Risikominimierung, z. B. Garantien.',
      'Segmentierungskriterien müssen u. a. messbar, kaufverhaltensrelevant, erreichbar, wirtschaftlich und zeitlich stabil sein – zeitliche Stabilität und Messbarkeit muss jedes Kriterium erfüllen. Benefit Segmentation = Segmentierung nach Nutzenerwartungen; Unterschied konsumtive vs. investive Dienstleistungen.',
    ],
    pdfPages: '23–27',
  },
  {
    id: 'k10',
    index: 10,
    title: 'Organisatorisches Kaufverhalten',
    subchapters: ['Grundlagen des organisationalen Kaufverhaltens', 'Modell organisationaler Kaufentscheidungen (Buying Center)'],
    keyIdeas: [
      'Organisationales Kaufverhalten umfasst den Entscheidungsprozess von der Bedarfserstellung bis zur Qualitätsbeurteilung; Kaufentscheidungen sind oft multipersonal und extensiv, Fehlentscheidungen haben größere Konsequenzen.',
      'B2B-Charakteristika: wenige Anbieter und Nachfrager, vom B2C-Markt abhängiger Bedarf, stabile Marktpartnerschaften, lange Entscheidungsprozesse, intensive Verhandlungen, kurze Absatzwege (Direktvertrieb), hoher Individualisierungsgrad, hohe Imagebedeutung.',
      'Geschäftsbeziehungen sind das A und O; Phasen: Aufmerksamkeit → Erkundung → Ausweitung → Bindung → Auflösung.',
      'Drei Arten der organisationalen Kaufentscheidung: identischer Wiederkauf (Routine), modifizierter Wiederkauf (abgewandelt), Erstkauf (risikohaft, ohne Erfahrung).',
      'Prozessphasen (Erstkauf): Problemerkennung → Bedarfsbeschreibung → Festlegung der Eigenschaften → Lieferantensuche → Angebotseinholung → Lieferantenauswahl → Bestellverfahren → Qualitäts-/Leistungsprüfung.',
      'Das Buying Center ist der Sammelbegriff für alle am Einkauf beteiligten Personen (keine eigene Abteilung) mit Rollen wie Initiator, Beeinflusser, Gatekeeper.',
      'Einflüsse auf den organisationalen Kaufprozess: Umweltdeterminanten (z. B. Stand der Technik), innerorganisationale, interpersonale und intrapersonale Determinanten (z. B. Autorität, Hierarchiestellung).',
    ],
    pdfPages: '27–32',
  },
];
