import { Question } from '@/lib/types';

/**
 * Bild- und diagrammbezogene Fragen für Bild-Lernmodus und Bild-Prüfmodus.
 * Jede Frage referenziert eine Figure (figureId) und wird mit dem Bild angezeigt.
 */
export const questionsImages: Question[] = [
  {
    id: 'qi-sor-1', chapterId: 'k2', figureId: 'f-sor', type: 'image_assignment', goal: 'understanding', difficulty: 1,
    prompt: 'Ordne die Variablentypen des S-O-R-Modells den Elementen zu.',
    pairs: [
      { left: 'Stimulus', right: 'Unabhängige Variable – wahrnehmbarer Reiz' },
      { left: 'Organismus', right: 'Intervenierende Variable – nicht beobachtbare Prozesse im Individuum' },
      { left: 'Response', right: 'Abhängige Variable – messbare Verhaltensreaktion' },
    ],
    explanation: 'Das S-O-R-Modell: Stimulus (unabhängig) wirkt über den Organismus (intervenierend, nicht beobachtbar) auf die Response (abhängig, messbar).',
    source: 'Abbildung S-O-R-Modell, PDF S. 1', conceptIds: ['c-neobehaviorismus'],
  },
  {
    id: 'qi-sor-2', chapterId: 'k2', figureId: 'f-sor', type: 'image_open', goal: 'understanding', difficulty: 2,
    prompt: 'Erkläre anhand der Abbildung das Prinzip des S-O-R-Modells und warum der mittlere Block besonders ist.',
    rubric: [
      { point: 'Stimulus = wahrnehmbarer Reiz (Input)', keywords: ['stimulus', 'reiz', 'input'] },
      { point: 'Organismus = nicht beobachtbare innere Prozesse', keywords: ['organismus', 'nicht beobachtbar', 'innere', 'black box'] },
      { point: 'Response = messbare Verhaltensreaktion', keywords: ['response', 'messbar', 'reaktion', 'verhalten'] },
      { point: 'Neobehaviorismus / intervenierende Variablen', keywords: ['neobehaviorismus', 'intervenierend'], weight: 0.5 },
    ],
    modelAnswer: 'Ein wahrnehmbarer Reiz (Stimulus) trifft auf den Konsumenten. Im Organismus laufen nicht beobachtbare innere Prozesse ab (z. B. Wahrnehmung, Emotion, Einstellung) – dieser Block ist besonders, weil er nicht direkt messbar ist und als intervenierende Variable modelliert wird (Neobehaviorismus). Das Ergebnis ist die messbare Response, z. B. der Kauf.',
    explanation: 'Kern: Der Organismus bleibt eine „Black Box“, wird aber – anders als im Behaviorismus – mitgedacht.',
    source: 'Abbildung S-O-R-Modell, PDF S. 1', conceptIds: ['c-neobehaviorismus'],
  },
  {
    id: 'qi-lambda-1', chapterId: 'k3', figureId: 'f-lambda', type: 'image_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Was zeigt die x-Achse des Diagramms zur Lambda-Hypothese?',
    options: ['Den Aktivierungsgrad von Schlaf bis Panik', 'Die Zeit in Minuten', 'Den Preis eines Produkts', 'Die Anzahl der Werbekontakte'],
    correctOptions: [0],
    explanation: 'x-Achse: Aktivierung (von Schlaf bis Panik); y-Achse: Leistungsfähigkeit. Die Kurve zeigt den optimalen Aktivierungsbereich in der Mitte.',
    source: 'Abbildung Lambda-Hypothese, PDF S. 5', conceptIds: ['c-lambda'],
  },
  {
    id: 'qi-lambda-2', chapterId: 'k3', figureId: 'f-lambda', type: 'image_open', goal: 'application', difficulty: 3,
    prompt: 'Interpretiere die Kurve: Warum können zu grelle Farben, zu laute Musik oder zu viel Gedränge im Geschäft schaden? Beziehe dich auf beide Kurvenäste.',
    rubric: [
      { point: 'Aufsteigender Ast: moderate Reize steigern Leistung/Aktivierung', keywords: ['steig', 'moderat', 'optimal', 'aufsteigend'] },
      { point: 'Nach dem Optimum fällt die Leistung (Überaktivierung)', keywords: ['ueberaktivierung', 'faellt', 'sinkt', 'abfall', 'panik'] },
      { point: 'Zu intensive Reize (grell, laut, Gedränge) führen in den absteigenden Ast', keywords: ['grell', 'laut', 'gedraenge', 'intensiv', 'zu viel'] },
      { point: 'Praxis: Unteraktivierung ist häufiger / Balance nötig', keywords: ['unteraktivierung', 'balance', 'selten', 'schwelle'], weight: 0.5 },
    ],
    modelAnswer: 'Die Kurve steigt zunächst: Moderate Reize (Farben, Musik, Düfte) erhöhen die Aktivierung und damit die Leistungsfähigkeit bzw. Ansprechbarkeit der Kunden. Nach dem optimalen Bereich kippt die Kurve jedoch: Zu grelle Farben, zu laute Musik, zu intensive Düfte oder zu viel Gedränge überaktivieren – die Leistungsfähigkeit sinkt bis hin zur Panik. Deshalb schaden übertriebene Reize. Praktisch ist allerdings Unteraktivierung das häufigere Problem.',
    explanation: 'Umgekehrtes U: Es gibt ein Optimum, kein „je mehr, desto besser“.',
    source: 'Abbildung Lambda-Hypothese, PDF S. 5', conceptIds: ['c-lambda'],
  },
  {
    id: 'qi-elm-1', chapterId: 'k3', figureId: 'f-elm', type: 'image_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Laut Abbildung: Was passiert, wenn Fähigkeit und Motivation zum aufmerksamen Zuhören NICHT vorhanden sind?',
    options: [
      'Überzeugung erfolgt über periphere Hinweisreize – die Einstellungsänderung ist anfällig für Veränderung',
      'Es findet gar keine Überzeugung statt',
      'Überzeugung erfolgt über starke Argumente – die Änderung ist langanhaltend',
      'Der Konsument wird automatisch zum Kauf gezwungen',
    ],
    correctOptions: [0],
    explanation: 'Nein-Pfad = peripherer Weg: Überzeugung durch periphere Hinweisreize; die resultierende Einstellungsänderung ist anfällig für Veränderung. Ja-Pfad = zentraler Weg mit stabiler Änderung.',
    source: 'Abbildung ELM, PDF S. 7', conceptIds: ['c-elm'],
  },
  {
    id: 'qi-maslow-1', chapterId: 'k4', figureId: 'f-maslow', type: 'image_assignment', goal: 'fact', difficulty: 2,
    prompt: 'Ordne die Maslow-Ebenen (von unten nach oben) den Inhalten zu.',
    pairs: [
      { left: 'Ebene 1 (Basis)', right: 'Physiologische Bedürfnisse: Überleben, Essen, Trinken, Wärme' },
      { left: 'Ebene 2', right: 'Sicherheitsbedürfnisse: Versicherungen, Kündigungsschutz, Dach über dem Kopf' },
      { left: 'Ebene 3', right: 'Soziale Bedürfnisse: Liebe, Freundschaft, Gruppenzugehörigkeit' },
      { left: 'Ebene 4', right: 'Wertschätzung: Anerkennung, Unabhängigkeit, Freiheit' },
      { left: 'Ebene 5 (Spitze)', right: 'Selbstverwirklichung: Individualität, Güte, Gerechtigkeit' },
    ],
    explanation: 'Reihenfolge von unten: physiologisch → Sicherheit → sozial → Wertschätzung → Selbstverwirklichung.',
    source: 'Abbildung Maslow-Pyramide, PDF S. 9', conceptIds: ['c-maslow'],
  },
  {
    id: 'qi-maslow-2', chapterId: 'k4', figureId: 'f-maslow', type: 'image_open', goal: 'understanding', difficulty: 2,
    prompt: 'Erkläre anhand der Pyramide den Unterschied zwischen Defizitbedürfnissen und dem Selbstverwirklichungsbedürfnis.',
    rubric: [
      { point: 'Ebenen 1–3 = Defizitbedürfnisse', keywords: ['defizit', 'ebenen 1', 'untere'] },
      { point: 'Sinkende Motivationskraft bei Befriedigung', keywords: ['sinkende', 'motivational', 'befriedig', 'vorhandensein'] },
      { point: 'Selbstverwirklichung ist unstillbar', keywords: ['unstillbar', 'nie', 'unersaettlich'] },
      { point: 'Wird erst angestrebt, wenn Grundbedürfnisse befriedigt sind', keywords: ['erst dann', 'grundlegend', 'befriedigt', 'vorher'] },
    ],
    modelAnswer: 'Die unteren drei Ebenen (physiologische, Sicherheits- und soziale Bedürfnisse) sind Defizitbedürfnisse: Sobald die entsprechenden Güter vorhanden sind, sinkt ihre motivationale Kraft. Das Selbstverwirklichungsbedürfnis an der Spitze ist dagegen unstillbar – es kann erst angestrebt werden, wenn alle grundlegenden Bedürfnisse befriedigt sind, verliert aber nie an Antriebskraft.',
    explanation: 'Defizit- vs. Wachstumslogik ist der Kern der Pyramide.',
    source: 'Abbildung Maslow-Pyramide, PDF S. 9', conceptIds: ['c-maslow'],
  },
  {
    id: 'qi-konstrukte-1', chapterId: 'k4', figureId: 'f-konstrukte', type: 'image_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Die Abbildung zeigt die Verhaltenskonstrukte übereinander. Was kommt bei jeder Stufe nach oben hinzu?',
    options: [
      'Jeweils eine kognitive Komponente (Interpretation → Zielorientierung → Gegenstandsbeurteilung)',
      'Jeweils mehr zentralnervöse Erregung',
      'Jeweils ein neuer Reiztyp',
      'Jeweils eine soziale Einflussgröße',
    ],
    correctOptions: [0],
    explanation: 'Aktivierung + Interpretation = Emotion; Emotion + Zielorientierung = Motivation; Motivation + Gegenstandsbeurteilung = Einstellung. Nach oben steigen Beständigkeit und Komplexität.',
    source: 'Abbildung Verhaltenskonstrukte, PDF S. 10', conceptIds: ['c-konstrukt-hierarchie'],
  },
  {
    id: 'qi-gedaechtnis-1', chapterId: 'k5', figureId: 'f-gedaechtnis', type: 'image_assignment', goal: 'fact', difficulty: 2,
    prompt: 'Ordne die Speicher den Kennwerten aus der Abbildung zu.',
    pairs: [
      { left: 'Sensorischer Speicher', right: 'Speicherdauer: Millisekunden – Informationen „verblassen“ schnell' },
      { left: 'Kurzzeit-/Arbeitsspeicher', right: 'Speicherdauer: Minuten – Kapazität 7±2 Chunks (optimal 3–4)' },
      { left: 'Langzeitspeicher', right: 'Speicherdauer: lebenslang – Kapazität quasi unbegrenzt' },
    ],
    explanation: 'Die drei Speicher unterscheiden sich in Dauer und Kapazität; Übergänge: Wahrnehmung/Aufmerksamkeit bzw. Lernen/Memorieren.',
    source: 'Abbildung Gedächtnismodell, PDF S. 11', conceptIds: ['c-dreispeicher'],
  },
  {
    id: 'qi-gedaechtnis-2', chapterId: 'k5', figureId: 'f-gedaechtnis', type: 'image_open', goal: 'understanding', difficulty: 3,
    prompt: 'Beschreibe anhand der Abbildung den Weg einer Werbebotschaft vom Umweltreiz bis ins Langzeitgedächtnis. Benenne die Übergänge zwischen den Speichern.',
    rubric: [
      { point: 'Umweltreiz → sensorischer Speicher (Reizexposition/-aufnahme)', keywords: ['umweltreiz', 'sensorisch', 'reizexposition', 'reizaufnahme', 'sinne'] },
      { point: 'Übergang 1: Wahrnehmung/Aufmerksamkeit', keywords: ['wahrnehmung', 'aufmerksamkeit', 'schwelle'] },
      { point: 'Kurzzeitspeicher: erkennen, verstehen, bewerten, entscheiden', keywords: ['kurzzeit', 'arbeitsspeicher', 'erkennen', 'verstehen', 'bewerten'] },
      { point: 'Übergang 2: Lernen/Memorieren (Rückweg: Abrufen/Vergessen)', keywords: ['lernen', 'memorieren', 'abrufen', 'vergessen'] },
      { point: 'Langzeitspeicher: Wissen, Bedeutung, Vorstellung', keywords: ['langzeit', 'wissen', 'bedeutung', 'lebenslang'] },
    ],
    modelAnswer: 'Die Werbebotschaft trifft als Umweltreiz auf die Sinne und wird im sensorischen Speicher für Millisekunden gehalten. Nur wenn sie die Wahrnehmungs-/Aufmerksamkeitsschwelle passiert, gelangt sie in den Kurzzeit-/Arbeitsspeicher, wo sie erkannt, verstanden, bewertet und entschieden wird (Kapazität 7±2 Chunks, Minuten). Durch Lernen/Memorieren wird sie in den Langzeitspeicher transferiert (Wissen, Bedeutung, Vorstellung – lebenslang); über Abrufen/Vergessen läuft der Rückweg. Das Zusammenspiel von Kurzzeit- und Langzeitspeicher beeinflusst das Verhalten.',
    explanation: 'Die Übergänge (Aufmerksamkeit; Memorieren/Abrufen) sind die kritischen Stellen für das Marketing.',
    source: 'Abbildung Gedächtnismodell, PDF S. 11', conceptIds: ['c-dreispeicher', 'c-kurzzeitspeicher'],
  },
  {
    id: 'qi-rollen-1', chapterId: 'k6', figureId: 'f-kaufrollen', type: 'image_choice', goal: 'application', difficulty: 2,
    prompt: 'In der Abbildung kauft die Mutter das Produkt, der Vater entscheidet. Wer ist im Beispiel der Nutzer?',
    options: ['Der Sohn', 'Die Tochter', 'Der Onkel', 'Die Mutter'],
    correctOptions: [0],
    explanation: 'Im Beispiel: Tochter = Initiator, Onkel = Beeinflusser, Vater = Entscheider, Mutter = Käufer, Sohn = Nutzer.',
    source: 'Abbildung Kaufrollen, PDF S. 14', conceptIds: ['c-kaufrollen'],
  },
  {
    id: 'qi-matrix-1', chapterId: 'k7', figureId: 'f-kaufmatrix', type: 'image_assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordne die Quadranten der Involvement-Matrix den Kaufentscheidungsarten zu.',
    pairs: [
      { left: 'Emotional hoch, kognitiv niedrig', right: 'Impulsive Kaufentscheidung' },
      { left: 'Emotional hoch, kognitiv hoch', right: 'Extensive Kaufentscheidung' },
      { left: 'Emotional niedrig, kognitiv niedrig', right: 'Habitualisierte Kaufentscheidung' },
      { left: 'Emotional niedrig, kognitiv hoch', right: 'Limitierte Kaufentscheidung' },
    ],
    explanation: 'Die Matrix kombiniert emotionales (y) und kognitives (x) Involvement: impulsiv, extensiv, habitualisiert, limitiert.',
    source: 'Abbildung Kaufentscheidungsarten, PDF S. 17', conceptIds: ['c-kaufarten', 'c-involvement'],
  },
  {
    id: 'qi-matrix-2', chapterId: 'k7', figureId: 'f-kaufmatrix', type: 'image_open', goal: 'application', difficulty: 3,
    prompt: 'Positioniere folgende Käufe in der Matrix und begründe kurz: (a) tägliches Brötchenholen beim selben Bäcker, (b) Hauskauf, (c) Schokoriegel an der Kasse, (d) Auswahl einer Käsesorte im Supermarkt.',
    rubric: [
      { point: '(a) habitualisiert – Gewohnheit, beide Involvements niedrig', keywords: ['habitualisiert', 'gewohnheit', 'autopilot'] },
      { point: '(b) extensiv – beide Involvements hoch, intensive Suche', keywords: ['extensiv', 'hoch', 'informationssuche'] },
      { point: '(c) impulsiv – emotional getrieben, kaum Kognition', keywords: ['impulsiv', 'emotional', 'ohne nachdenken', 'kasse'] },
      { point: '(d) limitiert – kognitive Auswahl aus bekannten Alternativen', keywords: ['limitiert', 'alternativen', 'wissen', 'auswahl'] },
    ],
    modelAnswer: '(a) Habitualisiert: Gewohnheitskauf im Autopilot – emotionales und kognitives Involvement niedrig. (b) Extensiv: Hauskauf involviert stark emotional und kognitiv, mit intensivem Informationssuchprozess. (c) Impulsiv: Der Schokoriegel wird durch den Reiz an der Kasse fast ohne Kognition gekauft – emotional hoch. (d) Limitiert: Die Käseauswahl erfolgt kognitiv aus einer bekannten Alternativenmenge, emotional wenig involviert.',
    explanation: 'Die vier Beispiele decken alle Quadranten ab – genau die Skript-Beispiele.',
    source: 'Abbildung Kaufentscheidungsarten, PDF S. 17', conceptIds: ['c-kaufarten'],
  },
  {
    id: 'qi-phasen-1', chapterId: 'k7', figureId: 'f-phasenmodell', type: 'image_assignment', goal: 'fact', difficulty: 2,
    prompt: 'Ordne die Prozessschritte der richtigen Phase des Kaufprozesses zu.',
    pairs: [
      { left: 'Problemerkennung & Informationssuche', right: 'Vorkaufphase' },
      { left: 'Alternativenidentifikation & Intentionsentwicklung', right: 'Kaufphase' },
      { left: 'Konsum, Evaluierung, Beschwerde, Entsorgung', right: 'Nachkauf-/Nutzungsphase' },
    ],
    explanation: 'Dreigliedriges Phasenmodell: Vorkauf- (Problem, Suche, Evaluation), Kauf- (Identifikation, Intention, Kauf) und Nachkaufphase (Konsum bis Entsorgung).',
    source: 'Abbildung Phasenmodell, PDF S. 18', conceptIds: ['c-phasenmodelle', 'c-kaufphase', 'c-nachkaufphase'],
  },
  {
    id: 'qi-problem-1', chapterId: 'k7', figureId: 'f-problemerkenntnis', type: 'image_open', goal: 'understanding', difficulty: 2,
    prompt: 'Die Abbildung zeigt drei Verläufe von Ideal- und Istzustand. Erkläre den Unterschied zwischen „Wahrnehmung der Gelegenheit“ und „Wahrnehmung des Bedarfs“.',
    rubric: [
      { point: 'Gelegenheit: Idealzustand steigt (bessere Produkte verfügbar)', keywords: ['ideal steigt', 'gelegenheit', 'bessere', 'verschoben'] },
      { point: 'Bedarf: Istzustand sinkt (Produkt defekt/verbraucht)', keywords: ['ist sinkt', 'bedarf', 'defekt', 'verbraucht', 'mangel'] },
      { point: 'Beide erzeugen eine Soll-Ist-Differenz = Problem', keywords: ['differenz', 'abweichung', 'problem', 'soll'] },
      { point: 'Differenz muss groß genug sein', keywords: ['gross genug', 'wahrgenommen', 'schwelle'], weight: 0.5 },
    ],
    modelAnswer: 'Bei der Wahrnehmung der Gelegenheit verschiebt sich der Idealzustand nach oben – z. B. bieten neue Produkte eine bessere Leistung, und man will den neuen Idealzustand erreichen. Bei der Wahrnehmung des Bedarfs sinkt der Istzustand unter das Ideal – z. B. ist ein Produkt verbraucht oder defekt. In beiden Fällen entsteht eine Differenz zwischen Soll und Ist, die als Problem wahrgenommen wird – sofern sie groß genug ist.',
    explanation: 'Zwei Wege zur Problemerkenntnis: Ideal steigt vs. Ist sinkt.',
    source: 'Abbildung Problemerkenntnis, PDF S. 18', conceptIds: ['c-problemerkenntnis'],
  },
  {
    id: 'qi-psm-1', chapterId: 'k7', figureId: 'f-psm', type: 'image_choice', goal: 'understanding', difficulty: 3,
    prompt: 'Wie wird im Price-Sensitivity-Meter die Preisuntergrenze bestimmt?',
    options: [
      'Schnittpunkt der Kurven „zu billig“ und „relativ hoch“',
      'Schnittpunkt der Kurven „noch akzeptabel“ und „zu teuer“',
      'Maximum der Kurve „zu teuer“',
      'Der niedrigste getestete Preis',
    ],
    correctOptions: [0],
    explanation: 'Preisuntergrenze = Schnittpunkt „zu billig/zu günstig“ × „relativ hoch“; Preisobergrenze = Schnittpunkt „noch akzeptabel“ × „zu teuer“. Dazwischen liegt der akzeptable Bereich.',
    source: 'Abbildung PSM, PDF S. 22', conceptIds: ['c-van-westendorp'],
  },
  {
    id: 'qi-psm-2', chapterId: 'k7', figureId: 'f-psm', type: 'image_open', goal: 'application', difficulty: 3,
    prompt: 'Erkläre anhand des Diagramms, wie ein Unternehmen den akzeptablen Preisbereich für sein Produkt ermittelt. Benenne die Achsen und die relevanten Kurven.',
    rubric: [
      { point: 'Achsen: Preis (x) und Prozent der Befragten (y)', keywords: ['achse', 'preis', 'prozent', 'befragten', 'kumuliert'] },
      { point: 'Vier Fragen/Kurven: zu billig, noch günstig, relativ hoch, zu teuer', keywords: ['zu billig', 'zu teuer', 'relativ hoch', 'guenstig', 'vier'] },
      { point: 'Untergrenze: Schnittpunkt zu billig × relativ hoch', keywords: ['untergrenze', 'schnittpunkt'] },
      { point: 'Obergrenze: Schnittpunkt noch akzeptabel × zu teuer; Bereich dazwischen akzeptabel', keywords: ['obergrenze', 'akzeptabel', 'dazwischen', 'bereich'] },
    ],
    modelAnswer: 'Auf der x-Achse ist der Preis abgetragen, auf der y-Achse der (kumulierte) Prozentanteil der Befragten. Aus den vier Van-Westendorp-Fragen entstehen vier Kurven: „zu billig“, „noch günstig“, „relativ hoch“ und „zu teuer“. Die Preisuntergrenze liegt am Schnittpunkt von „zu billig“ und „relativ hoch“, die Preisobergrenze am Schnittpunkt von „noch akzeptabel/günstig“ und „zu teuer“. Der (schattierte) Bereich zwischen beiden Grenzen ist der akzeptable Preisbereich, in dem das Unternehmen seinen Preis positionieren sollte.',
    explanation: 'PSM liefert einen Preisbereich, keinen Einzelpreis.',
    source: 'Abbildung PSM, PDF S. 22', conceptIds: ['c-van-westendorp'],
  },
  {
    id: 'qi-kette-1', chapterId: 'k8', figureId: 'f-erfolgskette', type: 'image_assignment', goal: 'fact', difficulty: 1,
    prompt: 'Bringe die Glieder der Erfolgskette in die richtige Reihenfolge (1 = Anfang).',
    pairs: [
      { left: '1. Glied', right: 'Kundenorientierung' },
      { left: '2. Glied', right: 'Kundenzufriedenheit' },
      { left: '3. Glied', right: 'Kundenbindung' },
      { left: '4. Glied', right: 'Kundenwert' },
    ],
    explanation: 'Erfolgskette: Kundenorientierung → Kundenzufriedenheit → Kundenbindung → Kundenwert; moderiert durch externe und interne Faktoren (oben/unten in der Abbildung).',
    source: 'Abbildung 19, PDF S. 23', conceptIds: ['c-erfolgskette'],
  },
  {
    id: 'qi-zonen-1', chapterId: 'k8', figureId: 'f-zufriedenheit-wert', type: 'image_open', goal: 'understanding', difficulty: 3,
    prompt: 'Erkläre die vier Zonen der Abbildung „Kundenzufriedenheit und Unternehmenswert“ – und warum die gestrichelte Kurve am Ende nach unten zeigt.',
    rubric: [
      { point: 'Zone der Enttäuschung: Erwartungen enttäuscht → Wert sinkt', keywords: ['enttaeuschung', 'enttaeuscht', 'sinkt'] },
      { point: 'Indifferenzzone: Erwartungen erfüllt → neutral', keywords: ['indifferenz', 'erfuellt', 'neutral'] },
      { point: 'Zone der Begeisterung: Erwartungen übertroffen → Wert steigt stark', keywords: ['begeisterung', 'uebertroffen', 'steigt'] },
      { point: 'Zone der Übertreibung/Overservicing: zu viel Service kippt ins Negative', keywords: ['uebertreibung', 'overservicing', 'zu viel service', 'umsorgt'] },
    ],
    modelAnswer: 'In der Zone der Enttäuschung (Erwartungen enttäuscht) sinkt der Unternehmenswert stark. In der Indifferenzzone (Erwartungen erfüllt) bleibt die Wirkung neutral. In der Zone der Begeisterung (Erwartungen übertroffen) steigt der Wert überproportional. Die gestrichelte Kurve zeigt die Zone der Übertreibung („Overservicing“): Noch mehr Service steigert den Wert nicht weiter, sondern kann ihn senken – der Kunde fühlt sich zu sehr umsorgt (Beispiel: ein zweiter Kellner).',
    explanation: 'Begeisterung lohnt sich – aber nur bis zur Übertreibungsgrenze.',
    source: 'Abbildung 20, PDF S. 24', conceptIds: ['c-kundenzufriedenheit'],
  },
  {
    id: 'qi-4ls-1', chapterId: 'k9', figureId: 'f-4ls', type: 'image_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Welcher Servicetyp weist laut Abbildung die HÖCHSTEN Ausprägungen bei Integration, Interaktion und Individualisierung auf?',
    options: ['Speciality Services (z. B. Rechtsberatung)', 'Mass Services (z. B. Reinigung)', 'Professional Services (z. B. Friseur)', 'Alle gleich'],
    correctOptions: [0],
    explanation: 'Speciality Services (z. B. Rechtsberatung) haben hohe Ausprägungen aller 4 Ls; Mass Services (Reinigung) niedrige, Professional Services (Friseur) mittlere.',
    source: 'Abbildung 4 Ls, PDF S. 26', conceptIds: ['c-4ls'],
  },
  {
    id: 'qi-servicekette-1', chapterId: 'k9', figureId: 'f-service-kette', type: 'image_assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordne die Beispiele den Stufen der Service-Erfolgskette zu.',
    pairs: [
      { left: 'Psychologische Wirkung', right: 'Kundenzufriedenheit, Image, Qualitätswahrnehmung' },
      { left: 'Verhaltenswirkung', right: 'Kundenbindung, Wiederkauf, Weiterempfehlung' },
      { left: 'Endergebnis', right: 'Ökonomischer Erfolg' },
    ],
    explanation: 'Kette: Marketingaktivitäten → psychologische Wirkungen (im Kopf) → Verhaltenswirkungen (sichtbares Handeln) → ökonomischer Erfolg.',
    source: 'Abbildung 22, PDF S. 27', conceptIds: ['c-service-erfolgskette'],
  },
  {
    id: 'qi-orgmodell-1', chapterId: 'k10', figureId: 'f-org-modell', type: 'image_open', goal: 'understanding', difficulty: 3,
    prompt: 'Beschreibe anhand der Abbildung die drei Blöcke des Modells organisationaler Kaufentscheidungen und ihr Zusammenwirken.',
    rubric: [
      { point: 'Umfeld: Marketinganreize (4 Ps) + sonstige Anreize (Wirtschaft, Technologie, Politik, Kultur, Wettbewerb)', keywords: ['umfeld', 'anreize', 'marketing', 'wirtschaft', 'technologie', 'politik', 'wettbewerb'] },
      { point: 'Organisation als Käufer: Buying Center + Kaufentscheidungsprozess', keywords: ['buying center', 'organisation', 'kaufentscheidungsprozess'] },
      { point: 'Einflüsse: einzelne Personen, Zusammenwirken, Organisation', keywords: ['einzelnen', 'zusammenwirken', 'einfluessen', 'personen'] },
      { point: 'Handeln des Käufers: Produktwahl, Stammlieferant, Bestell-/Liefer-/Zahlungsbedingungen', keywords: ['handeln', 'stammlieferant', 'bestellmenge', 'lieferbedingungen', 'zahlungsbedingungen', 'kaufentscheidung'] },
    ],
    modelAnswer: 'Block 1 (Umfeld): Auf die Organisation wirken Anreize aus dem Marketing (Produkt, Preis, Platzierung, Promotion) und sonstige Anreize (Wirtschaft, Technologie, Politik, Kultur, Wettbewerb). Block 2 (Organisation als Käufer): Im Buying Center läuft der Kaufentscheidungsprozess ab – beeinflusst von den einzelnen handelnden Personen, ihrem Zusammenwirken und der Organisation selbst. Block 3 (Handeln des Käufers): Ergebnis sind konkrete Entscheidungen – Produkt/Dienstleistung, ggf. Stammlieferant, Bestellmengen, Liefer-, Kundendienst- und Zahlungsbedingungen.',
    explanation: 'Das Modell ist die organisationale Entsprechung des S-O-R-Gedankens: Umfeld → Organisation (Black Box mit Buying Center) → Handeln.',
    source: 'Abbildung Modell org. Kaufentscheidungen, PDF S. 31', conceptIds: ['c-buying-center', 'c-org-kaufverhalten'],
  },
  {
    id: 'qi-total-1', chapterId: 'k2', figureId: 'f-totalmodell', type: 'image_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Welche Aussage über das abgebildete Totalmodell ist korrekt?',
    options: [
      'Es verbindet Informationsverarbeitung und Entscheidungsprozess mit Umwelteinflüssen und individuellen Charakteristika – didaktisch wertvoll, praktisch schwer anwendbar',
      'Es beschränkt sich bewusst auf wenige, besonders einflussreiche Variablen',
      'Es beschreibt nur die zeitliche Abfolge des Kaufprozesses',
      'Es ist das Standardwerkzeug der Marketingpraxis',
    ],
    correctOptions: [0],
    explanation: 'Totalmodelle erklären das Konsumentenverhalten ganzheitlich (Input → Informationsverarbeitung → Entscheidungsprozess, plus Umwelteinflüsse und individuelle Charakteristika). Sie sind didaktisch wertvoll, aber praktisch schlecht anwendbar – das ist die Stärke der Partialmodelle.',
    source: 'Abbildung Totalmodell, PDF S. 2', conceptIds: ['c-totalmodelle'],
  },
  {
    id: 'qi-partial-1', chapterId: 'k2', figureId: 'f-partialmodell', type: 'image_assignment', goal: 'fact', difficulty: 1,
    prompt: 'Bringe die Kette des abgebildeten Partialmodells in die richtige Reihenfolge.',
    pairs: [
      { left: '1. Schritt', right: 'Produktwissen' },
      { left: '2. Schritt', right: 'Einstellung' },
      { left: '3. Schritt', right: 'Kaufabsicht' },
      { left: '4. Schritt', right: 'Kauf' },
    ],
    explanation: 'Das Beispiel-Partialmodell: Produktwissen → Einstellung → Kaufabsicht → Kauf. Wenige Variablen, dafür praxistauglich.',
    source: 'Abbildung Partialmodell, PDF S. 2', conceptIds: ['c-partialmodelle'],
  },
  {
    id: 'qi-determinanten-1', chapterId: 'k2', figureId: 'f-determinanten', type: 'image_open', goal: 'understanding', difficulty: 2,
    prompt: 'Beschreibe anhand der Abbildung, wie Außen- und Innenreize über die beiden Prozessarten auf das Verhalten wirken.',
    rubric: [
      { point: 'Außenreize (extern, z. B. Werbung) und Innenreize (intern, z. B. Hunger)', keywords: ['aussenreiz', 'innenreiz', 'extern', 'intern', 'hunger', 'werbung'] },
      { point: 'Aktivierende Prozesse (Antrieb, Emotion)', keywords: ['aktivierend', 'antrieb', 'emotion'] },
      { point: 'Kognitive Prozesse (Denken, Informationsverarbeitung)', keywords: ['kognitiv', 'denken', 'informationsverarbeitung', 'verarbeitung'] },
      { point: 'Zusammenspiel/komplexe Prozesse führen zum Verhalten', keywords: ['komplex', 'zusammenspiel', 'verhalten', 'gemeinsam', 'reziprok'] },
    ],
    modelAnswer: 'Reize erreichen den Konsumenten von außen (z. B. ein Werbeflyer) oder von innen (z. B. Hunger). Sie stoßen aktivierende Prozesse (Antrieb, Emotion, Motivation) und kognitive Prozesse (Informationsaufnahme, -verarbeitung, -speicherung) an. Beide Prozessarten beeinflussen sich gegenseitig und wirken – oft als komplexe Prozesse kombiniert – auf das Verhalten. Ohne mindestens einen Reiz und Aktivierung entsteht kein Verhalten.',
    explanation: 'Die Abbildung zeigt die Grundarchitektur der Determinanten: Reize → Prozesse → Verhalten.',
    source: 'Abbildung Reize und Prozesse, PDF S. 3', conceptIds: ['c-aktivierende-prozesse', 'c-kognitive-prozesse'],
  },
  {
    id: 'qi-aufm-1', chapterId: 'k3', figureId: 'f-aufmerksamkeit', type: 'image_assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordne die Aufmerksamkeits-Subtypen aus der Tabelle den Beispielen zu.',
    pairs: [
      { left: 'Orientierende Aufmerksamkeit', right: 'Suche nach Weizenbier in einem Getränkefachmarkt' },
      { left: 'Selektive/fokussierte Aufmerksamkeit', right: 'Ausschließliche Suche nach Weizenbier der Brauerei X' },
      { left: 'Geteilte Aufmerksamkeit', right: 'TV-Werbung sehen und gleichzeitig Zeitschriftenwerbung wahrnehmen' },
      { left: 'Dauerhafte Aufmerksamkeit', right: 'Minutenlang das Biersortiment des Fachmarkts studieren' },
    ],
    explanation: 'Die vier Subtypen der Aufmerksamkeit mit den Skript-Beispielen rund um den Getränkefachmarkt.',
    source: 'Tabelle Aufmerksamkeits-Subtypen, PDF S. 5', conceptIds: ['c-aufmerksamkeit'],
  },
  {
    id: 'qi-lernen-1', chapterId: 'k5', figureId: 'f-kognitives-lernen', type: 'image_open', goal: 'understanding', difficulty: 2,
    prompt: 'Erkläre anhand der Abbildung, was sich zwischen Zeitpunkt t1 und t2 verändert – und warum das „Lernen“ ist.',
    rubric: [
      { point: 'Bei t1: Stimulus löst Problemlösungsprozess aus, Wissen wird gespeichert', keywords: ['t1', 'stimulus', 'problemloesung', 'gespeichert', 'erste'] },
      { point: 'Bei t2 fließt gespeichertes Wissen in den neuen Prozess ein', keywords: ['t2', 'wissen', 'einfliess', 'zurueckgreif', 'nutzt'] },
      { point: 'Wissenseinheiten/Schemata werden gebildet oder modifiziert', keywords: ['schema', 'wissenseinheit', 'gebildet', 'modifiziert', 'semantisch'] },
      { point: 'Lernen = konsistente Verhaltensänderung durch Erfahrung', keywords: ['verhaltensaenderung', 'erfahrung', 'konsistent'], weight: 0.5 },
    ],
    modelAnswer: 'Zum Zeitpunkt t1 löst ein Stimulus einen Problemlösungsprozess aus; die dabei gemachte Erfahrung wird als Wissen im Gedächtnis gespeichert. Zum Zeitpunkt t2 greift der neue Problemlösungsprozess auf dieses Wissen zurück – die Reaktion fällt anders (besser) aus. Genau diese erfahrungsbedingte, relativ konsistente Verhaltensänderung ist Lernen: Wissenseinheiten (Schemata) werden gebildet oder modifiziert.',
    explanation: 'Kognitives Lernen zeigt sich im Unterschied zwischen t1 und t2 – z. B. beim Regalaufbau: Man lernt, dass nicht immer alle Schrauben mitgeliefert werden.',
    source: 'Abbildung kognitives Lernen, PDF S. 12', conceptIds: ['c-schemata', 'c-lernen'],
  },
  {
    id: 'qi-vals-1', chapterId: 'k6', figureId: 'f-vals', type: 'image_choice', goal: 'distinction', difficulty: 3,
    prompt: 'Welche VALS-II-Gruppe steht an der Spitze der Abbildung und verfügt über Ressourcen im Überfluss?',
    options: ['Actualizers', 'Strugglers', 'Believers', 'Makers'],
    correctOptions: [0],
    explanation: 'Actualizers = erfolgreiche Konsumenten mit Ressourcen im Überfluss (Spitze); Strugglers bilden mit minimalen Ressourcen die Basis. Dazwischen: principle- (Fulfilleds, Believers), status- (Achievers, Strivers) und action-oriented (Experiencers, Makers).',
    source: 'Abbildung VALS-II, PDF S. 15', conceptIds: ['c-vals'],
  },
  {
    id: 'qi-zyklus-1', chapterId: 'k6', figureId: 'f-lebenszyklus', type: 'image_choice', goal: 'fact', difficulty: 2,
    prompt: 'Was kennzeichnet Phase IV des abgebildeten Familienlebenszyklus?',
    options: [
      'Verheiratet, ohne (ausgezogene) Kinder',
      'Unverheiratet und jung',
      'Verheiratet mit jungen Kindern',
      'Verheiratet mit älteren Kindern',
    ],
    correctOptions: [0],
    explanation: 'Phase I: unverheiratet/jung (bis ~32), Phase II: junge Kinder (bis ~42), Phase III: ältere Kinder (bis ~52), Phase IV: verheiratet ohne (ausgezogene) Kinder (bis ~77/82).',
    source: 'Tabelle Familienlebenszyklus, PDF S. 16', conceptIds: ['c-haushalt'],
  },
  {
    id: 'qi-zeit-1', chapterId: 'k7', figureId: 'f-kaufphase-zeit', type: 'image_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Ein Kunde bricht den Kauf ab, weil das Produkt nicht vorrätig ist. Welchem Verlauf der Abbildung entspricht das?',
    options: ['Stockt, wird abgebrochen', 'Stockt, wird fortgesetzt', 'Start neuer Alternativenidentifikation', 'Start eines neuen Informationssucheprozesses'],
    correctOptions: [0],
    explanation: 'Die zeitliche Ausdehnung der Kaufphase kennt vier Verläufe; ein nicht vorrätiges Produkt führt typischerweise zum Abbruch („stockt, wird abgebrochen“).',
    source: 'Abbildung zeitliche Ausdehnung der Kaufphase, PDF S. 20', conceptIds: ['c-kaufphase'],
  },
  {
    id: 'qi-bindung-1', chapterId: 'k8', figureId: 'f-bindungsinstrumente', type: 'image_assignment', goal: 'application', difficulty: 3,
    prompt: 'Ordne die Kundenbindungsinstrumente aus der Tabelle den Beispielen zu.',
    pairs: [
      { left: 'Buy-in/Follow-on-Strategie', right: 'Günstiger Drucker, Gewinn über teure Toner-Folgeprodukte' },
      { left: 'Bonussystem', right: 'Payback-Punkte belohnen Folgekäufe' },
      { left: 'Bundling', right: 'Software nur im Paket mit Service-Vertrag – Wechselkosten steigen' },
      { left: 'Beschwerdemanagement', right: 'Unzufriedene Kunden werden aktiv zurückgewonnen' },
    ],
    explanation: 'Die Instrumente aus der Übersicht: Buy-in/Follow-on (Einstiegsprodukt + Folgeprodukte), Bonussysteme (Belohnung), Bundling (Produktkombinationen), Beschwerdemanagement (Senkung bestehender Unzufriedenheit).',
    source: 'Tabelle Kundenbindungsinstrumente, PDF S. 25', conceptIds: ['c-kundenbindung'],
  },
  {
    id: 'qi-dl-dim-1', chapterId: 'k9', figureId: 'f-dl-dimensionen', type: 'image_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Ein Fitnessstudio wirbt mit modernen Geräten und erfahrenen Trainern. Welcher Dimension der Dienstleistung entspricht das laut Abbildung?',
    options: ['Potenzialdimension', 'Prozessdimension', 'Ergebnisdimension', 'Keiner – das ist Werbung'],
    correctOptions: [0],
    explanation: 'Die Potenzialdimension umfasst die Leistungsfähigkeit des Anbieters: tangible Faktoren (Equipment, Mitarbeiter) und intangible (Erfahrung). Prozessdimension = Leistungserstellung mit dem Kunden; Ergebnisdimension = immaterielles Resultat.',
    source: 'Tabelle Dienstleistungsdimensionen, PDF S. 26', conceptIds: ['c-dl-dimensionen'],
  },
  {
    id: 'qi-qual-1', chapterId: 'k9', figureId: 'f-qualitaet', type: 'image_choice', goal: 'distinction', difficulty: 3,
    prompt: 'Ein Kunde lobt, dass sein Anliegen „sofort und mit großer Bereitschaft“ bearbeitet wurde. Welche Qualitätsdimension aus der Tabelle spricht er an?',
    options: ['Responsiveness (Reaktionsfähigkeit)', 'Tangibles', 'Empathy', 'Reliability'],
    correctOptions: [0],
    explanation: 'Responsiveness = Reaktionsfähigkeit auf Kundenwünsche; wichtige Faktoren sind Bereitschaft und Schnelligkeit. Tangibles = Umfeld, Empathy = Einfühlung, Reliability = zugesagte Leistung zuverlässig erfüllen.',
    source: 'Tabelle Qualitätsdimensionen, PDF S. 28', conceptIds: ['c-qualitaetswahrnehmung'],
  },
  {
    id: 'qi-segm-1', chapterId: 'k9', figureId: 'f-segmentierung', type: 'image_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Die „Größe des Buying Centers“ ist laut Tabelle ein Segmentierungskriterium für …',
    options: ['investive Dienstleistungen (gruppenbezogene Kriterien)', 'konsumtive Dienstleistungen (demografische Kriterien)', 'beide gleichermaßen', 'keine von beiden'],
    correctOptions: [0],
    explanation: 'Investive Dienstleistungen (Empfänger = Unternehmen) werden u. a. gruppenbezogen segmentiert – z. B. nach Größe des Einkaufsgremiums/Buying Centers und Rollenverteilung. Konsumtive Kriterien betreffen Privatkunden.',
    source: 'Tabelle Segmentierungskriterien, PDF S. 29', conceptIds: ['c-benefit-segmentation'],
  },
  {
    id: 'qi-trichter-1', chapterId: 'k10', figureId: 'f-org-determinanten', type: 'image_assignment', goal: 'fact', difficulty: 2,
    prompt: 'Ordne die Determinanten-Ebenen des Trichters von außen nach innen.',
    pairs: [
      { left: 'Äußerste Ebene', right: 'Umweltdeterminanten (z. B. Stand der Technik)' },
      { left: '2. Ebene', right: 'Innerorganisationale Determinanten (Ziele, Strukturen)' },
      { left: '3. Ebene', right: 'Interpersonale Determinanten (Zusammenwirken der Beteiligten)' },
      { left: 'Innerste Ebene (vor dem Kauf)', right: 'Intrapersonale Determinanten (Autorität, Hierarchiestellung)' },
    ],
    explanation: 'Von außen nach innen: Umwelt → innerorganisational → interpersonal → intrapersonal → Kauf. Je weiter innen, desto direkter der Einfluss.',
    source: 'Abbildung Determinanten-Trichter, PDF S. 32', conceptIds: ['c-org-determinanten'],
  },
];
