import { Figure } from '@/lib/types';

/**
 * Visuelle Wissenseinheiten: alle didaktisch relevanten Abbildungen des
 * Modul-PDFs, jeweils mit semantischer Beschreibung, Bildelementen,
 * typischen Fehlinterpretationen und vierstufiger Bildprüfkette
 * (technisch → semantisch → didaktisch → validiert).
 */

const ok = { technical: true, semantic: true, didactic: true, validated: true };

export const figures: Figure[] = [
  {
    id: 'f-sor', chapterId: 'k2', file: 'img-001-000.png', pdfPage: 1,
    title: 'S-O-R-Modell',
    caption: 'Stimulus → Organismus → Response: das neobehavioristische Grundmodell.',
    explanationSimple: 'Ein Reiz (Stimulus) trifft auf den Konsumenten. In seinem Inneren (Organismus) passiert etwas, das wir nicht direkt sehen können. Am Ende zeigt er eine messbare Reaktion (Response) – z. B. er kauft oder kauft nicht.',
    explanationExpert: 'Das S-O-R-Modell des Neobehaviorismus erweitert das S-R-Modell um den Organismus: Der Stimulus ist die unabhängige Variable (wahrnehmbarer Reiz), der Organismus die intervenierende Variable (nicht beobachtbare innere Prozesse wie Wahrnehmung, Lernen, Aktivierung, Einstellung) und die Response die abhängige Variable (messbare Verhaltensreaktion, z. B. Kauf, Verweildauer am POS).',
    elements: [
      { label: 'Stimulus (unabhängige Variable)', meaning: 'Wahrnehmbarer Reiz aus der Umwelt, z. B. Werbung, Preis, Produktgestaltung (4 Ps).' },
      { label: 'Organismus (intervenierende Variable)', meaning: 'Nicht beobachtbare Prozesse im Individuum: kognitive (Wahrnehmung, Lernen) und affektive (Aktivierung, Emotion) Vorgänge.' },
      { label: 'Response (abhängige Variable)', meaning: 'Messbare Verhaltensreaktion, z. B. Kaufmenge, Verweildauer, Cross-Buyings.' },
    ],
    misconceptions: ['Der Organismus ist im S-O-R-Modell NICHT direkt beobachtbar – er bleibt eine „Black Box“, wird aber über intervenierende Variablen modelliert.', 'S-R (Behaviorismus) und S-O-R (Neobehaviorismus) nicht verwechseln.'],
    conceptIds: ['c-neobehaviorismus', 'c-behaviorismus', 'c-stimulus', 'c-response'],
    validation: ok,
  },
  {
    id: 'f-totalmodell', chapterId: 'k2', file: 'img-002-001.png', pdfPage: 2,
    title: 'Totalmodell des Konsumentenverhaltens',
    caption: 'Ganzheitliches Modell: Input, Informationsverarbeitungsprozess und Entscheidungsprozess mit Einflussvariablen.',
    explanationSimple: 'Das Schaubild versucht, den kompletten Kaufprozess in einem Modell abzubilden: Links kommen Reize (Stimuli) an, in der Mitte verarbeitet der Konsument Informationen (Kontakt, Aufmerksamkeit, Wahrnehmung), rechts läuft die Entscheidung ab – von der Problemerkennung über die Informationssuche bis zu Kauf, Nutzung und Nachkaufbewertung.',
    explanationExpert: 'Typisches Totalmodell: Der Input (marketingdominierte und andere Stimuli) durchläuft den Informationsverarbeitungsprozess (Kontakt → Aufmerksamkeit → Wahrnehmung → Annahme/Akzeptanz → Aufnahme, verbunden mit dem Gedächtnis). Der Entscheidungsprozess umfasst Problemerkennung → Informationssuche → Vorkauf-Alternativen-Bewertung → Kauf → Nutzung → Nachkaufbewertung (Zufriedenheit/Unzufriedenheit → ggf. Desinvestition). Einflussvariablen: Umwelteinflüsse (Kultur, soziale Schicht, Familie, Situation) und individuelle Charakteristika (Einkommen, Motive, Involvement, Einstellung, Kognition, Werte, Persönlichkeit, Lebensstil). Didaktisch wertvoll, praktisch schwer anwendbar.',
    elements: [
      { label: 'Input (Stimuli)', meaning: 'Marketingdominierte und andere Reize sowie externe Suche.' },
      { label: 'Informationsverarbeitungsprozess', meaning: 'Kontakt, Aufmerksamkeit, Wahrnehmung, Annahme/Akzeptanz, Aufnahme – gekoppelt an das Gedächtnis.' },
      { label: 'Entscheidungsprozess', meaning: 'Problemerkennung → Informationssuche → Alternativenbewertung → Kauf → Nutzung → Nachkaufbewertung → ggf. Desinvestition.' },
      { label: 'Einflussvariablen', meaning: 'Umwelteinflüsse (Kultur, soziale Schicht, Familie, Situation) und individuelle Charakteristika (Motive, Involvement, Einstellung …).' },
    ],
    misconceptions: ['Totalmodelle sind didaktisch wertvoll, aber in der Praxis schlecht anwendbar – nicht umgekehrt.'],
    conceptIds: ['c-totalmodelle'],
    validation: ok,
  },
  {
    id: 'f-partialmodell', chapterId: 'k2', file: 'img-002-002.png', pdfPage: 2,
    title: 'Partialmodell (Beispiel)',
    caption: 'Wirkungskette: Produktwissen → Einstellung → Kaufabsicht → Kauf.',
    explanationSimple: 'Ein Partialmodell greift bewusst nur wenige Variablen heraus: Hier führt Produktwissen zu einer Einstellung, daraus entsteht eine Kaufabsicht und schließlich der Kauf.',
    explanationExpert: 'Partialmodelle fokussieren einzelne Aspekte des Konsumentenverhaltens. Grundüberlegung: Wenige Variablen üben besonders hohen Einfluss aus, andere sind eher irrelevant. Dadurch praxistauglich, aber im Betrachtungsspektrum limitiert. Die dargestellte Kette (Wissen → Einstellung → Absicht → Verhalten) ist ein klassisches Beispiel.',
    elements: [
      { label: 'Produktwissen', meaning: 'Kognitive Basis: Was weiß der Konsument über das Produkt?' },
      { label: 'Einstellung', meaning: 'Bewertung des Produkts auf Basis des Wissens.' },
      { label: 'Kaufabsicht', meaning: 'Verhaltensintention als Vorstufe des Kaufs.' },
      { label: 'Kauf', meaning: 'Tatsächliches, beobachtbares Verhalten.' },
    ],
    conceptIds: ['c-partialmodelle'],
    validation: ok,
  },
  {
    id: 'f-determinanten', chapterId: 'k2', file: 'img-003-003.png', pdfPage: 3,
    title: 'Außen-/Innenreize und psychische Prozesse',
    caption: 'Außen- und Innenreize wirken über aktivierende und kognitive Prozesse (elementar und komplex) auf das Verhalten.',
    explanationSimple: 'Reize kommen von außen (z. B. Werbung) oder von innen (z. B. Hunger). Sie stoßen zwei Arten von Prozessen an: aktivierende (Antrieb, Gefühl) und kognitive (Denken, Verarbeiten). Beide wirken zusammen – oft über komplexe Prozesse – auf unser Verhalten.',
    explanationExpert: 'Psychische Vorgänge benötigen mindestens einen Reiz (Innen- oder Außenreiz, auch kombiniert). Aktivierende Prozesse (zentralnervöse Erregung: Aktivierung, Emotion, Motivation, Einstellung) und kognitive Prozesse (Informationsaufnahme, -verarbeitung, -speicherung) beeinflussen sich reziprok; viele mentale Prozesse sind „primär“ sowohl affektiv als auch kognitiv (z. B. Prospekt lesen: Decodieren = kognitiv, Aktivierung = affektiv). Elementare und komplexe Prozesse werden unterschieden.',
    elements: [
      { label: 'Außenreize', meaning: 'Externe Stimuli, z. B. Werbeflyer, Musik, Gerüche – von Unternehmen beeinflussbar.' },
      { label: 'Innenreize', meaning: 'Interne Stimuli, z. B. Hunger oder der Gedanke, lange nichts bestellt zu haben.' },
      { label: 'Aktivierende Prozesse', meaning: 'Verleihen Antrieb: Aktivierung, Emotion, Motivation, Einstellung.' },
      { label: 'Kognitive Prozesse', meaning: 'Informationsaufnahme, -verarbeitung, -speicherung; Lernen und Entscheiden.' },
      { label: 'Komplexe Prozesse', meaning: 'Zusammenspiel aus aktivierenden und kognitiven Anteilen.' },
      { label: 'Verhalten', meaning: 'Das Ergebnis der Prozesse – ohne Reiz und Aktivierung kein Verhalten.' },
    ],
    conceptIds: ['c-aktivierende-prozesse', 'c-kognitive-prozesse', 'c-determinante'],
    validation: ok,
  },
  {
    id: 'f-aufmerksamkeit', chapterId: 'k3', file: 'img-005-004.png', pdfPage: 5,
    title: 'Subtypen der Aufmerksamkeit',
    caption: 'Tabelle: orientierende, selektive/fokussierte, geteilte und dauerhafte Aufmerksamkeit mit Erklärungen und Beispielen.',
    explanationSimple: 'Aufmerksamkeit ist nicht gleich Aufmerksamkeit: Man kann sich räumlich orientieren, sich auf einen Reiz konzentrieren, mehrere Reize gleichzeitig verarbeiten oder länger bei einer Sache bleiben.',
    explanationExpert: 'Vier Subtypen: Orientierende Aufmerksamkeit (räumliche Ausrichtung, z. B. Suche nach Weizenbier im Getränkefachmarkt), selektive/fokussierte Aufmerksamkeit (Fokus auf bestimmten Ort/Stimulus, z. B. ausschließliche Suche nach Weizenbier der Brauerei X), geteilte Aufmerksamkeit (simultane Verarbeitung mehrerer Reize, z. B. TV-Werbung und Zeitschriftenwerbung gleichzeitig), dauerhafte Aufmerksamkeit (längerfristige Ausrichtung auf einen Reiz, z. B. minutenlanges Studieren des Biersortiments).',
    elements: [
      { label: 'Orientierende Aufmerksamkeit', meaning: 'Räumliche Aufmerksamkeitsausrichtung oder zeitlicher Verlauf – z. B. Suche nach Weizenbier im Markt.' },
      { label: 'Selektive/fokussierte Aufmerksamkeit', meaning: 'Fokus auf bestimmten Ort/Stimulus – z. B. nur Weizenbier der Brauerei X.' },
      { label: 'Geteilte Aufmerksamkeit', meaning: 'Verarbeitung mehrerer Reize simultan.' },
      { label: 'Dauerhafte Aufmerksamkeit', meaning: 'Längerfristige Ausrichtung auf einen Reiz.' },
    ],
    conceptIds: ['c-aufmerksamkeit'],
    validation: ok,
  },
  {
    id: 'f-lambda', chapterId: 'k3', file: 'img-005-005.png', pdfPage: 5,
    title: 'Lambda-Hypothese (Aktivierung und Überaktivierung)',
    caption: 'Umgekehrte U-Kurve: Leistungsfähigkeit in Abhängigkeit vom Aktivierungsgrad zwischen Schlaf und Panik.',
    explanationSimple: 'Zu wenig Aktivierung (fast schlafend) bringt keine Leistung, zu viel (Panik) auch nicht. Dazwischen liegt ein optimaler Bereich, in dem Menschen am leistungsfähigsten sind.',
    explanationExpert: 'Die Lambda-Hypothese beschreibt die Beziehung zwischen Aktivierung (x-Achse: von Schlaf bis Panik) und Leistungsfähigkeit (y-Achse) als umgekehrte U-Funktion mit optimalem Bereich. Normale Aktivierungssteigerungen (z. B. Farben, Musik, Düfte, Beliebtheit) erhöhen die Leistung; zu grelle Farben, zu laute Musik, zu intensive Düfte oder Gedränge führen zu Überaktivierung und Leistungsabfall. Empirisch weder widerlegt noch ganz bestätigt; praktisch ist Unteraktivierung das häufigere Problem.',
    elements: [
      { label: 'x-Achse: Aktivierung', meaning: 'Grad der inneren Erregung – von Schlaf (links) bis Panik (rechts).' },
      { label: 'y-Achse: Leistungsfähigkeit', meaning: 'Wie leistungsbereit/-fähig der Mensch beim jeweiligen Aktivierungsgrad ist.' },
      { label: 'Aufsteigender Ast', meaning: 'Moderate Reize (Farben, Musik, Düfte) steigern die Leistung.' },
      { label: 'Absteigender Ast (Überaktivierung)', meaning: 'Zu intensive Reize (grelle Farben, laute Musik, Gedränge) senken die Leistung.' },
    ],
    misconceptions: ['Mehr Aktivierung ist NICHT immer besser – nach dem Optimum fällt die Leistung.', 'Überaktivierung ist in der Praxis selten; meist wird die Aktivierungsschwelle gar nicht erreicht.'],
    conceptIds: ['c-lambda', 'c-aktivierung'],
    validation: ok,
  },
  {
    id: 'f-elm', chapterId: 'k3', file: 'img-007-006.png', pdfPage: 7,
    title: 'Elaboration-Likelihood-Modell (ELM)',
    caption: 'Zwei Überzeugungswege: zentraler Weg (starke Argumente) und peripherer Weg (Hinweisreize).',
    explanationSimple: 'Hat jemand Zeit und Lust, sich mit einem Produkt zu beschäftigen (Ja), überzeugen ihn gute Argumente – die Einstellung ändert sich dauerhaft. Wenn nicht (Nein), wirken eher schöne Bilder, Musik oder Promis – die Wirkung ist aber wackliger.',
    explanationExpert: 'Ausgangsfrage: Ist die Fähigkeit und Motivation zum aufmerksamen Zuhören vorhanden? Ja → zentraler Weg: Überzeugung durch starke Argumente, führt zu langanhaltender, änderungsresistenter Einstellungsänderung. Nein → peripherer Weg: Überzeugung durch periphere Hinweisreize (Bilder, Musik, attraktive Testimonials), führt zu Einstellungsänderung, die anfällig für Veränderung ist. Anwendung: teures funktionales Produkt → zentral; schnelllebiges Produkt → peripher.',
    elements: [
      { label: 'Eingangsfrage', meaning: 'Fähigkeit und Motivation zum aufmerksamen Zuhören vorhanden?' },
      { label: 'Zentraler Weg (Ja)', meaning: 'Starke Argumente → langanhaltende, änderungsresistente Einstellungsänderung.' },
      { label: 'Peripherer Weg (Nein)', meaning: 'Periphere Hinweisreize → Einstellungsänderung, anfällig für Veränderung.' },
    ],
    misconceptions: ['Periphere Reize haben nichts mit dem Produkt selbst zu tun.', 'Der periphere Weg ist nicht „schlechter“, aber die erzeugte Einstellung ist fragiler.'],
    conceptIds: ['c-elm'],
    validation: ok,
  },
  {
    id: 'f-maslow', chapterId: 'k4', file: 'img-009-007.png', pdfPage: 9,
    title: 'Maslow’sche Bedürfnispyramide',
    caption: 'Fünf Bedürfnisebenen von physiologischen Bedürfnissen bis Selbstverwirklichung.',
    explanationSimple: 'Unten stehen die Grundbedürfnisse (Essen, Wohnen), darüber Sicherheit, dann soziale Bedürfnisse (Freundschaft, Zugehörigkeit), dann Wertschätzung (Anerkennung) und ganz oben die Selbstverwirklichung. Erst wenn die unteren Ebenen erfüllt sind, strebt man nach oben.',
    explanationExpert: 'Von unten nach oben: 1. Existenz/physiologische Bedürfnisse (Überleben, Wohnung, Trinken, Essen, Wärme), 2. Sicherheitsbedürfnisse (materielle und berufliche Sicherheit, Versicherungen, Kündigungsschutz), 3. soziale Bedürfnisse (Kommunikation, Partnerschaft, Liebe, Freundschaft, Gruppenzugehörigkeit), 4. Wertschätzung (Anerkennung, Unabhängigkeit, Freiheit), 5. Selbstverwirklichung (Individualität, Güte, Gerechtigkeit). Ebenen 1–3 = Defizitbedürfnisse mit sinkender Motivationskraft bei Befriedigung; Selbstverwirklichung ist unstillbar. Marketingkritik: zu pauschal – relevanter sind Motive mittlerer Reichweite.',
    elements: [
      { label: 'Ebene 1: Physiologische Bedürfnisse', meaning: 'Überleben, Wohnung, Trinken, Essen, Wärme, Fortpflanzung.' },
      { label: 'Ebene 2: Sicherheitsbedürfnisse', meaning: 'Materielle/berufliche Sicherheit – Dach über dem Kopf, Versicherungen, Kündigungsschutz.' },
      { label: 'Ebene 3: Soziale Bedürfnisse', meaning: 'Kommunikation, Partnerschaft, Liebe, Freundschaft, Gruppenzugehörigkeit.' },
      { label: 'Ebene 4: Wertschätzung', meaning: 'Anerkennung, Verlangen nach Unabhängigkeit und Freiheit.' },
      { label: 'Ebene 5: Selbstverwirklichung', meaning: 'Individualität, Güte, Gerechtigkeit – unstillbar.' },
    ],
    misconceptions: ['Die Reihenfolge der Ebenen wird oft vertauscht – Sicherheit kommt VOR sozialen Bedürfnissen.', 'Für Marketingkonzeptionen ist das Modell nur bedingt geeignet (alle Konsumenten in einem Topf).'],
    conceptIds: ['c-maslow'],
    validation: ok,
  },
  {
    id: 'f-konstrukte', chapterId: 'k4', file: 'img-010-008.png', pdfPage: 10,
    title: 'Aufbau der Verhaltenskonstrukte',
    caption: 'Aktivierung → Emotion → Motivation → Einstellung: steigende zeitliche Beständigkeit und Komplexität.',
    explanationSimple: 'Die vier Konstrukte bauen aufeinander auf: Aktivierung ist reine Erregung. Kommt eine Interpretation dazu, wird daraus eine Emotion. Kommt ein Ziel dazu, wird daraus Motivation. Kommt eine Beurteilung eines Objekts dazu, entsteht eine Einstellung – das stabilste Konstrukt.',
    explanationExpert: 'Von unten nach oben: Aktivierung (zentralnervöses Erregungsmuster) → Emotion (Erregungsmuster + kognitive Interpretation) → Motivation (Emotion + kognitive Zielorientierung) → Einstellung (Motivation + kognitive Gegenstandsbeurteilung). Mit jeder Stufe steigen zeitliche Beständigkeit und Komplexität. Die Einstellung ist damit das komplexeste und persistenteste Konstrukt.',
    elements: [
      { label: 'Aktivierung', meaning: 'Zentralnervöses Erregungsmuster – Basis allen Verhaltens.' },
      { label: 'Emotion', meaning: 'Erregungsmuster + (kognitive) Interpretation.' },
      { label: 'Motivation', meaning: 'Emotion + (kognitive) Zielorientierung.' },
      { label: 'Einstellung', meaning: 'Motivation + (kognitive) Gegenstandsbeurteilung.' },
      { label: 'Pfeil (y-Achse)', meaning: 'Steigende zeitliche Beständigkeit und steigende Komplexität nach oben.' },
    ],
    misconceptions: ['Motivation setzt eine Emotion voraus – nicht umgekehrt.', 'Die Einstellung ist das stabilste, nicht das flüchtigste Konstrukt.'],
    conceptIds: ['c-konstrukt-hierarchie', 'c-einstellung', 'c-motivation', 'c-emotion', 'c-aktivierung'],
    validation: ok,
  },
  {
    id: 'f-gedaechtnis', chapterId: 'k5', file: 'img-011-009.png', pdfPage: 11,
    title: 'Modales Gedächtnismodell (Dreispeichermodell)',
    caption: 'Umweltreize → sensorischer Speicher → Kurzzeit-/Arbeitsspeicher → Langzeitspeicher; Ergebnis: Verhalten.',
    explanationSimple: 'Reize aus der Umwelt landen zuerst im sensorischen Speicher (Millisekunden). Was Aufmerksamkeit bekommt, wandert in den Kurzzeitspeicher (wenige Minuten, nur ca. 7±2 Elemente). Durch Lernen/Memorieren gelangt es in den Langzeitspeicher, der praktisch unbegrenzt ist.',
    explanationExpert: 'Ablauf: Reizexposition/Reizaufnahme → sensorischer Speicher (optisch, akustisch, haptisch, gustatorisch, olfaktorisch; Speicherdauer Millisekunden; Informationen „verblassen“ schnell) → über Wahrnehmung/Aufmerksamkeit in den Kurzzeit-/Arbeitsspeicher (erkennen, verstehen, bewerten, entscheiden; Speicherdauer Minuten; Kapazität 7±2 Chunks, optimal 3–4) → über Lernen/Memorieren in den Langzeitspeicher (Wissen, Bedeutung, Vorstellung; lebenslang, quasi unbegrenzt); zurück über Abrufen/Vergessen. Das Zusammenspiel von Kurzzeit- und Langzeitspeicher beeinflusst das Verhalten.',
    elements: [
      { label: 'Umweltreize', meaning: 'Eingang: alle Sinnesreize aus der Umgebung.' },
      { label: 'Sensorischer Speicher', meaning: 'Alle Sinneskanäle; Speicherdauer Millisekunden; nicht Weitergeleitetes verblasst.' },
      { label: 'Wahrnehmung/Aufmerksamkeit', meaning: 'Filter zwischen sensorischem und Kurzzeitspeicher.' },
      { label: 'Kurzzeit-/Arbeitsspeicher', meaning: 'Erkennen, verstehen, bewerten, entscheiden; Kapazität 7±2 Chunks (optimal 3–4); Minuten.' },
      { label: 'Lernen/Memorieren & Abrufen/Vergessen', meaning: 'Transfer in den Langzeitspeicher und zurück.' },
      { label: 'Langzeitspeicher/Gedächtnis', meaning: 'Wissen, Bedeutung, Vorstellung; lebenslang, quasi unbegrenzte Kapazität.' },
      { label: 'Verhalten', meaning: 'Ergebnis des Zusammenspiels von Kurzzeit- und Langzeitspeicher.' },
    ],
    misconceptions: ['Die Kapazität 7±2 gilt für den KURZZEITspeicher, nicht für den Langzeitspeicher.', 'Der sensorische Speicher hält Millisekunden, nicht Minuten.'],
    conceptIds: ['c-dreispeicher', 'c-sensorischer-speicher', 'c-kurzzeitspeicher'],
    validation: ok,
  },
  {
    id: 'f-kognitives-lernen', chapterId: 'k5', file: 'img-012-010.png', pdfPage: 12,
    title: 'Schematische Darstellung kognitiven Lernens',
    caption: 'Stimulus → Problemlösungsprozess → Reaktion; das Gedächtnis (Wissen) wird über die Zeit (t1 → t2) modifiziert.',
    explanationSimple: 'Beim ersten Kontakt (t1) löst ein Reiz einen Problemlösungsprozess aus, und wir speichern die Erfahrung als Wissen. Beim nächsten Mal (t2) greift der Prozess auf dieses Wissen zurück – wir haben gelernt.',
    explanationExpert: 'Kognitives Lernen: Zum Zeitpunkt t1 führt ein Stimulus zu einem Problemlösungsprozess und einer Reaktion; dabei wird Wissen im Gedächtnis gebildet. Zum Zeitpunkt t2 fließt das gespeicherte Wissen in den neuen Problemlösungsprozess ein – Wissenseinheiten (Schemata/semantische Netzwerke) werden gebildet oder modifiziert. Lernerfolge treten schon nach der ersten Informationsverarbeitung ein (Beispiel Regalmontage: man lernt, dass nicht immer alle Schrauben mitgeliefert werden).',
    elements: [
      { label: 't1 / t2', meaning: 'Zwei Zeitpunkte – Lernen zeigt sich in der Veränderung zwischen ihnen.' },
      { label: 'Stimulus', meaning: 'Auslösender Reiz (z. B. neues Problem).' },
      { label: 'Problemlösungsprozess', meaning: 'Kognitive Verarbeitung des Reizes.' },
      { label: 'Gedächtnis: Wissen', meaning: 'Gespeicherte bzw. modifizierte Wissenseinheiten (Schemata), die den nächsten Prozess beeinflussen.' },
      { label: 'Reaktion', meaning: 'Ergebnisverhalten des Prozesses.' },
    ],
    conceptIds: ['c-schemata', 'c-lernen'],
    validation: ok,
  },
  {
    id: 'f-kaufrollen', chapterId: 'k6', file: 'img-014-011.png', pdfPage: 14,
    title: 'Rollen im Kaufentscheidungsprozess',
    caption: 'Initiator, Beeinflusser, Entscheider, Käufer und Nutzer am Familienbeispiel.',
    explanationSimple: 'Bei komplexen Käufen übernehmen oft verschiedene Personen verschiedene Rollen: Die Tochter bringt die Idee auf (Initiator), der Onkel redet mit (Beeinflusser), der Vater entscheidet, die Mutter kauft, der Sohn nutzt das Produkt.',
    explanationExpert: 'Rollen im (komplexen) Kaufentscheidungsprozess: Initiator (stößt den Kauf an, z. B. Tochter), Beeinflusser (wirkt auf die Entscheidung, z. B. Onkel), Entscheider (trifft die Kaufentscheidung, z. B. Vater), Käufer (führt den Kauf aus, z. B. Mutter), Nutzer (verwendet das Produkt, z. B. Sohn). Eine Person kann mehrere Rollen einnehmen. Analog existieren diese Rollen im organisationalen Buying Center (inkl. Gatekeeper).',
    elements: [
      { label: 'Initiator', meaning: 'Stößt den Kaufprozess an (z. B. Tochter).' },
      { label: 'Beeinflusser', meaning: 'Wirkt auf die Entscheidung ein (z. B. Onkel).' },
      { label: 'Entscheider', meaning: 'Trifft die endgültige Kaufentscheidung (z. B. Vater).' },
      { label: 'Käufer', meaning: 'Führt die Transaktion durch (z. B. Mutter).' },
      { label: 'Nutzer', meaning: 'Verwendet das Produkt (z. B. Sohn).' },
    ],
    misconceptions: ['Käufer und Entscheider sind nicht zwingend dieselbe Person.', 'Der Nutzer muss weder entschieden noch bezahlt haben.'],
    conceptIds: ['c-kaufrollen'],
    validation: ok,
  },
  {
    id: 'f-vals', chapterId: 'k6', file: 'img-015-012.png', pdfPage: 15,
    title: 'VALS-II-Ansatz',
    caption: 'Lebensstilgruppen (Actualizers bis Strugglers) nach Ressourcen und Orientierung (principle/status/action).',
    explanationSimple: 'VALS-II teilt Konsumenten in Lebensstilgruppen ein – oben die Actualizers mit vielen Ressourcen, unten die Strugglers mit minimalen Ressourcen. Dazwischen unterscheiden sich die Gruppen danach, ob sie prinzipien-, status- oder handlungsorientiert sind.',
    explanationExpert: 'VALS-II segmentiert nach Ressourcen (abundant oben, minimal unten) und Orientierung: principle-oriented (Fulfilleds, Believers), status-oriented (Achievers, Strivers), action-oriented (Experiencers, Makers). Actualizers = erfolgreiche Konsumenten mit Ressourcen im Überfluss; Strugglers = besorgt, mit den täglichen Herausforderungen zurechtzukommen. Kurz-Charakteristika u. a.: Makers „action“-orientiert, Strivers besorgt um Anerkennung, Experiencers impulsiv/jung/risikofreudig, Achievers karriereorientiert, Fulfilleds zufrieden/reflektierend/erfahren, Believers stark prinzipienorientiert. Kulturelle Adaptionen bestehen.',
    elements: [
      { label: 'Actualizers', meaning: 'Erfolgreiche Konsumenten mit Ressourcen im Überfluss (Spitze).' },
      { label: 'principle-oriented', meaning: 'Fulfilleds (zufrieden, reflektierend, erfahren) und Believers (stark prinzipienorientiert).' },
      { label: 'status-oriented', meaning: 'Achievers (karriereorientiert) und Strivers (besorgt um Anerkennung durch andere).' },
      { label: 'action-oriented', meaning: 'Experiencers (impulsiv, jung, genießen riskante Erfahrungen) und Makers („Action“-orientiert).' },
      { label: 'Strugglers', meaning: 'Besorgt, mit den täglichen Herausforderungen des Lebens zurechtzukommen (Basis, minimale Ressourcen).' },
    ],
    conceptIds: ['c-vals'],
    validation: ok,
  },
  {
    id: 'f-lebenszyklus', chapterId: 'k6', file: 'img-016-013.png', pdfPage: 16,
    title: 'Phasen des Familienlebenszyklus',
    caption: 'Tabelle: Phasen I–IV mit Kennzeichen (unverheiratet/jung bis verheiratet ohne Kinder) und maximalem Alter.',
    explanationSimple: 'Der Familienlebenszyklus teilt Haushalte in Phasen ein: jung und unverheiratet, verheiratet mit jungen Kindern, mit älteren Kindern, und schließlich verheiratet ohne (ausgezogene) Kinder. Jede Phase hat typisches Konsumverhalten.',
    explanationExpert: 'Phase I: unverheiratet, jung (bis ca. 32 J.); Phase II: verheiratet, junge Kinder (bis ca. 42 J.); Phase III: verheiratet, ältere Kinder (bis ca. 52 J.); Phase IV: verheiratet, ohne (ausgezogene) Kinder (bis ca. 77/82 J., entsprechend der durchschnittlichen Lebenserwartung). Der Lebenszyklus liefert Segmentierungsrückschlüsse auf das Konsumentenverhalten – z. B. steht mit Kind weniger Geld zur Verfügung.',
    elements: [
      { label: 'Phase I', meaning: 'Unverheiratet, jung – maximales Alter ca. 32 Jahre.' },
      { label: 'Phase II', meaning: 'Verheiratet, junge Kinder – bis ca. 42 Jahre.' },
      { label: 'Phase III', meaning: 'Verheiratet, ältere Kinder – bis ca. 52 Jahre.' },
      { label: 'Phase IV', meaning: 'Verheiratet, ohne Kinder (ausgezogen) – bis ca. 77/82 Jahre.' },
    ],
    conceptIds: ['c-haushalt'],
    validation: ok,
  },
  {
    id: 'f-kaufmatrix', chapterId: 'k7', file: 'img-017-014.png', pdfPage: 17,
    title: 'Kaufentscheidungsarten nach Involvement',
    caption: '2×2-Matrix: emotionales × kognitives Involvement ergibt impulsive, extensive, habitualisierte und limitierte Kaufentscheidungen.',
    explanationSimple: 'Je nachdem, wie stark Gefühl und Nachdenken beteiligt sind, entstehen vier Kauftypen: viel Gefühl + wenig Nachdenken = Impulskauf; viel Gefühl + viel Nachdenken = extensiver Kauf; wenig Gefühl + wenig Nachdenken = Gewohnheitskauf; wenig Gefühl + viel Nachdenken = limitierter Kauf.',
    explanationExpert: 'Achsen: emotionales Involvement (y, niedrig→hoch) und kognitives Involvement (x, niedrig→hoch). Quadranten: impulsive Kaufentscheidung (emotional hoch, kognitiv niedrig), extensive Kaufentscheidung (beide hoch – Suchkauf mit intensiver Informationsverarbeitung), habitualisierte Kaufentscheidung (beide niedrig – „Autopilot“), limitierte Kaufentscheidung (kognitiv hoch, emotional niedrig – Auswahl aus bekannter Alternativenmenge).',
    elements: [
      { label: 'y-Achse: emotionales Involvement', meaning: 'Grad der emotionalen Beteiligung (niedrig → hoch).' },
      { label: 'x-Achse: kognitives Involvement', meaning: 'Grad der gedanklichen Beteiligung (niedrig → hoch).' },
      { label: 'Impulsiv (oben links)', meaning: 'Emotional hoch, kognitiv niedrig – Reiz ohne viel Nachdenken.' },
      { label: 'Extensiv (oben rechts)', meaning: 'Beides hoch – starker Informationssuch- und Verarbeitungsprozess.' },
      { label: 'Habitualisiert (unten links)', meaning: 'Beides niedrig – Gewohnheitskauf im „Autopilot“.' },
      { label: 'Limitiert (unten rechts)', meaning: 'Kognitiv hoch, emotional niedrig – Auswahl mit vorhandenem Wissen (z. B. Käsesorten).' },
    ],
    misconceptions: ['Impulsiv und habitualisiert werden oft verwechselt – impulsiv ist emotional getrieben, habitualisiert ist Gewohnheit (Gegenteil).'],
    conceptIds: ['c-kaufarten', 'c-involvement'],
    validation: ok,
  },
  {
    id: 'f-phasenmodell', chapterId: 'k7', file: 'img-018-015.png', pdfPage: 18,
    title: 'Dreigliedriges Phasenmodell des Kaufprozesses',
    caption: 'Vorkaufphase (Problemerkennung, Info-Suche, Evaluation) → Kaufphase (Alternativenidentifikation, Intentionsentwicklung, Kauf) → Nachkauf-/Nutzungsphase (Konsum, Evaluierung, Beschwerde, Entsorgung).',
    explanationSimple: 'Der Kaufprozess läuft in drei Phasen: Vorher (Problem erkennen, Informationen suchen, Alternativen bewerten), während (Alternativen identifizieren, Kaufabsicht entwickeln, kaufen) und danach (nutzen, bewerten, sich ggf. beschweren, entsorgen).',
    explanationExpert: 'Vorkaufphase: Problemerkennung → interne und externe Informationssuche → Evaluation. Kaufphase: Alternativenidentifikation → Intentionsentwicklung → Kauf. Nachkauf-/Nutzungsphase: Konsum/Nutzung → Evaluierung → ggf. Beschwerde → Entsorgung. Rückkopplungen (gestrichelte Pfeile) verbinden spätere Phasen mit früheren – z. B. fließt die Nachkaufbewertung in künftige Problemerkennungen ein. Fokus des Modells: Kundenbeziehung und Kundenbindung.',
    elements: [
      { label: 'Vorkaufphase', meaning: 'Problemerkennung, interne/externe Info-Suche, Evaluation.' },
      { label: 'Kaufphase', meaning: 'Alternativenidentifikation, Intentionsentwicklung, Kauf.' },
      { label: 'Nachkauf-/Nutzungsphase', meaning: 'Konsum/Nutzung, Evaluierung, Beschwerde, Entsorgung.' },
      { label: 'Rückkopplungspfeile', meaning: 'Erfahrungen fließen in künftige Kaufprozesse zurück.' },
    ],
    conceptIds: ['c-phasenmodelle', 'c-kaufphase', 'c-nachkaufphase', 'c-problemerkenntnis'],
    validation: ok,
  },
  {
    id: 'f-problemerkenntnis', chapterId: 'k7', file: 'img-018-016.png', pdfPage: 18,
    title: 'Problemerkenntnis: Ideal- und Istzustand',
    caption: 'Kein Problem, Wahrnehmung der Gelegenheit (Ideal steigt) und Wahrnehmung des Bedarfs (Ist sinkt).',
    explanationSimple: 'Ein Kaufproblem entsteht auf zwei Wegen: Entweder steigt der Idealzustand (man sieht etwas Besseres – eine Gelegenheit), oder der Istzustand sinkt (etwas geht kaputt oder fehlt – ein Bedarf). Sind Ideal und Ist gleich, gibt es kein Problem.',
    explanationExpert: 'Drei Fälle: 1. Kein Problem – Ideal- und Istzustand decken sich. 2. Wahrnehmung der Gelegenheit – der Idealzustand verschiebt sich nach oben (bessere Produkte verfügbar), der Abstand zum Ist wird als Problem wahrgenommen. 3. Wahrnehmung des Bedarfs – der Istzustand sinkt unter das Ideal (z. B. Produkt verbraucht/defekt). Die Differenz muss groß genug sein, um als Problem wahrgenommen zu werden; Probleme können offensichtlich oder versteckt sein (verdorbene Lebensmittel).',
    elements: [
      { label: 'Kein Problem', meaning: 'Ideal- und Istzustand stimmen überein.' },
      { label: 'Wahrnehmung der Gelegenheit', meaning: 'Idealzustand steigt über den Istzustand (Pfeil nach oben).' },
      { label: 'Wahrnehmung des Bedarfs', meaning: 'Istzustand fällt unter den Idealzustand (Pfeil nach unten).' },
    ],
    conceptIds: ['c-problemerkenntnis'],
    validation: ok,
  },
  {
    id: 'f-kaufphase-zeit', chapterId: 'k7', file: 'img-020-017.png', pdfPage: 20,
    title: 'Zeitliche Ausdehnung der Kaufphase',
    caption: 'Vier Verläufe: stockt und wird fortgesetzt, stockt und wird abgebrochen, Start neuer Alternativenidentifikation/Evaluation, Start eines neuen Informationssuchprozesses.',
    explanationSimple: 'Zwischen Kaufabsicht und Kauf kann viel passieren: Der Kauf kann stocken und später fortgesetzt oder ganz abgebrochen werden – oder der Kunde beginnt nochmal von vorn, sucht neue Alternativen oder neue Informationen.',
    explanationExpert: 'Die Kaufphase kann sich zeitlich ausdehnen, weil zwischen Intentionsentwicklung und Kauf Reize wirken (Marketingstimuli wie Ads, neutrale Stimuli wie Berichte oder persönliche Kontakte; auch Verkäuferaussagen wie ein angekündigter Lieferengpass). Vier mögliche Verläufe: 1. Prozess stockt, wird fortgesetzt. 2. Prozess stockt, wird abgebrochen (z. B. Produkt nicht vorrätig). 3. Start einer neuen Alternativenidentifikation oder Evaluation. 4. Start eines neuen Informationssucheprozesses.',
    elements: [
      { label: 'Stockt, wird fortgesetzt', meaning: 'Verzögerung, aber der Kauf kommt zustande.' },
      { label: 'Stockt, wird abgebrochen', meaning: 'Der Kaufprozess endet ohne Kauf.' },
      { label: 'Neue Alternativenidentifikation/Evaluation', meaning: 'Der Kunde bewertet erneut andere Optionen.' },
      { label: 'Neuer Informationssucheprozess', meaning: 'Der Kunde beginnt die Suche von vorn.' },
    ],
    conceptIds: ['c-kaufphase'],
    validation: ok,
  },
  {
    id: 'f-psm', chapterId: 'k7', file: 'img-022-018.png', pdfPage: 22,
    title: 'Price-Sensitivity-Meter (Van-Westendorp)',
    caption: 'Vier Preiskurven (zu billig, noch günstig, relativ hoch, zu teuer); Schnittpunkte markieren Preisunter- und -obergrenze.',
    explanationSimple: 'Kunden beantworten vier Preisfragen (zu billig? noch günstig? relativ hoch? zu teuer?). Trägt man die Antworten als Kurven auf, zeigen zwei Schnittpunkte, wo der Preis mindestens liegen sollte und wo er höchstens liegen darf – dazwischen ist der akzeptable Bereich.',
    explanationExpert: 'x-Achse: Preis; y-Achse: kumulierte Prozent der Befragten (n). Vier Kurven aus den Van-Westendorp-Fragen: „zu billig“ (fallend), „noch günstig“ (fallend), „relativ hoch“ (steigend), „zu teuer“ (steigend). Preisuntergrenze = Schnittpunkt „zu billig“ × „relativ hoch“; Preisobergrenze = Schnittpunkt „noch günstig/akzeptabel“ × „zu teuer“. Der Bereich zwischen den Grenzen (schattiert) ist der akzeptable Preisbereich. Erweiterung der Gabor-Granger-Methode.',
    elements: [
      { label: 'x-Achse', meaning: 'Preis (hier in €-Schritten).' },
      { label: 'y-Achse', meaning: 'Prozent der Befragten (kumuliert).' },
      { label: 'Kurve „zu billig“', meaning: 'Anteil, der den Preis als verdächtig günstig empfindet (fallend).' },
      { label: 'Kurve „zu teuer“', meaning: 'Anteil, dem der Preis zu hoch ist (steigend).' },
      { label: 'Preisuntergrenze', meaning: 'Schnittpunkt „zu billig“ × „relativ hoch“.' },
      { label: 'Preisobergrenze', meaning: 'Schnittpunkt „noch akzeptabel/günstig“ × „zu teuer“.' },
      { label: 'Schattierter Bereich', meaning: 'Akzeptabler Preisbereich zwischen den Grenzen.' },
    ],
    misconceptions: ['Die Grenzen entstehen aus SCHNITTPUNKTEN der Kurven, nicht aus Maxima.', 'Nicht mit Gabor-Granger verwechseln: PSM nutzt 4 Preisfragen, Gabor-Granger 5 Preispunkte + Kaufbereitschaftsskala.'],
    conceptIds: ['c-van-westendorp', 'c-gabor-granger'],
    validation: ok,
  },
  {
    id: 'f-erfolgskette', chapterId: 'k8', file: 'img-023-019.png', pdfPage: 23,
    title: 'Erfolgskette der Kundenorientierung',
    caption: 'Kundenorientierung → Kundenzufriedenheit → Kundenbindung → Kundenwert, moderiert durch externe und interne Faktoren.',
    explanationSimple: 'Wer sein Unternehmen an den Kunden ausrichtet, macht sie zufrieden. Zufriedene Kunden bleiben (Bindung) und werden dadurch wertvoll für das Unternehmen (Kundenwert). Äußere und innere Faktoren beeinflussen jeden Schritt.',
    explanationExpert: 'Die Erfolgskette illustriert den Weg von der Kundenorientierung zum Kundenwert: Kundenorientierung → Kundenzufriedenheit → Kundenbindung → Kundenwert. Ober- und unterhalb wirken unternehmensexterne moderierende Faktoren (z. B. Anzahl Konkurrenzanbieter, Variety Seeking – schlecht beeinflussbar) und unternehmensinterne moderierende Faktoren (kurzfristig steuerbar, z. B. Wechselbarrieren, Vertragsbindungen, Leistungsverbünde) auf alle Kettenglieder.',
    elements: [
      { label: 'Kundenorientierung', meaning: 'Ausrichtung der Unternehmensaktivitäten an Kundenwünschen.' },
      { label: 'Kundenzufriedenheit', meaning: 'Ergebnis erfüllter Erwartungen – Voraussetzung für Bindung.' },
      { label: 'Kundenbindung', meaning: 'Loyales Verhalten, Bereitschaft zu künftigen Transaktionen.' },
      { label: 'Kundenwert', meaning: 'Beitrag des Kunden zu monetären und nicht-monetären Unternehmenszielen.' },
      { label: 'Unternehmensexterne Faktoren', meaning: 'Moderieren die Kette, schlecht beeinflussbar (z. B. Konkurrenz, Variety Seeking).' },
      { label: 'Unternehmensinterne Faktoren', meaning: 'Moderieren die Kette, kurzfristig steuerbar (z. B. Wechselbarrieren).' },
    ],
    misconceptions: ['Die Reihenfolge ist fest: Orientierung → Zufriedenheit → Bindung → Wert.'],
    conceptIds: ['c-erfolgskette', 'c-kundenorientierung', 'c-kundenzufriedenheit', 'c-kundenbindung', 'c-kundenwert'],
    validation: ok,
  },
  {
    id: 'f-zufriedenheit-wert', chapterId: 'k8', file: 'img-024-020.png', pdfPage: 24,
    title: 'Kundenzufriedenheit und Unternehmenswert',
    caption: 'Zonen von Enttäuschung über Indifferenz bis Begeisterung – und die Zone der Übertreibung („Overservicing“).',
    explanationSimple: 'Werden Erwartungen enttäuscht, sinkt der Unternehmenswert (Zone der Enttäuschung). Werden sie erfüllt, ist der Kunde neutral (Indifferenzzone). Werden sie übertroffen, entsteht Begeisterung. Aber: Zu viel Service kippt ins Negative – der Kunde fühlt sich zu sehr umsorgt.',
    explanationExpert: 'x-Achse: Zufriedenheit (hohe Unzufriedenheit → hohe Zufriedenheit); y-Achse: Unternehmenswert. Zonen: Zone der Enttäuschung (Erwartungen enttäuscht, Wert sinkt stark), Indifferenzzone (Erwartungen erfüllt, neutral), Zone der Begeisterung (Erwartungen übertroffen, Wert steigt überproportional) und Zone der Übertreibung/„Overservicing“ (gestrichelt): Zusätzlicher Service steigert den Wert nicht mehr, sondern kann ihn senken – Beispiel: Ein zweiter Kellner verbessert die Servicequalität kaum oder schwächt sie sogar, weil der Kunde sich zu sehr umsorgt fühlt.',
    elements: [
      { label: 'Zone der Enttäuschung', meaning: 'Erwartungen enttäuscht – starker negativer Effekt auf den Unternehmenswert.' },
      { label: 'Indifferenzzone', meaning: 'Erwartungen erfüllt – kaum Wirkung.' },
      { label: 'Zone der Begeisterung', meaning: 'Erwartungen übertroffen – überproportional positiver Effekt.' },
      { label: 'Zone der Übertreibung (Overservicing)', meaning: 'Zu viel Service – Wirkung flacht ab oder kippt ins Negative.' },
    ],
    misconceptions: ['Mehr Service ist nicht immer besser – Overservicing kann den Wert senken.'],
    conceptIds: ['c-kundenzufriedenheit'],
    validation: ok,
  },
  {
    id: 'f-bindungsinstrumente', chapterId: 'k8', file: 'img-025-021.png', pdfPage: 25,
    title: 'Übersicht der Kundenbindungsinstrumente',
    caption: 'Tabelle: Maßnahmen (Zufriedenheitsmanagement, Beschwerdemanagement, Bonussysteme, Buy-in/Follow-on, Bundling, IT-Einsatz) mit Charakteristika.',
    explanationSimple: 'Unternehmen binden Kunden mit verschiedenen Instrumenten: Zufriedenheit aktiv managen, Beschwerden ernst nehmen, Bonusprogramme anbieten, günstige Einstiegsprodukte mit Folgeprodukten koppeln, Produkte bündeln oder CRM-Software einsetzen.',
    explanationExpert: 'Wesentliche Instrumente: Kundenzufriedenheitsmanagement (Optimierung über Determinanten wie Engagement, Freundlichkeit, Mitarbeiterkompetenz – steht im Bindungs-Mix an oberster Stelle), Beschwerdemanagement (Senkung bestehender Unzufriedenheit, im Vergleich geringer Einsatz in der Praxis), Wechselabsichten entgegenwirken (zeitlich begrenzte Angebote, Kommunikationsmaßnahmen), Bonussysteme (aktive Bindung durch Belohnung von Folgekäufen), vielseitige Maßnahmen zur Beziehungspflege (v. a. im Dienstleistungsbereich), Buy-in/Follow-on-Strategien (günstiges Einstiegsprodukt, Gewinnerzielung durch benötigte Folgeprodukte, z. B. Drucker und Toner – langfristige Strategie), Bundling (Produktkombinationen erhöhen Wechselkosten), IT-Einsatz (Informationsmanagement zur Unterstützung der Kundensegmentierung; isolierter CRM-Einsatz führt nicht zu gesteigerter Bindung).',
    elements: [
      { label: 'Kundenzufriedenheitsmanagement', meaning: 'Oberste Stelle im Bindungs-Mix; Optimierung über Determinanten der Zufriedenheit.' },
      { label: 'Beschwerdemanagement', meaning: 'Senkung bestehender Unzufriedenheit.' },
      { label: 'Bonussysteme', meaning: 'Belohnung von Folgekäufen; nur wirksam mit Produktalternativen.' },
      { label: 'Buy-in/Follow-on', meaning: 'Günstiger Einstieg (z. B. Drucker), Gewinn über Folgeprodukte (Toner).' },
      { label: 'Bundling', meaning: 'Produktkombinationen erhöhen die Wechselkosten.' },
      { label: 'IT-Einsatz', meaning: 'CRM/Informationsmanagement – isoliert keine Bindungswirkung.' },
    ],
    conceptIds: ['c-kundenbindung'],
    validation: ok,
  },
  {
    id: 'f-dl-dimensionen', chapterId: 'k9', file: 'img-026-022.png', pdfPage: 26,
    title: 'Dimensionen der Dienstleistung',
    caption: 'Potenzial-, Prozess- und Ergebnisdimension mit Beschreibungen.',
    explanationSimple: 'Eine Dienstleistung hat drei Seiten: die Fähigkeit des Anbieters (Potenzial – z. B. Ausstattung, Personal), den Ablauf mit dem Kunden (Prozess) und das Ergebnis, das man nicht anfassen oder lagern kann.',
    explanationExpert: 'Potenzialdimension: Bereitstellung der Leistungsfähigkeit des Dienstleisters – involvierte tangible (berührbare) und intangible (nicht berührbare) Faktoren (z. B. Erfahrung intangibel, Equipment/Mitarbeiter tangibel). Prozessdimension: Einbeziehung interner und externer Faktoren – externe: Person oder Sache (häufig der Dienstleistungsempfänger selbst), interne: Nutzung (in)tangibler Faktoren. Ergebnisdimension: Immaterialität der Leistung – Dienstleistungen sind weder transport- noch lagerfähig; Ergebnisse können materiell „gespeist“ sein.',
    elements: [
      { label: 'Potenzialdimension', meaning: 'Leistungsfähigkeit des Anbieters: tangible + intangible Faktoren.' },
      { label: 'Prozessdimension', meaning: 'Einbeziehung interner und externer Faktoren (oft der Kunde selbst).' },
      { label: 'Ergebnisdimension', meaning: 'Immaterialität: weder transport- noch lagerfähig.' },
    ],
    conceptIds: ['c-dl-dimensionen'],
    validation: ok,
  },
  {
    id: 'f-4ls', chapterId: 'k9', file: 'img-026-023.png', pdfPage: 26,
    title: 'Leistungstypologien (4 Ls)',
    caption: 'Mass, Professional und Speciality Services auf vier Merkmalskalen: Integration, Interaktion, Individualisierung, Immaterialität.',
    explanationSimple: 'Dienstleistungen unterscheiden sich darin, wie stark der Kunde eingebunden ist, wie viel Interaktion stattfindet, wie individuell die Leistung ist und wie immateriell sie ist. Eine Reinigung (Mass Service) hat niedrige Werte, eine Rechtsberatung (Speciality Service) hohe.',
    explanationExpert: 'Die 4 Ls typologisieren Dienstleistungen über vier Merkmale, jeweils von gering bis hoch: Grad der Integration (Einbindung des Kunden), Grad der Interaktion, Grad der Individualisierung und Grad der Immaterialität. Beispiele: Mass Services (z. B. Reinigung – geringe Ausprägungen), Professional Services (z. B. Friseur – mittlere), Speciality Services (z. B. Rechtsberatung – hohe Ausprägungen).',
    elements: [
      { label: 'Mass Services', meaning: 'Z. B. Reinigung – geringe Integration, Interaktion, Individualisierung.' },
      { label: 'Professional Services', meaning: 'Z. B. Friseur – mittlere Ausprägungen.' },
      { label: 'Speciality Services', meaning: 'Z. B. Rechtsberatung – hohe Ausprägungen aller Merkmale.' },
      { label: 'Vier Skalen', meaning: 'Integration, Interaktion, Individualisierung, Immaterialität – jeweils gering ↔ hoch.' },
    ],
    conceptIds: ['c-4ls'],
    validation: ok,
  },
  {
    id: 'f-service-kette', chapterId: 'k9', file: 'img-027-024.png', pdfPage: 27,
    title: 'Wirkungsgrößen der Service-Erfolgskette',
    caption: 'Aktivitäten des Dienstleistungsmarketings → psychologische Wirkungen → Verhaltenswirkungen → ökonomischer Erfolg.',
    explanationSimple: 'Marketingaktivitäten wirken zuerst im Kopf des Kunden (Zufriedenheit, Image, Qualitätseindruck), dann im Verhalten (er bleibt, kauft wieder, empfiehlt weiter) – und das führt am Ende zum wirtschaftlichen Erfolg.',
    explanationExpert: 'Kette: Aktivitäten des Dienstleistungsmarketings → psychologische Wirkungen (Kundenzufriedenheit, Image, Qualitätswahrnehmung, Beziehungsqualität, Commitment, Risikowahrnehmung) → Verhaltenswirkungen (Kundenbindung, (Wieder-)Kauf, Weiterempfehlung, Zusatzkauf) → ökonomischer Erfolg. Wichtig: Die Wirkungskomponenten können sich im zeitlichen Verlauf gegenseitig beeinflussen; Dienstleistungsmarketing hat besonders starke psychologische Wirkungen.',
    elements: [
      { label: 'Aktivitäten des Dienstleistungsmarketings', meaning: 'Ausgangspunkt der Kette.' },
      { label: 'Psychologische Wirkungen', meaning: 'Zufriedenheit, Image, Qualitätswahrnehmung, Beziehungsqualität, Commitment, Risikowahrnehmung.' },
      { label: 'Verhaltenswirkungen', meaning: 'Bindung, (Wieder-)Kauf, Weiterempfehlung, Zusatzkauf.' },
      { label: 'Ökonomischer Erfolg', meaning: 'Ergebnis der Kette.' },
    ],
    conceptIds: ['c-service-erfolgskette'],
    validation: ok,
  },
  {
    id: 'f-qualitaet', chapterId: 'k9', file: 'img-028-025.png', pdfPage: 28,
    title: 'Qualitätsdimensionen der Dienstleistungsqualität',
    caption: 'Tabelle: Tangibles, Reliability, Responsiveness, Assurance, Empathy.',
    explanationSimple: 'Kunden beurteilen Dienstleistungsqualität über fünf Dimensionen: das sichtbare Umfeld, Zuverlässigkeit, Reaktionsfähigkeit, Kompetenz und Einfühlungsvermögen.',
    explanationExpert: 'Fünf Dimensionen der wahrgenommenen Dienstleistungsqualität: Tangibles (Annehmlichkeiten des tangiblen Umfelds – Erscheinungsbild von Räumen, Equipment, Mitarbeitern), Reliability (Zuverlässigkeit – zugesagte Leistung auf vereinbartem Niveau erfüllen), Responsiveness (Reaktionsfähigkeit – Fähigkeit, auf Kundenwünsche einzugehen; wichtige Faktoren: Bereitschaft und Schnelligkeit), Assurance (Leistungskompetenz – Fähigkeit zur Erbringung der Leistung, inkl. Know-how, Höflichkeit, Vertrauenswürdigkeit der Mitarbeiter), Empathy (Einfühlungsvermögen – Bereitschaft und Fähigkeit, jedem Kunden die entsprechende Fürsorge und Aufmerksamkeit zukommen zu lassen).',
    elements: [
      { label: 'Tangibles', meaning: 'Erscheinungsbild des tangiblen Umfelds (Räume, Equipment, Mitarbeiter).' },
      { label: 'Reliability', meaning: 'Zuverlässigkeit: zugesagte Leistung auf vereinbartem Niveau.' },
      { label: 'Responsiveness', meaning: 'Reaktionsfähigkeit: Bereitschaft + Schnelligkeit.' },
      { label: 'Assurance', meaning: 'Leistungskompetenz: Know-how, Höflichkeit, Vertrauenswürdigkeit.' },
      { label: 'Empathy', meaning: 'Einfühlungsvermögen: individuelle Fürsorge und Aufmerksamkeit.' },
    ],
    conceptIds: ['c-qualitaetswahrnehmung'],
    validation: ok,
  },
  {
    id: 'f-segmentierung', chapterId: 'k9', file: 'img-029-026.png', pdfPage: 29,
    title: 'Segmentierungskriterien: konsumtiv vs. investiv',
    caption: 'Tabelle: Kriterien für konsumtive (demografisch, sozioökonomisch, psychologisch, verhaltensbezogen) und investive Dienstleistungen (branchen-, unternehmens-, gruppen-, personenbezogen).',
    explanationSimple: 'Für Privatkunden (konsumtiv) segmentiert man z. B. nach Alter, Einkommen, Einstellungen und Verhalten. Für Geschäftskunden (investiv) nach Branche, Unternehmensmerkmalen, Gruppen und Personen im Buying Center.',
    explanationExpert: 'Konsumtive Dienstleistungen (Empfänger = Konsument): 1. demografische Kriterien (Geschlecht, Alter, Familienlebenszyklus, geografische Kriterien), 2. sozioökonomische (Einkommen, soziale Schicht, Beruf, Ausbildung, Customer Lifetime Value), 3. psychologische (Motive, Einstellungen, Lifestyle), 4. verhaltensbezogene (dienstleistungs-, kommunikations-, preisbezogene Kriterien, Einkaufsstättenwahl). Investive Dienstleistungen (Empfänger = Unternehmen): 1. branchenbezogene (Art der Branche, Konkurrenzintensität, Bedarfshäufigkeit), 2. unternehmensbezogene (Umsatzgröße, Mitarbeiterzahl, DL-technologische Ausstattung, Budget), 3. gruppenbezogene (Größe des Einkaufsgremiums/Buying Centers, Rollenverteilung, Arbeitsauffassung), 4. personenbezogene (demografische, sozioökonomische, psychologische Kriterien, Verhaltenskriterien).',
    elements: [
      { label: 'Konsumtive Kriterien', meaning: 'Demografisch, sozioökonomisch, psychologisch, verhaltensbezogen.' },
      { label: 'Investive Kriterien', meaning: 'Branchen-, unternehmens-, gruppen- und personenbezogen.' },
    ],
    conceptIds: ['c-benefit-segmentation', 'c-segmentierungskriterien'],
    validation: ok,
  },
  {
    id: 'f-org-modell', chapterId: 'k10', file: 'img-031-027.png', pdfPage: 31,
    title: 'Modell organisationaler Kaufentscheidungen',
    caption: 'Umfeld (Anreize) → Organisation als Käufer (Buying Center, Kaufentscheidungsprozess) → Handeln des Käufers.',
    explanationSimple: 'Reize aus dem Umfeld (Marketing, Wirtschaft, Technologie) treffen auf die kaufende Organisation. Dort läuft im Buying Center der Entscheidungsprozess ab – beeinflusst von einzelnen Personen, ihrem Zusammenspiel und der Organisation. Am Ende stehen konkrete Entscheidungen: Produkt, Lieferant, Mengen, Konditionen.',
    explanationExpert: 'Drei Blöcke: 1. Das Umfeld – Anreize aus dem Marketing (Produkt, Preis, Platzierung, Promotion) und sonstige Anreize (Wirtschaft, Technologie, Politik, Kultur, Wettbewerb). 2. Die Organisation als Käufer – das Buying Center mit dem Kaufentscheidungsprozess, mit Einflüssen der einzelnen handelnden Personen, aus ihrem Zusammenwirken und aus der Organisation. 3. Handeln des Käufers – Kaufentscheidung für ein bestimmtes Produkt bzw. eine Dienstleistung, u. U. Festlegung eines Stammlieferanten, Bestellmenge, Lieferbedingungen, Zusagen über Liefermenge, Kundendienstbedingungen, Zahlungsbedingungen.',
    elements: [
      { label: 'Das Umfeld', meaning: 'Marketinganreize (4 Ps) + sonstige Anreize (Wirtschaft, Technologie, Politik, Kultur, Wettbewerb).' },
      { label: 'Die Organisation als Käufer', meaning: 'Buying Center + Kaufentscheidungsprozess mit personellen, interpersonellen und organisationalen Einflüssen.' },
      { label: 'Handeln des Käufers', meaning: 'Produkt-/Lieferantenwahl, Bestellmengen, Liefer-, Kundendienst- und Zahlungsbedingungen.' },
    ],
    conceptIds: ['c-buying-center', 'c-org-kaufverhalten'],
    validation: ok,
  },
  {
    id: 'f-org-determinanten', chapterId: 'k10', file: 'img-032-028.png', pdfPage: 32,
    title: 'Determinanten des organisationalen Kaufs (Trichter)',
    caption: 'Umweltdeterminanten → innerorganisationale → interpersonale → intrapersonale Determinanten → Kauf.',
    explanationSimple: 'Wie ein Trichter: Außen wirken Umweltfaktoren (z. B. Technik), dann die Organisation selbst, dann die Beziehungen zwischen Personen und schließlich die einzelne Person – ganz unten steht der Kauf.',
    explanationExpert: 'Der umgekehrte Trichter zeigt die Einflussebenen von außen nach innen: Umweltdeterminanten (extern, z. B. Stand der Technik) → innerorganisationale Determinanten (Ziele und Strukturen der Organisation) → interpersonale Determinanten (Zusammenspiel der Beteiligten, z. B. im Buying Center) → intrapersonale Determinanten (direkteste Einflüsse: z. B. Autorität, Stellung in der Hierarchie) → Kauf. Je weiter innen, desto direkter der Einfluss auf die Kaufentscheidung.',
    elements: [
      { label: 'Umweltdeterminanten', meaning: 'Externe Einflüsse, z. B. Stand der Technik (äußerste Ebene).' },
      { label: 'Innerorganisationale Determinanten', meaning: 'Ziele und Strukturen der Organisation.' },
      { label: 'Interpersonale Determinanten', meaning: 'Beziehungen und Zusammenwirken der beteiligten Personen.' },
      { label: 'Intrapersonale Determinanten', meaning: 'Direkteste Einflüsse: Autorität, Hierarchiestellung der Einzelperson.' },
      { label: 'Kauf', meaning: 'Ergebnis an der Trichterspitze.' },
    ],
    misconceptions: ['Die intrapersonalen (nicht die Umwelt-)Determinanten sind die direktesten Einflüsse.'],
    conceptIds: ['c-org-determinanten'],
    validation: ok,
  },
];
