import { Question } from '@/lib/types';

/** Fragenkatalog Kapitel 6–10 (aus dem Modul-PDF abgeleitet). */
export const questions610: Question[] = [
  // ================= Kapitel 6 =================
  {
    id: 'q6-01', chapterId: 'k6', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche Dimensionen gehören zum Big-Five-Modell der Persönlichkeit?',
    options: ['Extraversion', 'Verträglichkeit', 'Gewissenhaftigkeit', 'Neurotizismus', 'Offenheit für Erfahrungen', 'Dominanz'],
    correctOptions: [0, 1, 2, 3, 4],
    explanation: 'Die Big Five: Extraversion, Verträglichkeit, Gewissenhaftigkeit, Neurotizismus (analog emotionale Stabilität) und Offenheit für Erfahrungen – kulturunabhängig. „Dominanz“ gehört nicht dazu.',
    source: 'Kapitel 6.1, PDF S. 12–13', conceptIds: ['c-bigfive'],
  },
  {
    id: 'q6-02', chapterId: 'k6', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Der Kauf eines Einwegfeuerzeugs vs. die Anschaffung einer Photovoltaikanlage – wie unterscheiden sich diese Käufe im Involvement?',
    options: [
      'Feuerzeug = Low Involvement, Photovoltaik = High Involvement',
      'Feuerzeug = High Involvement, Photovoltaik = Low Involvement',
      'Beide sind High Involvement',
      'Involvement spielt bei beiden keine Rolle',
    ],
    correctOptions: [0],
    explanation: 'Involvement = Grad der Beteiligung an der Informationsverarbeitung. Low: niedrige kognitive/emotionale Aktivität (Einwegfeuerzeug); High: hohe Aktivität (Photovoltaikanlage). Auch situative Faktoren wirken.',
    source: 'Kapitel 6.1, PDF S. 13', conceptIds: ['c-involvement'],
  },
  {
    id: 'q6-03', chapterId: 'k6', type: 'assignment', goal: 'application', difficulty: 2,
    prompt: 'Familie Meier kauft ein neues Auto. Ordne die Rollen zu.',
    pairs: [
      { left: 'Initiator', right: 'Die Tochter schlägt vor, ein neues Auto zu kaufen' },
      { left: 'Beeinflusser', right: 'Der Onkel empfiehlt eine bestimmte Marke' },
      { left: 'Entscheider', right: 'Der Vater trifft die endgültige Wahl' },
      { left: 'Käufer', right: 'Die Mutter unterschreibt den Kaufvertrag im Autohaus' },
      { left: 'Nutzer', right: 'Der Sohn fährt das Auto am häufigsten' },
    ],
    explanation: 'Rollen im komplexen Kaufentscheidungsprozess: Initiator, Beeinflusser, Entscheider, Käufer, Nutzer – eine Person kann mehrere Rollen einnehmen.',
    source: 'Kapitel 6.2, PDF S. 13–14', conceptIds: ['c-kaufrollen'],
  },
  {
    id: 'q6-04', chapterId: 'k6', type: 'cloze', goal: 'fact', difficulty: 2,
    prompt: 'Kaufentscheidungen im Haushalt erfolgen entweder ______ (eine Person entscheidet) oder ______ (gemeinsame Entscheidung).',
    clozeAnswers: [['autokratisch'], ['synkratisch']],
    explanation: 'Autokratisch = eine Person, synkratisch = gemeinsam. Der Familienlebenszyklus liefert zusätzliche Segmentierungsrückschlüsse.',
    source: 'Kapitel 6.2, PDF S. 14', conceptIds: ['c-haushalt'],
  },
  {
    id: 'q6-05', chapterId: 'k6', type: 'single_choice', goal: 'fact', difficulty: 2,
    prompt: 'Wofür stehen die drei Buchstaben im AIO-Konzept der Lifestylesegmentierung?',
    options: ['Activities, Interests, Opinions', 'Attitudes, Income, Objectives', 'Actions, Involvement, Orientation', 'Age, Interests, Occupation'],
    correctOptions: [0],
    explanation: 'AIO = Activities, Interests, Opinions. Das Konzept ist westlich orientiert und erlaubt keine universelle Aussage. Weitere Ansätze: Sinus-Milieus, VALS-II.',
    source: 'Kapitel 6.2, PDF S. 14', conceptIds: ['c-vals'],
  },
  {
    id: 'q6-06', chapterId: 'k6', type: 'true_false', goal: 'fact', difficulty: 2,
    prompt: 'Kulturelle Einflussgrößen (soziale Schicht, Kultur, Subkultur) zählen zu den stärksten Einflussgrößen auf das Konsumentenverhalten.',
    correctBool: false,
    explanation: 'Falsch: Laut Skript sind kulturelle Einflussgrößen die SCHWÄCHSTEN Einflussgrößen auf das Konsumentenverhalten.',
    source: 'Kapitel 6.3, PDF S. 14', conceptIds: ['c-soziale-schicht'],
  },
  {
    id: 'q6-07', chapterId: 'k6', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Was ist Ethnomarketing und warum ist es umstritten?',
    rubric: [
      { point: 'Anpassung des Marketing-Mix an ethnische Minderheiten', keywords: ['ethnisch', 'minderheit', 'marketing-mix', 'anpassung'] },
      { point: 'Beispiele: andere Sprache, Zertifizierungen (Halal)', keywords: ['sprache', 'halal', 'zertifizierung', 'greenforce'] },
      { point: 'Kritik: kann Integration verhindern', keywords: ['integration verhindern', 'ausgrenzung', 'segregation'] },
      { point: 'Gegenposition: kann Integration fördern', keywords: ['integration foerdern', 'foerderung', 'andererseits'] },
    ],
    modelAnswer: 'Ethnomarketing ist die Anpassung des Marketing-Mix an ethnische Minderheiten – z. B. Werbung in anderer Sprache oder Zertifizierungen wie Halal. Es ist umstritten: Einerseits kann es Integration verhindern (separate Ansprache), andererseits sprechen manche von Integrationsförderung (Anerkennung der Bedürfnisse).',
    explanation: 'Beide Seiten der Kontroverse nennen können.',
    source: 'Kapitel 6.3, PDF S. 14–15', conceptIds: ['c-ethnomarketing'],
  },
  {
    id: 'q6-08', chapterId: 'k6', type: 'multiple_choice', goal: 'fact', difficulty: 3,
    prompt: 'Welche Dimensionen gehören zu Hofstedes Kulturdimensionen (laut Skript)?',
    options: ['Machtdistanz', 'Unsicherheitsvermeidung', 'Männlichkeit/Weiblichkeit', 'Individualisierung', 'Verarbeitungstiefe'],
    correctOptions: [0, 1, 2, 3],
    explanation: 'Hofstede operationalisiert Kultur u. a. über Machtdistanz, Unsicherheitsvermeidung, Männlichkeit/Weiblichkeit und Individualisierung. „Verarbeitungstiefe“ stammt aus der Lernpsychologie (Kapitel 5).',
    source: 'Kapitel 6.3, PDF S. 15', conceptIds: ['c-hofstede'],
  },
  {
    id: 'q6-09', chapterId: 'k6', type: 'single_choice', goal: 'fact', difficulty: 2,
    prompt: 'Was versteht man unter Microtargeting?',
    options: [
      'Profilanalyse von Personen für genaue Zielansprache durch individuelle Botschaften',
      'Werbung ausschließlich auf kleinen Bildschirmen',
      'Segmentierung nach Unternehmensgröße',
      'Die Analyse von Kleinstmärkten in Nischenbranchen',
    ],
    correctOptions: [0],
    explanation: 'Microtargeting = Profilanalyse der Personen, um sie durch individuelle Botschaften genau anzusprechen – eine zentrale digitale Einflussgröße.',
    source: 'Kapitel 6.4, PDF S. 15', conceptIds: ['c-microtargeting'],
  },
  {
    id: 'q6-10', chapterId: 'k6', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Erkläre, wie Referenzgruppen das Konsumentenverhalten beeinflussen. Gehe auf Anpassung und Abgrenzung ein.',
    rubric: [
      { point: 'Fremdgruppen als reale oder imaginäre Referenz-/Bezugsgruppen', keywords: ['fremdgruppe', 'referenz', 'bezugsgruppe', 'imaginaer'] },
      { point: 'Adaption des Verhaltens der Gruppenmitglieder', keywords: ['adaptier', 'anpass', 'uebernehmen', 'nachahm'] },
      { point: 'Vermeidung von Ausgrenzung/Sanktionen', keywords: ['ausgrenzung', 'sanktion', 'zugehoerigkeit'] },
      { point: 'Demonstrative Abgrenzung mancher Individuen', keywords: ['abgrenz', 'demonstrativ', 'distanzier'] },
      { point: 'Mund-zu-Mund-Propaganda / Meinungsführer', keywords: ['mund-zu-mund', 'meinungsfuehrer', 'word of mouth', 'empfehlung'], weight: 0.5 },
    ],
    modelAnswer: 'Fremdgruppen fungieren als reale oder imaginäre Referenz-/Bezugsgruppen und haben große Bedeutung für die Erklärung menschlichen Verhaltens: Individuen adaptieren das Verhalten der Gruppenmitglieder und vermeiden so Ausgrenzung oder Sanktionen. Manche Individuen grenzen sich dagegen demonstrativ von bestimmten Gruppen ab. Über Mund-zu-Mund-Propaganda und Meinungsführer beeinflussen Gruppen Kaufentscheidungen signifikant.',
    explanation: 'Referenzgruppen wirken in beide Richtungen: Anpassung UND Abgrenzung.',
    source: 'Kapitel 6.2, PDF S. 13', conceptIds: ['c-gruppen', 'c-meinungsfuehrer'],
  },

  // ================= Kapitel 7 =================
  {
    id: 'q7-01', chapterId: 'k7', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordne die Kaufentscheidungsarten den Beschreibungen zu.',
    pairs: [
      { left: 'Impulsiv', right: 'Reiz größtenteils ohne Kognition – animiert direkt zum Handeln' },
      { left: 'Habitualisiert', right: 'Gewohnheitskauf im „Autopilot“, gleiche Marke wird wiederholt gekauft' },
      { left: 'Limitiert', right: 'Auswahl mehrerer Alternativen mit vorhandenem Wissen (z. B. Käsesorten)' },
      { left: 'Extensiv', right: 'Stark emotional & kognitiv involviert, intensiver Informationssuchprozess' },
    ],
    explanation: 'Die vier Arten unterscheiden sich im emotionalen und kognitiven Involvement: impulsiv (E hoch/K niedrig), habitualisiert (beide niedrig), limitiert (K hoch/E niedrig), extensiv (beide hoch).',
    source: 'Kapitel 7.1, PDF S. 15–17', conceptIds: ['c-kaufarten'],
  },
  {
    id: 'q7-02', chapterId: 'k7', type: 'single_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Was ist der zentrale Auslöser der Vorkaufphase?',
    options: [
      'Die Problemerkenntnis: Soll- und Istzustand weichen voneinander ab',
      'Die Werbung eines Anbieters',
      'Die Entsorgung des alten Produkts',
      'Der Preisvergleich',
    ],
    correctOptions: [0],
    explanation: 'Zentral ist die Problemerkenntnis: Ideal-/Soll- und Istzustand weichen ab – über einen Bedarf (Ist sinkt) oder eine Gelegenheit (Ideal steigt). Die Differenz muss groß genug sein, um als Problem wahrgenommen zu werden.',
    source: 'Kapitel 7.2, PDF S. 17–18', conceptIds: ['c-problemerkenntnis'],
  },
  {
    id: 'q7-03', chapterId: 'k7', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Wie verhält sich das Consideration Set zum Evoked Set?',
    options: [
      'Das Consideration Set ist die engere Auswahl aus dem Evoked Set',
      'Das Evoked Set ist eine Teilmenge des Consideration Sets',
      'Beide Begriffe sind identisch',
      'Das Consideration Set enthält nur unbekannte Alternativen',
    ],
    correctOptions: [0],
    explanation: 'Evoked Set = Menge der bekannten Alternativen; Consideration Set = die engere Auswahl daraus, die tatsächlich in Frage kommt.',
    source: 'Kapitel 7.2, PDF S. 18', conceptIds: ['c-evoked-set', 'c-consideration-set'],
  },
  {
    id: 'q7-04', chapterId: 'k7', type: 'cloze', goal: 'fact', difficulty: 2,
    prompt: 'Die Kaufphase gliedert sich in: 1. ______identifikation, 2. ______entwicklung, 3. Kauf.',
    clozeAnswers: [['Alternativen', 'Alternativen-'], ['Intentions', 'Intention', 'Intentions-']],
    explanation: 'Kaufphase: Alternativenidentifikation → Intentionsentwicklung → Kauf. Bei Impulskäufen entfällt die Alternativenidentifikation.',
    source: 'Kapitel 7.3, PDF S. 18–19', conceptIds: ['c-kaufphase'],
  },
  {
    id: 'q7-05', chapterId: 'k7', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche POS-Aktivitäten nennt das Skript?',
    options: ['Verkaufsraumgestaltung', 'Verkaufsgespräch (verbal und nonverbal)', 'Verbundkäufe/Cross-Buyings', 'Services (Muss- und Kann-Leistungen)', 'Preisverhandlungen mit Lieferanten'],
    correctOptions: [0, 1, 2, 3],
    explanation: 'POS-Aktivitäten: Verkaufsraumgestaltung, Verkaufsgespräch (auch nonverbal, z. B. Haltung), Verbundkäufe/Cross-Buyings (Up-Sell) und Services. Lieferantenverhandlungen gehören zum organisationalen Einkauf.',
    source: 'Kapitel 7.3, PDF S. 19', conceptIds: ['c-pos'],
  },
  {
    id: 'q7-06', chapterId: 'k7', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Beschreibe die vier Schritte der Nachkauf- und Nutzungsphase und erkläre, warum diese Phase für Unternehmen so wichtig ist.',
    rubric: [
      { point: 'Konsum', keywords: ['konsum', 'nutzung'] },
      { point: 'Evaluierung (erwartete vs. tatsächliche Leistung)', keywords: ['evaluier', 'bewert', 'vergleich', 'erwartung'] },
      { point: 'Ggf. Beschwerde', keywords: ['beschwerde'] },
      { point: 'Entsorgung (entsorgen, tauschen, verschenken, verkaufen)', keywords: ['entsorg', 'tauschen', 'verschenken', 'verkaufen'] },
      { point: '„Pole-Position“ für langfristige Kundenbeziehungen', keywords: ['pole', 'kundenbeziehung', 'langfristig', 'kundenbindung'] },
    ],
    modelAnswer: 'Ablauf: 1. Konsum, 2. Evaluierung (Vergleich von erwarteter und tatsächlicher Leistung → Zufriedenheit, Unzufriedenheit oder Indifferenz), 3. ggf. Beschwerde, 4. Entsorgung (entsorgen, tauschen, verschenken, verkaufen). Die Phase nimmt für langfristige Kundenbeziehungen die „Pole-Position“ ein – hier entscheidet sich, ob der Kunde wiederkommt.',
    explanation: 'Die Nachkaufphase ist der Startpunkt der Kundenbindung.',
    source: 'Kapitel 7.4, PDF S. 19–20', conceptIds: ['c-nachkaufphase'],
  },
  {
    id: 'q7-07', chapterId: 'k7', type: 'true_false', goal: 'distinction', difficulty: 2,
    prompt: 'Beschwerde und Reklamation sind rechtlich dasselbe – Unternehmen müssen auf beide gleichermaßen eingehen.',
    correctBool: false,
    explanation: 'Falsch: Eine Beschwerde beruht auf einer subjektiv empfundenen Schädigung; Unternehmen müssen darauf nicht eingehen (anders als bei berechtigten Reklamationen).',
    source: 'Kapitel 7.4, PDF S. 20', conceptIds: ['c-beschwerde'],
  },
  {
    id: 'q7-08', chapterId: 'k7', type: 'single_choice', goal: 'distinction', difficulty: 3,
    prompt: 'Bei welcher Preisbestimmungsmethode werden Probanden zu VIER Preispunkten befragt (zu günstig, angemessen, gerade noch akzeptabel, zu teuer)?',
    options: ['Van-Westendorp-Methode (Price-Sensitivity-Meter)', 'Gabor-Granger-Methode', 'Vickrey-Auktion', 'Conjoint-Analyse'],
    correctOptions: [0],
    explanation: 'Van-Westendorp erweitert Gabor-Granger um vier Fragen zur Preisbereitschaft. Gabor-Granger nutzt 5 Preispunkte mit Kaufbereitschaftsskala; Vickrey und Conjoint sind indirekte Methoden.',
    source: 'Kapitel 7.5, PDF S. 20–21', conceptIds: ['c-van-westendorp', 'c-gabor-granger'],
  },
  {
    id: 'q7-09', chapterId: 'k7', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Erkläre die Gabor-Granger-Methode: Vorgehen und Ermittlung des optimalen Preises.',
    rubric: [
      { point: '5 Preispunkte werden vorgegeben', keywords: ['5 preispunkte', 'fuenf preispunkte', 'preispunkte'] },
      { point: 'Kaufbereitschaft auf fünfstufiger Skala', keywords: ['skala', 'kaufbereitschaft', 'fuenfstufig'] },
      { point: 'Übertragung in Koordinatensystem (Kaufwahrscheinlichkeit/Preis)', keywords: ['koordinatensystem', 'kurve', 'achse', 'kaufwahrscheinlichkeit'] },
      { point: 'Stärkster Kurvenabfall = optimaler Preis', keywords: ['kurvenabfall', 'staerkster abfall', 'optimaler preis'] },
    ],
    modelAnswer: 'Probanden werden 5 Preispunkte eines Produkts vorgegeben; für jeden geben sie auf einer fünfstufigen Skala ihre Kaufbereitschaft an. Die Ergebnisse werden in ein Koordinatensystem übertragen (eine Achse: Kaufwahrscheinlichkeit, andere Achse: Preis). Der Punkt mit dem stärksten Kurvenabfall markiert den optimalen Preis.',
    explanation: 'Direkte Preisbestimmungsmethode – Grundlage für die Van-Westendorp-Erweiterung.',
    source: 'Kapitel 7.5, PDF S. 20', conceptIds: ['c-gabor-granger'],
  },
  {
    id: 'q7-10', chapterId: 'k7', type: 'single_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Warum wirken gebrochene Preise wie 10,99 € günstiger als 11,00 €?',
    options: [
      'Wegen des Primacy-Effekts werden Zahlen nach dem Komma schwächer wahrgenommen',
      'Weil Kunden grundsätzlich nicht rechnen können',
      'Wegen des Recency-Effekts werden die letzten Ziffern überbewertet',
      'Weil das Komma optisch den Preis verkürzt',
    ],
    correctOptions: [0],
    explanation: 'Gemäß Primacy-Effekt dominiert die erste Ziffer die Wahrnehmung – Zahlen nach dem Komma werden schwächer wahrgenommen, gebrochene Preise wirken günstiger.',
    source: 'Kapitel 7.5, PDF S. 20', conceptIds: ['c-primacy-preis'],
  },
  {
    id: 'q7-11', chapterId: 'k7', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein Online-Shop stellt fest, dass viele Kunden Produkte in den Warenkorb legen, aber nicht kaufen. Erkläre mit der „zeitlichen Ausdehnung der Kaufphase“, welche Verläufe möglich sind, und nenne eine Gegenmaßnahme.',
    rubric: [
      { point: 'Kauf stockt und wird fortgesetzt oder abgebrochen', keywords: ['stockt', 'fortgesetzt', 'abgebrochen', 'abbruch'] },
      { point: 'Neue Alternativenidentifikation/Evaluation oder neue Informationssuche', keywords: ['alternativen', 'evaluation', 'informationssuche', 'neu'] },
      { point: 'Reize zwischen Intention und Kauf wirken beschleunigend/bremsend', keywords: ['reiz', 'intention', 'beschleunig', 'brems', 'stimuli'] },
      { point: 'Gegenmaßnahme (z. B. Verknappung, Erinnerung, einfacher Checkout)', keywords: ['verknappung', 'erinnerung', 'remarketing', 'checkout', 'rabatt', 'lieferengpass'] },
    ],
    modelAnswer: 'Zwischen Intentionsentwicklung und Kauf liegt Zeit, in der Reize wirken: Der Prozess kann stocken und fortgesetzt oder abgebrochen werden, oder der Kunde startet eine neue Alternativenidentifikation/Evaluation bzw. einen neuen Informationssuchprozess (z. B. Preisvergleich). Gegenmaßnahmen: beschleunigende Reize wie Verknappungshinweise („nur noch 2 verfügbar“), Erinnerungs-Mails oder ein besonders einfacher Checkout.',
    explanation: 'Die vier Verläufe der zeitlichen Ausdehnung erklären Warenkorbabbrüche direkt.',
    source: 'Kapitel 7.3, PDF S. 19–20', conceptIds: ['c-kaufphase'],
  },

  // ================= Kapitel 8 =================
  {
    id: 'q8-01', chapterId: 'k8', type: 'cloze', goal: 'fact', difficulty: 1,
    prompt: 'Erfolgskette: Kundenorientierung → Kunden______ → Kunden______ → Kundenwert.',
    clozeAnswers: [['zufriedenheit'], ['bindung']],
    explanation: 'Die Erfolgskette der Kundenorientierung: Kundenorientierung → Kundenzufriedenheit → Kundenbindung → Kundenwert, moderiert durch externe und interne Faktoren.',
    source: 'Kapitel 8.1, PDF S. 21', conceptIds: ['c-erfolgskette'],
  },
  {
    id: 'q8-02', chapterId: 'k8', type: 'multiple_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Über welche Effekte wirkt Kundenzufriedenheit positiv auf den Unternehmenserfolg?',
    options: ['Wiedereinkäufe', 'Cross-Buyings', 'Geringere Preissensibilität', 'Positive Mund-zu-Mund-Propaganda', 'Höhere Beschaffungskosten'],
    correctOptions: [0, 1, 2, 3],
    explanation: 'Positive Zufriedenheitseffekte: Wiederkäufe, Cross-Buyings, geringere Preissensibilität und positive Mund-zu-Mund-Propaganda.',
    source: 'Kapitel 8.1, PDF S. 21–22', conceptIds: ['c-kundenzufriedenheit'],
  },
  {
    id: 'q8-03', chapterId: 'k8', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Was sind Nachkaufdissonanzen, wie mildern Käufer sie und wie können Unternehmen proaktiv reagieren?',
    rubric: [
      { point: 'Störgefühle/Zweifel nach dem Kauf', keywords: ['stoergefuehl', 'zweifel', 'nach dem kauf', 'dissonanz'] },
      { point: 'Milderung 1: Entscheidung bestätigen (z. B. Testberichte)', keywords: ['bestaetig', 'testbericht', 'rechtfertig'] },
      { point: 'Milderung 2: Kauf rückgängig machen', keywords: ['rueckgaengig', 'zurueckgeben', 'storno'] },
      { point: 'Unternehmen: Rückgabemöglichkeit, gratulierendes Begleitmaterial', keywords: ['rueckgabe', 'begleitmaterial', 'gratulier', 'proaktiv'] },
      { point: 'Bewusste Verstärkung kann zu neuen Produkten animieren', keywords: ['verstaerk', 'neue produkte', 'animieren'], weight: 0.5 },
    ],
    modelAnswer: 'Nachkaufdissonanzen sind Störgefühle oder Zweifel nach dem Kauf (z. B. neue Kleidung wird belächelt, die finanzielle Lage wird bewusst). Käufer mildern sie, indem sie ihre Entscheidung bestätigen (positive Testberichte) oder den Kauf rückgängig machen. Unternehmen sollten proaktiv handeln: Rückgabemöglichkeiten anbieten oder Produktbegleitmaterial einsetzen, das zum Kauf gratuliert. Manchmal werden Dissonanzen sogar bewusst verstärkt, um zur Nutzung neuer Produkte zu animieren.',
    explanation: 'Klassisches Konzept der kognitiven Dissonanz im Nachkaufkontext.',
    source: 'Kapitel 8.1, PDF S. 22', conceptIds: ['c-nachkaufdissonanz'],
  },
  {
    id: 'q8-04', chapterId: 'k8', type: 'assignment', goal: 'distinction', difficulty: 3,
    prompt: 'Ordne die Formen der Kundenloyalität zu.',
    pairs: [
      { left: 'Bedingte Kundenloyalität', right: 'Freiwillige Kundenbindung' },
      { left: 'Oberflächliche Kundenloyalität', right: 'Ausschließliche Wiederkäufer – auch durch Zwang wie Abos' },
      { left: 'Commitment', right: 'Langfristige Geschäftsbeziehung mit eingeschränkter Wahlfreiheit und hoher Unzufriedenheitstoleranz' },
    ],
    explanation: 'Kundenbindung bedingt Kundenloyalität, oberflächliche Loyalität und Commitment – Commitment toleriert Unzufriedenheit besonders stark.',
    source: 'Kapitel 8.2, PDF S. 22', conceptIds: ['c-kundenbindung'],
  },
  {
    id: 'q8-05', chapterId: 'k8', type: 'single_choice', goal: 'distinction', difficulty: 3,
    prompt: 'Ein zufriedener Kunde wechselt trotzdem regelmäßig die Shampoo-Marke, „einfach mal was anderes“. Welches Konzept beschreibt das?',
    options: ['Variety Seeking', 'Nachkaufdissonanz', 'Commitment', 'Reizdiskriminierung'],
    correctOptions: [0],
    explanation: 'Variety Seeking: Bei niedrigem Involvement wechseln Kunden trotz fehlender Unzufriedenheit den Anbieter, weil sie nach Abwechslung streben. Wichtig: Der Wechsel geschieht OHNE Unzufriedenheit.',
    source: 'Kapitel 8.2, PDF S. 23', conceptIds: ['c-variety-seeking'],
  },
  {
    id: 'q8-06', chapterId: 'k8', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordne die Ebenen der Kundenbindung den Beispielen zu.',
    pairs: [
      { left: 'Organisations-/Unternehmensebene', right: 'B2B: Verzahnung von Arbeitsabläufen zweier Unternehmen' },
      { left: 'Personenebene', right: 'Man geht immer zum selben Friseur wegen der Person' },
      { left: 'Leistungsebene', right: 'Konsumgüter: Bindung über Funktionsumfang und Design' },
    ],
    explanation: 'Drei Ebenen: Unternehmensebene (v. a. B2B), Personenebene (v. a. Dienstleistungen), Leistungsebene (für Konsumgüterhersteller oft die einzige Ebene).',
    source: 'Kapitel 8.2, PDF S. 22–23', conceptIds: ['c-bindungsebenen'],
  },
  {
    id: 'q8-07', chapterId: 'k8', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Definiere Kundenwert aus Unternehmens- und aus Nachfragersicht.',
    rubric: [
      { point: 'Unternehmenssicht: Beitrag zu monetären und nicht-monetären Zielen', keywords: ['monetaer', 'nicht monetaer', 'beitrag', 'unternehmensziel'] },
      { point: 'Beispiel nicht-monetär: Feedback zur Produktoptimierung', keywords: ['feedback', 'produktoptimierung'], weight: 0.5 },
      { point: 'Nachfragersicht: Leistungswert', keywords: ['leistungswert', 'funktionsumfang', 'preis'] },
      { point: 'Markenwert und Beziehungswert', keywords: ['markenwert', 'beziehungswert', 'image', 'wertschaetzung'] },
    ],
    modelAnswer: 'Aus Unternehmenssicht ist der Kundenwert der Beitrag des Kunden zum Erreichen monetärer und nicht-monetärer Unternehmensziele (nicht-monetär z. B. Feedback zur Produktoptimierung). Aus Nachfragersicht besteht er aus Leistungswert (Funktionsumfang, Leistung, Preis), Markenwert (Image, symbolische Assoziationen) und Beziehungswert (Wertschätzung, Kommunikation).',
    explanation: 'Beide Perspektiven unterscheiden können.',
    source: 'Kapitel 8.2, PDF S. 23', conceptIds: ['c-kundenwert'],
  },
  {
    id: 'q8-08', chapterId: 'k8', type: 'true_false', goal: 'understanding', difficulty: 2,
    prompt: 'Mehr Service führt immer zu höherer Kundenzufriedenheit und höherem Unternehmenswert.',
    correctBool: false,
    explanation: 'Falsch: In der „Zone der Übertreibung“ (Overservicing) kann zusätzlicher Service den Wert sogar senken – z. B. würde ein zweiter Kellner die Servicequalität kaum verbessern oder sogar schwächen, weil sich der Kunde zu sehr umsorgt fühlt.',
    source: 'Kapitel 8.1, PDF S. 22', conceptIds: ['c-kundenzufriedenheit'],
  },

  // ================= Kapitel 9 =================
  {
    id: 'q9-01', chapterId: 'k9', type: 'assignment', goal: 'fact', difficulty: 2,
    prompt: 'Ordne die Dimensionen der Dienstleistung zu.',
    pairs: [
      { left: 'Potenzialdimension', right: 'Leistungsfähigkeit des Anbieters: tangible und intangible Faktoren (Equipment, Erfahrung)' },
      { left: 'Prozessdimension', right: 'Einbeziehung interner und externer Faktoren – oft des Kunden selbst' },
      { left: 'Ergebnisdimension', right: 'Immaterialität: weder transport- noch lagerfähig' },
    ],
    explanation: 'Die drei Dimensionen der Dienstleistung: Potenzial (Können), Prozess (Erstellung mit dem Kunden), Ergebnis (immateriell).',
    source: 'Kapitel 9.1, PDF S. 24–26', conceptIds: ['c-dl-dimensionen'],
  },
  {
    id: 'q9-02', chapterId: 'k9', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Nach welchen vier Merkmalen (4 Ls) werden Dienstleistungen typologisiert?',
    options: ['Integration', 'Interaktion', 'Individualisierung', 'Immaterialität', 'Internationalisierung'],
    correctOptions: [0, 1, 2, 3],
    explanation: 'Die 4 Ls der Leistungstypologie: Integration, Interaktion, Individualisierung, Immaterialität – jeweils von gering (Mass Services wie Reinigung) bis hoch (Speciality Services wie Rechtsberatung).',
    source: 'Kapitel 9.1, PDF S. 26', conceptIds: ['c-4ls'],
  },
  {
    id: 'q9-03', chapterId: 'k9', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Was versteht man unter der Beurteilungsproblematik bei Dienstleistungen, und wie können Konsumenten und Anbieter damit umgehen?',
    rubric: [
      { point: 'Qualität ist vor dem Kauf schwer einschätzbar', keywords: ['vor dem kauf', 'schwer', 'qualitaet', 'einschaetz', 'beurteil'] },
      { point: 'Besonders bedeutend in der Vorkonsum-/Vorkaufphase', keywords: ['vorkonsum', 'vorkauf'] },
      { point: 'Sucheigenschaften nutzen (Testergebnisse, Preise, Ausstattung)', keywords: ['sucheigenschaft', 'testergebnis', 'preis', 'ausstattung', 'equipment'] },
      { point: 'Vertrauen (v. a. Spezialdienstleister wie Arzt), Kostenvoranschläge', keywords: ['vertrauen', 'arzt', 'kostenvoranschlag', 'garantie'] },
    ],
    modelAnswer: 'Die Beurteilungsproblematik: Bei Dienstleistungen ist die erhaltene Qualität vor dem Kauf schwer einzuschätzen – besonders bedeutend in der Vorkonsumphase. Konsumenten schließen über Sucheigenschaften (Testergebnisse, Preise, Raumausstattung/Equipment) auf das spätere Ergebnis; bei Spezialdienstleistern (z. B. Arzt) ist Vertrauen besonders relevant. Der hohe Evaluationsaufwand (z. B. Kostenvoranschläge einholen) schränkt den Auswahlprozess deutlich ein.',
    explanation: 'Kernproblem der Dienstleistung: Immaterialität → Unsicherheit vor dem Kauf.',
    source: 'Kapitel 9.1, PDF S. 26–27', conceptIds: ['c-beurteilungsproblematik'],
  },
  {
    id: 'q9-04', chapterId: 'k9', type: 'cloze', goal: 'fact', difficulty: 2,
    prompt: 'Service-Erfolgskette: Aktivitäten des Dienstleistungsmarketings → ______ Wirkungen (z. B. Zufriedenheit, Image) → ______wirkungen (z. B. Wiederkauf) → ökonomischer Erfolg.',
    clozeAnswers: [['psychologische', 'psychologisch'], ['Verhaltens', 'Verhaltens-']],
    explanation: 'Die Kette: Marketingaktivitäten → psychologische Wirkungen → Verhaltenswirkungen → ökonomischer Erfolg; die Komponenten beeinflussen sich gegenseitig.',
    source: 'Kapitel 9.2, PDF S. 27', conceptIds: ['c-service-erfolgskette'],
  },
  {
    id: 'q9-05', chapterId: 'k9', type: 'assignment', goal: 'distinction', difficulty: 3,
    prompt: 'Ordne die Qualitätsdimensionen der Dienstleistungsqualität zu.',
    pairs: [
      { left: 'Tangibles', right: 'Erscheinungsbild von Räumen, Equipment und Mitarbeitern' },
      { left: 'Reliability', right: 'Zugesagte Leistung zuverlässig auf vereinbartem Niveau erfüllen' },
      { left: 'Responsiveness', right: 'Bereitschaft und Schnelligkeit, auf Kundenwünsche einzugehen' },
      { left: 'Assurance', right: 'Leistungskompetenz: Know-how, Höflichkeit, Vertrauenswürdigkeit' },
      { left: 'Empathy', right: 'Individuelle Fürsorge und Aufmerksamkeit für jeden Kunden' },
    ],
    explanation: 'Die fünf Qualitätsdimensionen der wahrgenommenen Dienstleistungsqualität (SERVQUAL-Logik).',
    source: 'Kapitel 9.2, PDF S. 28', conceptIds: ['c-qualitaetswahrnehmung'],
  },
  {
    id: 'q9-06', chapterId: 'k9', type: 'true_false', goal: 'understanding', difficulty: 2,
    prompt: 'Beim Erwerb von Dienstleistungen ist das gefühlte Risiko oft höher als beim Kauf von Sachgütern.',
    correctBool: true,
    explanation: 'Richtig – deshalb sollten Anbieter proaktiv Risiko minimieren, z. B. Garantien für Vertrauen einsetzen.',
    source: 'Kapitel 9.2, PDF S. 28', conceptIds: ['c-risikowahrnehmung'],
  },
  {
    id: 'q9-07', chapterId: 'k9', type: 'single_choice', goal: 'fact', difficulty: 3,
    prompt: 'Welche zwei Anforderungen muss JEDES Segmentierungskriterium erfüllen (nicht nur der Gesamtkriterienkatalog)?',
    options: [
      'Zeitliche Stabilität und Messbarkeit',
      'Wirtschaftlichkeit und Erreichbarkeit',
      'Kaufverhaltensrelevanz und Handlungsfähigkeit',
      'Dienstleistungsbezug und Wirtschaftlichkeit',
    ],
    correctOptions: [0],
    explanation: 'Zeitliche Stabilität und Messbarkeit müssen von jedem Kriterium erfüllt werden; die übrigen Anforderungen (Kaufverhaltensrelevanz, Erreichbarkeit, Handlungsfähigkeit, Wirtschaftlichkeit, Dienstleistungsbezug) nur für den Gesamtkriterienkatalog.',
    source: 'Kapitel 9.3, PDF S. 28–29', conceptIds: ['c-segmentierungskriterien'],
  },
  {
    id: 'q9-08', chapterId: 'k9', type: 'open', goal: 'distinction', difficulty: 2,
    prompt: 'Was ist Benefit Segmentation, und worin unterscheiden sich konsumtive und investive Dienstleistungen?',
    rubric: [
      { point: 'Benefit Segmentation = Segmentierung nach Nutzenerwartungen', keywords: ['nutzenerwartung', 'nutzen', 'benefit'] },
      { point: 'Konsumtiv: Empfänger = Konsument', keywords: ['konsument', 'konsumtiv', 'privat'] },
      { point: 'Investiv: Empfänger = Unternehmen', keywords: ['unternehmen', 'investiv', 'b2b'] },
      { point: 'Motive wegen Messbarkeit ungeeignet / Lifestyle als Alternative', keywords: ['motive', 'messbarkeit', 'lifestyle'], weight: 0.5 },
    ],
    modelAnswer: 'Benefit Segmentation ist die Segmentierung nach Nutzenerwartungen der Kunden. Konsumtive Dienstleistungen richten sich an Konsumenten (Empfänger = Konsument), investive an Unternehmen (Empfänger = Unternehmen). Motive sind wegen unzureichender Messbarkeit als Kriterium eher ungeeignet; Lifestyle-Kriterien eignen sich, wenn sonst hoher finanzieller Messaufwand entsteht.',
    explanation: 'Die Unterscheidung konsumtiv/investiv bestimmt die passenden Segmentierungskriterien.',
    source: 'Kapitel 9.3, PDF S. 29', conceptIds: ['c-benefit-segmentation'],
  },
  {
    id: 'q9-09', chapterId: 'k9', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein neues Fitnessstudio will Vertrauen bei Erstkunden aufbauen (hohe Beurteilungsproblematik). Leite aus Kapitel 9 drei konkrete Maßnahmen ab.',
    rubric: [
      { point: 'Sucheigenschaften sichtbar machen (Ausstattung, Testergebnisse, Bewertungen)', keywords: ['ausstattung', 'equipment', 'bewertung', 'testergebnis', 'sucheigenschaft', 'probetraining'] },
      { point: 'Garantien/Risikominimierung (z. B. Geld-zurück, kostenloses Probetraining)', keywords: ['garantie', 'geld-zurueck', 'risiko', 'probetraining', 'kostenlos'] },
      { point: 'Interaktion/Kontrolle: Kunde einbeziehen, Personal, Beziehungsqualität', keywords: ['interaktion', 'kontrolle', 'personal', 'beziehung', 'betreuung'] },
    ],
    modelAnswer: 'Erstens Sucheigenschaften sichtbar machen: moderne Ausstattung zeigen, Bewertungen/Testergebnisse und transparente Preise kommunizieren. Zweitens Risiko minimieren: Garantien wie kostenloses Probetraining oder Geld-zurück-Optionen anbieten. Drittens die Interaktionsqualität sichern: kompetentes, freundliches Personal und dem Kunden wahrgenommene Kontrolle geben (z. B. individuelle Trainingspläne) – je mehr Kontrolle der Kunde wahrnimmt, desto besser die Bewertung.',
    explanation: 'Beurteilungsproblematik → Sucheigenschaften, Garantien und Interaktionsqualität als Antworten.',
    source: 'Kapitel 9.1–9.2, PDF S. 26–28', conceptIds: ['c-beurteilungsproblematik', 'c-risikowahrnehmung'],
  },

  // ================= Kapitel 10 =================
  {
    id: 'q10-01', chapterId: 'k10', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche Charakteristika kennzeichnen organisationale Kaufentscheidungen (B2B)?',
    options: ['Wenige Anbieter und Nachfrager', 'Multipersonale Entscheidungen', 'Kurze Absatzwege (häufig Direktvertrieb)', 'Lange Entscheidungsprozesse', 'Impulskäufe als Regelfall'],
    correctOptions: [0, 1, 2, 3],
    explanation: 'B2B: wenige Marktteilnehmer, multipersonale Entscheidungen, Direktvertrieb, lange Entscheidungsprozesse, intensive Verhandlungen, hoher Individualisierungsgrad. Impulskäufe sind gerade NICHT übertragbar.',
    source: 'Kapitel 10.1, PDF S. 30', conceptIds: ['c-b2b-charakteristika'],
  },
  {
    id: 'q10-02', chapterId: 'k10', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordne die Arten der organisationalen Kaufentscheidung zu.',
    pairs: [
      { left: 'Identischer Wiederkauf', right: 'Routinekauf gleicher Produkte auf Basis vergangener Bestellungen' },
      { left: 'Modifizierter Wiederkauf', right: 'Grundform bereits erfolgt, aber z. B. bei Preis oder Eigenschaften abgewandelt' },
      { left: 'Erstkauf', right: 'Risikohaft – keine bisherigen Erfahrungen vorhanden' },
    ],
    explanation: 'Drei Haupttypen: identischer Wiederkauf, modifizierter Wiederkauf, Erstkauf. Die Art beeinflusst z. B. die Intensität der Informationssuche.',
    source: 'Kapitel 10.1, PDF S. 31', conceptIds: ['c-wiederkauf-arten'],
  },
  {
    id: 'q10-03', chapterId: 'k10', type: 'single_choice', goal: 'fact', difficulty: 2,
    prompt: 'Was ist das Buying Center?',
    options: [
      'Der Sammelbegriff für alle an einem Einkauf beteiligten Personen – keine eigene Abteilung',
      'Die Einkaufsabteilung eines Unternehmens',
      'Ein zentrales Einkaufszentrum für B2B-Produkte',
      'Eine Software für Beschaffungsprozesse',
    ],
    correctOptions: [0],
    explanation: 'Das Buying Center ist der Sammelbegriff für alle am Einkauf beteiligten Personen – ausdrücklich KEINE eigene Abteilung. Rollen: u. a. Initiator, Beeinflusser, Informationsselektierer/Gatekeeper.',
    source: 'Kapitel 10.2, PDF S. 31', conceptIds: ['c-buying-center'],
  },
  {
    id: 'q10-04', chapterId: 'k10', type: 'cloze', goal: 'fact', difficulty: 3,
    prompt: 'Phasen der Geschäftsbeziehung: 1. Aufmerksamkeit, 2. ______, 3. Ausweitung, 4. ______, 5. Auflösung.',
    clozeAnswers: [['Erkundung'], ['Bindung']],
    explanation: 'Phasen: Aufmerksamkeit → Erkundung (Erwartungsaufbau, Verhandlungen) → Ausweitung (nach ersten positiven Abschlüssen) → Bindung → Auflösung.',
    source: 'Kapitel 10.1, PDF S. 30–31', conceptIds: ['c-geschaeftsbeziehungen'],
  },
  {
    id: 'q10-05', chapterId: 'k10', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Nenne mindestens fünf der acht Prozessphasen des organisationalen Kaufverhaltens (bei Erstkäufen) in sinnvoller Reihenfolge.',
    rubric: [
      { point: 'Problemerkennung', keywords: ['problemerkennung', 'problem'] },
      { point: 'Beschreibung des Bedarfs / Festlegung der Eigenschaften', keywords: ['bedarf', 'eigenschaften', 'beschreibung', 'festlegung'] },
      { point: 'Lieferantensuche / Angebotseinholung', keywords: ['lieferantensuche', 'angebot', 'suche'] },
      { point: 'Auswahl der Lieferanten / Bestellverfahren', keywords: ['auswahl', 'bestellverfahren', 'festlegung der lieferanten'] },
      { point: 'Überprüfung von Qualität und Leistungsfähigkeit', keywords: ['ueberpruefung', 'qualitaet', 'leistungsfaehigkeit', 'kontrolle'] },
    ],
    modelAnswer: '1. Problemerkennung, 2. Beschreibung des Bedarfs, 3. Festlegung der Produkt-/Dienstleistungseigenschaften, 4. Suche nach Lieferanten/Angeboten, 5. Einholung von Angeboten, 6. Auswahl und Festlegung der Lieferanten, 7. Festlegung des Bestellverfahrens, 8. Überprüfung von Qualität und Leistungsfähigkeit der Lieferanten. Bei Wiederkäufen sind die Phasen entsprechend verkürzt.',
    explanation: 'Die Phasen beziehen sich auf Erstkäufe; Phasen können hinzukommen oder übersprungen werden.',
    source: 'Kapitel 10.2, PDF S. 31', conceptIds: ['c-prozessphasen-org'],
  },
  {
    id: 'q10-06', chapterId: 'k10', type: 'single_choice', goal: 'distinction', difficulty: 3,
    prompt: 'Welche Determinanten haben die DIREKTESTEN Einflüsse auf den organisationalen Kaufprozess?',
    options: [
      'Intrapersonale Determinanten (z. B. Autorität, Stellung in der Hierarchie)',
      'Umweltdeterminanten (z. B. Stand der Technik)',
      'Innerorganisationale Determinanten (Ziele und Strukturen)',
      'Konjunkturelle Determinanten',
    ],
    correctOptions: [0],
    explanation: 'Die intrapersonalen Determinanten (Autorität, Hierarchiestellung) sind die direktesten Einflüsse – im Trichtermodell die innerste Ebene vor dem Kauf. Umweltdeterminanten sind die äußerste Ebene.',
    source: 'Kapitel 10.2, PDF S. 32', conceptIds: ['c-org-determinanten'],
  },
  {
    id: 'q10-07', chapterId: 'k10', type: 'true_false', goal: 'understanding', difficulty: 2,
    prompt: 'Die Arten der Kaufentscheidungen von Konsumgütermärkten (habitualisiert, limitiert, extensiv, impulsiv) sind vollständig auf das organisationale Kaufverhalten übertragbar.',
    correctBool: false,
    explanation: 'Falsch: Sie sind bis auf die IMPULSIVE Kaufentscheidung anwendbar – Impulskäufe passen nicht zu organisationalen, extensiven Entscheidungsprozessen.',
    source: 'Kapitel 10.1, PDF S. 31', conceptIds: ['c-wiederkauf-arten', 'c-org-kaufverhalten'],
  },
  {
    id: 'q10-08', chapterId: 'k10', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein Softwareanbieter will an einen Mittelständler verkaufen. Im Unternehmen gibt es eine IT-Leiterin (prüft Angebote technisch), einen Geschäftsführer (entscheidet), einen Assistenten (filtert eingehende Anbieter-Mails) und Mitarbeitende (nutzen die Software). Analysiere die Buying-Center-Rollen und leite eine Vertriebsempfehlung ab.',
    rubric: [
      { point: 'Gatekeeper erkannt (Assistent filtert Informationen)', keywords: ['gatekeeper', 'informationsselektierer', 'filter'] },
      { point: 'Entscheider (Geschäftsführer), Beeinflusser (IT-Leiterin), Nutzer (Mitarbeitende)', keywords: ['entscheider', 'beeinflusser', 'nutzer', 'initiator'] },
      { point: 'Empfehlung: verschiedene Rollen gezielt und unterschiedlich ansprechen', keywords: ['ansprechen', 'zielgruppen', 'unterschiedlich', 'argumniete', 'technisch', 'wirtschaftlich', 'vertrieb'] },
      { point: 'Beziehungsaufbau/persönliche Kontakte (Geschäftsbeziehung)', keywords: ['beziehung', 'persoenlich', 'kontakt', 'vertrauen'], weight: 0.5 },
    ],
    modelAnswer: 'Rollen: Der Assistent ist Gatekeeper/Informationsselektierer (muss passiert werden), die IT-Leiterin ist Beeinflusserin (technische Prüfung), der Geschäftsführer ist Entscheider, die Mitarbeitenden sind Nutzer. Empfehlung: jede Rolle passend ansprechen – dem Gatekeeper relevante, knappe Informationen liefern; der IT-Leiterin technische Argumente und Testzugänge; dem Geschäftsführer wirtschaftliche Argumente (ROI); die Nutzerperspektive über Usability-Demos einbinden. Da Geschäftsbeziehungen im B2B das A und O sind, sollte früh persönlicher Kontakt und Vertrauen aufgebaut werden.',
    explanation: 'Buying-Center-Analyse ist die Grundlage erfolgreicher B2B-Vertriebsstrategien.',
    source: 'Kapitel 10.2, PDF S. 31–32', conceptIds: ['c-buying-center', 'c-geschaeftsbeziehungen'],
  },
];
