import { Question } from '@/lib/types';

/** Fragenkatalog Kapitel 1–5 (aus dem Modul-PDF abgeleitet). */
export const questions15: Question[] = [
  // ================= Kapitel 1 =================
  {
    id: 'q1-01', chapterId: 'k1', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Was versteht man unter Konsumentenverhalten im engeren Sinn?',
    options: [
      'Das beobachtbare, äußere Verhalten beim Kauf oder Konsum wirtschaftlicher Güter',
      'Alle inneren psychischen Prozesse während des Kaufs',
      'Ausschließlich den Konsum immaterieller Güter wie Kino- oder Arztbesuche',
      'Die Werbewirkung auf den Konsumenten',
    ],
    correctOptions: [0],
    explanation: 'Im engeren Sinn meint Konsumentenverhalten das beobachtbare, äußere Verhalten beim Kauf/Konsum. Der weitere Sinn schließt materielle UND immaterielle Güter (Kino, Arzt, Wahl) ein – diese sind teils nicht beobachtbar.',
    source: 'Kapitel 1.1, PDF S. 1', conceptIds: ['c-konsumentenverhalten'],
  },
  {
    id: 'q1-02', chapterId: 'k1', type: 'true_false', goal: 'fact', difficulty: 1,
    prompt: 'Die wissenschaftliche Betrachtung des Konsumentenverhaltens begann in den 1920er-Jahren, etablierte sich aber erst nach dem 2. Weltkrieg.',
    correctBool: true,
    explanation: 'Richtig: Beginn in den 1920ern, etabliert nach dem 2. Weltkrieg – ausgelöst durch den Marktwandel vom Verkäufer- zum Käufermarkt, mit professionellem Marketing als Folge.',
    source: 'Kapitel 1.1, PDF S. 1', conceptIds: ['c-konsumentenverhalten'],
  },
  {
    id: 'q1-03', chapterId: 'k1', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Jemand kauft einen Sportwagen vor allem wegen des Fahrgefühls und der Emotionen. Welche Konsumform liegt vor?',
    options: ['Hedonistischer Konsum', 'Utilitaristischer Konsum', 'Habitualisierter Konsum', 'Organisationaler Konsum'],
    correctOptions: [0],
    explanation: 'Hedonistischer Konsum: Fantasie und Emotionen stehen im Vordergrund (Sportwagen). Utilitaristischer Konsum betont den praktischen Nutzen (z. B. familienfreundliches Auto). Schnittmengen sind möglich.',
    source: 'Kapitel 1.3, PDF S. 1', conceptIds: ['c-hedonistisch', 'c-utilitaristisch'],
  },
  {
    id: 'q1-04', chapterId: 'k1', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erkläre den Unterschied zwischen utilitaristischem und hedonistischem Konsum und nenne je ein Beispiel.',
    rubric: [
      { point: 'Utilitaristisch = praktischer Nutzen im Vordergrund', keywords: ['praktisch', 'nutzen', 'utility', 'funktional'] },
      { point: 'Hedonistisch = Fantasie/Emotionen durch die Nutzung', keywords: ['emotion', 'fantasie', 'genuss', 'erlebnis', 'gefuehl'] },
      { point: 'Beispiele (z. B. Familienauto vs. Sportwagen)', keywords: ['auto', 'sportwagen', 'beispiel', 'familienfreundlich'] },
      { point: 'Schnittmengen möglich', keywords: ['schnittmenge', 'kombination', 'beides', 'ueberschneid'], weight: 0.5 },
    ],
    modelAnswer: 'Beim utilitaristischen Konsum steht der praktische Nutzen im Vordergrund (z. B. familienfreundliches Auto), beim hedonistischen Konsum will der Konsument Fantasie und Emotionen durch die Nutzung erleben (z. B. Sportwagen). Schnittmengen zwischen beiden sind möglich.',
    explanation: 'Kernunterscheidung: Nutzen vs. Emotion/Erlebnis. Wichtig: Beide Formen können sich überschneiden.',
    source: 'Kapitel 1.3, PDF S. 1', conceptIds: ['c-utilitaristisch', 'c-hedonistisch'],
  },
  {
    id: 'q1-05', chapterId: 'k1', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche Entscheidungsformen machen jemanden zum Konsumenten? (Mindestens eine muss vorliegen.)',
    options: ['Kaufentscheidung treffen', 'Produkt/Dienstleistung bezahlen', 'Konsumieren', 'Werbung wahrnehmen'],
    correctOptions: [0, 1, 2],
    explanation: 'Konsument ist, wer mindestens eine der drei Formen ausübt: Kaufentscheidung treffen, bezahlen oder konsumieren. Das bloße Wahrnehmen von Werbung genügt nicht.',
    source: 'Kapitel 1.3, PDF S. 1', conceptIds: ['c-entscheidungsformen'],
  },
  {
    id: 'q1-06', chapterId: 'k1', type: 'cloze', goal: 'fact', difficulty: 1,
    prompt: 'Hauptziel des Konsumentenverhaltens (aus Unternehmenssicht): das Konsumentenverhalten ______ im Sinne des eigenen Unternehmens beeinflussen – zentrale Fragen: Was, warum, wann, wie, wie oft und ______ kauft der Kunde?',
    clozeAnswers: [['positiv'], ['wo']],
    explanation: 'Hauptziel: Konsumentenverhalten positiv im Sinne des Unternehmens beeinflussen. Die W-Fragen: was, warum, wann, wie, wie oft, wo.',
    source: 'Kapitel 1.2, PDF S. 1', conceptIds: ['c-konsumentenverhalten'],
  },
  {
    id: 'q1-07', chapterId: 'k1', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein Hersteller von E-Bikes will sowohl utilitaristische als auch hedonistische Kaufmotive ansprechen. Skizziere je einen Werbeansatz für beide Motive.',
    rubric: [
      { point: 'Utilitaristischer Ansatz: praktischer Nutzen (Pendeln, Kosten, Gesundheit)', keywords: ['pendeln', 'nutzen', 'praktisch', 'kosten', 'sparen', 'alltag', 'funktional'] },
      { point: 'Hedonistischer Ansatz: Emotion/Erlebnis (Freiheit, Fahrspaß, Abenteuer)', keywords: ['fahrspass', 'freiheit', 'erlebnis', 'emotion', 'abenteuer', 'spass', 'genuss'] },
      { point: 'Bezug zur Zielgruppe/Ansprache', keywords: ['zielgruppe', 'ansprache', 'werbung', 'kampagne'], weight: 0.5 },
    ],
    modelAnswer: 'Utilitaristisch: Werbung betont den praktischen Nutzen – z. B. günstiges, schnelles Pendeln zur Arbeit ohne Stau und Parkplatzsuche. Hedonistisch: Werbung inszeniert Fahrspaß, Freiheit und Naturerlebnis am Wochenende – Emotionen statt Funktionsargumente.',
    explanation: 'Transferaufgabe: Beide Motivlagen erfordern unterschiedliche Botschaften – Nutzenargumente vs. emotionale Inszenierung.',
    source: 'Kapitel 1.3, PDF S. 1', conceptIds: ['c-utilitaristisch', 'c-hedonistisch'],
  },

  // ================= Kapitel 2 =================
  {
    id: 'q2-01', chapterId: 'k2', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Worin unterscheidet sich der Neobehaviorismus vom Behaviorismus?',
    options: [
      'Er berücksichtigt zusätzlich die Introspektion – innere Prozesse als intervenierende Variablen (S-O-R)',
      'Er verzichtet vollständig auf beobachtbare Reaktionen',
      'Er betrachtet ausschließlich Marketingreize',
      'Er hält innere Prozesse für direkt beobachtbar',
    ],
    correctOptions: [0],
    explanation: 'Der Neobehaviorismus ergänzt das S-R-Modell um den Organismus (S-O-R) und damit um die Introspektion. Die inneren Prozesse bleiben aber unbeobachtbar (weiterhin „Black Box“) und werden als intervenierende Variablen modelliert.',
    source: 'Kapitel 2.1, PDF S. 1–2', conceptIds: ['c-neobehaviorismus', 'c-behaviorismus'],
  },
  {
    id: 'q2-02', chapterId: 'k2', type: 'cloze', goal: 'fact', difficulty: 1,
    prompt: 'Im S-O-R-Modell steht S für ______, O für ______ und R für ______.',
    clozeAnswers: [['Stimulus', 'Stimuli', 'Reiz'], ['Organismus'], ['Response', 'Reaktion', 'Reaction']],
    explanation: 'S-O-R: Stimulus (Reiz) – Organismus (innere, nicht beobachtbare Prozesse) – Response (messbare Reaktion).',
    source: 'Kapitel 2.1, PDF S. 1–2', conceptIds: ['c-neobehaviorismus'],
  },
  {
    id: 'q2-03', chapterId: 'k2', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Marketingdominante Reize lassen sich in die 4 Ps unterteilen. Welche sind das?',
    options: [
      'Price, Product, Place, Promotion',
      'People, Process, Physical Evidence, Price',
      'Product, Position, Power, Publicity',
      'Price, Publicity, Package, Person',
    ],
    correctOptions: [0],
    explanation: 'Die 4 Ps der marketingdominanten Reize: Price, Product, Place, Promotion.',
    source: 'Kapitel 2.1, PDF S. 2', conceptIds: ['c-stimulus'],
  },
  {
    id: 'q2-04', chapterId: 'k2', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordne die Modellarten ihrer Beschreibung zu.',
    pairs: [
      { left: 'Totalmodelle', right: 'Erklären das Verhalten ganzheitlich – didaktisch wertvoll, praktisch schwer anwendbar' },
      { left: 'Partialmodelle', right: 'Fokus auf einzelne Aspekte – praxistauglich, aber limitiertes Betrachtungsspektrum' },
      { left: 'Phasenmodelle', right: 'Zeitliche Einteilung des Kaufprozesses (Vorkauf-, Kauf-, Nachkaufphase)' },
    ],
    explanation: 'Totalmodelle = ganzheitlich (Theorie), Partialmodelle = einzelne Variablen (Praxis), Phasenmodelle = zeitliche Struktur des Kaufprozesses.',
    source: 'Kapitel 2.2, PDF S. 2', conceptIds: ['c-totalmodelle', 'c-partialmodelle', 'c-phasenmodelle'],
  },
  {
    id: 'q2-05', chapterId: 'k2', type: 'true_false', goal: 'understanding', difficulty: 2,
    prompt: 'Phasenmodelle eignen sich besonders gut zur Analyse von Impulskäufen.',
    correctBool: false,
    explanation: 'Falsch: Phasenmodelle versprechen bei extensiven Kaufentscheidungen maximalen Erfolg und sind wertvoll für organisationale Kaufentscheidungen – für Impulskäufe sind sie eher ungeeignet.',
    source: 'Kapitel 2.2, PDF S. 2', conceptIds: ['c-phasenmodelle'],
  },
  {
    id: 'q2-06', chapterId: 'k2', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Warum wird der Konsument im Behaviorismus als „Black Box“ bezeichnet – und was ändert sich beim Neobehaviorismus?',
    rubric: [
      { point: 'Behaviorismus betrachtet nur Reiz und Reaktion', keywords: ['reiz', 'reaktion', 's-r', 'stimulus', 'response'] },
      { point: 'Innere Prozesse werden nicht berücksichtigt/beobachtet', keywords: ['innere', 'nicht beobachtbar', 'unbeobachtbar', 'black box', 'prozesse im inneren'] },
      { point: 'Neobehaviorismus ergänzt Organismus/Introspektion (S-O-R)', keywords: ['organismus', 's-o-r', 'introspektion', 'intervenierende'] },
      { point: 'Innere Prozesse bleiben trotzdem nicht direkt beobachtbar', keywords: ['weiterhin', 'trotzdem', 'bleibt', 'nicht direkt'], weight: 0.5 },
    ],
    modelAnswer: 'Im Behaviorismus werden nur Reize und Reaktionen betrachtet (S-R-Modell); die inneren Prozesse der Person bleiben unbeachtet – daher „Black Box“. Der Neobehaviorismus ergänzt die Introspektion: Im S-O-R-Modell steht der Organismus für die inneren Prozesse (intervenierende Variablen). Diese werden zwar modelliert, sind aber weiterhin nicht direkt beobachtbar.',
    explanation: 'Zentral: „Black Box“ = keine Betrachtung des Inneren; S-O-R modelliert das Innere, ohne es beobachten zu können.',
    source: 'Kapitel 2.1, PDF S. 1–2', conceptIds: ['c-behaviorismus', 'c-neobehaviorismus'],
  },
  {
    id: 'q2-07', chapterId: 'k2', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Welche der folgenden Größen ist eine direkt messbare Response im S-O-R-Modell?',
    options: ['Verweildauer am POS', 'Einstellung zur Marke', 'Motivation des Kunden', 'Wahrnehmung der Werbung'],
    correctOptions: [0],
    explanation: 'Die Response ist direkt beobachtbar/messbar – z. B. Verweildauer am POS, gekaufte Menge, Cross-Buyings. Einstellung, Motivation und Wahrnehmung sind innere (Organismus-)Prozesse.',
    source: 'Kapitel 2.1, PDF S. 2', conceptIds: ['c-response'],
  },
  {
    id: 'q2-08', chapterId: 'k2', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Was sind Determinanten des Konsumentenverhaltens, und über welche zwei Prozessarten laufen psychische Vorgänge ab? Gib je ein Beispiel für Innen- und Außenreiz.',
    rubric: [
      { point: 'Determinanten = psychische, soziale, persönliche, kulturelle Erklärungsfaktoren', keywords: ['psychisch', 'sozial', 'kulturell', 'persoenlich', 'faktoren', 'erklaerung'] },
      { point: 'Aktivierende und kognitive Prozesse', keywords: ['aktivierend', 'kognitiv'] },
      { point: 'Beispiel Innenreiz (z. B. Hunger, eigener Gedanke)', keywords: ['hunger', 'innenreiz', 'eingefallen', 'gedanke', 'intern'] },
      { point: 'Beispiel Außenreiz (z. B. Flyer, Werbung)', keywords: ['flyer', 'werbung', 'aussenreiz', 'extern', 'plakat'] },
    ],
    modelAnswer: 'Determinanten sind psychische, soziale, persönliche oder kulturelle Faktoren zur Erklärung des Konsumentenverhaltens. Psychische Vorgänge laufen über aktivierende und kognitive Prozesse; nötig ist mindestens ein Reiz. Innenreiz: Man bestellt Pizza, weil einem einfällt, dass man lange nichts bestellt hat. Außenreiz: Man sieht einen Werbeflyer.',
    explanation: 'Beide Prozessarten beeinflussen sich reziprok – viele mentale Prozesse sind sowohl affektiv als auch kognitiv „primär“.',
    source: 'Kapitel 2.3, PDF S. 3', conceptIds: ['c-determinante', 'c-aktivierende-prozesse', 'c-kognitive-prozesse'],
  },

  // ================= Kapitel 3 =================
  {
    id: 'q3-01', chapterId: 'k3', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Warum ist aus Marketingsicht vor allem die phasische Aktivierung relevant?',
    options: [
      'Weil Unternehmen auf die tonische Aktivierung wenig bis keinen Einfluss nehmen können',
      'Weil tonische Aktivierung keine Rolle für das Verhalten spielt',
      'Weil phasische Aktivierung dauerhaft anhält',
      'Weil sie genetisch bedingt ist',
    ],
    correctOptions: [0],
    explanation: 'Die tonische Aktivierung (allgemeine Wachheit über längere Zeit, z. B. Mittagstief) ist von Unternehmen kaum beeinflussbar. Die phasische (zeitlich begrenzte) Aktivierung kann dagegen durch Stimuli gezielt ausgelöst werden.',
    source: 'Kapitel 3.1, PDF S. 4', conceptIds: ['c-phasisch', 'c-tonisch'],
  },
  {
    id: 'q3-02', chapterId: 'k3', type: 'cloze', goal: 'fact', difficulty: 1,
    prompt: 'Ohne ______ gibt es kein Verhalten. Die Bereitschaft, Außenreize wahrzunehmen, heißt ______.',
    clozeAnswers: [['Aktivierung'], ['Aufmerksamkeit']],
    explanation: 'Aktivierung ist die Grunddimension aller Antriebsprozesse; Aufmerksamkeit ist die Bereitschaft, Außenreize wahrzunehmen.',
    source: 'Kapitel 3.1, PDF S. 4', conceptIds: ['c-aktivierung', 'c-aufmerksamkeit'],
  },
  {
    id: 'q3-03', chapterId: 'k3', type: 'single_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Was besagt die Lambda-Hypothese?',
    options: [
      'Es gibt einen optimalen Aktivierungsbereich – zu wenig und zu viel Aktivierung senken die Leistung',
      'Je höher die Aktivierung, desto höher die Leistung – ohne Grenze',
      'Aktivierung und Leistung sind unabhängig voneinander',
      'Nur Überaktivierung steigert die Leistungsfähigkeit',
    ],
    correctOptions: [0],
    explanation: 'Die Lambda-Hypothese beschreibt eine Funktion von Aktivierung und Leistung mit optimalem Bereich (umgekehrtes U). Sie ist weder empirisch widerlegt noch ganz bestätigt; praktisch ist Unteraktivierung häufiger als Überaktivierung.',
    source: 'Kapitel 3.1, PDF S. 4–5', conceptIds: ['c-lambda'],
  },
  {
    id: 'q3-04', chapterId: 'k3', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordne die Stimulus-Art dem Beispiel zu.',
    pairs: [
      { left: 'Affektiver (emotionaler) Stimulus', right: 'Babyfoto oder erotisches Motiv in der Werbung' },
      { left: 'Physischer Stimulus', right: 'Große Plakatfläche in Signalfarbe Rot' },
      { left: 'Kognitiver Stimulus', right: 'Überraschende, widersprüchliche Werbebotschaft, die zum Nachdenken zwingt' },
    ],
    explanation: 'Affektive Stimuli wirken emotional (teils genetisch disponiert), physische über Größe/Form/Farbe/Geruch/Lautstärke, kognitive über Widersprüche, Konflikte und Überraschung.',
    source: 'Kapitel 3.2, PDF S. 5', conceptIds: ['c-stimuli-arten'],
  },
  {
    id: 'q3-05', chapterId: 'k3', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Was ist der Bumerang-Effekt und in welchem Zusammenhang tritt er bei Schockwerbung auf?',
    rubric: [
      { point: 'Gegenteilige Kommunikationswirkung wird erreicht', keywords: ['gegenteil', 'umgekehrt', 'entgegengesetzt'] },
      { point: 'Ursache: Reize passen nicht zum Kontext / lenken von der Botschaft ab', keywords: ['ablenk', 'kontext', 'passen nicht', 'botschaft'] },
      { point: 'Schockwerbung: Verstoß gegen gute Sitten, um Gehör zu finden', keywords: ['sitten', 'moral', 'schock', 'provokation', 'aufmerksamkeit'] },
      { point: 'Risiken: negative Publicity/Nichtkauf', keywords: ['negativ', 'publicity', 'nichtkauf', 'einstellung'], weight: 0.5 },
    ],
    modelAnswer: 'Beim Bumerang-Effekt wird die gegenteilige Kommunikationswirkung erreicht – etwa wenn Reize nicht zum Gesamtkontext passen oder von der eigentlichen Werbebotschaft ablenken. Schockwerbung verstößt bewusst gegen gute Sitten und Moralvorstellungen, um Gehör zu finden; sie hebt zwar von der Konkurrenz ab, riskiert aber Bumerang-Effekt und negative Publicity.',
    explanation: 'Aktivierung um jeden Preis kann nach hinten losgehen – irritierende Stimuli können Nichtkauf und negative Einstellungen auslösen.',
    source: 'Kapitel 3.2, PDF S. 5–6', conceptIds: ['c-bumerang', 'c-schockwerbung'],
  },
  {
    id: 'q3-06', chapterId: 'k3', type: 'single_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Nach dem Elaboration-Likelihood-Modell: Wann ist der zentrale Weg der Überzeugung erfolgversprechend?',
    options: [
      'Wenn der Konsument Fähigkeit und Motivation hat, sich mit Argumenten auseinanderzusetzen',
      'Wenn der Konsument wenig Zeit hat und kaum involviert ist',
      'Wenn nur periphere Hinweisreize verfügbar sind',
      'Wenn das Produkt schnelllebig und billig ist',
    ],
    correctOptions: [0],
    explanation: 'Zentraler Weg: Fakten und Argumente überzeugen, wenn Zeit, Fähigkeit und Motivation vorhanden sind (z. B. teure, funktionale Produkte) – die Einstellungsänderung ist nachhaltig. Ohne Zeit/Motivation wirkt der periphere Weg (Bilder, Musik, Testimonials), aber fragiler.',
    source: 'Kapitel 3.3, PDF S. 6–7', conceptIds: ['c-elm'],
  },
  {
    id: 'q3-07', chapterId: 'k3', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein Anbieter von Photovoltaikanlagen (teuer, funktional) und ein Hersteller von Kaugummis planen Kampagnen. Welchen ELM-Weg sollte jeweils gewählt werden? Begründe.',
    rubric: [
      { point: 'Photovoltaik: zentraler Weg', keywords: ['zentral', 'argument', 'fakten'] },
      { point: 'Begründung: hohes Involvement/teuer/funktional, nachhaltige Einstellungsänderung', keywords: ['involvement', 'teuer', 'funktional', 'nachhaltig', 'abwaegen', 'langanhaltend'] },
      { point: 'Kaugummi: peripherer Weg', keywords: ['peripher', 'hinweisreiz', 'bilder', 'musik', 'testimonial'] },
      { point: 'Begründung: schnelllebig, geringes Involvement, Kauflaune', keywords: ['schnelllebig', 'gering', 'kauflaune', 'impuls', 'effizient'] },
    ],
    modelAnswer: 'Photovoltaik: zentraler Weg – Kunden sind hoch involviert, nehmen sich Zeit und wägen Vor-/Nachteile ab; starke Argumente erzeugen eine nachhaltige, änderungsresistente Einstellung. Kaugummi: peripherer Weg – geringes Involvement und schnelllebiges Produkt; angenehme Bilder, Musik oder Testimonials bringen Konsumenten effizient in Kauflaune, auch wenn die Einstellungsänderung fragiler ist.',
    explanation: 'Faustregel aus dem Skript: teures funktionales Produkt → zentral; schnelllebiges Produkt → peripher.',
    source: 'Kapitel 3.3, PDF S. 6–7', conceptIds: ['c-elm'],
  },
  {
    id: 'q3-08', chapterId: 'k3', type: 'assignment', goal: 'distinction', difficulty: 3,
    prompt: 'Ordne die Cialdini-Prinzipien den Beispielen zu.',
    pairs: [
      { left: 'Reziprozität', right: 'Nach einer Gratis-Verkostung fühlt man sich verpflichtet, etwas zu kaufen' },
      { left: 'Verpflichtung & Konsistenz', right: 'Wer eine Kundenkarte besitzt, kauft auch künftig dort ein' },
      { left: 'Soziale Bewährtheit', right: '„Über 10.000 zufriedene Kunden“ – man orientiert sich am Verhalten anderer' },
      { left: 'Autorität', right: 'Werbung mit einem Experten im Arztkittel' },
      { left: 'Verknappung', right: '„Nur noch 2 Zimmer verfügbar“ löst reflexartiges Zugreifen aus' },
    ],
    explanation: 'Die 6 Strategien nach Cialdini: Reziprozität (Gegenseitigkeit), Verpflichtung/Konsistenz (Verlässlichkeit), soziale Bewährtheit (Orientierung an anderen), Gefallen (Sympathie/Vertrautheit), Autorität (Respekt vor Überlegenen), Verknappung (empfundene Freiheitseinschränkung).',
    source: 'Kapitel 3.4, PDF S. 7', conceptIds: ['c-reziprozitaet', 'c-konsistenz', 'c-soziale-bewaehrtheit', 'c-autoritaet', 'c-verknappung'],
  },
  {
    id: 'q3-09', chapterId: 'k3', type: 'true_false', goal: 'fact', difficulty: 2,
    prompt: 'Bei wenig involvierten Konsumenten sollten aktivierende Stimuli möglichst stark eingesetzt werden, da Unteraktivierung sonst nur durch kostenintensive Wiederholungskontakte kompensiert werden kann.',
    correctBool: true,
    explanation: 'Richtig: Bei wenig involvierten Konsumenten dienen aktivierende Stimuli als „Türöffner“. Unteraktivierung muss sonst teuer durch Wiederholungskontakte ausgeglichen werden. Auf aktivierende Stimuli zu verzichten ist im B2C/B2B ein absolutes No-Go.',
    source: 'Kapitel 3.2, PDF S. 6', conceptIds: ['c-aktivierung', 'c-stimuli-arten'],
  },
  {
    id: 'q3-10', chapterId: 'k3', type: 'single_choice', goal: 'distinction', difficulty: 3,
    prompt: 'Ein Kunde erhält an der Bar einen kostenlosen Schnaps und gibt danach deutlich mehr Trinkgeld. Welches Cialdini-Prinzip wirkt hier primär?',
    options: ['Reziprozität', 'Verknappung', 'Autorität', 'Soziale Bewährtheit'],
    correctOptions: [0],
    explanation: 'Reziprozität: Der Mensch fühlt sich durch eine erhaltene Leistung (kostenloser Schnaps) verpflichtet, etwas zurückzugeben (höheres Trinkgeld) – evolutionspsychologisch begründeter sozialer Austausch.',
    source: 'Kapitel 3.4, PDF S. 7', conceptIds: ['c-reziprozitaet'],
  },

  // ================= Kapitel 4 =================
  {
    id: 'q4-01', chapterId: 'k4', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche vier Dimensionen von Emotionen nennt das Skript?',
    options: ['Erregung', 'Richtung', 'Qualität', 'Subjektives Bewusstsein', 'Dauer', 'Intensität der Werbung'],
    correctOptions: [0, 1, 2, 3],
    explanation: 'Die vier Dimensionen: Erregung (Ausmaß der inneren Erregung), Richtung (positiv/negativ), Qualität (Art der Emotion, z. B. Optimismus) und subjektives Bewusstsein (wie bewusst die Emotion erlebt wird).',
    source: 'Kapitel 4.1, PDF S. 7–8', conceptIds: ['c-emotion'],
  },
  {
    id: 'q4-02', chapterId: 'k4', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Was unterscheidet Motivation von einem Motiv?',
    options: [
      'Motivation ist die aktuelle, zielgerichtete Energetisierung; ein Motiv ist ein zeitlich latenter Zustand',
      'Motive sind immer bewusst, Motivation immer unbewusst',
      'Motivation ist genetisch bedingt, Motive sind erlernt',
      'Es gibt keinen Unterschied',
    ],
    correctOptions: [0],
    explanation: 'Motiv = zeitlich latenter Zustand, ähnlich auf bestimmte Ziele zu reagieren (z. B. Selbstverwirklichung). Motivation = die aktuelle Energetisierung, also momentane zielgerichtete Beweggründe.',
    source: 'Kapitel 4.2, PDF S. 8', conceptIds: ['c-motiv', 'c-motivation'],
  },
  {
    id: 'q4-03', chapterId: 'k4', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordne die Begriffe den Definitionen zu.',
    pairs: [
      { left: 'Bedürfnis', right: 'Gefühlter Mangelzustand ohne Zielausrichtung mit dem Wunsch, ihn zu beseitigen' },
      { left: 'Trieb', right: 'Genetisch bedingtes Motiv ohne kognitive Komponente (z. B. Hunger bei Glukosemangel)' },
      { left: 'Primäres Motiv', right: 'Genetisch bedingt, z. B. Hunger' },
      { left: 'Sekundäres Motiv', right: 'Erlernt und kulturell geprägt, z. B. Anerkennung oder Freiheit' },
    ],
    explanation: 'Bedürfnis = Mangelzustand; Trieb = genetisch, ohne Kognition; primäre Motive angeboren, sekundäre erlernt (können logische Folgen primärer sein, z. B. Gelderwerb zur Nahrungsbeschaffung).',
    source: 'Kapitel 4.2, PDF S. 8', conceptIds: ['c-beduerfnis', 'c-trieb', 'c-motiv'],
  },
  {
    id: 'q4-04', chapterId: 'k4', type: 'cloze', goal: 'fact', difficulty: 2,
    prompt: 'Maslow: Die Ebenen 1–3 heißen ______bedürfnisse; das Bedürfnis nach ______ ist unstillbar.',
    clozeAnswers: [['Defizit'], ['Selbstverwirklichung']],
    explanation: 'Ebenen 1–3 sind Defizitbedürfnisse (sinkende Motivationskraft bei Befriedigung); das Selbstverwirklichungsbedürfnis ist unstillbar und wird erst angestrebt, wenn die grundlegenden Bedürfnisse befriedigt sind.',
    source: 'Kapitel 4.2, PDF S. 8–9', conceptIds: ['c-maslow'],
  },
  {
    id: 'q4-05', chapterId: 'k4', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Warum ist die Maslow-Pyramide für Marketingkonzeptionen nur bedingt geeignet, und was ist stattdessen relevanter?',
    rubric: [
      { point: 'Alle Konsumenten werden „in einen Topf geworfen“ (zu pauschal)', keywords: ['topf', 'pauschal', 'alle konsumenten', 'undifferenziert', 'verallgemein'] },
      { point: 'Motive zu kleiner oder zu großer Reichweite', keywords: ['reichweite', 'zu klein', 'zu gross'] },
      { point: 'Relevanter: Motive mittlerer Reichweite', keywords: ['mittlere reichweite', 'mittlerer'] },
      { point: 'Beispiele: Ökonomie/Sparsamkeit, Prestige/Status, Lust/Neugier, Angst/Risiko, Konsistenz', keywords: ['prestige', 'status', 'sparsamkeit', 'oekonomie', 'neugier', 'angst', 'konsistenz', 'erotik'], weight: 0.5 },
    ],
    modelAnswer: 'Das Modell wirft alle Konsumenten in einen Topf – die Motive haben zu kleine oder zu große Reichweite und eignen sich daher kaum für differenzierte Marketingkonzeptionen. Relevanter sind Motive mittlerer Reichweite, z. B. Ökonomie/Sparsamkeit/Rationalität, Prestige/Status/Anerkennung, Wünschbarkeit/Normunterwerfung, Lust/Erregung/Neugier, Sex/Erotik, Angst/Furcht/Risikoneigung und Konsistenz-/Dissonanzvermeidung.',
    explanation: 'Prüfungsklassiker: Maslow kennen UND kritisch einordnen können.',
    source: 'Kapitel 4.2, PDF S. 9', conceptIds: ['c-maslow'],
  },
  {
    id: 'q4-06', chapterId: 'k4', type: 'single_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welches Verhaltenskonstrukt besitzt die höchste Komplexität und die größte zeitliche Persistenz?',
    options: ['Einstellung', 'Aktivierung', 'Emotion', 'Motivation'],
    correctOptions: [0],
    explanation: 'Die Einstellung (Motivation + kognitive Gegenstandsbeurteilung) ist das subjektbezogene Verhaltenskonstrukt mit der höchsten Komplexität und der größten zeitlichen Persistenz.',
    source: 'Kapitel 4.3, PDF S. 9', conceptIds: ['c-einstellung', 'c-konstrukt-hierarchie'],
  },
  {
    id: 'q4-07', chapterId: 'k4', type: 'assignment', goal: 'distinction', difficulty: 3,
    prompt: 'Ordne die einstellungsnahen Begriffe ihrer Definition zu.',
    pairs: [
      { left: 'Meinung', right: 'Verbalisierte Einstellung' },
      { left: 'Überzeugung', right: 'Persistente, kognitive Grundlage der Einstellung' },
      { left: 'Präferenz', right: 'Relativierte Einstellung' },
      { left: 'Vorurteil/Stereotyp', right: 'Schlecht begründete, rigide und pauschale Einstellung (häufig negativ)' },
      { left: 'Image', right: 'Analogbegriff mit Objektbezug (das Auto, nicht das Autofahren)' },
    ],
    explanation: 'Diese Abgrenzungen sind beliebte Prüfungsinhalte: Meinung (verbalisiert), Überzeugung (kognitive Grundlage), Präferenz (relativiert), Vorurteil (rigide/pauschal), Image (Objektbezug).',
    source: 'Kapitel 4.3, PDF S. 9–10', conceptIds: ['c-meinung', 'c-image', 'c-einstellung'],
  },
  {
    id: 'q4-08', chapterId: 'k4', type: 'cloze', goal: 'fact', difficulty: 2,
    prompt: 'Das ABC-Modell zerlegt die Einstellung in drei Komponenten: A wie ______ (gefühlsmäßig), B wie ______ (Handlungsabsicht) und C wie ______ (subjektives Wissen).',
    clozeAnswers: [['Affect', 'Affekt', 'affektiv'], ['Behavior', 'Verhalten', 'Behaviour'], ['Cognition', 'Kognition', 'kognitiv']],
    explanation: 'ABC-Modell: Affect (affektiv/gefühlsmäßig), Behavior (Verhalten/Handlungsabsicht), Cognition (Kognition/subjektives Wissen). Nicht immer ist ersichtlich, welche Komponente am Anfang steht.',
    source: 'Kapitel 4.3, PDF S. 10', conceptIds: ['c-abc-modell'],
  },
  {
    id: 'q4-09', chapterId: 'k4', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Eine Person hat eine negative Einstellung zu Fast Food, isst aber trotzdem im Bahnhofs-Schnellrestaurant, als ihr Zug ausfällt und nichts anderes offen hat. Erkläre dieses Verhalten mit dem Einstellungsbegriff des Skripts.',
    rubric: [
      { point: 'Einstellung gilt unter bestimmten situativen Voraussetzungen', keywords: ['situativ', 'situation', 'voraussetzung', 'umstaende'] },
      { point: 'Einstellung ist Bereitschaft/Prädisposition, kein deterministisches Verhalten', keywords: ['bereitschaft', 'praedisposition', 'nicht zwingend', 'wahrscheinlich'] },
      { point: 'Situative Elemente/Normen können Verhalten gegen die Einstellung bewirken', keywords: ['norm', 'situative elemente', 'zwang', 'alternative', 'keine wahl'] },
      { point: 'Korrelation Einstellung–Verhalten wird von Studien nicht immer bestätigt (Solomon)', keywords: ['solomon', 'korrelation', 'studien', 'nicht bestaetigt'], weight: 0.5 },
    ],
    modelAnswer: 'Die Einstellung ist eine erlernte, relativ konstante Verhaltensbereitschaft gegenüber einem Objekt – aber unter bestimmten situativen Voraussetzungen. Fällt der Zug aus und ist das Schnellrestaurant die einzige Essensmöglichkeit, überlagert die Situation die negative Einstellung: Die Wahrscheinlichkeit ist groß, doch dort zu essen. Das zeigt auch, warum die Korrelation zwischen Einstellung und Verhalten (Solomon 2013) von vielen Studien nicht bestätigt wird – situative Elemente, Art der Einstellung, persönliche Faktoren und Käufertyp wirken mit.',
    explanation: 'Einstellung ≠ Verhalten: Situative Faktoren können das Verhalten entgegen der Einstellung lenken.',
    source: 'Kapitel 4.3, PDF S. 9–10', conceptIds: ['c-einstellung'],
  },
  {
    id: 'q4-10', chapterId: 'k4', type: 'true_false', goal: 'fact', difficulty: 2,
    prompt: 'Nach Izard gibt es 8 Basisemotionen, nach Plutchik 10.',
    correctBool: false,
    explanation: 'Umgekehrt: Izard nennt 10 Basisemotionen (Interesse, Freude, Überraschung, Kummer, Wut, Ekel, Geringschätzung, Angst, Scham, Schuldgefühl), Plutchik 8 (Erwartung, Freude, Überraschung, Trauer, Wut, Ekel, Akzeptanz, Angst).',
    source: 'Kapitel 4.1, PDF S. 8', conceptIds: ['c-basisemotionen'],
  },
  {
    id: 'q4-11', chapterId: 'k4', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Wie bauen die Verhaltenskonstrukte Aktivierung, Emotion, Motivation und Einstellung aufeinander auf?',
    rubric: [
      { point: 'Aktivierung = zentralnervöses Erregungsmuster (Basis)', keywords: ['erregung', 'zentralnervoes', 'basis', 'grunddimension'] },
      { point: 'Emotion = Erregung + Interpretation', keywords: ['interpretation', 'erlebt', 'empfunden'] },
      { point: 'Motivation = Emotion + Zielorientierung', keywords: ['ziel', 'zielorientierung', 'verhaltensziel'] },
      { point: 'Einstellung = Motivation + Gegenstandsbeurteilung', keywords: ['gegenstand', 'beurteilung', 'objekt'] },
      { point: 'Steigende Beständigkeit/Komplexität', keywords: ['bestaendig', 'komplex', 'persistenz', 'stabil'], weight: 0.5 },
    ],
    modelAnswer: 'Aktivierung ist das zentralnervöse Erregungsmuster. Kommt eine (kognitive) Interpretation hinzu, entsteht eine Emotion. Emotion mit (kognitiver) Zielorientierung wird zur Motivation. Motivation mit (kognitiver) Gegenstandsbeurteilung wird zur Einstellung. Mit jeder Stufe steigen zeitliche Beständigkeit und Komplexität.',
    explanation: 'Merke: Jede Stufe fügt genau eine kognitive Komponente hinzu.',
    source: 'Kapitel 4, PDF S. 10', conceptIds: ['c-konstrukt-hierarchie'],
  },

  // ================= Kapitel 5 =================
  {
    id: 'q5-01', chapterId: 'k5', type: 'single_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche Kapazität hat der Kurzzeit-/Arbeitsspeicher laut Dreispeichermodell?',
    options: ['7±2 Elemente (Chunks), optimal 3–4', 'Unbegrenzt', '1–2 Elemente', '20–30 Elemente'],
    correctOptions: [0],
    explanation: 'Der Kurzzeit-/Arbeitsspeicher fasst 7±2 Chunks (optimal 3–4) bei einer Speicherdauer von Minuten. Der Langzeitspeicher ist quasi unbegrenzt, der sensorische Speicher arbeitet in Millisekunden.',
    source: 'Kapitel 5.1, PDF S. 10–11', conceptIds: ['c-kurzzeitspeicher', 'c-dreispeicher'],
  },
  {
    id: 'q5-02', chapterId: 'k5', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordne die Speicher des Gedächtnismodells ihren Eigenschaften zu.',
    pairs: [
      { left: 'Sensorischer Speicher', right: 'Speicherdauer (Milli-)Sekunden; Sinneseindrücke verblassen ohne Weiterleitung' },
      { left: 'Kurzzeit-/Arbeitsspeicher', right: 'Minuten; Kapazität 7±2 Chunks; erkennen, verstehen, bewerten, entscheiden' },
      { left: 'Langzeitspeicher', right: 'Lebenslang; quasi unbegrenzte Kapazität; Wissen, Bedeutung, Vorstellung' },
    ],
    explanation: 'Reihenfolge: sensorischer Speicher → (Wahrnehmung/Aufmerksamkeit) → Kurzzeitspeicher → (Lernen/Memorieren) → Langzeitspeicher.',
    source: 'Kapitel 5.1, PDF S. 10–11', conceptIds: ['c-dreispeicher', 'c-sensorischer-speicher', 'c-kurzzeitspeicher'],
  },
  {
    id: 'q5-03', chapterId: 'k5', type: 'true_false', goal: 'fact', difficulty: 1,
    prompt: 'Das menschliche Hirn speichert Informationen vor allem in Form von Geschichten.',
    correctBool: true,
    explanation: 'Richtig – deshalb ist Storytelling im Marketing so wirksam.',
    source: 'Kapitel 5.1, PDF S. 11', conceptIds: ['c-dreispeicher'],
  },
  {
    id: 'q5-04', chapterId: 'k5', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Ein Markenname wird in der Werbung über Jahre mit schönen Emotionen „aufgeladen“, bis allein das Logo positive Gefühle auslöst. Welcher Lernmechanismus liegt vor?',
    options: ['Klassische Konditionierung', 'Instrumentelle Konditionierung', 'Kognitives Lernen', 'Reizdiskriminierung'],
    correctOptions: [0],
    explanation: 'Klassische Konditionierung: Ein zu erlernender Stimulus (Marke) wird mit einem bereits gelernten Reiz-Reaktions-Muster (positive Emotionen) verknüpft – wie beim Pawlow’schen Hund mit der Glocke.',
    source: 'Kapitel 5.2, PDF S. 11', conceptIds: ['c-klassische-konditionierung'],
  },
  {
    id: 'q5-05', chapterId: 'k5', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Lernen durch Belohnung oder Strafe (Verstärkung) nennt man …',
    options: ['instrumentelle (operante) Konditionierung', 'klassische Konditionierung', 'Stimulusgeneralisierung', 'Habitualisierung'],
    correctOptions: [0],
    explanation: 'Instrumentelle/operante Konditionierung: selektiver Lernprozess durch Verstärkung. Aus Marketingsicht wichtig für Habitualisierung (Gewohnheit) und Internalisierung (Verinnerlichung).',
    source: 'Kapitel 5.2, PDF S. 11', conceptIds: ['c-instrumentelle-konditionierung'],
  },
  {
    id: 'q5-06', chapterId: 'k5', type: 'open', goal: 'distinction', difficulty: 3,
    prompt: 'Erkläre Stimulusgeneralisierung und Reizdiskriminierung und gib je ein Marketingbeispiel.',
    rubric: [
      { point: 'Generalisierung = gleiche Reaktionen auf ähnliche Reize', keywords: ['gleiche reaktion', 'aehnliche reize', 'uebertrag'] },
      { point: 'Beispiel Generalisierung (ähnliche Produkte/neue Kollektion)', keywords: ['kollektion', 'aehnliche produkte', 'markenfamilie', 'line extension'] },
      { point: 'Diskriminierung = unterschiedliche Reaktionen auf Reize', keywords: ['unterschiedliche reaktion', 'unterscheiden', 'differenz'] },
      { point: 'Beispiel Diskriminierung (Abhebung von der Konkurrenz)', keywords: ['konkurrenz', 'abheben', 'eigenschaften', 'differenzierung'] },
    ],
    modelAnswer: 'Stimulusgeneralisierung: gleiche Reaktionen auf ähnliche Reize – z. B. überträgt der Kunde seine positiven Erfahrungen auf ähnliche Produkte einer neuen Kollektion (Wissensübertragung). Reizdiskriminierung: unterschiedliche Reaktionen auf Reize – z. B. hebt ein Unternehmen sein Produkt durch besondere Eigenschaften bewusst von der Konkurrenz ab.',
    explanation: 'Generalisierung nutzt Ähnlichkeit, Diskriminierung nutzt Unterscheidbarkeit.',
    source: 'Kapitel 5.2, PDF S. 11–12', conceptIds: ['c-stimulusgeneralisierung', 'c-reizdiskriminierung'],
  },
  {
    id: 'q5-07', chapterId: 'k5', type: 'cloze', goal: 'fact', difficulty: 2,
    prompt: 'Durch kognitives Lernen werden Wissenseinheiten gebildet oder modifiziert. Diese Einheiten heißen auch semantische Netzwerke oder ______. Das Ausmaß der kognitiven Aktivität beim Lernen nennt man ______.',
    clozeAnswers: [['Schemata', 'Schema'], ['Verarbeitungstiefe']],
    explanation: 'Schemata (semantische Netzwerke) ordnen und kategorisieren Wissen. Die Verarbeitungstiefe beschreibt das Ausmaß der kognitiven Aktivität – hohe Tiefe steigert Gedächtnisleistung und kritische Auseinandersetzung.',
    source: 'Kapitel 5.2, PDF S. 12', conceptIds: ['c-schemata', 'c-verarbeitungstiefe'],
  },
  {
    id: 'q5-08', chapterId: 'k5', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein Möbelhaus möchte, dass Kunden sich Werbeinhalte besser merken. Leite aus dem Dreispeichermodell zwei konkrete Maßnahmen ab.',
    rubric: [
      { point: 'Aufmerksamkeitsschwelle überwinden (Aktivierung, auffällige Reize)', keywords: ['aufmerksamkeit', 'aktivierung', 'auffaellig', 'reiz', 'schwelle'] },
      { point: 'Kurzzeitspeicher nicht überladen: wenige Chunks (3–4)', keywords: ['chunk', '3-4', 'wenige', 'reduzieren', 'einfach', 'kernbotschaft'] },
      { point: 'Transfer in Langzeitspeicher durch Wiederholung/Memorieren/Geschichten', keywords: ['wiederhol', 'memorieren', 'geschichte', 'story', 'verknuepf'] },
    ],
    modelAnswer: 'Erstens muss die Werbung die Aufmerksamkeitsschwelle überwinden – z. B. durch aktivierende, auffällige Reize, damit die Information überhaupt in den Kurzzeitspeicher gelangt. Zweitens sollte die Botschaft auf wenige Chunks (optimal 3–4) reduziert werden, da der Kurzzeitspeicher nur 7±2 Elemente fasst. Drittens fördern Wiederholung und Geschichten (Storytelling) das Memorieren und damit den Transfer in den Langzeitspeicher.',
    explanation: 'Das Gedächtnismodell liefert direkte Gestaltungsregeln: Aktivieren, Reduzieren, Wiederholen/Erzählen.',
    source: 'Kapitel 5.1, PDF S. 10–11', conceptIds: ['c-dreispeicher', 'c-kurzzeitspeicher'],
  },
  {
    id: 'q5-09', chapterId: 'k5', type: 'true_false', goal: 'understanding', difficulty: 2,
    prompt: 'Das Ausbleiben einer Strafe oder Belohnung kann zu habitualisiertem Kaufverhalten führen, da es keiner kognitiven Anstrengung bedarf.',
    correctBool: true,
    explanation: 'Richtig: Ohne korrigierende Verstärkung wird das Verhalten zur Gewohnheit – der bequemste Weg (Habitualisierung).',
    source: 'Kapitel 5.2, PDF S. 11', conceptIds: ['c-instrumentelle-konditionierung'],
  },
];
