import { Chapter } from '@/lib/types';

/**
 * Kapitelstruktur des Moduls Marketing I (Studiengang Online-Marketing),
 * extrahiert aus dem hochgeladenen PDF "Marketing I – Zusammenfassung".
 */
export const chapters: Chapter[] = [
  {
    id: 'm1',
    index: 1,
    title: 'Grundlagen des Marketings',
    subchapters: ['Begriffe des Marketings', 'Markenführung, Positionierung & Wettbewerbsstrategien', 'Marketingmanagement'],
    keyIdeas: [
      'Marketing leitet sich von „(to) market“ ab (Markt und vermarkten). Der Markt ist Ziel- UND Bezugsobjekt: Ziel, Märkte zu schaffen/beeinflussen; zugleich geben Märkte die Rahmenbedingungen für effizientes und effektives Gestalten von Austauschprozessen vor.',
      'Zwei Leitideen: Gratifikationsprinzip (der Austausch soll für beide Seiten vorteilhaft sein – Nachfrager- und Anbieternutzen maximieren) und Knappheitsprinzip (die gehandelten Ressourcen sind knapp).',
      'Auf einem Käufermarkt ist das Angebot größer als die Nachfrage – die Nachfrage bildet den Engpass, der Nachfrager steht im Zentrum des modernen Marketings. Die meisten Märkte sind heute Käufermärkte. Der Begriff löste in den 1960ern die „Absatzwirtschaft“ ab (Paradigmenwechsel von Angebot zu Nachfrage).',
      'AMA-Definition (2017): Marketing ist eine Organisationsfunktion und ein Bündel von Prozessen, um Wert für Kunden zu schaffen, zu kommunizieren und zu liefern und Beziehungen so zu managen, dass Organisation und Stakeholder profitieren. Kundennutzen (Nettonutzen) = Differenz aus Aufwand und erhaltenem Wert.',
      'Drei Kernbausteine des Marketingbegriffs: funktional (systematischer Planungsprozess/Abteilung), führungsorientiert (Leitphilosophie – alle Funktionen am Markt ausrichten) und aktivitätenorientiert (Sozialtechnologie – der „Werkzeugkasten“ Marketingmix beeinflusst die Nachfrage).',
      'Marketingmix = die vier Ps: Product (Leistungspolitik), Price (Preispolitik), Place (Vertriebspolitik), Promotion (Kommunikationspolitik). Für Dienstleistungen zusätzlich: People, Processes, Physical Facilities.',
      'Transaktionales Marketing (kurzfristig, Produkt, Kundenakquisition, Leistungsdarstellung) vs. Beziehungsmarketing (langfristig, Produkt + Interaktion, Akquisition/Bindung/Rückgewinnung, Dialog). Erkenntnis stammt aus Dienstleistung/B2B. Ergänzend die drei Rs: Recruitment, Retention, Recovery.',
      'Markenführung (Branding) in vier Schritten: Positionierung aufbauen, Markenmarketing planen/umsetzen, Markenleistung messen, Markenwert (Brand Equity) aufbauen/erhalten. Marken sind mehr als Produkte und schaffen Werte; Brand Equity bringt reale Vorteile (Kundentreue, höhere Margen, unelastischere Reaktion auf Preiserhöhungen).',
      'Positionierung bestimmt, wie eine Marke gegenüber Wettbewerbern wahrgenommen werden soll (Kern jeder Marketingstrategie). Innerhalb des Wettbewerbsrahmens: Points of Parity (gleichauf) und Points of Difference (besser als die Konkurrenz).',
      'Zwei Grundstrategien: Qualitätsführerschaft (Differenzierung – besser sein) und Kostenführerschaft (billiger, über Kostendegression). Dritter Weg: Nischenstrategie. Kombiniert entsteht eine Vier-Felder-Matrix: (aggressive/selektive) Kostenführerschaft und (Gesamt-/selektive) Qualitätsführerschaft.',
      'Marketingmanagement setzt das erweiterte Marketingverständnis im Unternehmen um und berücksichtigt vier Orientierungspunkte: Unternehmen, Kunde, Wettbewerber, gesellschaftliches Umfeld. Sechs Schritte: 1) Situationsanalyse, 2) Marketingziele, 3) Marketingstrategie, 4) Marketinginstrumente (4 Ps), 5) Implementierung, 6) Controlling.',
    ],
    pdfPages: '1–6',
  },
  {
    id: 'm2',
    index: 2,
    title: 'Produktpolitik',
    subchapters: ['Begriffe der Produktpolitik', 'Gestaltungsfelder der Produktpolitik', 'Innovationsmanagement'],
    keyIdeas: [
      'Produktpolitik ist als eines der vier Ps das Herz des Marketingmix (ein Produkt ist Grundvoraussetzung jeder Marketingtätigkeit) und umfasst alle Entscheidungen zur Gestaltung des Leistungsangebots. Zentrale Frage: Was soll vermarktet werden?',
      'Ein Produkt ist ein Bündel von Attributen (Ausstattung, Funktionen, Nutzen, Verwendung) und kann materiell (Smartphone) oder immateriell (Streaming, Ideen, digitale Güter) sein. Wegen der Vielfalt spricht man oft von Leistungspolitik.',
      'Produktebenen nach Nutzen: Grundnutzen (Befriedigung des ursprünglichen Bedürfnisses) plus mögliche Zusatznutzen: sozialer/Geltungsnutzen, Erbauungsnutzen, emotionaler Nutzen. Leistung ist, was das Unternehmen bietet; Nutzen, was der Kunde davon hat.',
      'Qualität = Gesamtheit der Eigenschaften, die die Fähigkeit zur Bedürfnisbefriedigung beeinflussen; objektiv oder subjektiv. Qualitätsdimensionen: Gebrauchsnutzen, Haltbarkeit, Zuverlässigkeit, Ausstattung, Normgerechtigkeit, Ästhetik, Umwelt-/Sozialverträglichkeit.',
      'Produkttypologisierung nach: Materialität (Sachgüter/Dienstleistungen), Konsumentengruppe (Konsumgüter B2C/Investitionsgüter B2B), Nutzungsdauer (Verbrauchs-/Gebrauchsgüter), Nutzungshäufigkeit (täglich/aperiodisch) und Kaufgewohnheit (Convenience-, Shopping-, Specialty-, Unsought Goods).',
      'Drei Gestaltungsfelder: erstmalige Produktgestaltung, Variation über die Zeit, Kombination zu Produktprogrammen. Produktgestaltung umfasst technisch-funktionale Eigenschaften, Produktdesign, Verpackung (schützen, anpreisen, anwenderfreundlich, ökologisch entsorgbar), Qualitätsmanagement und Servicepolitik.',
      'Produktpolitische Entscheidungen im Lebenszyklus: Produktvariation (Nutzenkomponenten ändern, Basisfunktion bleibt – ersetzt), Produktdifferenzierung (neue Version für neues Segment – Programm wird breiter, beide bleiben), Produktelimination (Entfernen aus dem Angebot).',
      'Produktprogramm (Portfolio/Sortiment): Programmbreite = Anzahl der Produktlinien, Programmtiefe = Zahl der Produkte pro Linie. Ausrichtung nach Material/Herkunft, Preislagen oder Bedarfskreisen.',
      'Innovationsmanagement gestaltet ein System zur Entwicklung von Neuprodukten (heute erfolgsentscheidend – Negativbeispiel Kodak). Der Produktlebenszyklus durchläuft Einführung, Wachstum, Reife, Sättigung, Verfall; Reifephase: höchste Erfahrungskurven- und Economies-of-Scale-Effekte.',
      'Das S-Kurvenkonzept (Foster) sensibilisiert für technologische Diskontinuitäten: Jede Technologie stößt an eine Leistungsgrenze und wird durch eine neue ersetzt – der reine Produktlebenszyklus (Variable Zeit) erklärt Technologiesprünge nicht.',
      'Adoptionsprozess (individuell): Aufmerksamkeit, Interesse, Bewertung, Versuch, Annahme. Innovatoren/frühe Adopter sind einflussreiche Multiplikatoren (Influencer). Der Diffusionsprozess beschreibt die kumulierte Adoption im Zeitverlauf (S-förmig: langsamer Start, starker Mittelteil, Abflachen bei Sättigung).',
    ],
    pdfPages: '6–11',
  },
  {
    id: 'm3',
    index: 3,
    title: 'Kommunikationspolitik',
    subchapters: ['Integrierte Marketingkommunikation', 'Kommunikationsinstrumente'],
    keyIdeas: [
      'Kommunikationspolitik gestaltet und übermittelt Informationen, um Konsumenten im Sinne der Unternehmensziele zu beeinflussen. Aufgaben: informieren, überzeugen, erinnern. Kommunikation muss integriert und aufeinander abgestimmt sein (medienneutrale Planung: alle Kanäle nach Effektivität und Effizienz bewerten).',
      'Ziele: ökonomische (Marktanteil, Absatz, Rentabilität – betreffen den Marketingmix als Ganzes) und vorökonomische/potenzialbezogene = die reinen Kommunikationsziele: Kategoriebedürfnis, Bekanntheitsgrad/Image, Einstellungen, Kaufabsicht.',
      'Kommunikationsprogramme werden in acht Schritten geplant: 1) Zielgruppe, 2) Kommunikationsziele, 3) Botschaft, 4) Kanäle, 5) Budget (empfohlen: ziel-/aufgabenorientiert), 6) Kommunikationsmix, 7) Ergebnisse messen (CTR, Conversion Rate, Engagement Rate), 8) Prozess steuern.',
      'Sechs Kriterien für Effektivität/Effizienz der integrierten Kommunikation (Keller/Swaminathan): Reichweite, Mitwirkung, Gemeinsamkeit (konsistente Botschaft), Komplementarität, Vielseitigkeit, Kosten.',
      'Massenmediale Kommunikation richtet sich an eine Masse (nicht individuell); persönliche Kommunikation an einzelne Konsumenten (anpassbar). Fragmentierung: Mainstreammedien verlieren Reichweite, es entstehen spitze Zielgruppensegmente.',
      'Der Kommunikationsmix besteht aus ACHT Werkzeugen. Massenmedial: Werbung, Verkaufsförderung, Sponsoring & Eventmarketing, Public Relations. Persönlich: Direktmarketing, interaktives Marketing, Mund-zu-Mund-Kommunikation, persönlicher Verkauf. Ziel: eine einheitliche, stimmige Markenbotschaft.',
      'Werbung: unpersönliche, bezahlte Präsentation mit genanntem Auftraggeber (Print, Übertragung, Display, digital; TV-Spots, SEA, Product Placement). Vorteile: große Reichweite, Ausdruckskraft, Imageaufbau; Nachteile: hohe Kosten, Werbemüdigkeit, keine individuelle Ansprache, schwer messbar.',
      'Verkaufsförderung: kurzfristige Anreize (Warenproben, Coupons, Preisnachlässe, Flash Sales, Gamification, Verbundwerbung). Vorteil: messbare Kurzeffekte, direkter Kaufanreiz; Nachteil: Wirkungsnachlass, kann dem Markenwert schaden. Sponsoring/Events schaffen emotionale Bindung; PR (Öffentlichkeitsarbeit) beeinflusst über hohe Glaubwürdigkeit die öffentliche Meinung und pflegt Stakeholder-Beziehungen.',
      'Persönliche Instrumente: Direktmarketing (direkte Ansprache, ethische/Datenschutz-Probleme), interaktives Marketing (Weiterentwicklung mit Austausch, suchgebundene Anzeigen), Mund-zu-Mund-Kommunikation (Word-of-Mouth; Buzz-, Viral-, Influencer-Marketing – sehr einflussreich) und persönlicher Verkauf (effektivstes Mittel, v. a. B2B, aber teuer).',
    ],
    pdfPages: '11–17',
  },
  {
    id: 'm4',
    index: 4,
    title: 'Preispolitik',
    subchapters: ['Stellung der Preispolitik', 'Preispolitische Strategien', 'Preisbestimmung & Konditionierung'],
    keyIdeas: [
      'Preispolitik = alle Entscheidungen zur Festlegung eines Entgelts (auch Kontrahierungspolitik – inkl. Zahlungsbedingungen und Rabatten). Preise sind Indikator der Marktstellung und wirken direkt auf Umsatz und Gewinn.',
      'Einflussfaktoren der Preisfestlegung: Käufer (Zahlungsbereitschaft = Preisobergrenze), Kosten (Gesamtkosten = Preisuntergrenze), Konkurrenzsituation (Preiskorridor, Preistransparenz durch Vergleichsportale), externe Rahmenbedingungen und psychologische Effekte (Schwellenpreise, z. B. 2,99 €).',
      'Preis-Absatz-Funktion (funktionaler Zusammenhang Preis↔Menge): 1) lineare PAF x(p)=a−b·p (Monopol; a = Sättigungsmenge, a/b = Maximalpreis, b = Preisreagibilität), 2) multiplikative PAF x(p)=a·p^(−b) (kein Maximalpreis/keine Sättigungsmenge), 3) Gutenberg-Modell (doppelt geknickt; monopolistischer Mittelbereich, z. B. Apple).',
      'Prozess der Preisfestlegung: 1) Analyse des Preisspielraums, 2) Zielsetzung, 3) Strategieentwicklung, 4) Einsatz der Preisinstrumente, 5) Preiskontrolle. Vier Instrumente: Preise, Preisnachlässe (Rabatte/Boni/Skonti), Preiszuschläge, Zugaben.',
      'Strategien der Preispositionierung (Preishöhe): Hochpreis- (Premium), Mittelpreis- (Standard), Niedrigpreisstrategie (Mindestqualität, sehr günstig).',
      'Strategien des Preiswettbewerbs (Orientierung an der Konkurrenz): Preisführerschaft (hoher Preis als Orientierung, z. B. Apple), Preiskampf (niedrigster Preis, Discounter) und Preisfolgerschaft (Reaktion auf den Marktführer).',
      'Strategien der Preisabfolge (im Lebenszyklus): Skimming (hohe Einführungspreise abschöpfen, dann senken) vs. Penetration (niedrige Einführungspreise zur schnellen Marktdurchdringung, dann erhöhen).',
      'Preisdifferenzierung: unterschiedliche Preise für verschiedene Segmente – mengenmäßig, zeitlich, räumlich, personell, leistungsbezogen; Sonderform Preisbündelung. Ziel: unterschiedliche Zahlungsbereitschaften ausschöpfen (Customer Lifetime Value maximieren).',
      'Preisbestimmung: kostenorientiert (Stückkosten + Aufschlag; einfach/fair, aber ignoriert Markt) vs. marktorientiert (Break-even-Analyse, Perceived-Value-Pricing, Cournot-Preis). Innovative Modelle: Yield Management, Dynamic Pricing, Auction Pricing, Reverse Pricing.',
      'Konditionenpolitik (v. a. B2B): Absatzkredite, Lieferungs-/Zahlungsbedingungen und Rabatte. Vier Rabattarten: Funktions-, Mengen-, Zeit- (Skonto als Sonderform) und Treuerabatte.',
    ],
    pdfPages: '17–20',
  },
  {
    id: 'm5',
    index: 5,
    title: 'Distributionspolitik',
    subchapters: ['Grundlagen der Distributionspolitik', 'Vertikale Gestaltung', 'Horizontale Gestaltung'],
    keyIdeas: [
      'Distributionspolitik (Vertriebspolitik) verteilt Leistungen von der Produktion zur Konsumption. Erfolg hängt auch von der Qualität der Vertriebskanäle ab. Zwei Komponenten: akquisitorisch (Vertriebssystem effizient/effektiv gestalten) und logistisch (adäquater Zugriff der Konsumenten).',
      'Drei Vertriebsziele parallel: psychologische (positives, markentreues Kauferlebnis), versorgungsorientierte (lückenlose Verfügbarkeit) und ökonomische (Absatz, Preisniveau, Vertriebskosten optimieren). Vertrieb soll zum übrigen Marketingmix passen.',
      'Vertriebskanal = Gesamtheit aller Organisationen, die ein Produkt von der Herstellung bis zum Endverbraucher leiten. Push-Strategie „drückt“ Produkte in den Handel (Rabatte, Retail Media, Exklusivverträge); Pull-Strategie erzeugt einen Nachfragesog bei Endkunden (SEO, Content Marketing). Meist werden beide kombiniert.',
      'Der Handel schafft Wertschöpfung durch Überbrückung von Diskrepanzen: räumlich (Transport), zeitlich (Lagerung/Vorratshaltung) und Sortimentsgestaltung (quantitative/qualitative Diskrepanz). Intermediäre kaufen und verkaufen Sachgüter, bearbeiten sie aber nicht weiter.',
      'Disintermediation: Ausschaltung von Intermediären (z. B. Direct-to-Consumer über E-Commerce, Einsparung der Handelsmarge). Vertikale Integration: ein Unternehmen gliedert vor-/nachgelagerte Wertschöpfungsstufen ein (z. B. Edeka-Bananenreiferei).',
      'Vertikale Gestaltung (Länge des Vertriebswegs): direkter Vertrieb (Unternehmen verkauft selbst, nullstufig – enge Kundenbeziehung/Kontrolle, aber hoher Aufwand) vs. indirekter Vertrieb (externe Marktakteure mit akquisitorischer Funktion – Arbeitsteilung/Marktkenntnis, aber Handelsmargen und weniger Kontrolle).',
      'Externe Vertriebsorgane: Vertragshändler (Auto), Franchisepartner (Weisungsrecht, z. B. Fast Food), Absatzhelfer (Handelsvertreter, Kommissionäre, Makler – erwerben KEIN Eigentum) und Absatzmittler (Groß-/Einzelhandel – erwerben Eigentum).',
      'Horizontale Gestaltung (Breite = Zahl der Absatzmittler je Stufe): Einkanalsystem, Multichannel (auf mehreren Kanälen präsent) und Omnichannel (über alle Kanäle vernetzt/konsistent, z. B. Click & Collect). Shop-in-Shop und Click & Collect als Ausprägungen.',
      'Distributionsgrad/Vertriebswegedifferenzierung: intensiver Vertrieb (viele Partner, Convenience Goods), selektiver Vertrieb (mehrere Partner, Shopping Goods), exklusiver Vertrieb (wenige Partner, Specialty Goods). Der Vertrieb ist ein markenbildendes Element; Einflussfaktoren: Produkt, Unternehmen, Markt, Kunden, Absatzmittler, Konkurrenz, Umfeld.',
    ],
    pdfPages: '20–24',
  },
];
