import { Figure } from '@/lib/types';

/**
 * Visuelle Wissenseinheiten des Moduls Marketing I: alle didaktisch relevanten
 * Abbildungen des PDFs mit semantischer Beschreibung, Bildelementen, typischen
 * Fehlinterpretationen und vierstufiger Bildprüfkette.
 */
const ok = { technical: true, semantic: true, didactic: true, validated: true };

export const figures: Figure[] = [
  {
    id: 'f-produktebenen3', chapterId: 'm2', file: 'img-000.png', pdfPage: 7,
    title: 'Drei Produktebenen (Zwiebelmodell)',
    caption: 'Kernprodukt → reales Produkt → erweitertes Produkt, am Beispiel E-Bike.',
    explanationSimple: 'Ein Produkt hat drei Schichten wie eine Zwiebel. Innen der Kern: die eigentliche Leistung (E-Bike = Fortbewegung). Darum das reale Produkt: das, was man tatsächlich kauft (Rahmen, Akku, Motor, Display, Design, Marke). Außen das erweiterte Produkt: alle Zusatzleistungen (Software-Updates, Wartung, Garantie).',
    explanationExpert: 'Konzentrisches Drei-Ebenen-Modell: (1) Kernprodukt = Kernleistung, d. h. Befriedigung des Grundbedürfnisses bzw. Lösung eines Problems. (2) Reales Produkt = Umsetzung des Kernnutzens in ein sichtbares, kaufbares Produkt mit Design, technischer Qualität, Funktionalitäten, Verpackung und Markennamen. (3) Erweitertes Produkt = Produkt mit allen Zusatzleistungen wie Lieferung, Finanzierung, Garantie, Beratung, Installation und Service.',
    elements: [
      { label: 'Kernprodukt (innen)', meaning: 'Kernleistung/Grundnutzen – Befriedigung des Bedürfnisses (E-Bike: Fortbewegung, erleichtert durch Elektroantrieb).' },
      { label: 'Reales Produkt (Mitte)', meaning: 'Sichtbares, kaufbares Produkt mit Design, Qualität, Funktionen, Verpackung, Marke (E-Bike: Rahmen, Akku, Motor, Display).' },
      { label: 'Erweitertes Produkt (außen)', meaning: 'Alle Zusatzleistungen: Lieferung, Finanzierung, Garantie, Beratung, Service (E-Bike: Software-Updates, Wartung beim Fachhändler).' },
    ],
    misconceptions: ['Der Kern ist der abstrakte Nutzen, NICHT das physische Produkt – das physische Ding ist das „reale Produkt“.', 'Nicht mit dem Fünf-Ebenen-Modell (Kotler) verwechseln.'],
    conceptIds: ['mc-produkt', 'mc-grundnutzen'],
    validation: ok,
  },
  {
    id: 'f-produktebenen5', chapterId: 'm2', file: 'img-001.png', pdfPage: 7,
    title: 'Fünf Produktebenen (Kotler)',
    caption: 'Grundnutzen → generisches → erwartetes → augmentiertes → potenzielles Produkt, am Beispiel Hose.',
    explanationSimple: 'Ein feiner gestuftes Modell mit fünf Ebenen. Ganz unten der Grundnutzen (eine Hose soll bekleiden und wärmen – ein Stück Stoff). Darüber das generische Produkt (Hosenbeine geschnitten), das erwartete (bequemer Sitz, gefälliges Design), das augmentierte (Marke, wasserabweisend, Thermo) und ganz oben das potenzielle Produkt (Extras der Zukunft, z. B. „smart clothing“).',
    explanationExpert: 'Fünfstufiges Modell der Produktnutzenebenen: (1) Grundnutzen = Kernnutzen (bekleiden/wärmen). (2) Generisches Produkt = Basisversion (Hosenbeine geschneidert). (3) Erwartetes Produkt = Eigenschaften, die der Kunde selbstverständlich erwartet (bequemer Sitz, gefälliges Design). (4) Augmentiertes Produkt = Zusätze über die Erwartung hinaus (Markenname, wasserabweisend, Thermo, modisch). (5) Potenzielles Produkt = alle künftig denkbaren Erweiterungen (Extrafunktionalitäten, „smart clothing“).',
    elements: [
      { label: 'Grundnutzen', meaning: 'Kernnutzen – befriedigt das Grundbedürfnis (bekleiden und wärmen).' },
      { label: 'Generisches Produkt', meaning: 'Minimale funktionale Ausführung (Hosenbeine geschneidert).' },
      { label: 'Erwartetes Produkt', meaning: 'Selbstverständlich erwartete Eigenschaften (bequemer Sitz, Design).' },
      { label: 'Augmentiertes Produkt', meaning: 'Zusätze über die Erwartung hinaus (Marke, wasserabweisend, Thermo).' },
      { label: 'Potenzielles Produkt', meaning: 'Alle künftig denkbaren Erweiterungen („smart clothing“).' },
    ],
    misconceptions: ['Die Reihenfolge geht von innen/unten (Grundnutzen) nach außen/oben (potenziell) – zunehmender Zusatznutzen.', 'Erwartetes ≠ augmentiertes Produkt: erwartet = selbstverständlich, augmentiert = Extra darüber hinaus.'],
    conceptIds: ['mc-grundnutzen', 'mc-produkt'],
    validation: ok,
  },
  {
    id: 'f-programmbreite', chapterId: 'm2', file: 'img-002.png', pdfPage: 9,
    title: 'Programmbreite und Programmtiefe',
    caption: 'Breite = Anzahl Produktlinien (waagerecht), Tiefe = Produkte je Linie (senkrecht). Beispiel P&G.',
    explanationSimple: 'Eine Tabelle zeigt das Sortiment eines Konzerns. Waagerecht stehen die verschiedenen Produktlinien nebeneinander – das ist die Breite. Senkrecht darunter stehen die einzelnen Produkte/Marken einer Linie – das ist die Tiefe.',
    explanationExpert: 'Matrix des Produktprogramms: Die Breite ergibt sich aus der Anzahl der Produktlinien (hier vier: Baby-/Damenhygiene, Schönheitspflege, Wasch-/Reinigungsmittel, Gesundheit/Rasur). Die Tiefe ergibt sich aus der Zahl der Produkte je Linie (z. B. Always, Pampers … in der Hygiene-Linie). Beispiel Procter & Gamble.',
    elements: [
      { label: 'Breite (waagerechter Pfeil)', meaning: 'Anzahl der Produktlinien nebeneinander.' },
      { label: 'Tiefe (senkrechter Pfeil)', meaning: 'Zahl der Produkte/Marken innerhalb einer Produktlinie.' },
      { label: 'Produktlinie (Spalte)', meaning: 'Gruppe von Produkten mit gemeinsamem Kriterium, z. B. „Schönheitspflege“ (Olaz, Herbal Essences …).' },
    ],
    misconceptions: ['Breite und Tiefe nicht vertauschen: Breite = Zahl der Linien, Tiefe = Produkte je Linie.'],
    conceptIds: ['mc-programmbreite'],
    validation: ok,
  },
  {
    id: 'f-lebenszyklus', chapterId: 'm2', file: 'img-003.png', pdfPage: 10,
    title: 'Produktlebenszyklus',
    caption: 'Umsatz über die Zeit in fünf Phasen: Einführung, Wachstum, Reife, Sättigung, Verfall.',
    explanationSimple: 'Die Kurve zeigt den Umsatz eines Produkts im Zeitverlauf. Am Anfang (Einführung) niedrig, dann steigt er (Wachstum), erreicht sein Maximum (Reife/Sättigung) und fällt am Ende wieder (Verfall). Unter jeder Phase stehen die typischen Marketing-Aktivitäten.',
    explanationExpert: 'Idealtypischer Verlauf des Umsatzes über die Zeit in fünf Phasen mit je typischen Marketingaktivitäten: Einführung (Nachfrage stimulieren), Wachstum (Kampf um Marktanteile über Preis/Konditionen), Reife (Erhöhung der Werbeausgaben, Produktdifferenzierung; Erfahrungskurven-/Skaleneffekte am höchsten), Sättigung (Preissenkungen), Verfall (Produkt wird nicht mehr unterstützt).',
    elements: [
      { label: 'y-Achse: Umsatz', meaning: 'Höhe des Umsatzes.' },
      { label: 'x-Achse: Zeit', meaning: 'Zeitverlauf – die einzige Erklärungsvariable (Schwäche gegenüber dem S-Kurvenkonzept).' },
      { label: 'Reife-/Sättigungsphase', meaning: 'Umsatzmaximum; Erfahrungskurven- und Economies-of-Scale-Effekte am höchsten.' },
    ],
    misconceptions: ['Der reine Lebenszyklus erklärt nur über die Variable „Zeit“ – Technologiesprünge erfasst er nicht (dafür das S-Kurvenkonzept).'],
    conceptIds: ['mc-lebenszyklus', 'mc-erfahrungskurve'],
    validation: ok,
  },
  {
    id: 'f-skurve', chapterId: 'm2', file: 'img-004.png', pdfPage: 10,
    title: 'S-Kurvenkonzept (Foster)',
    caption: 'Leistungsfähigkeit über kumulierte F&E-Aufwendungen; Ablösung alter durch neue Technologie.',
    explanationSimple: 'Zwei S-förmige Kurven zeigen, wie leistungsfähig eine Technologie wird, je mehr man in Forschung investiert. Jede Technologie stößt irgendwann an eine Grenze (flacht ab). Dann übernimmt eine neue Technologie mit einer eigenen S-Kurve und höherem Potenzial.',
    explanationExpert: 'x-Achse: kumulierte Aufwendungen für Forschung und Entwicklung; y-Achse: Leistungsfähigkeit der Technologie. Die alte Technologie nähert sich ihrer Leistungsgrenze (Kurve flacht ab). Am „heutigen Stand“ ist das verbleibende Entwicklungspotenzial gering. Eine neue Technologie startet niedrig, hat aber eine höhere Grenze und löst die alte ab (technologische Diskontinuität). Ziel: Innovationsmanagement für Technologiesprünge sensibilisieren.',
    elements: [
      { label: 'x-Achse', meaning: 'Kumulierte F&E-Aufwendungen.' },
      { label: 'y-Achse', meaning: 'Leistungsfähigkeit der Technologie.' },
      { label: 'Grenze alte/neue Technologie', meaning: 'Obere Leistungsgrenze der jeweiligen Technologie.' },
      { label: 'heutiger Stand + Entwicklungspotenzial', meaning: 'Aktueller Punkt; der Abstand zur Grenze zeigt das verbleibende Potenzial.' },
    ],
    misconceptions: ['Die x-Achse ist NICHT die Zeit, sondern die kumulierten F&E-Aufwendungen – das unterscheidet das Konzept vom Produktlebenszyklus.'],
    conceptIds: ['mc-skurve', 'mc-innovationsmgmt'],
    validation: ok,
  },
  {
    id: 'f-diffusion', chapterId: 'm2', file: 'img-005.png', pdfPage: 11,
    title: 'Adopterkategorien / Diffusionskurve',
    caption: 'Verteilung der Übernehmer über die Adoptionszeit: Innovatoren bis Nachzügler.',
    explanationSimple: 'Die Glockenkurve zeigt, wann verschiedene Kundentypen ein neues Produkt annehmen. Zuerst die wenigen Innovatoren (2,5 %), dann Frühadopter (13,5 %), dann die große Mehrheit (frühe 34 %, späte 34 %) und zuletzt die Nachzügler (16 %).',
    explanationExpert: 'Normalverteilte Adopterkategorien nach Adoptionszeitpunkt (Rogers): Innovatoren 2,5 %, Frühadopter 13,5 %, frühe Mehrheit 34 %, späte Mehrheit 34 %, Nachzügler 16 %. Innovatoren und Frühadopter sind einflussreiche Multiplikatoren. Aufsummiert ergibt sich die S-förmige Diffusionskurve (Verlauf der kumulierten Adoption).',
    elements: [
      { label: 'x-Achse: Adoptionszeit', meaning: 'Zeitpunkt der Übernahme.' },
      { label: 'y-Achse: Adopter', meaning: 'Zahl der Übernehmer je Zeitpunkt.' },
      { label: 'Innovatoren/Frühadopter', meaning: 'Frühe, einflussreiche Segmente (Multiplikatoren/Influencer), zusammen ca. 16 %.' },
      { label: 'Frühe/späte Mehrheit', meaning: 'Das Gros der Nachfrage (je 34 %).' },
    ],
    misconceptions: ['Die glockenförmige Kurve zeigt die Übernehmer je Zeitpunkt; die kumulierte (aufsummierte) Kurve ist dagegen S-förmig (Diffusion).', 'Adoption (Einzelperson) ≠ Diffusion (Gesamtmarkt).'],
    conceptIds: ['mc-diffusion', 'mc-adoption'],
    validation: ok,
  },
  {
    id: 'f-paf', chapterId: 'm4', file: 'img-006.png', pdfPage: 18,
    title: 'Preis-Absatz-Funktionen im Vergleich',
    caption: 'Lineare, Gutenberg- und multiplikative PAF im selben Diagramm (Absatz über Preis).',
    explanationSimple: 'Das Diagramm zeigt drei Kurven, wie viel abgesetzt wird, je nachdem wie hoch der Preis ist. Die gerade Linie ist die lineare Funktion. Die doppelt geknickte Kurve ist das Gutenberg-Modell (in der Mitte reagiert die Menge kaum auf den Preis). Die stark gebogene Kurve ist die multiplikative Funktion.',
    explanationExpert: 'x-Achse: Preis p; y-Achse: Absatz x. Lineare PAF x(p)=a−b·p: Gerade von der Sättigungsmenge a (bei Preis 0) bis zum Maximalpreis a/b; die Steigung b ist die Preisreagibilität. Gutenberg-PAF: doppelt geknickt – im mittleren, monopolistischen Bereich reagiert die Menge kaum auf Preisänderungen (Markentreue). Multiplikative PAF x(p)=a·p^(−b): konvexe Kurve, schneidet die Achsen nicht → weder Sättigungsmenge noch Maximalpreis.',
    elements: [
      { label: 'Sättigungsmenge a', meaning: 'Absatz bei Preis 0 (Achsenabschnitt der linearen PAF).' },
      { label: 'Maximalpreis a/b', meaning: 'Preis, bei dem der Absatz der linearen PAF auf 0 fällt.' },
      { label: 'Steigung b (Dreieck 1/b)', meaning: 'Preisreagibilität – wie stark die Menge auf Preisänderungen reagiert.' },
      { label: 'Gutenberg-Kurve (doppelt geknickt)', meaning: 'Monopolistischer Mittelbereich: Menge bleibt trotz Preisänderung stabil.' },
    ],
    misconceptions: ['Die multiplikative PAF hat keinen Maximalpreis und keine Sättigungsmenge (schneidet die Achsen nie).', 'Der monopolistische Bereich ist der MITTLERE, flache Teil der Gutenberg-Kurve.'],
    conceptIds: ['mc-paf', 'mc-paf-linear', 'mc-gutenberg', 'mc-paf-mult'],
    validation: ok,
  },
  {
    id: 'f-pushpull', chapterId: 'm5', file: 'img-007.png', pdfPage: 21,
    title: 'Push- vs. Pull-Strategie',
    caption: 'Push „drückt“ über den Handel zum Kunden; Pull erzeugt Nachfragesog beim Endkunden.',
    explanationSimple: 'Oben der Hersteller, in der Mitte der Handel, unten der Kunde. Bei Push (rote Pfeile) drückt der Hersteller die Ware über Rabatte in den Handel, der Handel bewirbt sie beim Kunden. Bei Pull (lila Pfeile) spricht der Hersteller direkt die Endkunden an (z. B. Werbung), sodass diese das Produkt beim Handel nachfragen.',
    explanationExpert: 'Push-Strategie: Der Hersteller wirkt aktiv auf den Handel ein (Exklusivrechte, Boni, Rabatte); der Handel bewirbt das Produkt beim Endkunden (Werbung, Regalplatzierung) – die Ware wird „durch“ den Kanal gedrückt. Pull-Strategie: Der Hersteller richtet seine Kommunikation direkt an die Endkunden (SEO, Social-Media-Kampagnen, TV-Werbung); der Kunde fragt das Produkt aktiv beim Handel nach, der Handel fordert die Ware an – es entsteht ein Nachfragesog. In der Praxis werden beide kombiniert.',
    elements: [
      { label: 'Rote Pfeile (abwärts)', meaning: 'Push: Hersteller → Handel → Kunde; Ware wird in den Kanal gedrückt.' },
      { label: 'Lila Pfeile (aufwärts)', meaning: 'Pull: Kommunikation an Endkunden; Kunde fragt nach, Handel fordert an – Nachfragesog.' },
      { label: 'Herstellungs-, Handelsunternehmen, Kunde', meaning: 'Die drei Stufen des Vertriebskanals.' },
    ],
    misconceptions: ['Push und Pull schließen sich nicht aus – meist werden beide kombiniert.', 'Bei Pull richtet sich die Kommunikation an den Endkunden, NICHT an den Handel.'],
    conceptIds: ['mc-push-pull'],
    validation: ok,
  },
  {
    id: 'f-vertriebswege', chapterId: 'm5', file: 'img-008.png', pdfPage: 22,
    title: 'Indirekte Vertriebswege nach Stufigkeit',
    caption: 'Ein-, zwei- und dreistufiger Vertriebsweg zwischen Hersteller und Endverbraucher.',
    explanationSimple: 'Drei Wege, wie ein Produkt vom Hersteller zum Kunden kommt. Einstufig: nur über den Einzelhandel (z. B. Konsumgüter). Zweistufig: über Groß- und Einzelhandel (z. B. Pharma). Dreistufig: zusätzlich über einen Absatzhelfer (z. B. exotische Früchte).',
    explanationExpert: 'Darstellung indirekter Vertriebswege nach Zahl der zwischengeschalteten Handelsstufen: einstufig (Hersteller → Einzelhandel → Endverbraucher, z. B. Konsumgüter), zweistufig (+ Großhandel, z. B. Pharmaprodukte), dreistufig (+ Absatzhelfer, z. B. exotische Früchte). Je mehr Stufen, desto größer Marktabdeckung/Arbeitsteilung, aber desto mehr Handelsmargen und geringere Kontrolle.',
    elements: [
      { label: 'Einstufiger Weg', meaning: 'Hersteller → Einzelhandel → Endverbraucher (z. B. Konsumgüter).' },
      { label: 'Zweistufiger Weg', meaning: 'Zusätzlich Großhandel (z. B. Pharmaprodukte).' },
      { label: 'Dreistufiger Weg', meaning: 'Zusätzlich Absatzhelfer (z. B. exotische Früchte).' },
    ],
    misconceptions: ['Alle drei sind Formen des INDIREKTEN Vertriebs (immer mind. eine Handelsstufe). Direkter Vertrieb wäre nullstufig (Hersteller → Endverbraucher).'],
    conceptIds: ['mc-direkt-indirekt', 'mc-absatzhelfer-mittler'],
    validation: ok,
  },
  {
    id: 'f-distributionsgrad', chapterId: 'm5', file: 'img-009.png', pdfPage: 23,
    title: 'Distributionsgrad (Vertriebswegedifferenzierung)',
    caption: 'Pyramide: intensiver, selektiver und exklusiver Vertrieb mit passenden Gütertypen.',
    explanationSimple: 'Eine Pyramide mit drei Stufen. Unten der intensive Vertrieb: sehr viele Partner, günstige Produkte (Convenience Goods). Mitte der selektive Vertrieb: mehrere Partner, Shopping Goods. Oben der exklusive Vertrieb: wenige Partner, teure Specialty Goods.',
    explanationExpert: 'Der Distributionsgrad beschreibt, über wie viele Absatzmittler je Stufe verkauft wird: Intensiver Vertrieb (sehr viele Vertriebspartner, günstige Produkte, Convenience Goods) – maximale Verfügbarkeit. Selektiver Vertrieb (mehrere Partner, Shopping Goods) – gezielte Auswahl. Exklusiver Vertrieb (wenige Partner, teure Produkte, Specialty Goods) – Prestige und Kontrolle.',
    elements: [
      { label: 'Intensiver Vertrieb (Basis)', meaning: 'Sehr viele Partner, günstige Convenience Goods.' },
      { label: 'Selektiver Vertrieb (Mitte)', meaning: 'Mehrere Partner, Shopping Goods.' },
      { label: 'Exklusiver Vertrieb (Spitze)', meaning: 'Wenige Partner, teure Specialty Goods.' },
    ],
    misconceptions: ['Convenience Goods → intensiv, Specialty Goods → exklusiv (nicht vertauschen).', 'Weniger Partner bedeutet nicht weniger Umsatz, sondern mehr Kontrolle/Prestige.'],
    conceptIds: ['mc-distributionsgrad', 'mc-kaufgewohnheit'],
    validation: ok,
  },
];
