import { Question } from '@/lib/types';

/** Fragen Kapitel 2 – Produktpolitik (PDF S. 6–10). */
export const questions2: Question[] = [
  // ======================= bestehende Fragen (IDs unverändert) =======================
  {
    id: 'qm2-01', chapterId: 'm2', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Warum wird statt Produktpolitik oft der Begriff „Leistungspolitik“ verwendet?',
    options: [
      'Um die große Vielfalt materieller und immaterieller Produkte (z. B. digitale Güter, Ideen) zu erfassen',
      'Weil ausschließlich Dienstleistungen gemeint sind',
      'Weil es nur um die Leistung der Mitarbeiter geht',
      'Weil die Produktpolitik nicht zu den vier Ps gehört',
    ],
    correctOptions: [0],
    explanation: 'Produkte können materiell (Smartphone) oder immateriell (Streaming, Ideen, In-Game-Items, Online-Coaching) sein – deshalb der umfassendere Begriff Leistungspolitik.',
    source: 'Kapitel 2.1, PDF S. 6', conceptIds: ['mc-leistungspolitik', 'mc-produkt'],
  },
  {
    id: 'qm2-02', chapterId: 'm2', type: 'cloze', goal: 'fact', difficulty: 1,
    prompt: 'Ein Produkt ist ein Bündel von ______ (Ausstattung, Funktionen, Nutzen und Verwendung). ______ ist das, was das Unternehmen bietet; Nutzen beschreibt, was der Kunde davon hat.',
    clozeAnswers: [['Attributen', 'Attribute', 'Eigenschaften'], ['Leistung', 'Die Leistung']],
    explanation: 'Produkt = Bündel von Attributen. Leistung = Anbietersicht, Nutzen = Kundensicht; Leistung führt meist zu Nutzen.',
    source: 'Kapitel 2.1, PDF S. 6–7', conceptIds: ['mc-produkt', 'mc-leistung-nutzen'],
  },
  {
    id: 'qm2-03', chapterId: 'm2', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie den Gütertyp nach Kaufgewohnheit dem passenden Skript-Beispiel zu.',
    pairs: [
      { left: 'Convenience Goods', right: 'Shampoo, Brot – mühelos und regelmäßig gekauft' },
      { left: 'Shopping Goods', right: 'Kleidung, Möbel – mit Such- und Vergleichsaufwand' },
      { left: 'Specialty Goods', right: 'Antiquitäten, hochpreisige Modemarken – einzigartige Eigenschaften' },
      { left: 'Unsought Goods', right: 'Versicherungen – nicht aktiv nachgefragt' },
    ],
    explanation: 'Die vier Typen nach Kaufgewohnheit (Walsh/Deseniss/Kilian 2013) – sie tauchen beim Distributionsgrad wieder auf.',
    source: 'Kapitel 2.1, PDF S. 8', conceptIds: ['mc-kaufgewohnheit', 'mc-convenience', 'mc-shopping', 'mc-specialty', 'mc-unsought'],
  },
  {
    id: 'qm2-04', chapterId: 'm2', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Ein Hersteller ändert Design und Geschmack seines Riegels; die Basisfunktion bleibt, die alte Variante verschwindet. Was liegt vor?',
    options: ['Produktvariation', 'Produktdifferenzierung', 'Produktelimination', 'Produktprogrammerweiterung'],
    correctOptions: [0],
    explanation: 'Produktvariation: bewusste Veränderung von Nutzenkomponenten bei gleicher Basisfunktion. Bei Differenzierung würden beide Varianten angeboten.',
    source: 'Kapitel 2.2, PDF S. 8–9', conceptIds: ['mc-produktvariation', 'mc-produktdiff'],
  },
  {
    id: 'qm2-05', chapterId: 'm2', type: 'true_false', goal: 'distinction', difficulty: 2,
    prompt: 'Bei der Produktdifferenzierung erweitert sich das Produktprogramm, weil die abgewandelte Version zusätzlich zur bestehenden angeboten wird.',
    correctBool: true,
    explanation: 'Richtig – abgewandelte Versionen sprechen neue Marktsegmente an; anders als bei der Variation bleiben beide Varianten im Angebot.',
    source: 'Kapitel 2.2, PDF S. 9', conceptIds: ['mc-produktdiff', 'mc-produktvariation'],
  },
  {
    id: 'qm2-06', chapterId: 'm2', type: 'cloze', goal: 'fact', difficulty: 1,
    prompt: 'Im Produktprogramm wird die ______ durch die Anzahl der Produktlinien definiert; die ______ beschreibt die Zahl der Produkte pro Produktlinie.',
    clozeAnswers: [['Programmbreite', 'Breite'], ['Programmtiefe', 'Tiefe']],
    explanation: 'Breite = Anzahl der Linien; Tiefe = Produkte je Linie.',
    source: 'Kapitel 2.2, PDF S. 9', conceptIds: ['mc-programmbreite', 'mc-programmtiefe'],
  },
  {
    id: 'qm2-07', chapterId: 'm2', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche Anforderungen sollte eine gute Produktverpackung laut Skript erfüllen? (Mehrfachauswahl)',
    options: ['Das Produkt schützen', 'Werblich anpreisen', 'Anwenderfreundlich sein', 'Möglichst schwer und massiv sein', 'Möglichst leicht und ökologisch sinnvoll zu entsorgen sein'],
    correctOptions: [0, 1, 2, 4],
    explanation: 'Schützen, anpreisen, anwenderfreundlich, leicht und ökologisch sinnvoll entsorgbar.',
    source: 'Kapitel 2.2, PDF S. 8', conceptIds: ['mc-verpackung'],
  },
  {
    id: 'qm2-08', chapterId: 'm2', type: 'assignment', goal: 'fact', difficulty: 2,
    prompt: 'Ordnen Sie der Phase des Produktlebenszyklus die typische Marketingaktivität laut Abbildung zu.',
    pairs: [
      { left: 'Einführungsphase', right: 'Einführungsaktivitäten, um Nachfrage zu stimulieren' },
      { left: 'Wachstumsphase', right: 'Kampf um Marktanteile über Preis und Konditionen' },
      { left: 'Reifephase', right: 'Erhöhung der Werbeausgaben, Produktdifferenzierung' },
      { left: 'Sättigungsphase', right: 'Preissenkungen' },
      { left: 'Verfallsphase', right: 'Produkt wird nicht mehr unterstützt' },
    ],
    explanation: 'Die Aktivitäten stehen in der Abbildung zum Produktlebenszyklus unter den Phasen.',
    source: 'Kapitel 2.3, Abbildung PDF S. 9', conceptIds: ['mc-lebenszyklus', 'mc-einfuehrungsphase', 'mc-wachstumsphase', 'mc-reifephase', 'mc-saettigungsphase', 'mc-verfallsphase'],
  },
  {
    id: 'qm2-09', chapterId: 'm2', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Warum reicht der Produktlebenszyklus nicht aus, um Technologiesprünge zu erklären? Erläutern Sie, was das S-Kurvenkonzept zusätzlich leistet.',
    rubric: [
      { point: 'Produktlebenszyklus nutzt hauptsächlich die Erklärungsvariable Zeit', keywords: ['zeit', 'erklärungsvariable'] },
      { point: 'S-Kurve (Foster 1986): Innovationsmanagement für technologische Diskontinuitäten sensibilisieren', keywords: ['diskontinuität', 'sensibilisier', 'foster', 'technologiesprung'] },
      { point: 'Jede Technologie stößt an eine Leistungsgrenze (Größe, Komplexität, Materialeigenschaften) und wird ersetzt', keywords: ['leistungsgrenze', 'grenze', 'größe', 'komplexität', 'material', 'ersetzt', 'neue technologie'] },
      { point: 'Konsequenz: Grenzen abschätzen, F&E entwickelt kontinuierlich neue Produkte', keywords: ['f&e', 'forschung', 'kontinuierlich', 'abschätzen', 'vorbereit'], weight: 0.5 },
    ],
    modelAnswer: 'Der Produktlebenszyklus erklärt den Verlauf hauptsächlich über die Variable Zeit und kann deshalb Technologiesprünge nicht erklären. Das S-Kurvenkonzept (Foster 1986) soll das Innovationsmanagement für technologische Diskontinuitäten sensibilisieren: Jede Technologie stößt zwangsläufig an eine Leistungsgrenze – bedingt durch Größe, Komplexität oder Materialeigenschaften – und wird durch eine neue Technologie ersetzt. Unternehmen müssen daher die Grenzen ihrer Technologien abschätzen; F&E sollte kontinuierlich neue Produkte entwickeln und vorbereiten.',
    explanation: 'Zeit (PLZ) vs. Leistungsgrenze/F&E-Aufwand (S-Kurve).',
    source: 'Kapitel 2.3, PDF S. 10', conceptIds: ['mc-skurve', 'mc-lebenszyklus', 'mc-diskontinuitaet'],
  },
  {
    id: 'qm2-10', chapterId: 'm2', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Was beschreibt der Diffusionsprozess im Unterschied zum Adoptionsprozess?',
    options: [
      'Die kumulierte Adoption einer Neuerung im Zeitablauf',
      'Die fünf Phasen von der Aufmerksamkeit bis zur Annahme bei einer Person',
      'Die Entwicklung eines Produkts in der F&E-Abteilung',
      'Die Preisentwicklung im Produktlebenszyklus',
    ],
    correctOptions: [0],
    explanation: 'Diffusion = kumulierte Adoption im Zeitablauf. Adoptionsprozess = fünf Phasen (Aufmerksamkeit, Interesse, Bewertung, Versuch, Annahme).',
    source: 'Kapitel 2.3, PDF S. 10', conceptIds: ['mc-diffusion', 'mc-adoption'],
  },
  {
    id: 'qm2-11', chapterId: 'm2', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein Tech-Unternehmen bringt eine neue Smartwatch heraus. Wie kann es den Diffusionsprozess gezielt beschleunigen? Beziehen Sie die Adopterkategorien ein.',
    rubric: [
      { point: 'Innovatoren und frühe Adopter zuerst gezielt ansprechen', keywords: ['innovatoren', 'frühe adopter', 'frühadopter', 'zuerst'] },
      { point: 'Sie sind hochinformiert und einflussreiche Multiplikatoren (Tech-Blogger, YouTuber, Fachexperten)', keywords: ['multiplikator', 'influencer', 'blogger', 'youtuber', 'experten'] },
      { point: 'Dadurch Verbreitung zur frühen und späten Mehrheit (soziale Empfehlungen)', keywords: ['mehrheit', 'empfehlung', 'verbreitung', 'diffusion'] },
    ],
    modelAnswer: 'Das Unternehmen sollte zuerst Innovatoren und frühe Adopter gezielt ansprechen. Diese sind hochinformiert, haben großes Interesse am Produkt und sind heute oft als Tech-Blogger, YouTuber oder Fachexperten aktiv – also einflussreiche Multiplikatoren. Laut Skript ist ihre Ansprache äußerst wichtig, um den Diffusionsprozess voranzutreiben (Rogers 2003): Über soziale Empfehlungen wird das Produkt bekannter, die Unsicherheit sinkt, und die frühe und späte Mehrheit zieht nach.',
    explanation: 'Frühe Segmente als Hebel für die Verbreitung im Gesamtmarkt.',
    source: 'Kapitel 2.3, PDF S. 10', conceptIds: ['mc-innovatoren', 'mc-diffusion', 'mc-adopterkategorien'],
  },

  // ======================= neue offene Fragen =======================
  {
    id: 'qm2-12', chapterId: 'm2', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erläutern Sie, warum die Produktpolitik als „Herz des Marketingmix“ gilt, und definieren Sie den Produktbegriff einschließlich materieller und immaterieller Produkte.',
    rubric: [
      { point: 'Produkt ist Grundvoraussetzung für jede Marketingtätigkeit', keywords: ['grundvoraussetzung', 'voraussetzung', 'herz'] },
      { point: 'Produktpolitik = alle Entscheidungen zur Gestaltung des Leistungsangebots (Bruhn 2016)', keywords: ['leistungsangebot', 'entscheidungen', 'gestaltung'] },
      { point: 'Produkt = Bündel von Attributen, ausgetauscht/verwendet zur Bedürfnisbefriedigung', keywords: ['bündel', 'attribut', 'bedürfnisbefriedigung'] },
      { point: 'Materiell (Smartphone) und immateriell (Streaming, Ideen, digitale Güter)', keywords: ['materiell', 'immateriell', 'smartphone', 'stream', 'digitale güter'] },
    ],
    modelAnswer: 'Die Produktpolitik ist das Herz des Marketingmix, weil ein zu vermarktendes Produkt die Grundvoraussetzung für jede Marketingtätigkeit ist. Sie umfasst alle Entscheidungen, die die Gestaltung des Leistungsangebots betreffen (Bruhn 2016); zentrale Frage: Was soll vermarktet werden? Ein Produkt ist ein Bündel von Attributen (Ausstattung, Funktionen, Nutzen, Verwendung), das ausgetauscht oder verwendet werden kann – alles, was ein Konsument zur Bedürfnisbefriedigung erhalten kann. Es kann materiell (z. B. Smartphone) oder immateriell sein (z. B. Streamen eines Liedes, Ideen wie Liedtext oder Melodie, digitale Güter wie In-Game-Items oder Online-Coaching).',
    explanation: 'Begründung + Definition + Beispiele.',
    source: 'Kapitel 2.1, PDF S. 6', conceptIds: ['mc-produktpolitik', 'mc-produkt'],
  },
  {
    id: 'qm2-13', chapterId: 'm2', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erläutern Sie die drei Produktebenen nach Leistung am Beispiel eines E-Bikes und erklären Sie, warum Zusatzleistungen in gesättigten Märkten immer wichtiger werden.',
    rubric: [
      { point: 'Kernprodukt: Kernleistung/Bedürfnisbefriedigung (Fortbewegung, erleichtert durch Elektroantrieb)', keywords: ['kernprodukt', 'kernleistung', 'fortbewegung'] },
      { point: 'Reales Produkt: sichtbares, kaufbares Produkt (Rahmen, Akku, Motor, Display, Design, Marke)', keywords: ['reales produkt', 'akku', 'motor', 'display', 'design'] },
      { point: 'Erweitertes Produkt: Zusatzleistungen (Software-Updates, Wartung, Garantie, Service)', keywords: ['erweitertes produkt', 'zusatzleistung', 'update', 'wartung', 'garantie', 'service'] },
      { point: 'Gesättigte Märkte: Produkte unterscheiden sich kaum → Abhebung über Zusatzleistungen', keywords: ['gesättigt', 'geringfügig', 'abheb', 'unterscheiden'] },
    ],
    modelAnswer: 'Das Kernprodukt ist die Kernleistung – die Befriedigung eines Bedürfnisses: Das E-Bike ermöglicht Fortbewegung auf zwei Rädern, durch den Elektroantrieb wird das Fahren erleichtert. Das reale Produkt setzt dies in ein sichtbares, kaufbares Produkt mit Design, technischer Qualität, Funktionen, Verpackung und Marke um: Rahmen mit integriertem Akku und Motor, Unterstützungsstufen, Display. Das erweiterte Produkt umfasst alle Zusatzleistungen wie Lieferung, Finanzierung, Garantie, Beratung, Installation und Service – beim E-Bike z. B. regelmäßige Software-Updates und Wartung beim Fachhändler. In gesättigten Märkten unterscheiden sich Produkte oft nur geringfügig, deshalb werden Zusatzleistungen immer bedeutender, um sich aus Kundensicht vom Wettbewerb abzuheben.',
    explanation: 'Leistungs-Sicht der Produktebenen (Abbildung S. 7).',
    source: 'Kapitel 2.1, PDF S. 6–7', conceptIds: ['mc-produktebenen-leistung', 'mc-kernprodukt', 'mc-reales-produkt', 'mc-erweitertes-produkt'],
  },
  {
    id: 'qm2-14', chapterId: 'm2', type: 'open', goal: 'distinction', difficulty: 2,
    prompt: 'Grenzen Sie die Begriffe Leistung und Nutzen voneinander ab und nennen Sie das Skript-Beispiel für eine Leistung ohne unmittelbaren Kundennutzen.',
    rubric: [
      { point: 'Leistung: was das Unternehmen bietet', keywords: ['unternehmen bietet', 'anbieter', 'bietet'] },
      { point: 'Nutzen: was der Kunde davon hat', keywords: ['kunde davon hat', 'kunde', 'kundensicht'] },
      { point: 'Leistung führt meist zu Nutzen, aber nicht immer', keywords: ['meist', 'nicht immer', 'ohne unmittelbaren'] },
      { point: 'Beispiel: Pappverpackung der Zahnpastatube nützt durch Stapelbarkeit eher dem Handel', keywords: ['zahnpasta', 'pappverpackung', 'stapel', 'handel'] },
    ],
    modelAnswer: 'Leistung ist das, was das Unternehmen bietet; Nutzen beschreibt, was der Kunde davon hat. Leistung führt meist zu Nutzen, es sind aber auch Leistungen ohne unmittelbaren Kundennutzen denkbar – z. B. die Pappverpackung einer Zahnpastatube, die durch ihre Stapelbarkeit eher dem Handel zugutekommt.',
    explanation: 'Anbietersicht vs. Kundensicht.',
    source: 'Kapitel 2.1, PDF S. 7', conceptIds: ['mc-leistung-nutzen'],
  },
  {
    id: 'qm2-15', chapterId: 'm2', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Was versteht man unter Grundnutzen und Zusatznutzen? Nennen und erläutern Sie die drei Arten von Zusatznutzen am Beispiel einer Hose.',
    rubric: [
      { point: 'Grundnutzen: Befriedigung des ursprünglichen Bedürfnisses (Hose bekleidet und wärmt)', keywords: ['ursprüngliche', 'bedürfnis', 'bekleid', 'wärmt'] },
      { point: 'Nur Grundnutzen ist meist nicht akzeptabel', keywords: ['nicht akzeptabel', 'reicht nicht'] },
      { point: 'Sozialer Nutzen/Geltungsnutzen: dem Anlass angemessen', keywords: ['geltungsnutzen', 'sozialer nutzen', 'anlass'] },
      { point: 'Erbauungsnutzen: gut sitzen, der Figur schmeicheln', keywords: ['erbauungsnutzen', 'sitzen', 'figur'] },
      { point: 'Emotionaler Nutzen: Marke, gutes Gefühl', keywords: ['emotional', 'gutes gefühl', 'marke'] },
    ],
    modelAnswer: 'Der Grundnutzen ist die Befriedigung des ursprünglichen Bedürfnisses – eine Hose bekleidet und wärmt. Ein Produkt, das nur den Grundnutzen erfüllt, ist meist nicht akzeptabel. Zusatznutzen sind: sozialer bzw. Geltungsnutzen (die Hose ist dem Anlass angemessen), Erbauungsnutzen (sie sitzt gut, schmeichelt der Figur) und emotionaler Nutzen (Marke, gutes Gefühl). Die Zusatznutzen sind nicht an eine Reihenfolge gebunden und müssen nicht zwangsläufig vorhanden sein.',
    explanation: 'Grundnutzen + drei Zusatznutzen mit Hosen-Beispiel.',
    source: 'Kapitel 2.1, PDF S. 7', conceptIds: ['mc-grundnutzen', 'mc-zusatznutzen'],
  },
  {
    id: 'qm2-16', chapterId: 'm2', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Vom Nutzenstandpunkt aus ergeben sich fünf Produktkategorien. Erläutern Sie diese in der richtigen Reihenfolge am Beispiel einer Hose.',
    rubric: [
      { point: 'Grundnutzen: bekleiden und wärmen (Stück Stoff)', keywords: ['grundnutzen', 'bekleiden', 'stoff'] },
      { point: 'Generisches Produkt: Hosenbeine geschneidert', keywords: ['generisch', 'hosenbeine', 'geschneidert'] },
      { point: 'Erwartetes Produkt: bequemer Sitz, gefälliges Design', keywords: ['erwartet', 'bequem', 'design'] },
      { point: 'Augmentiertes Produkt: Marke, wasserabweisend, Thermo, modisch', keywords: ['augmentiert', 'wasserabweisend', 'thermo', 'markenname'] },
      { point: 'Potenzielles Produkt: Extrafunktionalitäten, smart clothing', keywords: ['potenziell', 'smart clothing', 'extrafunktion'] },
    ],
    modelAnswer: 'Je mehr Nutzenkomponenten, desto höher die Kategorie: 1) Grundnutzen – bekleiden und wärmen, z. B. ein ausreichend großes Stück Stoff. 2) Generisches Produkt – Hosenbeine geschneidert. 3) Erwartetes Produkt – bequemer Sitz und gefälliges Design. 4) Augmentiertes Produkt – Markenname, wasserabweisend, Thermo, modisch. 5) Potenzielles Produkt – Extrafunktionalitäten wie „smart clothing“.',
    explanation: 'Nutzen-Sicht der Produktebenen (Abbildung S. 7).',
    source: 'Kapitel 2.1, Abbildung PDF S. 7', conceptIds: ['mc-nutzenkategorien', 'mc-generisches-produkt', 'mc-erwartetes-produkt', 'mc-augmentiertes-produkt', 'mc-potenzielles-produkt', 'mc-grundnutzen'],
  },
  {
    id: 'qm2-17', chapterId: 'm2', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Definieren Sie den Qualitätsbegriff und erläutern Sie mindestens fünf Qualitätsdimensionen.',
    rubric: [
      { point: 'Definition: Gesamtheit der Bestandteile/Eigenschaften, die die Fähigkeit zur Bedürfnisbefriedigung beeinflussen', keywords: ['gesamtheit', 'eigenschaften', 'bedürfnisse zu befriedigen', 'bedürfnis'] },
      { point: 'Objektiv (messbar) oder subjektiv (Vorstellungen des Konsumenten)', keywords: ['objektiv', 'subjektiv', 'messbar'] },
      { point: 'Gebrauchsnutzen, Haltbarkeit, Zuverlässigkeit', keywords: ['gebrauchsnutzen', 'haltbarkeit', 'zuverlässigkeit'] },
      { point: 'Ausstattung, Normgerechtigkeit, Ästhetik, Umwelt-/Sozialverträglichkeit', keywords: ['ausstattung', 'normgerecht', 'ästhetik', 'umwelt', 'sozialverträglich'] },
    ],
    modelAnswer: 'Qualität ist die „Gesamtheit der Bestandteile und Eigenschaften eines Produkts oder einer Dienstleistung, die sich auf seine Fähigkeit auswirken, Bedürfnisse zu befriedigen“ (Kotler/Keller/Opresnik 2015); sie kann objektiv (messbare Eigenschaften) oder subjektiv (gemessen an den Vorstellungen des Konsumenten) betrachtet werden. Dimensionen (Meffert/Burmann/Kirchgeorg 2015): Gebrauchsnutzen (funktioniert es wie erwartet?), Haltbarkeit (Lebensdauer), Zuverlässigkeit (Wahrscheinlichkeit des Versagens), Ausstattung (Zusatzvorzüge), Normgerechtigkeit (Gütenormen), Ästhetik (gefällt es?), Umwelt- und Sozialverträglichkeit (ist es nachhaltig?).',
    explanation: 'Definition + objektiv/subjektiv + Dimensionen.',
    source: 'Kapitel 2.1, PDF S. 7', conceptIds: ['mc-qualitaet', 'mc-qualitaetsdimensionen'],
  },
  {
    id: 'qm2-18', chapterId: 'm2', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Erläutern Sie die fünf Unterscheidungsmerkmale der Produkttypologisierung jeweils mit Beispiel. Warum ist eine solche Kategorisierung sinnvoll?',
    rubric: [
      { point: 'Materialität: Sachgüter vs. Dienstleistungen', keywords: ['materialität', 'sachgüter', 'dienstleistung'] },
      { point: 'Konsumentengruppe: Konsumgüter (B2C) vs. Investitionsgüter (B2B)', keywords: ['konsumgüter', 'investitionsgüter', 'b2c', 'b2b'] },
      { point: 'Nutzungsdauer: Verbrauchs- vs. Gebrauchsgüter', keywords: ['verbrauchsgüter', 'gebrauchsgüter', 'nutzungsdauer'] },
      { point: 'Nutzungshäufigkeit: täglicher vs. aperiodischer Bedarf', keywords: ['täglich', 'aperiodisch', 'nutzungshäufigkeit'] },
      { point: 'Kaufgewohnheit: Convenience, Shopping, Specialty, Unsought Goods', keywords: ['kaufgewohnheit', 'convenience', 'shopping', 'specialty', 'unsought'] },
      { point: 'Nutzen: Begriffsverständnis + Auswahl passender Marketingstrategien', keywords: ['marketingstrategie', 'begriffsverständnis', 'handbücher'], weight: 0.5 },
    ],
    modelAnswer: 'Nach Walsh/Deseniss/Kilian (2013): Materialität – Sachgüter (physisch berührbar: Bleistift, Auto) vs. Dienstleistungen (Haarschnitt, Ölwechsel, Steuererklärung). Konsumentengruppe – Konsumgüter für Endkonsumenten (B2C) vs. Investitionsgüter für Unternehmen (B2B); manche Produkte wie Büromaterial gehören zu beiden. Nutzungsdauer – Verbrauchsgüter (Lebensmittel) vs. Gebrauchsgüter (Fahrrad). Nutzungshäufigkeit – Waren des täglichen (Zahnpasta) vs. aperiodischen Bedarfs (Weihnachtsbäume). Kaufgewohnheit – Convenience Goods (Shampoo, Brot), Shopping Goods (Kleidung, Möbel), Specialty Goods (Antiquitäten, hochpreisige Modemarken), Unsought Goods (Versicherungen). Die Kategorisierung hilft dem Begriffsverständnis und ist für die Auswahl passender Marketingstrategien bedeutsam (z. B. eigene Handbücher für Dienstleistungs-, B2B- oder Destinationsmarketing).',
    explanation: 'Fünf Merkmale + Begründung.',
    source: 'Kapitel 2.1, PDF S. 7–8', conceptIds: ['mc-guetertypen', 'mc-sachgueter-dl', 'mc-konsum-invest', 'mc-verbrauch-gebrauch', 'mc-bedarf', 'mc-kaufgewohnheit'],
  },
  {
    id: 'qm2-19', chapterId: 'm2', type: 'transfer', goal: 'application', difficulty: 2,
    prompt: 'Ordnen Sie folgende Produkte den Gütern nach Kaufgewohnheit zu und begründen Sie kurz: Duschgel, Esstisch, Mantel einer hochpreisigen Modemarke, Berufsunfähigkeitsversicherung.',
    rubric: [
      { point: 'Duschgel: Convenience Good (mühelos, regelmäßig – wie Shampoo)', keywords: ['convenience'] },
      { point: 'Esstisch: Shopping Good (Such- und Vergleichsaufwand – wie Möbel)', keywords: ['shopping'] },
      { point: 'Mantel der hochpreisigen Modemarke: Specialty Good (einzigartige Eigenschaften)', keywords: ['specialty'] },
      { point: 'Versicherung: Unsought Good (nicht aktiv nachgefragt, unattraktiv)', keywords: ['unsought'] },
    ],
    modelAnswer: 'Duschgel ist ein Convenience Good: Es wird mühelos, ohne viel Aufwand und regelmäßig gekauft (wie Shampoo). Der Esstisch ist ein Shopping Good: seltener gekauft, mit mehr Such- und Vergleichsaufwand (wie Möbel). Der Mantel einer hochpreisigen Modemarke ist ein Specialty Good mit einzigartigen Eigenschaften. Die Berufsunfähigkeitsversicherung ist ein Unsought Good: Sie wird nicht aktiv nachgefragt, weil sie unbekannt oder unattraktiv ist (wie Versicherungen im Skript).',
    explanation: 'Anwendung der vier Kaufgewohnheits-Typen.',
    source: 'Kapitel 2.1, PDF S. 8', conceptIds: ['mc-convenience', 'mc-shopping', 'mc-specialty', 'mc-unsought'],
  },
  {
    id: 'qm2-20', chapterId: 'm2', type: 'open', goal: 'fact', difficulty: 2,
    prompt: 'Wer trifft produktpolitische Entscheidungen, welche Ziele kann die Produktpolitik verfolgen und welche drei Gestaltungsfelder gibt es?',
    rubric: [
      { point: 'Produktmanager (Entwicklung und Führung der Produkte am Markt)', keywords: ['produktmanager'] },
      { point: 'Ziele: ökonomisch (verkaufte Mengen, Segmente) oder psychologisch (Image, Einstellungen)', keywords: ['ökonomisch', 'psychologisch', 'image', 'einstellung', 'mengen'] },
      { point: 'Gestaltungsfelder: erstmalige Produktgestaltung, Variation mit der Zeit, Kombination zu Produktprogrammen', keywords: ['erstmalig', 'grundsätzliche', 'variation', 'kombination', 'produktprogramm'] },
    ],
    modelAnswer: 'Produktmanager treffen die Entscheidungen; sie sind für Entwicklung und Führung der Produkte am Markt zuständig (Bruhn 2016). Die Ziele können ökonomisch (verkaufte Mengen, Ansprache bestimmter Segmente) oder psychologisch (Image, Konsumenteneinstellungen) sein. Drei Gestaltungsfelder: die grundsätzliche (erstmalige) Produktgestaltung, die Variation von Produkten mit der Zeit und die Kombination von Produkten zu Produktprogrammen (Portfolio/Sortiment).',
    explanation: 'Akteur + Ziele + Gestaltungsfelder (Kapitel 2.2).',
    source: 'Kapitel 2.2, PDF S. 8', conceptIds: ['mc-produktmanager', 'mc-ziele-produktpolitik', 'mc-gestaltungsfelder', 'mc-produktprogramm'],
  },
  {
    id: 'qm2-21', chapterId: 'm2', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Erläutern Sie die fünf Aspekte der Produktgestaltung jeweils mit Leitfrage und – wo vorhanden – am Beispiel Pampers.',
    rubric: [
      { point: 'Technisch-funktionale Eigenschaften: Kernnutzen bereitstellen (saugstark und sanft)', keywords: ['technisch', 'funktional', 'kernnutzen', 'saugstark'] },
      { point: 'Produktdesign: äußere Gestaltung (Schnitt, Farben, Muster)', keywords: ['design', 'farbe', 'form', 'muster', 'schnitt'] },
      { point: 'Produktverpackung: schützen, anpreisen, anwenderfreundlich, ökologisch entsorgbar', keywords: ['verpackung', 'schützen', 'anpreisen', 'entsorg'] },
      { point: 'Qualitätsmanagement: Eigenschaften dauerhaft sichern, Prozesse optimieren', keywords: ['qualitätsmanagement', 'dauerhaft', 'prozesse', 'arbeitsabläufe'] },
      { point: 'Servicepolitik: Garantien, Lieferung, Kundendienst, Value Added Services (Onlinebabyratgeber)', keywords: ['service', 'garantie', 'kundendienst', 'value added', 'babyratgeber'] },
    ],
    modelAnswer: 'Die Produktgestaltung entwickelt die Gesamtheit von Kern- und Zusatzleistungen. 1) Technisch-funktionale Eigenschaften: Wie wird der Kernnutzen bereitgestellt? – Pampers: Material, das saugstark und zugleich sanft ist. 2) Produktdesign: Wie ist das Produkt äußerlich durch Farbe, Form usw. gestaltet? – Schnitt, Farben, Muster. 3) Produktverpackung: Sie soll das Produkt schützen, werblich anpreisen, anwenderfreundlich sowie leicht und ökologisch sinnvoll zu entsorgen sein. 4) Qualitätsmanagement: Wie werden die funktional-technischen Eigenschaften dauerhaft gesichert? – dient der Optimierung von Arbeitsabläufen und Prozessen. 5) Servicepolitik: Sollen weitere Serviceleistungen (Garantien, Lieferung, Kundendienst, Value Added Services) angeboten werden? – Pampers-Onlinebabyratgeber und Schwangerschaftstipps.',
    explanation: 'Fünf Aspekte der Produktgestaltung (Kapitel 2.2).',
    source: 'Kapitel 2.2, PDF S. 8', conceptIds: ['mc-produktgestaltung', 'mc-technisch-funktional', 'mc-produktdesign', 'mc-verpackung', 'mc-qualitaetsmanagement', 'mc-servicepolitik'],
  },
  {
    id: 'qm2-22', chapterId: 'm2', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Was versteht man unter Serviceleistungen und welche Fragen klärt die Servicepolitik?',
    rubric: [
      { point: 'Immaterielle Leistungen, die die Primärleistung unterstützen oder eigenständig sind', keywords: ['immateriell', 'primärleistung', 'eigenständig', 'unterstütz'] },
      { point: 'Steigern den Kundennutzen', keywords: ['kundennutzen', 'steigern'] },
      { point: 'Servicepolitik: ob Garantien, Lieferung, Kundendienst, Value Added Services angeboten werden', keywords: ['garantie', 'lieferung', 'kundendienst', 'value added'] },
    ],
    modelAnswer: 'Serviceleistungen sind „immaterielle, die Primärleistung unterstützende oder eigenständige Leistungen, die den Kundennutzen steigern“ (Bruhn 2016). Die Servicepolitik klärt, ob weitere Serviceleistungen wie Garantien, Lieferung, Kundendienst oder Value Added Services angeboten werden sollen – bei Pampers z. B. ein Onlinebabyratgeber und Schwangerschaftstipps.',
    explanation: 'Definition nach Bruhn + Aufgabe der Servicepolitik.',
    source: 'Kapitel 2.2, PDF S. 8', conceptIds: ['mc-serviceleistungen', 'mc-servicepolitik'],
  },
  {
    id: 'qm2-23', chapterId: 'm2', type: 'open', goal: 'distinction', difficulty: 2,
    prompt: 'Grenzen Sie Produktvariation, Produktdifferenzierung und Produktelimination voneinander ab und nennen Sie jeweils den Anlass.',
    rubric: [
      { point: 'Variation: Nutzenkomponenten verändern, Basisfunktion bleibt (Design, Farbe, Geschmack)', keywords: ['variation', 'basisfunktion', 'design', 'geschmack', 'farbe'] },
      { point: 'Anlass Variation: geänderte Kundenbedürfnisse oder Marktposition verteidigen', keywords: ['kundenbedürfnisse ändern', 'marktposition', 'verteidig'] },
      { point: 'Differenzierung: abgewandelte Versionen für neue Segmente, beide Varianten bleiben, Programm erweitert sich', keywords: ['differenzierung', 'neue marktsegmente', 'beide', 'erweitert'] },
      { point: 'Elimination: Produkt dient Unternehmenszielen nicht mehr → wird entfernt', keywords: ['elimination', 'entfernt', 'unternehmenszielen nicht'] },
    ],
    modelAnswer: 'Produktvariation ist die bewusste Veränderung von Nutzenkomponenten: Die Basisfunktion bleibt, Design, Farbe oder Geschmack werden variiert – nötig, wenn sich Kundenbedürfnisse ändern oder die Marktposition verteidigt werden muss. Bei der Produktdifferenzierung sprechen abgewandelte Versionen neue Marktsegmente an; anders als bei der Variation werden beide Varianten angeboten, das Produktprogramm erweitert sich. Bei der Produktelimination wird ein Produkt, das den Unternehmenszielen nicht mehr dient, aus dem Angebot entfernt.',
    explanation: 'Drei produktpolitische Entscheidungen im Lebenszyklus (Walsh/Deseniss/Kilian 2013).',
    source: 'Kapitel 2.2, PDF S. 8–9', conceptIds: ['mc-produktvariation', 'mc-produktdiff', 'mc-produktelimination'],
  },
  {
    id: 'qm2-24', chapterId: 'm2', type: 'transfer', goal: 'application', difficulty: 2,
    prompt: 'Ein Schokoladenhersteller bietet zusätzlich zu seiner bekannten Vollmilchtafel eine vegane Variante für eine neue Zielgruppe an; die Vollmilchtafel bleibt im Sortiment. Um welche Entscheidung handelt es sich und wie verändert sich das Produktprogramm?',
    rubric: [
      { point: 'Produktdifferenzierung', keywords: ['differenzierung'] },
      { point: 'Neues Marktsegment wird angesprochen', keywords: ['segment', 'zielgruppe'] },
      { point: 'Beide Varianten bleiben → Produktprogramm erweitert sich (mehr Produkte je Linie)', keywords: ['erweitert', 'beide', 'programmtiefe', 'tiefe'] },
      { point: 'Abgrenzung: keine Variation, da die alte Version nicht ersetzt wird', keywords: ['keine variation', 'nicht ersetzt', 'variation'], weight: 0.5 },
    ],
    modelAnswer: 'Es handelt sich um Produktdifferenzierung: Eine abgewandelte Version spricht ein neues Marktsegment an, und anders als bei der Variation werden beide Varianten angeboten. Das Produktprogramm erweitert sich – innerhalb der Produktlinie Schokolade steigt die Zahl der Produkte (Programmtiefe).',
    explanation: 'Zusätzliche Variante neben dem Original = Differenzierung.',
    source: 'Kapitel 2.2, PDF S. 9', conceptIds: ['mc-produktdiff', 'mc-programmtiefe'],
  },
  {
    id: 'qm2-25', chapterId: 'm2', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erklären Sie Produktportfoliomanagement, Programmbreite, Programmtiefe und Produktlinie am Beispiel Procter & Gamble.',
    rubric: [
      { point: 'Portfoliomanagement: steuert Marketingziele aller Produkte/Marken, verteilt Ressourcen, Sortimentserweiterung/-bereinigung', keywords: ['ressourcen', 'steuert', 'sortimentserweiterung', 'bereinigung'] },
      { point: 'Produktlinie: Gruppe von Produkten mit gemeinsamen Kriterien', keywords: ['gruppe', 'gemeinsam', 'kriterien'] },
      { point: 'Breite = Anzahl Produktlinien (z. B. Hygiene, Schönheitspflege, Waschmittel, Gesundheit/Rasur)', keywords: ['breite', 'anzahl der produktlinien', 'linien'] },
      { point: 'Tiefe = Produkte je Linie (z. B. Always, Pampers in Baby-/Damenhygiene)', keywords: ['tiefe', 'pro produktlinie', 'always', 'pampers', 'je linie'] },
    ],
    modelAnswer: 'Das Produktportfoliomanagement steuert die Marketingziele aller Produkte/Marken im Portfolio und verteilt die Ressourcen; dazu gehören auch Sortimentserweiterung und -bereinigung. Eine Produktlinie ist eine Gruppe von Produkten mit gemeinsamen Kriterien. Die Programmbreite ist die Anzahl der Produktlinien – bei P&G z. B. Baby- und Damenhygiene, Schönheitspflege, Wasch- und Reinigungsmittel sowie Gesundheit und Rasur. Die Programmtiefe ist die Zahl der Produkte pro Linie – z. B. Always und Pampers in der Hygiene-Linie oder Ariel und Lenor bei den Waschmitteln.',
    explanation: 'Siehe Abbildung Programmbreite/-tiefe (S. 9).',
    source: 'Kapitel 2.2, PDF S. 9', conceptIds: ['mc-portfoliomanagement', 'mc-programmbreite', 'mc-programmtiefe', 'mc-produktlinie'],
  },
  {
    id: 'qm2-26', chapterId: 'm2', type: 'open', goal: 'fact', difficulty: 2,
    prompt: 'Nach welchen Leitlinien kann die Struktur eines Produktprogramms ausgerichtet werden? Nennen Sie jeweils das Unternehmensbeispiel aus dem Skript.',
    rubric: [
      { point: 'Material oder Herkunft der Güter – Kraft Heinz (Lebensmittel)', keywords: ['material', 'herkunft', 'kraft heinz'] },
      { point: 'Bestimmte Preislagen – LVMH (sehr hohe Preise)', keywords: ['preislage', 'lvmh'] },
      { point: 'Bedarfskreise – Procter & Gamble (Bedarfsfeld Hygiene)', keywords: ['bedarfskreis', 'bedarfsfeld', 'procter', 'p&g', 'hygiene'] },
    ],
    modelAnswer: 'Nach Walsh/Deseniss/Kilian (2013): Ausrichtung am Material oder der Herkunft der Güter (Kraft Heinz Company, Lebensmittel), an bestimmten Preislagen (LVMH, heterogenes Markenprogramm zu sehr hohen Preisen) oder an Bedarfskreisen (Procter & Gamble, Bedarfsfeld Hygiene).',
    explanation: 'Drei Leitlinien der Programmstruktur.',
    source: 'Kapitel 2.2, PDF S. 9', conceptIds: ['mc-programmstruktur'],
  },
  {
    id: 'qm2-27', chapterId: 'm2', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Was versteht man unter Innovationsmanagement? Erläutern Sie am Beispiel Kodak, warum es heute eine Voraussetzung für wirtschaftlichen Erfolg ist.',
    rubric: [
      { point: 'Bewusste Gestaltung eines Innovationssystems zur Entwicklung von Neuprodukten + damit verbundene Veränderungen', keywords: ['innovationssystem', 'neuprodukt', 'bewusste gestaltung', 'veränderung'] },
      { point: 'Heute Voraussetzung für wirtschaftlichen Erfolg', keywords: ['voraussetzung', 'wirtschaftlichen erfolg', 'erfolg'] },
      { point: 'Kodak: erste Digitalkamera 1975 erfunden, aber nicht strategisch verfolgt', keywords: ['1975', 'digitalkamera', 'nicht als strategie', 'nicht verfolgt'] },
      { point: '2012 Insolvenz; digitale Revolution bewusst vernachlässigt (nicht verschlafen)', keywords: ['2012', 'insolvenz', 'bewusst vernachlässigt'] },
    ],
    modelAnswer: 'Innovationsmanagement ist die bewusste Gestaltung eines Innovationssystems zur Entwicklung von Neuprodukten und der damit verbundenen Veränderungen im Unternehmen – heute Voraussetzung für wirtschaftlichen Erfolg. Kodak zeigt die Folgen: Ein Kodak-Mitarbeiter erfand 1975 die erste Digitalkamera, doch das Unternehmen verfolgte sie nicht als Strategie und ging 2012 in die Insolvenz. Kodak hat die digitale Revolution nicht verschlafen, sondern bewusst vernachlässigt.',
    explanation: 'Definition + Kodak als Negativbeispiel.',
    source: 'Kapitel 2.3, PDF S. 9', conceptIds: ['mc-innovationsmgmt'],
  },
  {
    id: 'qm2-28', chapterId: 'm2', type: 'open', goal: 'fact', difficulty: 2,
    prompt: 'Beschreiben Sie die fünf Phasen des Produktlebenszyklus mit ihren Merkmalen.',
    rubric: [
      { point: 'Einführung: hohe Investitionen, geringe Umsätze', keywords: ['einführung', 'hohe investition', 'geringe umsätze'] },
      { point: 'Wachstum: überdurchschnittlicher Zuwachs, Gewinnzone wird erreicht', keywords: ['wachstum', 'gewinnzone', 'überdurchschnittlich'] },
      { point: 'Reife: Markt dehnt sich aus, Wachstumsraten sinken, Erfahrungskurven-/Skaleneffekte am höchsten', keywords: ['reife', 'wachstumsraten sinken', 'erfahrungskurve', 'economies of scale'] },
      { point: 'Sättigung: Markt gesättigt, Umsätze gehen zurück', keywords: ['sättigung', 'gesättigt', 'umsätze gehen zurück', 'rückgang'] },
      { point: 'Verfall: kaum Bedarf, Umsatz stark rückläufig, Ende des Zyklus', keywords: ['verfall', 'kaum noch bedarf', 'stark rückläufig', 'ende'] },
    ],
    modelAnswer: 'Der Produktlebenszyklus ist die idealtypische Darstellung der Phasen von der Neueinführung bis zur Eliminierung: Einführungsphase (hohe Investitionen, geringe Umsätze), Wachstumsphase (überdurchschnittlicher Zuwachs, die Gewinnzone wird erreicht), Reifephase (der Markt dehnt sich weiter aus, die Wachstumsraten sinken; Erfahrungskurveneffekte und Economies of Scale sind am höchsten), Sättigungsphase (der Markt ist gesättigt, die Umsätze gehen zurück), Verfallsphase (kaum noch Bedarf, Umsatz stark rückläufig – Ende des Zyklus).',
    explanation: 'Fünf Phasen mit Merkmalen aus dem Skript.',
    source: 'Kapitel 2.3, PDF S. 9', conceptIds: ['mc-lebenszyklus', 'mc-einfuehrungsphase', 'mc-wachstumsphase', 'mc-reifephase', 'mc-saettigungsphase', 'mc-verfallsphase'],
  },
  {
    id: 'qm2-29', chapterId: 'm2', type: 'open', goal: 'distinction', difficulty: 2,
    prompt: 'Erklären Sie Erfahrungskurveneffekte und Economies of Scale und geben Sie an, in welcher Lebenszyklusphase sie am höchsten sind.',
    rubric: [
      { point: 'Erfahrungskurveneffekte: Effizienzsteigerung durch gesammelte Erfahrung im Markt/mit dem Produkt', keywords: ['effizienzsteigerung', 'erfahrung', 'verbesserung'] },
      { point: 'Economies of Scale: Betriebsgrößenvorteile', keywords: ['betriebsgröße', 'größenvorteil'] },
      { point: 'Beispiele: Mengenrabatte beim Einkauf, sinkende Stückkosten durch Verwaltungskostenumlage', keywords: ['mengenrabatt', 'einkaufskondition', 'verwaltungskosten', 'stückkosten'] },
      { point: 'Am höchsten in der Reifephase', keywords: ['reifephase', 'reife'] },
    ],
    modelAnswer: 'Erfahrungskurveneffekte sind Effizienzsteigerungen, weil bereits Erfahrung im Markt und mit dem Produkt gesammelt wurde und auf dieser Basis Verbesserungen möglich sind. Economies of Scale sind Betriebsgrößenvorteile, z. B. günstigere Einkaufskonditionen durch Mengenrabatte oder sinkende Stückkosten wegen besserer Verwaltungskostenumlage. Beide sind in der Reifephase des Produktlebenszyklus am höchsten.',
    explanation: 'Zwei Effizienzeffekte + Phase.',
    source: 'Kapitel 2.3, PDF S. 9–10', conceptIds: ['mc-erfahrungskurve', 'mc-economies-of-scale', 'mc-reifephase'],
  },
  {
    id: 'qm2-30', chapterId: 'm2', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Erläutern Sie Grundidee, Ziel und Konsequenz des S-Kurvenkonzepts und beschreiben Sie, was die Achsen der zugehörigen Abbildung darstellen.',
    rubric: [
      { point: 'Ziel (Foster 1986): Innovationsmanagement für technologische Diskontinuitäten sensibilisieren', keywords: ['sensibilisier', 'diskontinuität', 'foster'] },
      { point: 'Grundidee: Leistungsgrenze (Größe, Komplexität, Materialeigenschaften) → Ablösung durch neue Technologie', keywords: ['leistungsgrenze', 'grenze', 'ersetzt', 'neue technologie'] },
      { point: 'Abbildung: x = kumulierte F&E-Aufwendungen, y = Leistungsfähigkeit der Technologie', keywords: ['kumulierte', 'forschung und entwicklung', 'f&e', 'leistungsfähigkeit'] },
      { point: 'Konsequenz: Grenzen abschätzen, F&E entwickelt kontinuierlich neue Produkte', keywords: ['abschätzen', 'kontinuierlich', 'vorbereit'] },
    ],
    modelAnswer: 'Das S-Kurvenkonzept (Foster 1986) soll das Innovationsmanagement für technologische Diskontinuitäten sensibilisieren. Grundidee: Jede Technologie stößt irgendwann zwangsläufig an eine Leistungsgrenze – bedingt durch Größe, Komplexität oder Materialeigenschaften – und wird durch eine neue Technologie ersetzt. In der Abbildung ist auf der x-Achse der kumulierte Aufwand für Forschung und Entwicklung, auf der y-Achse die Leistungsfähigkeit der Technologie abgetragen; alte und neue Technologie haben jeweils eine eigene Grenze, der Abstand zwischen heutigem Stand und Grenze zeigt die technologischen Entwicklungspotenziale. Konsequenz: Unternehmen müssen die Grenzen ihrer Technologien abschätzen, um auf Technologiesprünge vorbereitet zu sein; F&E sollte kontinuierlich neue Produkte entwickeln und vorbereiten.',
    explanation: 'Ziel + Grundidee + Abbildung + Konsequenz.',
    source: 'Kapitel 2.3, PDF S. 10', conceptIds: ['mc-skurve', 'mc-diskontinuitaet'],
  },
  {
    id: 'qm2-31', chapterId: 'm2', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Beschreiben Sie den Adoptionsprozess und erklären Sie die Bedeutung von Innovatoren und frühen Adoptern für die Verbreitung neuer Produkte.',
    rubric: [
      { point: 'Fünf Phasen: Aufmerksamkeit, Interesse, Bewertung, Versuch, Annahme', keywords: ['aufmerksamkeit', 'interesse', 'bewertung', 'versuch', 'annahme'] },
      { point: 'Akzeptanz braucht Zeit (Sony 1981 → 20 Jahre)', keywords: ['zeit', 'sony', '20 jahre'], weight: 0.5 },
      { point: 'Innovatoren/frühe Adopter: hochinformiert, großes Interesse, Multiplikatoren (Influencer)', keywords: ['hochinformiert', 'multiplikator', 'influencer', 'blogger', 'youtuber'] },
      { point: 'Gezielte Ansprache treibt den Diffusionsprozess voran', keywords: ['diffusion', 'voranzutreiben', 'gezielte ansprache'] },
    ],
    modelAnswer: 'Der Adoptionsprozess wird generell in fünf Phasen unterteilt: Aufmerksamkeit, Interesse, Bewertung, Versuch und Annahme. Die Akzeptanz neuer Produkte braucht oft Zeit – Sony brachte 1981 die erste filmlose Kamera, doch es dauerte weitere 20 Jahre bis zum Massenmarkt. Innovatoren und frühe Adopter sind hochinformiert und haben großes Interesse am Produkt; heute sind sie oft als Tech-Blogger, YouTuber oder Fachexperten aktiv und damit einflussreiche Multiplikatoren. Ihre gezielte Ansprache ist äußerst wichtig, um den Diffusionsprozess von Produktinnovationen voranzutreiben (Rogers 2003).',
    explanation: 'Phasen + Bedeutung früher Adopter.',
    source: 'Kapitel 2.3, PDF S. 10', conceptIds: ['mc-adoption', 'mc-innovatoren', 'mc-diffusion'],
  },
  {
    id: 'qm2-32', chapterId: 'm2', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Beschreiben Sie den Verlauf der Diffusionskurve und begründen Sie den starken Anstieg in der Mitte sowie die Verlangsamung am Schluss.',
    rubric: [
      { point: 'Zunächst wenige Übernehmer, dann starker Anstieg der Neukäufer, gegen Ende Abnahme', keywords: ['wenige', 'stark an', 'nimmt ab', 'abnahme', 'gegen ende'] },
      { point: 'Anstieg: Produkt bekannter, Unsicherheit und Preise sinken', keywords: ['bekannter', 'unsicherheit', 'preise sinken'] },
      { point: 'Anstieg: Verfügbarkeit steigt, soziale Empfehlungen wirken', keywords: ['verfügbarkeit', 'empfehlung'] },
      { point: 'Verlangsamung: Markt weitgehend gesättigt', keywords: ['gesättigt', 'sättigung'] },
    ],
    modelAnswer: 'Zunächst übernehmen nur wenige das Produkt, dann steigt die Zahl der Neukäufer stark an, gegen Ende nimmt sie wieder ab. Der Anstieg in der Mitte entsteht, weil das Produkt bekannter wird, Unsicherheit und Preise sinken, die Verfügbarkeit steigt und soziale Empfehlungen wirken. Am Schluss verlangsamt sich die Diffusion, weil der Markt weitgehend gesättigt ist.',
    explanation: 'Kurvenverlauf + Gründe (S. 10).',
    source: 'Kapitel 2.3, PDF S. 10', conceptIds: ['mc-diffusion'],
  },
  {
    id: 'qm2-33', chapterId: 'm2', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein Hersteller investiert weiterhin massiv in die Verbesserung einer Technologie, deren Leistungsfähigkeit trotz hoher F&E-Ausgaben kaum noch steigt, während ein Wettbewerber eine neue Technologie erforscht. Beurteilen Sie die Situation mithilfe des S-Kurvenkonzepts.',
    rubric: [
      { point: 'Alte Technologie nähert sich ihrer Leistungsgrenze (Kurve flacht ab)', keywords: ['leistungsgrenze', 'grenze', 'flacht', 'kaum noch'] },
      { point: 'Weitere F&E-Ausgaben bringen kaum Leistungszuwachs', keywords: ['f&e', 'forschung', 'aufwand', 'kaum'] },
      { point: 'Neue Technologie wird die alte ablösen (technologische Diskontinuität)', keywords: ['neue technologie', 'ablös', 'ersetzt', 'diskontinuität', 'technologiesprung'] },
      { point: 'Empfehlung: Grenzen abschätzen, frühzeitig in neue Technologie/neue Produkte investieren (Kodak als Warnung)', keywords: ['abschätzen', 'kontinuierlich', 'neue produkte', 'kodak', 'frühzeitig'] },
    ],
    modelAnswer: 'Die Technologie des Herstellers befindet sich im oberen, flachen Teil ihrer S-Kurve: Sie nähert sich ihrer Leistungsgrenze, sodass zusätzliche F&E-Aufwendungen kaum noch Leistungszuwachs bringen. Laut S-Kurvenkonzept wird jede Technologie an dieser Grenze durch eine neue ersetzt – der Wettbewerber bereitet genau diesen Technologiesprung vor. Der Hersteller sollte die Grenzen seiner Technologie realistisch abschätzen und seine F&E kontinuierlich auf neue Produkte bzw. die neue Technologie ausrichten; sonst droht ein Schicksal wie bei Kodak.',
    explanation: 'Anwendung der S-Kurve auf eine Investitionsentscheidung.',
    source: 'Kapitel 2.3, PDF S. 9–10', conceptIds: ['mc-skurve', 'mc-diskontinuitaet', 'mc-innovationsmgmt'],
  },

  // ======================= neue geschlossene Fragen =======================
  {
    id: 'qm2-34', chapterId: 'm2', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Welches Beispiel nennt das Skript für ein immaterielles Produkt?',
    options: ['Das Streamen eines Liedes', 'Ein Smartphone', 'Ein Bleistift', 'Ein Fahrrad'],
    correctOptions: [0],
    explanation: 'Immateriell: Streamen eines Liedes, Ideen (Liedtext, Melodie), digitale Güter (In-Game-Items, Online-Coaching). Das Smartphone ist materiell.',
    source: 'Kapitel 2.1, PDF S. 6', conceptIds: ['mc-produkt'],
  },
  {
    id: 'qm2-35', chapterId: 'm2', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie die Produktebene (nach Leistung) der Ausprägung beim E-Bike zu.',
    pairs: [
      { left: 'Kernprodukt', right: 'Fortbewegung auf zwei Rädern, durch Elektroantrieb erleichtert' },
      { left: 'Reales Produkt', right: 'Rahmen mit integriertem Akku und Motor, Unterstützungsstufen, Display' },
      { left: 'Erweitertes Produkt', right: 'Regelmäßige Software-Updates, Wartungsservices beim Fachhändler' },
    ],
    explanation: 'Kern = Bedürfnisbefriedigung; real = sichtbares, kaufbares Produkt; erweitert = Zusatzleistungen.',
    source: 'Kapitel 2.1, Abbildung PDF S. 7', conceptIds: ['mc-kernprodukt', 'mc-reales-produkt', 'mc-erweitertes-produkt'],
  },
  {
    id: 'qm2-36', chapterId: 'm2', type: 'true_false', goal: 'fact', difficulty: 2,
    prompt: 'Die Zusatznutzen eines Produkts sind an eine feste Reihenfolge gebunden und müssen immer alle vorhanden sein.',
    correctBool: false,
    explanation: 'Falsch – laut Skript sind die Zusatznutzen nicht an eine Reihenfolge gebunden und müssen nicht zwangsläufig vorhanden sein.',
    source: 'Kapitel 2.1, PDF S. 7', conceptIds: ['mc-zusatznutzen'],
  },
  {
    id: 'qm2-37', chapterId: 'm2', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie die Art des Zusatznutzens dem Hosen-Beispiel zu.',
    pairs: [
      { left: 'Sozialer Nutzen / Geltungsnutzen', right: 'Die Hose ist dem Anlass angemessen' },
      { left: 'Erbauungsnutzen', right: 'Die Hose sitzt gut und schmeichelt der Figur' },
      { left: 'Emotionaler Nutzen', right: 'Marke, gutes Gefühl' },
    ],
    explanation: 'Drei Zusatznutzen über den Grundnutzen (bekleiden, wärmen) hinaus.',
    source: 'Kapitel 2.1, PDF S. 7', conceptIds: ['mc-zusatznutzen', 'mc-grundnutzen'],
  },
  {
    id: 'qm2-38', chapterId: 'm2', type: 'single_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche Nutzenkategorie folgt auf das erwartete Produkt?',
    options: ['Augmentiertes Produkt', 'Generisches Produkt', 'Potenzielles Produkt', 'Grundnutzen'],
    correctOptions: [0],
    explanation: 'Reihenfolge: Grundnutzen → generisches → erwartetes → augmentiertes → potenzielles Produkt.',
    source: 'Kapitel 2.1, Abbildung PDF S. 7', conceptIds: ['mc-nutzenkategorien', 'mc-augmentiertes-produkt', 'mc-erwartetes-produkt'],
  },
  {
    id: 'qm2-39', chapterId: 'm2', type: 'assignment', goal: 'fact', difficulty: 2,
    prompt: 'Ordnen Sie die Qualitätsdimension ihrer Leitfrage zu.',
    pairs: [
      { left: 'Gebrauchsnutzen', right: 'Funktioniert das Produkt wie erwartet?' },
      { left: 'Zuverlässigkeit', right: 'Wie wahrscheinlich ist es, dass das Produkt versagt?' },
      { left: 'Normgerechtigkeit', right: 'Werden Gütenormen eingehalten?' },
      { left: 'Haltbarkeit', right: 'Was ist die Lebensdauer des Produkts?' },
      { left: 'Umwelt- und Sozialverträglichkeit', right: 'Ist das Produkt nachhaltig?' },
    ],
    explanation: 'Qualitätsdimensionen nach Meffert/Burmann/Kirchgeorg (2015); dazu Ausstattung und Ästhetik.',
    source: 'Kapitel 2.1, PDF S. 7', conceptIds: ['mc-qualitaetsdimensionen'],
  },
  {
    id: 'qm2-40', chapterId: 'm2', type: 'true_false', goal: 'understanding', difficulty: 1,
    prompt: 'Qualität kann laut Skript nur objektiv anhand messbarer Eigenschaften diskutiert werden.',
    correctBool: false,
    explanation: 'Falsch – Qualität kann objektiv (messbare Eigenschaften) oder subjektiv (gemessen an den Vorstellungen des Konsumenten) diskutiert werden.',
    source: 'Kapitel 2.1, PDF S. 7', conceptIds: ['mc-qualitaet'],
  },
  {
    id: 'qm2-41', chapterId: 'm2', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie das Beispielpaar dem passenden Merkmal der Produkttypologisierung zu.',
    pairs: [
      { left: 'Haarschnitt vs. Bleistift', right: 'Materialität' },
      { left: 'Lebensmittel vs. Fahrrad', right: 'Nutzungsdauer' },
      { left: 'Zahnpasta vs. Weihnachtsbäume', right: 'Nutzungshäufigkeit' },
      { left: 'Privatkunde vs. Unternehmen als Käufer', right: 'Konsumentengruppe' },
    ],
    explanation: 'Materialität (Dienstleistung vs. Sachgut), Nutzungsdauer (Verbrauchs- vs. Gebrauchsgut), Nutzungshäufigkeit (täglich vs. aperiodisch), Konsumentengruppe (B2C vs. B2B).',
    source: 'Kapitel 2.1, PDF S. 8', conceptIds: ['mc-sachgueter-dl', 'mc-verbrauch-gebrauch', 'mc-bedarf', 'mc-konsum-invest'],
  },
  {
    id: 'qm2-42', chapterId: 'm2', type: 'single_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Wofür steht Büromaterial im Skript als Beispiel?',
    options: [
      'Für Produkte, die sowohl Konsum- als auch Investitionsgüter sein können',
      'Für typische Unsought Goods',
      'Für Specialty Goods',
      'Für Waren des aperiodischen Bedarfs',
    ],
    correctOptions: [0],
    explanation: 'Manche Produkte fallen in beide Kategorien der Konsumentengruppe – z. B. Büromaterial (B2C und B2B).',
    source: 'Kapitel 2.1, PDF S. 8', conceptIds: ['mc-konsum-invest'],
  },
  {
    id: 'qm2-43', chapterId: 'm2', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Wer trifft laut Skript produktpolitische Entscheidungen?',
    options: ['Produktmanager', 'Handelsvertreter', 'Die PR-Abteilung', 'Absatzmittler'],
    correctOptions: [0],
    explanation: 'Produktmanager sind für Entwicklung und Führung der Produkte am Markt zuständig (Bruhn 2016).',
    source: 'Kapitel 2.2, PDF S. 8', conceptIds: ['mc-produktmanager'],
  },
  {
    id: 'qm2-44', chapterId: 'm2', type: 'multiple_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Welche der folgenden Ziele nennt das Skript als psychologische Ziele der Produktpolitik? (Mehrfachauswahl)',
    options: ['Image', 'Konsumenteneinstellungen', 'Verkaufte Mengen', 'Ansprache bestimmter Segmente'],
    correctOptions: [0, 1],
    explanation: 'Psychologisch: Image, Konsumenteneinstellungen. Ökonomisch: verkaufte Mengen, Ansprache bestimmter Segmente.',
    source: 'Kapitel 2.2, PDF S. 8', conceptIds: ['mc-ziele-produktpolitik'],
  },
  {
    id: 'qm2-45', chapterId: 'm2', type: 'cloze', goal: 'fact', difficulty: 1,
    prompt: 'Das Produktprogramm – auch ______ oder ______ genannt – ist die Gesamtheit aller Leistungen, die ein Anbieter zum Kauf bereitstellt.',
    clozeAnswers: [['Portfolio', 'Sortiment'], ['Sortiment', 'Portfolio']],
    explanation: 'Produktprogramm = Portfolio = Sortiment.',
    source: 'Kapitel 2.2, PDF S. 8', conceptIds: ['mc-produktprogramm'],
  },
  {
    id: 'qm2-46', chapterId: 'm2', type: 'assignment', goal: 'application', difficulty: 2,
    prompt: 'Ordnen Sie das Pampers-Beispiel dem Aspekt der Produktgestaltung zu.',
    pairs: [
      { left: 'Material, das saugstark und zugleich sanft ist', right: 'Technisch-funktionale Eigenschaften' },
      { left: 'Schnitt, Farben, Muster', right: 'Produktdesign' },
      { left: 'Onlinebabyratgeber, Schwangerschaftstipps', right: 'Servicepolitik' },
    ],
    explanation: 'Beispiel Pampers von Procter & Gamble (S. 8).',
    source: 'Kapitel 2.2, PDF S. 8', conceptIds: ['mc-technisch-funktional', 'mc-produktdesign', 'mc-servicepolitik'],
  },
  {
    id: 'qm2-47', chapterId: 'm2', type: 'single_choice', goal: 'fact', difficulty: 2,
    prompt: 'Wie definiert Bruhn (2016) Serviceleistungen?',
    options: [
      'Immaterielle, die Primärleistung unterstützende oder eigenständige Leistungen, die den Kundennutzen steigern',
      'Materielle Zusatzprodukte, die kostenlos beigelegt werden',
      'Alle Leistungen des Handels',
      'Leistungen ohne Kundennutzen, die dem Handel dienen',
    ],
    correctOptions: [0],
    explanation: 'Wörtliche Definition nach Bruhn (2016).',
    source: 'Kapitel 2.2, PDF S. 8', conceptIds: ['mc-serviceleistungen'],
  },
  {
    id: 'qm2-48', chapterId: 'm2', type: 'true_false', goal: 'fact', difficulty: 1,
    prompt: 'Bei der Produktelimination wird ein Produkt, das den Unternehmenszielen nicht mehr dient, aus dem Angebot entfernt.',
    correctBool: true,
    explanation: 'Richtig – neben Variation und Differenzierung die dritte produktpolitische Entscheidung im Lebenszyklus.',
    source: 'Kapitel 2.2, PDF S. 9', conceptIds: ['mc-produktelimination'],
  },
  {
    id: 'qm2-49', chapterId: 'm2', type: 'assignment', goal: 'fact', difficulty: 2,
    prompt: 'Ordnen Sie die Leitlinie der Programmstruktur dem Unternehmensbeispiel zu.',
    pairs: [
      { left: 'Material oder Herkunft der Güter', right: 'Kraft Heinz Company (Lebensmittel)' },
      { left: 'Bestimmte Preislagen', right: 'LVMH (heterogenes Markenprogramm zu sehr hohen Preisen)' },
      { left: 'Bedarfskreise', right: 'Procter & Gamble (Bedarfsfeld Hygiene)' },
    ],
    explanation: 'Leitlinien nach Walsh/Deseniss/Kilian (2013).',
    source: 'Kapitel 2.2, PDF S. 9', conceptIds: ['mc-programmstruktur'],
  },
  {
    id: 'qm2-50', chapterId: 'm2', type: 'single_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Was lehrt das Kodak-Beispiel laut Skript?',
    options: [
      'Kodak hat die digitale Revolution nicht verschlafen, sondern bewusst vernachlässigt – mit der Insolvenz 2012 als Folge.',
      'Kodak hat die Digitalkamera nie erfunden.',
      'Kodak scheiterte an zu hohen Preisen.',
      'Kodak scheiterte an fehlender Distribution.',
    ],
    correctOptions: [0],
    explanation: 'Ein Kodak-Mitarbeiter erfand 1975 die erste Digitalkamera; sie wurde nicht als Strategie verfolgt.',
    source: 'Kapitel 2.3, PDF S. 9', conceptIds: ['mc-innovationsmgmt'],
  },
  {
    id: 'qm2-51', chapterId: 'm2', type: 'cloze', goal: 'fact', difficulty: 2,
    prompt: 'In der Einführungsphase gibt es hohe ______ und geringe Umsätze; in der Wachstumsphase wird die ______ erreicht.',
    clozeAnswers: [['Investitionen', 'Investition'], ['Gewinnzone']],
    explanation: 'Einführung: hohe Investitionen, geringe Umsätze. Wachstum: überdurchschnittlicher Zuwachs, Gewinnzone.',
    source: 'Kapitel 2.3, PDF S. 9', conceptIds: ['mc-einfuehrungsphase', 'mc-wachstumsphase'],
  },
  {
    id: 'qm2-52', chapterId: 'm2', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'In welcher Phase des Produktlebenszyklus sind Erfahrungskurveneffekte und Economies of Scale am höchsten?',
    options: ['Reifephase', 'Einführungsphase', 'Wachstumsphase', 'Verfallsphase'],
    correctOptions: [0],
    explanation: 'Reifephase: Der Markt dehnt sich weiter aus, die Wachstumsraten sinken, Effizienzeffekte sind am höchsten.',
    source: 'Kapitel 2.3, PDF S. 9', conceptIds: ['mc-reifephase', 'mc-erfahrungskurve', 'mc-economies-of-scale'],
  },
  {
    id: 'qm2-53', chapterId: 'm2', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Wodurch kann laut S-Kurvenkonzept die Leistungsgrenze einer Technologie bedingt sein? (Mehrfachauswahl)',
    options: ['Größe', 'Komplexität', 'Materialeigenschaften', 'Höhe des Werbebudgets', 'Zahlungsbereitschaft der Kunden'],
    correctOptions: [0, 1, 2],
    explanation: 'Die Leistungsgrenze ist bedingt durch Größe, Komplexität oder Materialeigenschaften.',
    source: 'Kapitel 2.3, PDF S. 10', conceptIds: ['mc-skurve', 'mc-diskontinuitaet'],
  },
  {
    id: 'qm2-54', chapterId: 'm2', type: 'cloze', goal: 'fact', difficulty: 1,
    prompt: 'Der Adoptionsprozess umfasst fünf Phasen: Aufmerksamkeit, ______, Bewertung, ______ und Annahme.',
    clozeAnswers: [['Interesse'], ['Versuch']],
    explanation: 'Aufmerksamkeit → Interesse → Bewertung → Versuch → Annahme.',
    source: 'Kapitel 2.3, PDF S. 10', conceptIds: ['mc-adoption'],
  },
  {
    id: 'qm2-55', chapterId: 'm2', type: 'single_choice', goal: 'fact', difficulty: 2,
    prompt: 'Sony brachte 1981 die erste filmlose Kamera auf den Markt. Wie lange dauerte es laut Skript noch bis zum Massenmarkt?',
    options: ['Weitere 20 Jahre', 'Etwa 2 Jahre', 'Etwa 5 Jahre', 'Sie erreichte nie den Massenmarkt'],
    correctOptions: [0],
    explanation: 'Beispiel dafür, dass die Akzeptanz neuer Produkte oft Zeit braucht.',
    source: 'Kapitel 2.3, PDF S. 10', conceptIds: ['mc-adoption'],
  },
  {
    id: 'qm2-56', chapterId: 'm2', type: 'true_false', goal: 'fact', difficulty: 1,
    prompt: 'Innovatoren und frühe Adopter sind heute oft als Tech-Blogger, YouTuber oder Fachexperten aktiv und damit einflussreiche Multiplikatoren.',
    correctBool: true,
    explanation: 'Richtig – sie sind hochinformiert, haben großes Interesse am Produkt und wirken als Influencer.',
    source: 'Kapitel 2.3, PDF S. 10', conceptIds: ['mc-innovatoren'],
  },
  {
    id: 'qm2-57', chapterId: 'm2', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Welches Beispiel passt laut Skript zu Economies of Scale?',
    options: [
      'Günstigere Einkaufskonditionen durch Mengenrabatte',
      'Verbesserungen durch bereits gesammelte Markterfahrung',
      'Ein höherer Preis durch eine starke Marke',
      'Ein Kinotag am Wochenanfang',
    ],
    correctOptions: [0],
    explanation: 'Economies of Scale = Betriebsgrößenvorteile (Mengenrabatte, bessere Verwaltungskostenumlage). Verbesserung durch Erfahrung = Erfahrungskurveneffekte.',
    source: 'Kapitel 2.3, PDF S. 10', conceptIds: ['mc-economies-of-scale', 'mc-erfahrungskurve'],
  },
  {
    id: 'qm2-58', chapterId: 'm2', type: 'assignment', goal: 'fact', difficulty: 2,
    prompt: 'Ordnen Sie der Adopterkategorie ihren Anteil laut Abbildung zu.',
    pairs: [
      { left: 'Innovatoren', right: '2,5 %' },
      { left: 'Frühadopter', right: '13,5 %' },
      { left: 'Nachzügler', right: '16 %' },
      { left: 'Frühe Mehrheit', right: '34 %' },
    ],
    explanation: 'Innovatoren 2,5 %, Frühadopter 13,5 %, frühe Mehrheit 34 %, späte Mehrheit 34 %, Nachzügler 16 %.',
    source: 'Kapitel 2.3, Abbildung PDF S. 10', conceptIds: ['mc-adopterkategorien'],
  },
];
