import { Question } from '@/lib/types';

/** Fragen Kapitel 5 – Distributionspolitik (PDF S. 20–24). */
export const questions5: Question[] = [
  // ======================= bestehende Fragen (IDs unverändert) =======================
  {
    id: 'qm5-01', chapterId: 'm5', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Welche zwei Komponenten stellt die Distributionspolitik sicher?',
    options: [
      'Akquisitorische Komponente (effizientes und effektives Vertriebssystem) und logistische Komponente (adäquater Zugriff der Konsumenten auf die Waren)',
      'Preisliche und werbliche Komponente',
      'Materielle und immaterielle Komponente',
      'Interne und externe Kommunikation',
    ],
    correctOptions: [0],
    explanation: 'Akquisitorisch = Gestaltung des Vertriebssystems; logistisch = Zugriff der Konsumenten auf die Waren.',
    source: 'Kapitel 5.1, PDF S. 20', conceptIds: ['mc-distribution', 'mc-akquisitorisch', 'mc-logistisch'],
  },
  {
    id: 'qm5-02', chapterId: 'm5', type: 'true_false', goal: 'distinction', difficulty: 2,
    prompt: 'Bei der Pull-Strategie richtet sich der Hersteller mit Kommunikationsmaßnahmen direkt an die Endkunden und erzeugt so einen Nachfragesog.',
    correctBool: true,
    explanation: 'Richtig – z. B. Social-Media-Kampagnen, Content Marketing, SEO. Die Push-Strategie „drückt“ dagegen Produkte über Rabatte, Boni oder Exklusivrechte in den Handel.',
    source: 'Kapitel 5.1, PDF S. 20', conceptIds: ['mc-pull', 'mc-push-pull'],
  },
  {
    id: 'qm5-03', chapterId: 'm5', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie die Überbrückungsfunktion des Handels dem Bananen-Beispiel aus dem Skript zu.',
    pairs: [
      { left: 'Räumliche Überbrückung', right: 'Bananen aus Costa Rica, Kolumbien, Ecuador in jedem Supermarkt' },
      { left: 'Zeitliche Überbrückung', right: 'Kühlung nach der Ernte, Nachreifung in Reifereien durch Begasung mit Ethen' },
      { left: 'Sortimentsgestaltung', right: 'Importeure liefern große Mengen, Endverbraucher kaufen wenige Stück und andere Lebensmittel dazu' },
    ],
    explanation: 'Handelsunternehmen steigern den Kundennutzen durch die Überbrückung räumlicher, zeitlicher und sortimentsbezogener Diskrepanzen.',
    source: 'Kapitel 5.1, PDF S. 21', conceptIds: ['mc-ueberbrueckung', 'mc-raeumlich', 'mc-zeitlich', 'mc-sortiment'],
  },
  {
    id: 'qm5-04', chapterId: 'm5', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Edeka betreibt in Hamburg eine eigene Bananenreiferei. Wie nennt man dieses Vorgehen?',
    options: ['Vertikale Integration', 'Disintermediation', 'Horizontale Gestaltung', 'Franchising'],
    correctOptions: [0],
    explanation: 'Vertikale Integration: Eine vor- oder nachgelagerte Wertschöpfungsstufe wird eingegliedert – die Funktion wird nicht beseitigt, sondern integriert.',
    source: 'Kapitel 5.1, PDF S. 21–22', conceptIds: ['mc-vertikale-integration', 'mc-disintermediation'],
  },
  {
    id: 'qm5-05', chapterId: 'm5', type: 'cloze', goal: 'fact', difficulty: 1,
    prompt: 'Beim ______ Vertrieb verkauft das Unternehmen selbst direkt an Endkunden; beim ______ Vertrieb werden Vertriebsaufgaben mit externen Marktakteuren geteilt.',
    clozeAnswers: [['direkten', 'direkt'], ['indirekten', 'indirekt']],
    explanation: 'Direkt = unternehmensinterne Vertriebsorgane (nullstufig); indirekt = externe Vertriebsorgane mit wesentlicher akquisitorischer Funktion.',
    source: 'Kapitel 5.2, PDF S. 22', conceptIds: ['mc-direkt-indirekt', 'mc-indirekt'],
  },
  {
    id: 'qm5-06', chapterId: 'm5', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Was unterscheidet Absatzhelfer von Absatzmittlern?',
    options: [
      'Absatzhelfer erwerben kein Eigentum an den abzusetzenden Produkten, Absatzmittler schon.',
      'Absatzhelfer erwerben Eigentum, Absatzmittler nicht.',
      'Beide erwerben immer Eigentum.',
      'Beide erwerben nie Eigentum.',
    ],
    correctOptions: [0],
    explanation: 'Absatzhelfer = Handelsvertreter, Kommissionäre, Makler (kein Eigentum); Absatzmittler = Groß- und Einzelhandel (Eigentum).',
    source: 'Kapitel 5.2, PDF S. 22', conceptIds: ['mc-absatzhelfer-mittler', 'mc-absatzmittler'],
  },
  {
    id: 'qm5-07', chapterId: 'm5', type: 'true_false', goal: 'distinction', difficulty: 2,
    prompt: 'Omnichannel-Marketing bedeutet lediglich, auf mehreren Vertriebskanälen präsent zu sein.',
    correctBool: false,
    explanation: 'Falsch – das beschreibt Multichannel. Omnichannel heißt, über alle Kanäle hinweg vernetzt und konsistent zu sein (nahtloses, widerspruchsfreies Kundenerlebnis).',
    source: 'Kapitel 5.3, PDF S. 23', conceptIds: ['mc-omnichannel', 'mc-multi-omni'],
  },
  {
    id: 'qm5-08', chapterId: 'm5', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie den Distributionsgrad dem Butter-Beispiel aus dem Skript zu.',
    pairs: [
      { left: 'Intensiver Vertrieb', right: '„Deutsche Markenbutter“ in jedem Lebensmittelgeschäft' },
      { left: 'Selektiver Vertrieb', right: 'Andechser Bio-Almbutter vor allem in gut sortierten Bioläden' },
      { left: 'Exklusiver Vertrieb', right: 'Tarbiana-Trüffelbutter nur in Spezialitätenläden und online' },
    ],
    explanation: 'Intensiv = sehr viele Partner (Convenience Goods), selektiv = mehrere (Shopping Goods), exklusiv = sehr wenige (Specialty Goods).',
    source: 'Kapitel 5.3, PDF S. 23', conceptIds: ['mc-distributionsgrad', 'mc-intensiv', 'mc-selektiv', 'mc-exklusiv'],
  },
  {
    id: 'qm5-09', chapterId: 'm5', type: 'multiple_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Welche Aussagen zum direkten Vertrieb treffen laut Skript zu? (Mehrfachauswahl)',
    options: [
      'Er ermöglicht eine enge Kundenbeziehung und daraus resultierende Kundentreue.',
      'Er erlaubt die Kontrolle über Preise, Rabatte und Präsentation.',
      'Er erzielt in der Regel größere Absatzmengen als der indirekte Vertrieb.',
      'Er liefert ungefilterte Kundeninformationen, ist aber mit hohem Aufwand verbunden.',
    ],
    correctOptions: [0, 1, 3],
    explanation: 'Größere Absatzmengen sind ein Vorteil des INDIREKTEN Vertriebs; beim direkten Vertrieb ist die geringere Absatzmenge ein Nachteil.',
    source: 'Kapitel 5.2, PDF S. 22', conceptIds: ['mc-direkt-indirekt', 'mc-indirekt'],
  },
  {
    id: 'qm5-10', chapterId: 'm5', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erläutern Sie den Begriff Disintermediation, nennen Sie die Gründe dafür aus dem Skript sowie ein Beispiel und das Gegenbeispiel Nordstrom Local.',
    rubric: [
      { point: 'Trend zur Ausschaltung von Intermediären', keywords: ['ausschaltung', 'intermediär', 'zwischenhändler'] },
      { point: 'Gründe: Intermediäre bringen keinen Zusatznutzen mehr; Einsparung der Handelsmarge', keywords: ['zusatznutzen', 'handelsmarge', 'marge'] },
      { point: 'Beispiel: D2C über E-Commerce (Adidas, Social Brands über Instagram)', keywords: ['d2c', 'direct-to-consumer', 'e-commerce', 'adidas', 'instagram'] },
      { point: 'Gegenbeispiel Nordstrom Local: Stylistenberatung, Café-Atmosphäre, Lieferung – Händler schafft Zusatznutzen', keywords: ['nordstrom', 'stylist', 'café', 'beratung'] },
    ],
    modelAnswer: 'Disintermediation bezeichnet den Trend zur Ausschaltung von Intermediären. Das geschieht oft, wenn sie keinen Zusatznutzen mehr bringen; ein weiterer Grund ist die Einsparung der Handelsmarge. Beispiel: Durch E-Commerce verkaufen Hersteller direkt an Endverbraucher (Direct-to-Consumer), etwa Adidas oder „Social Brands“, die ausschließlich über Instagram verkaufen. Gegenbeispiel ist Nordstrom Local: Statt Kleiderständern gibt es Café-Atmosphäre mit professioneller Stylistenberatung, die zusammengestellten Outfits werden geliefert – der Händler schafft also Zusatznutzen und bleibt relevant.',
    explanation: 'Begriff + Gründe + Beispiel + Gegenbeispiel.',
    source: 'Kapitel 5.1, PDF S. 21', conceptIds: ['mc-disintermediation', 'mc-d2c'],
  },
  {
    id: 'qm5-11', chapterId: 'm5', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein Hersteller sehr teurer, handgefertigter Uhren für eine kleine, anspruchsvolle Zielgruppe plant sein Vertriebssystem. Empfehlen Sie einen Distributionsgrad und begründen Sie, welche Rolle direkter Vertrieb spielen kann.',
    rubric: [
      { point: 'Exklusiver Vertrieb: sehr wenige Partner, teure Specialty Goods', keywords: ['exklusiv', 'wenige', 'specialty'] },
      { point: 'Begründung: kleine Zielgruppe, sachkundige Bedienung (wie Trüffelbutter-Gourmetkunden)', keywords: ['sachkundig', 'kleine zielgruppe', 'wenige kunden', 'beratung', 'trüffel'] },
      { point: 'Direkter Vertrieb (eigene Boutique/Onlineshop): Kontrolle über Preise und Präsentation, enge Kundenbeziehung', keywords: ['direkt', 'kontrolle', 'kundenbeziehung', 'präsentation', 'onlineshop'] },
      { point: 'Vertrieb als markenbildendes Element / Einklang mit Image', keywords: ['markenbildend', 'image', 'einklang'], weight: 0.5 },
    ],
    modelAnswer: 'Passend ist ein exklusiver Vertrieb mit sehr wenigen Vertriebspartnern – er ist für teure Specialty Goods gedacht, deren wenige Kunden sachkundig bedient werden (wie die Tarbiana-Trüffelbutter nur in Spezialitätenläden und online). Zusätzlich bietet sich direkter Vertrieb an (eigene Boutique, Onlineshop): Er sichert die Kontrolle über Preise, Rabatte und Präsentation, eine enge Kundenbeziehung und ungefilterte Kundeninformationen – der hohe Aufwand ist bei kleiner Zielgruppe tragbar. So wird der Vertrieb als markenbildendes Element im Einklang mit dem hochwertigen Image geplant.',
    explanation: 'Specialty Good → exklusiv; Direktvertrieb sichert Kontrolle.',
    source: 'Kapitel 5.2–5.3, PDF S. 22–24', conceptIds: ['mc-exklusiv', 'mc-direkt-indirekt', 'mc-vertrieb-einklang', 'mc-specialty'],
  },

  // ======================= neue offene Fragen =======================
  {
    id: 'qm5-12', chapterId: 'm5', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Definieren Sie die Distributionspolitik, erläutern Sie ihre beiden Komponenten und begründen Sie, warum die Qualität der Vertriebskanäle über den Markterfolg mitentscheidet.',
    rubric: [
      { point: 'Verteilung von Leistungen von der Produktion zur Konsumption (Meffert/Burmann/Kirchgeorg 2015)', keywords: ['verteilung', 'produktion', 'konsumption'] },
      { point: 'Akquisitorische Komponente: effizientes und effektives Vertriebssystem', keywords: ['akquisitorisch', 'vertriebssystem', 'effizient'] },
      { point: 'Logistische Komponente: adäquater Zugriff der Konsumenten auf die Waren', keywords: ['logistisch', 'zugriff'] },
      { point: 'Beste Produkte nutzen wenig, wenn sie nicht kostengünstig und zeitnah ankommen', keywords: ['kostengünstig', 'zeitnah', 'beste produkte', 'nutzen wenig', 'qualität der vertriebskanäle'] },
    ],
    modelAnswer: 'Die Distributions- bzw. Vertriebspolitik bezieht sich auf die Verteilung von Leistungen von der Produktion zur Konsumption (Meffert/Burmann/Kirchgeorg 2015). Sie stellt sicher, dass das Vertriebssystem effizient und effektiv gestaltet ist (akquisitorische Komponente) und dass die Konsumenten adäquaten Zugriff auf die Waren haben (logistische Komponente). Der Erfolg hängt nicht nur von der Qualität der Leistungen, sondern auch von der Qualität der Vertriebskanäle ab: Die besten Produkte nutzen wenig, wenn sie nicht kostengünstig und zeitnah bei den Konsumenten ankommen.',
    explanation: 'Definition + zwei Komponenten + Erfolgsrelevanz.',
    source: 'Kapitel 5.1, PDF S. 20', conceptIds: ['mc-distribution', 'mc-akquisitorisch', 'mc-logistisch'],
  },
  {
    id: 'qm5-13', chapterId: 'm5', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erläutern Sie die drei Arten von Vertriebszielen und die Anforderungen, die sich aus dem Einklang mit den übrigen Marketingmaßnahmen ergeben.',
    rubric: [
      { point: 'Aufgabe: Verfügbarkeit von Leistungen gewährleisten; Ziele parallel verfolgt', keywords: ['verfügbarkeit', 'parallel'] },
      { point: 'Psychologisch: einzigartiges, markentreues, positives Kauferlebnis', keywords: ['psychologisch', 'kauferlebnis', 'markentreu'] },
      { point: 'Versorgungsorientiert: lückenlose Verfügbarkeit; ökonomisch: Absatzmenge, Preisniveau, Vertriebskosten optimieren', keywords: ['versorgungsorientiert', 'lückenlos', 'ökonomisch', 'absatzmenge', 'vertriebskosten'] },
      { point: 'Einklang: der Leistung angemessen, der Zielgruppe entgegenkommen, Image aus Preis- und Kommunikationspolitik unterstützen', keywords: ['angemessen', 'zielgruppe', 'image', 'einklang', 'preis- und kommunikationspolitik'] },
    ],
    modelAnswer: 'Aufgabe des Vertriebs ist es, die Verfügbarkeit von Leistungen für die Kunden zu gewährleisten. Drei Zielarten werden parallel verfolgt: psychologische Ziele (ein einzigartiges, markentreues und positives Kauferlebnis vermitteln), versorgungsorientierte Ziele (lückenlose Verfügbarkeit) und ökonomische Ziele (Absatzmenge, Preisniveau und Vertriebskosten optimieren). Die Distributionspolitik soll im Einklang mit den übrigen Marketingmaßnahmen stehen: der Unternehmensleistung angemessen sein, der Zielgruppe entgegenkommen und das durch Preis- und Kommunikationspolitik vermittelte Image unterstützen.',
    explanation: 'Drei Zielarten + Einklang.',
    source: 'Kapitel 5.1, PDF S. 20', conceptIds: ['mc-vertriebsziele', 'mc-vertrieb-einklang'],
  },
  {
    id: 'qm5-14', chapterId: 'm5', type: 'open', goal: 'distinction', difficulty: 3,
    prompt: 'Grenzen Sie Push- und Pull-Strategie voneinander ab. Gehen Sie auf den Ansatz, typische (auch digitale) Maßnahmen und die Bedingungen ein, unter denen die jeweilige Strategie sinnvoll ist.',
    rubric: [
      { point: 'Push: Produkte in den Handel „drücken“ – Rabatte, Boni, Exklusivrechte', keywords: ['drückt', 'in den handel', 'rabatt', 'boni', 'exklusivrecht'] },
      { point: 'Push digital: Retail Media (gesponserte Platzierungen auf Amazon), Prime-Exklusiv, „Only at Zalando“', keywords: ['retail media', 'amazon', 'prime', 'zalando'] },
      { point: 'Push sinnvoll bei geringer Markentreue, impulsiver Entscheidung im Geschäft, klarem Produktnutzen', keywords: ['markentreue gering', 'geringe markentreue', 'impulsiv', 'produktnutzen'] },
      { point: 'Pull: Nachfragesog, Kommunikation an Endkunden (Social Media, Content Marketing, SEO)', keywords: ['nachfragesog', 'endkunden', 'social media', 'content marketing', 'seo'] },
      { point: 'Pull sinnvoll bei markentreuen, stark involvierten Kunden; meist Kombination beider', keywords: ['markentreu', 'involviert', 'involvement', 'beide', 'gleichzeitig'] },
    ],
    modelAnswer: 'Die Push-Strategie „drückt“ Produkte in den Handel, etwa durch Absatzförderungsmaßnahmen wie Rabatte, Boni oder Exklusivrechte; digital z. B. über Retail Media (bezahlte, gesponserte Produktplatzierungen auf Amazon) oder exklusive Verträge („Prime-Exklusivprodukte“, „Only at Zalando“). Sie ist sinnvoll, wenn die Markentreue gering ist, Kunden sich impulsiv im Geschäft entscheiden und der Produktnutzen relativ klar ist. Die Pull-Strategie erzeugt einen Nachfragesog: Der Hersteller richtet seine Kommunikation direkt an die Endkunden (Social-Media-Kampagnen, Content Marketing, gute Suchmaschinenplatzierung/SEO), um ein positives Image zu schaffen, das Konsumenten ins Geschäft oder in den Onlineshop zieht. Sie ist sinnvoll, wenn Kunden markentreu und stärker in den Kauf involviert sind. In der Regel wenden Unternehmen beide Strategien gleichzeitig an.',
    explanation: 'Vollständige Abgrenzung inkl. Einsatzbedingungen.',
    source: 'Kapitel 5.1, PDF S. 20–21', conceptIds: ['mc-push-pull', 'mc-pull', 'mc-retail-media', 'mc-involvement'],
  },
  {
    id: 'qm5-15', chapterId: 'm5', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Hersteller A verkauft günstige Kaugummis, die Kunden spontan an der Kasse mitnehmen; die Markentreue ist gering. Hersteller B verkauft hochwertige Kopfhörer an eine markentreue, intensiv vergleichende Zielgruppe. Welche Distributionsstrategie (Push/Pull) sollte jeweils im Vordergrund stehen? Begründen Sie.',
    rubric: [
      { point: 'A: Push-Strategie', keywords: ['push'] },
      { point: 'Begründung A: geringe Markentreue, impulsive Entscheidung im Geschäft, klarer Produktnutzen', keywords: ['impulsiv', 'markentreue', 'kasse', 'produktnutzen'] },
      { point: 'B: Pull-Strategie', keywords: ['pull'] },
      { point: 'Begründung B: markentreu, stark involviert → Nachfragesog über Kommunikation an Endkunden', keywords: ['involviert', 'involvement', 'markentreu', 'nachfragesog', 'endkunden'] },
    ],
    modelAnswer: 'Bei A steht die Push-Strategie im Vordergrund: Die Markentreue ist gering, Kunden entscheiden impulsiv im Geschäft und der Produktnutzen ist klar – also muss der Hersteller das Produkt über Rabatte, Boni oder Platzierungsvereinbarungen in den Handel bzw. an die Kasse „drücken“. Bei B steht die Pull-Strategie im Vordergrund: Die Kunden sind markentreu und stark involviert (sie investieren viel Zeit in die Entscheidung); Kommunikation direkt an die Endkunden (Social Media, Content Marketing, SEO) erzeugt einen Nachfragesog, der sie gezielt nach der Marke fragen lässt. In der Praxis kombinieren beide Unternehmen meist Push und Pull.',
    explanation: 'Anwendung der Einsatzbedingungen aus dem Skript.',
    source: 'Kapitel 5.1, PDF S. 20–21', conceptIds: ['mc-push-pull', 'mc-pull', 'mc-involvement'],
  },
  {
    id: 'qm5-16', chapterId: 'm5', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erklären Sie die Begriffe Involvement, Content Marketing und Search Engine Optimization (SEO) und zeigen Sie ihren Bezug zur Pull-Strategie.',
    rubric: [
      { point: 'Involvement: starke Beteiligung beim Kauf, viel Zeit in die Entscheidung', keywords: ['beteiligung', 'viel zeit', 'entscheidung'] },
      { point: 'Content Marketing: nützliche Inhalte zur Kundenansprache/-bindung (Blog, Tutorials, Rezeptideen)', keywords: ['nützliche inhalte', 'blog', 'tutorial', 'rezept'] },
      { point: 'SEO: Webseiten optimieren für Sichtbarkeit und Ranking in Suchmaschinen', keywords: ['ranking', 'sichtbarkeit', 'optimierung', 'google'] },
      { point: 'Bezug: Pull bei stark involvierten Kunden; Content Marketing und SEO sind Pull-Maßnahmen', keywords: ['pull', 'nachfragesog'] },
    ],
    modelAnswer: 'Involvement liegt vor, wenn ein Konsument beim Produktkauf eine starke Beteiligung verspürt und viel Zeit in die Entscheidung investiert – bei solchen (und markentreuen) Kunden ist die Pull-Strategie sinnvoll. Content Marketing ist die gezielte Bereitstellung nützlicher Inhalte zur Kundenansprache und -bindung, z. B. ein Blog mit Tipps, YouTube-Tutorials oder Rezeptideen von Lebensmittelmarken. SEO ist die Optimierung von Webseiten für höhere Sichtbarkeit und ein besseres Ranking in Suchmaschinen wie Google. Content Marketing und SEO sind typische Pull-Maßnahmen, die einen Nachfragesog bei den Endkunden erzeugen.',
    explanation: 'Drei Begriffe + Einordnung.',
    source: 'Kapitel 5.1, PDF S. 20–21', conceptIds: ['mc-involvement', 'mc-content-marketing', 'mc-seo', 'mc-pull'],
  },
  {
    id: 'qm5-17', chapterId: 'm5', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Was sind Intermediäre, und warum übertragen Hersteller einen Großteil ihrer Vertriebsaufgaben an Handelsunternehmen?',
    rubric: [
      { point: 'Intermediäre kaufen und verkaufen Sachgüter, bearbeiten sie nicht weiter, verbinden sie oft mit Dienstleistungen', keywords: ['kaufen und verkaufen', 'nicht weiter', 'dienstleistung'] },
      { point: 'Alle Vertriebsaufgaben selbst zu übernehmen, wäre für Hersteller sehr aufwendig', keywords: ['aufwendig', 'selbst zu übernehmen'] },
      { point: 'Handel hat spezielle Kontakte, Kompetenz, Erfahrung', keywords: ['kontakte', 'kompetenz', 'erfahrung'] },
      { point: 'Leistungen: Nachfrage erzeugen, Kunden beraten, Risiko übernehmen, Marktforschung', keywords: ['nachfrage', 'beraten', 'risiko', 'marktforschung'] },
    ],
    modelAnswer: 'Intermediäre kaufen und verkaufen Sachgüter; sie bearbeiten diese zwar nicht weiter, verbinden sie aber oft mit relevanten Dienstleistungen. Weil es für Hersteller sehr aufwendig wäre, alle Vertriebsaufgaben selbst zu übernehmen, geben sie einen Großteil an Handelsunternehmen ab, die spezielle Kontakte, Kompetenz und Erfahrung haben: Diese erzeugen Nachfrage durch Marketingkommunikation, beraten Kunden bei Kaufentscheidungen, übernehmen Teile des Risikos und betreiben Marktforschung. Handelsunternehmen tragen zur Wertschöpfung bei, sofern sie den Kundennutzen steigern.',
    explanation: 'Definition + Gründe + Leistungen des Handels.',
    source: 'Kapitel 5.1, PDF S. 21', conceptIds: ['mc-intermediaere', 'mc-handelsleistungen'],
  },
  {
    id: 'qm5-18', chapterId: 'm5', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Erläutern Sie, wie Handelsunternehmen durch die Überbrückung von Diskrepanzen Wert schaffen. Gehen Sie auf alle drei Überbrückungsfunktionen am Beispiel Bananen ein und unterscheiden Sie quantitative und qualitative Diskrepanz.',
    rubric: [
      { point: 'Wertschöpfung, sofern Kundennutzen steigt; Lücken zwischen Herstellung und Konsum überbrücken', keywords: ['kundennutzen', 'lücken', 'herstellung und konsum', 'diskrepanz'] },
      { point: 'Räumlich: Transport in die Nähe des Verbrauchsorts (Costa Rica, Kolumbien, Ecuador)', keywords: ['räumlich', 'transport', 'costa rica', 'kolumbien', 'ecuador'] },
      { point: 'Zeitlich: Lagerung/Vorratshaltung (Kühlung, Nachreifung mit Ethen)', keywords: ['zeitlich', 'lagerung', 'vorratshaltung', 'kühl', 'ethen', 'reife'] },
      { point: 'Sortiment: quantitative Diskrepanz (große Mengen vs. wenige Stück)', keywords: ['quantitativ', 'große mengen', 'wenige stück'] },
      { point: 'Sortiment: qualitative Diskrepanz (auch andere Lebensmittel)', keywords: ['qualitativ', 'andere lebensmittel'] },
    ],
    modelAnswer: 'Handelsunternehmen tragen zur Wertschöpfung bei, sofern sie den Kundennutzen steigern – insbesondere durch die Überbrückung von Lücken zwischen Herstellung und Konsum. Räumliche Überbrückung: Transport der Waren vom Herstellungsort in die Nähe des Ge- oder Verbrauchsorts – Bananen aus Costa Rica, Kolumbien und Ecuador liegen in jedem Supermarkt. Zeitliche Überbrückung: Lagerung und Vorratshaltung sorgen für Verfügbarkeit zur rechten Zeit – Bananen werden nach der Ernte gekühlt und später in Reifereien durch Begasung mit Ethen nachgereift. Sortimentsgestaltung: Abstimmung des Herstellerangebots mit der Nachfrage – quantitativ liefern Importeure große Mengen, während Endverbraucher wenige Stück kaufen (quantitative Diskrepanz); qualitativ wollen Endverbraucher auch andere Lebensmittel mitnehmen (qualitative Diskrepanz).',
    explanation: 'Drei Funktionen + zwei Diskrepanzarten.',
    source: 'Kapitel 5.1, PDF S. 21', conceptIds: ['mc-ueberbrueckung', 'mc-raeumlich', 'mc-zeitlich', 'mc-sortiment'],
  },
  {
    id: 'qm5-19', chapterId: 'm5', type: 'open', goal: 'distinction', difficulty: 2,
    prompt: 'Grenzen Sie Disintermediation und vertikale Integration voneinander ab und nennen Sie jeweils ein Beispiel aus dem Skript.',
    rubric: [
      { point: 'Disintermediation: Ausschaltung von Intermediären', keywords: ['ausschaltung', 'ausgeschaltet', 'fällt weg'] },
      { point: 'Beispiel: D2C (Adidas, Social Brands über Instagram)', keywords: ['d2c', 'adidas', 'instagram', 'direct-to-consumer'] },
      { point: 'Vertikale Integration: vor-/nachgelagerte Wertschöpfungsstufen werden eingegliedert', keywords: ['eingegliedert', 'eingliedern', 'wertschöpfungsstufe', 'vorgelagert', 'nachgelagert'] },
      { point: 'Beispiel Edeka-Bananenreiferei: Funktion wird nicht beseitigt, sondern integriert', keywords: ['edeka', 'reiferei', 'integriert', 'nicht beseitigt'] },
    ],
    modelAnswer: 'Disintermediation ist der Trend zur Ausschaltung von Intermediären – die Zwischenstufe fällt weg, etwa wenn Hersteller per E-Commerce direkt an Endverbraucher verkaufen (D2C, z. B. Adidas oder Social Brands über Instagram). Bei der vertikalen Integration gliedert ein Unternehmen dagegen vor- oder nachgelagerte Wertschöpfungsstufen ein, die vorher eigenständige Akteure erbracht haben: Edeka betreibt in Hamburg eine eigene Bananenreiferei – die Funktion wird nicht beseitigt, sondern integriert.',
    explanation: 'Wegfall vs. Eingliederung einer Funktion.',
    source: 'Kapitel 5.1, PDF S. 21–22', conceptIds: ['mc-disintermediation', 'mc-vertikale-integration', 'mc-d2c'],
  },
  {
    id: 'qm5-20', chapterId: 'm5', type: 'open', goal: 'distinction', difficulty: 3,
    prompt: 'Erläutern Sie direkten und indirekten Vertrieb und stellen Sie jeweils die Vor- und Nachteile laut Skript gegenüber.',
    rubric: [
      { point: 'Direkt: Unternehmen verkauft selbst an Endkunden über interne Vertriebsorgane (Hofladen, Onlineshop, Social Commerce, Apps)', keywords: ['selbst', 'direkt an endkunden', 'intern', 'hofladen', 'onlineshop', 'app'] },
      { point: 'Direkt-Vorteile: Kundenbeziehung/-treue, Kontrolle, ungefilterte Informationen, geringere Kosten (nur Personal)', keywords: ['kundentreue', 'kontrolle', 'ungefiltert', 'personalkosten'] },
      { point: 'Direkt-Nachteile: hoher Aufwand, geringere Absatzmenge, fehlende komplementäre Produkte', keywords: ['hoher aufwand', 'geringere absatzmenge', 'komplementär'] },
      { point: 'Indirekt: Aufgaben mit externen Marktakteuren geteilt; Vorteile Arbeitsteilung, Marktkenntnis, geringerer Aufwand, größere Mengen', keywords: ['extern', 'arbeitsteilung', 'kennen den markt', 'größere absatzmengen', 'geringerer aufwand'] },
      { point: 'Indirekt-Nachteile: kein direktes Feedback, Handelsmargen, Abhängigkeit, weniger Kontrolle', keywords: ['feedback', 'handelsmarge', 'abhängigkeit', 'geringere kontroll'] },
    ],
    modelAnswer: 'Beim direkten Vertrieb verkauft das Unternehmen selbst an Endkunden, organisiert über interne Vertriebsorgane (Innen-/Außendienst) – klassisch Hofläden, heute eigene Onlineshops, Social-Commerce-Funktionen oder markeneigene Apps. Vorteile: enge Kundenbeziehung und Kundentreue, Kontrolle der Vertriebsaktivitäten (Preise, Rabatte, Präsentation), ungefilterte Kundeninformationen, geringere Kosten (nur Personalkosten). Nachteile: hoher Aufwand, geringere Absatzmenge, Fehlen komplementärer Produkte. Beim indirekten Vertrieb werden die Vertriebsaufgaben mit externen Marktakteuren geteilt. Vorteile: Arbeitsteilung, Intermediäre kennen den Markt besser, geringerer Aufwand, größere Absatzmengen. Nachteile: kein direktes Feedback vom Markt, Handelsmargen, Abhängigkeit von Vertriebspartnern, geringere Kontrollmöglichkeiten.',
    explanation: 'Vollständige Gegenüberstellung nach der Skript-Tabelle.',
    source: 'Kapitel 5.2, PDF S. 22', conceptIds: ['mc-direkt-indirekt', 'mc-indirekt', 'mc-vertriebsorgane'],
  },
  {
    id: 'qm5-21', chapterId: 'm5', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Wie entscheiden Unternehmen laut Skript zwischen direktem und indirektem Vertrieb, und wie sieht die Praxis meist aus?',
    rubric: [
      { point: 'Vergleichsberechnungen: Handelsmarge vs. Kosten einer eigenen Vertriebsabteilung', keywords: ['vergleichsberechnung', 'handelsmarge', 'eigenen vertriebsabteilung', 'kosten'] },
      { point: 'Weitere Kriterien: Zahl der Kunden, Komplexität, monetärer Wert des Produkts', keywords: ['zahl der kunden', 'komplexität', 'monetär', 'wert des produkts'] },
      { point: 'Praxis: Mischformen aus direktem und indirektem Vertrieb', keywords: ['mischform', 'beides', 'direkt und indirekt'] },
    ],
    modelAnswer: 'Die Wahl erfolgt oft durch Vergleichsberechnungen: Die Handelsmarge wird den Kosten einer eigenen Vertriebsabteilung gegenübergestellt. Zusätzlich spielen die Zahl der Kunden, die Komplexität und der monetäre Wert des Produkts eine Rolle. In der Praxis entscheiden sich Unternehmen oft für Mischformen und nutzen direkten und indirekten Vertrieb.',
    explanation: 'Entscheidungskriterien + Praxis.',
    source: 'Kapitel 5.2, PDF S. 22', conceptIds: ['mc-vertriebsweg-wahl'],
  },
  {
    id: 'qm5-22', chapterId: 'm5', type: 'open', goal: 'distinction', difficulty: 3,
    prompt: 'Erläutern Sie die externen Vertriebsorgane nach Homburg (2017) und grenzen Sie sie voneinander ab.',
    rubric: [
      { point: 'Indirekter Vertrieb = externe, unabhängige Vertriebsorgane mit wesentlicher akquisitorischer Funktion', keywords: ['akquisitorisch', 'unabhängig', 'extern', 'homburg'] },
      { point: 'Vertragshändler: rechtlich selbstständig, vertraglich fest eingebunden (Automobil)', keywords: ['vertragshändler', 'rechtlich selbstständig', 'automobil', 'auto'] },
      { point: 'Franchisepartner: stärkere Bindung, Weisungsrecht und Kontrolle (Fast Food)', keywords: ['franchise', 'weisungsrecht', 'fast-food', 'fast food'] },
      { point: 'Absatzhelfer: Handelsvertreter, Kommissionäre, Makler – kein Eigentum', keywords: ['absatzhelfer', 'handelsvertreter', 'kommissionär', 'makler', 'kein eigentum'] },
      { point: 'Absatzmittler: Groß- und Einzelhandel – erwerben Eigentum', keywords: ['absatzmittler', 'großhandel', 'einzelhandel', 'eigentum'] },
    ],
    modelAnswer: 'Werden unternehmensunabhängige, externe Vertriebsorgane mit einer wesentlichen akquisitorischen Funktion beauftragt, spricht man von indirektem Vertrieb. Vertragshändler sind rechtlich selbstständig, aber durch Verträge fest in die Vertriebsstrategie des Anbieters eingebunden (typisch für die Automobilbranche). Franchisepartner sind noch stärker gebunden: Der Anbieter hat ein Weisungsrecht und darf Verhalten und Ergebnisse kontrollieren (z. B. Fast-Food-Restaurants). Absatzhelfer – Handelsvertreter (Kosmetik), Kommissionäre (Antiquitäten) und Makler (Immobilien, Versicherungen) – unterscheiden sich nach Tätigkeit, Dauer und Vergütungsanspruch und erwerben kein Eigentum an den Produkten. Absatzmittler sind Groß- und Einzelhandel: Der Großhandel verkauft große Mengen an gewerbliche Nachfrager, der Einzelhandel an private Endverbraucher; sie erwerben Eigentum.',
    explanation: 'Vier externe Vertriebsorgane mit Abgrenzung.',
    source: 'Kapitel 5.2, PDF S. 22', conceptIds: ['mc-externe-vertriebsorgane', 'mc-vertragshaendler', 'mc-franchising', 'mc-absatzhelfer-mittler', 'mc-absatzmittler'],
  },
  {
    id: 'qm5-23', chapterId: 'm5', type: 'open', goal: 'distinction', difficulty: 2,
    prompt: 'Was versteht man unter Franchising, und worin unterscheidet sich ein Franchisepartner von einem Vertragshändler?',
    rubric: [
      { point: 'Franchisenehmer übernimmt gegen Gebühren ein bestehendes Konzept und setzt es vor Ort um', keywords: ['gebühr', 'konzept', 'vor ort', 'franchisegeber'] },
      { point: 'Franchisepartner: Weisungsrecht und Kontrolle von Verhalten und Ergebnissen durch den Anbieter', keywords: ['weisungsrecht', 'kontrolle', 'verhalten', 'ergebnisse'] },
      { point: 'Vertragshändler: rechtlich selbstständig, durch Verträge eingebunden – schwächere Bindung', keywords: ['rechtlich selbstständig', 'verträge', 'eingebunden', 'schwächer'] },
    ],
    modelAnswer: 'Beim Franchising übernimmt der Franchisenehmer gegen Zahlung von Gebühren an den Franchisegeber ein bestehendes Franchisekonzept und setzt es vor Ort um (z. B. Fast-Food-Restaurants). Franchisepartner sind dabei noch stärker gebunden als Vertragshändler: Der Anbieter hat ein Weisungsrecht und darf Verhalten und Ergebnisse kontrollieren. Vertragshändler (z. B. Autohäuser) sind rechtlich selbstständig und „nur“ durch Verträge fest in die Vertriebsstrategie eingebunden.',
    explanation: 'Bindungsintensität als Unterschied.',
    source: 'Kapitel 5.2, PDF S. 22', conceptIds: ['mc-franchising', 'mc-vertragshaendler'],
  },
  {
    id: 'qm5-24', chapterId: 'm5', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Wovon hängt die Länge eines Vertriebsweges ab? Erläutern Sie den null-, ein-, zwei- und dreistufigen Vertriebsweg mit Beispielen.',
    rubric: [
      { point: 'Je mehr Vertriebsorgane zwischen Hersteller und Endverbraucher, desto länger', keywords: ['je mehr', 'länger', 'zwischen hersteller und endverbraucher'] },
      { point: 'Nullstufig = direkter Vertrieb', keywords: ['nullstufig', 'direkt'] },
      { point: 'Einstufig (Einzelhandel, Konsumgüter); zweistufig (+ Großhandel, Pharma)', keywords: ['einstufig', 'konsumgüter', 'zweistufig', 'pharma', 'großhandel'] },
      { point: 'Dreistufig (+ Absatzhelfer, exotische Früchte); Mischformen wie Pop-up-Stores', keywords: ['dreistufig', 'exotische früchte', 'absatzhelfer', 'pop-up'] },
    ],
    modelAnswer: 'Je mehr verschiedene Vertriebsorgane zwischen Hersteller und Endverbraucher stehen, desto länger ist der Vertriebsweg. Der direkte Vertrieb heißt daher nullstufiger Vertriebsweg. Laut Abbildung führt der einstufige Weg über den Einzelhandel (z. B. Konsumgüter), der zweistufige zusätzlich über den Großhandel (z. B. Pharmaprodukte) und der dreistufige zusätzlich über einen Absatzhelfer (z. B. exotische Früchte). Daneben gibt es alternative Varianten und Mischformen wie Pop-up-Stores.',
    explanation: 'Länge = Zahl der zwischengeschalteten Stufen.',
    source: 'Kapitel 5.2, PDF S. 23', conceptIds: ['mc-vertriebsweglaenge', 'mc-direkt-indirekt'],
  },
  {
    id: 'qm5-25', chapterId: 'm5', type: 'open', goal: 'distinction', difficulty: 3,
    prompt: 'Grenzen Sie die vertikale von der horizontalen Gestaltung des Vertriebssystems ab und erläutern Sie die drei Ausprägungen der Breite des Vertriebssystems.',
    rubric: [
      { point: 'Vertikal: Stufen/Länge der Vertriebskanäle', keywords: ['vertikal', 'länge', 'stufen'] },
      { point: 'Horizontal: Zahl der Absatzmittler innerhalb der Absatzstufen (Breite)', keywords: ['horizontal', 'zahl der', 'absatzmittler', 'breite'] },
      { point: 'Einkanalsystem: nur ein Vertriebsweg (z. B. Einzelhandel)', keywords: ['einkanal', 'nur ein', 'lediglich'] },
      { point: 'Multichannel: mehrere Kanäle, heute die Regel (möve)', keywords: ['multichannel', 'mehrkanal', 'mehrere', 'möve'] },
      { point: 'Omnichannel: alle Kanäle nahtlos vernetzt, durchgängiges Erlebnis', keywords: ['omnichannel', 'vernetzt', 'nahtlos', 'durchgängig'] },
    ],
    modelAnswer: 'Die vertikale Gestaltung betrachtet die Stufen möglicher Vertriebsorgane, also die Länge der Vertriebskanäle; die horizontale Gestaltung bezieht sich auf die Zahl der unterschiedlichen Absatzmittler innerhalb der einzuschaltenden Absatzstufen. Die Breite des Vertriebssystems hängt von der Zahl der gewählten Vertriebskanäle ab (Homburg 2017): Beim Einkanalsystem wird nur ein Vertriebsweg genutzt (z. B. der Einzelhandel). Beim Mehrkanalvertrieb (Multichannel) – heute die Regel – nutzt ein Unternehmen mehrere Kanäle, um Kundensegmente zu erreichen (möve: Flagship- und Outlet-Stores, Onlineshop, Shop-in-Shops, Fachhändler, möve Professional). Beim Omnichannel-Marketing werden die bisher getrennten Kanäle nahtlos vernetzt, um ein durchgängiges, widerspruchsfreies Kundenerlebnis zu schaffen.',
    explanation: 'Länge vs. Breite + drei Ausprägungen.',
    source: 'Kapitel 5.2–5.3, PDF S. 22–23', conceptIds: ['mc-vertikale-gestaltung', 'mc-horizontale-gestaltung', 'mc-breite', 'mc-einkanal', 'mc-multi-omni', 'mc-omnichannel'],
  },
  {
    id: 'qm5-26', chapterId: 'm5', type: 'transfer', goal: 'application', difficulty: 2,
    prompt: 'Ein Elektronikhändler ermöglicht es, die Verfügbarkeit online zu prüfen, Ware per App zu reservieren, sie im Markt abzuholen und dabei App-Treuepunkte einzulösen. Liegt Multichannel- oder Omnichannel-Marketing vor? Begründen Sie und erklären Sie den enthaltenen Service.',
    rubric: [
      { point: 'Omnichannel-Marketing', keywords: ['omnichannel'] },
      { point: 'Begründung: Kanäle nahtlos vernetzt, durchgängiges und widerspruchsfreies Kundenerlebnis', keywords: ['vernetzt', 'nahtlos', 'durchgängig', 'widerspruchsfrei'] },
      { point: 'Abgrenzung: Multichannel = nur auf mehreren Kanälen präsent', keywords: ['multichannel', 'präsent', 'mehreren kanälen'] },
      { point: 'Click & Collect: digital bestellen, im Geschäft abholen', keywords: ['click & collect', 'click and collect', 'digital bestellen', 'abholen'] },
    ],
    modelAnswer: 'Es liegt Omnichannel-Marketing vor: Die Kanäle (Website, App, Filiale, Treueprogramm) sind nicht nur parallel vorhanden, sondern nahtlos miteinander verknüpft und schaffen ein durchgängiges, widerspruchsfreies Kundenerlebnis – genau das Skript-Beispiel. Multichannel hieße lediglich, auf mehreren Kanälen präsent zu sein. Enthalten ist Click & Collect: Kunden bestellen bzw. reservieren digital und erhalten die Ware persönlich im Geschäft.',
    explanation: 'Präsent (Multi) vs. vernetzt (Omni).',
    source: 'Kapitel 5.3, PDF S. 23', conceptIds: ['mc-omnichannel', 'mc-multi-omni', 'mc-click-collect'],
  },
  {
    id: 'qm5-27', chapterId: 'm5', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erklären Sie den Distributionsgrad und erläutern Sie intensiven, selektiven und exklusiven Vertrieb mit Gütertyp und Butter-Beispiel.',
    rubric: [
      { point: 'Distributionsgrad: Breite innerhalb eines Vertriebswegs; je mehr Organe auf einer Stufe, desto intensiver', keywords: ['je mehr', 'intensiver', 'auf einer stufe', 'breite'] },
      { point: 'Intensiv: sehr viele Partner, günstige Convenience Goods, große Zielgruppe (Deutsche Markenbutter)', keywords: ['intensiv', 'convenience', 'markenbutter', 'sehr viele'] },
      { point: 'Selektiv: mehrere Partner, Shopping Goods (Andechser Bio-Almbutter)', keywords: ['selektiv', 'shopping', 'andechser'] },
      { point: 'Exklusiv: sehr wenige Partner, teure Specialty Goods, sachkundige Bedienung (Tarbiana-Trüffelbutter)', keywords: ['exklusiv', 'specialty', 'trüffel', 'tarbiana', 'sehr wenige'] },
    ],
    modelAnswer: 'Auch innerhalb eines Vertriebskanals kann die Breite variieren – das beschreibt der Distributionsgrad: Je mehr Vertriebsorgane auf einer Stufe eingesetzt werden, desto intensiver ist der Vertrieb. Intensiver Vertrieb: sehr viele Partner, günstige Produkte, Convenience Goods, sinnvoll bei sehr großer Zielgruppe – „Deutsche Markenbutter“ in jedem Lebensmittelgeschäft. Selektiver Vertrieb: mehrere Partner, Shopping Goods – Andechser Bio-Almbutter vor allem in gut sortierten Bioläden. Exklusiver Vertrieb: sehr wenige Partner, teure Specialty Goods, wenige Gourmetkunden werden sachkundig bedient – Tarbiana-Trüffelbutter nur in Spezialitätenläden und online.',
    explanation: 'Drei Distributionsgrade + Verknüpfung mit Kapitel 2.',
    source: 'Kapitel 5.3, PDF S. 23–24', conceptIds: ['mc-distributionsgrad', 'mc-intensiv', 'mc-selektiv', 'mc-exklusiv'],
  },
  {
    id: 'qm5-28', chapterId: 'm5', type: 'open', goal: 'fact', difficulty: 3,
    prompt: 'Nennen und erläutern Sie die sieben Einflussfaktoren auf die Wahl des Vertriebssystems mit ihren Leitfragen bzw. Aspekten.',
    rubric: [
      { point: 'Produkt: Erklärungsbedürftigkeit, Gebrauchshäufigkeit, Transport-/Lagerfähigkeit, Kundendienst', keywords: ['produkt', 'erklärungsbedürftig', 'lagerfähig', 'kundendienst'] },
      { point: 'Unternehmen: Größe, Finanzkraft, Erfahrung, Marktstellung, Strategie', keywords: ['unternehmen', 'finanzkraft', 'größe', 'marktstellung'] },
      { point: 'Markt (Marktposition/Wachstum der Kanäle) und Kunden (Einkaufsverhalten)', keywords: ['markt', 'wachstumsraten', 'kunden', 'einkaufsverhalten'] },
      { point: 'Absatzmittler: Bindung, Flexibilität, Standort, Größe, Image, Beeinflussbarkeit, Kosten', keywords: ['absatzmittler', 'flexibilität', 'standort', 'beeinflussbarkeit'] },
      { point: 'Konkurrenz (Vertriebsstrategie) und Umfeld (Technologie, Gesetzgebung, Soziokultur)', keywords: ['konkurrenz', 'umfeld', 'technologie', 'gesetzgebung', 'soziokulturell'] },
    ],
    modelAnswer: 'Produkt: Wie erklärungsbedürftig ist es, wie oft wird es gebraucht, ist es transport- und lagerfähig, wie viel Kundendienst ist nötig? Unternehmen: Größe, Finanzkraft, Erfahrung, Marktstellung, Strategie. Markt: Marktposition und Wachstumsraten der Vertriebskanäle. Kunden: Einkaufsverhalten. Absatzmittler: vertragliche Bindung, Flexibilität, Standort, Größe, Image, Beeinflussbarkeit, Vertriebskosten. Konkurrenz: Vertriebsstrategie der Konkurrenz. Umfeld: Technologie, Gesetzgebung, soziokulturelle Veränderungen. Der Vertrieb ist dabei als markenbildendes Element im Einklang mit den übrigen Marketingmaßnahmen zu planen.',
    explanation: 'Sieben Faktoren aus der Tabelle auf S. 24.',
    source: 'Kapitel 5.3, PDF S. 24', conceptIds: ['mc-einflussfaktoren-vertrieb', 'mc-vertrieb-einklang'],
  },
  {
    id: 'qm5-29', chapterId: 'm5', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein junges Unternehmen mit geringer Finanzkraft entwickelt ein teures, sehr erklärungsbedürftiges Spezialwerkzeug für Handwerksbetriebe. Leiten Sie anhand von Einflussfaktoren aus dem Skript eine Empfehlung für Länge (direkt/indirekt) und Distributionsgrad ab.',
    rubric: [
      { point: 'Faktor Produkt: hohe Erklärungsbedürftigkeit, Kundendienst → Beratung nötig', keywords: ['erklärungsbedürftig', 'beratung', 'kundendienst', 'produkt'] },
      { point: 'Faktor Unternehmen: geringe Finanzkraft → eigener Außendienst teuer/aufwendig', keywords: ['finanzkraft', 'aufwand', 'kosten', 'unternehmen'] },
      { point: 'Empfehlung Länge: z. B. indirekt über spezialisierte Partner/Absatzhelfer oder Mischform; Begründung mit Vor-/Nachteilen', keywords: ['indirekt', 'mischform', 'absatzhelfer', 'handelsvertreter', 'fachhandel', 'direkt'] },
      { point: 'Distributionsgrad: selektiv oder exklusiv (wenige, kompetente Partner), nicht intensiv', keywords: ['selektiv', 'exklusiv', 'wenige', 'nicht intensiv'] },
    ],
    modelAnswer: 'Produkt: Das Werkzeug ist teuer und sehr erklärungsbedürftig, es braucht Beratung und Kundendienst – ein intensiver Vertrieb über viele Händler scheidet aus; sinnvoll ist ein selektiver oder sogar exklusiver Vertrieb über wenige, fachkundige Partner. Unternehmen: Die geringe Finanzkraft spricht gegen einen großen eigenen Außendienst, weil der direkte Vertrieb hohen Aufwand bedeutet. Empfehlenswert ist daher eine Mischform: indirekter Vertrieb über spezialisierte Absatzhelfer (z. B. Handelsvertreter, die nur bei Abschluss eine Provision erhalten) oder ausgewählten Fachhandel, ergänzt um direkte Elemente wie einen Onlineshop mit Beratung, um Kundenkontakt und ungefilterte Informationen zu sichern. Die Wahl sollte durch eine Vergleichsrechnung (Handelsmarge vs. Kosten eigener Vertrieb) abgesichert werden.',
    explanation: 'Einflussfaktoren → begründete Vertriebsentscheidung (mehrere vertretbare Lösungen, Begründung zählt).',
    source: 'Kapitel 5.2–5.3, PDF S. 22–24', conceptIds: ['mc-einflussfaktoren-vertrieb', 'mc-vertriebsweg-wahl', 'mc-selektiv', 'mc-absatzhelfer-mittler'],
  },

  // ======================= neue geschlossene Fragen =======================
  {
    id: 'qm5-30', chapterId: 'm5', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Was ist ein Vertriebskanal (auch Vertriebsweg, Distributions- oder Absatzkanal)?',
    options: [
      'Die Gesamtheit aller Organisationen, die ein Produkt von seiner Herstellung bis zum Endverbraucher leiten und transportieren',
      'Ein einzelner Fernsehsender für Werbung',
      'Die Lagerhalle eines Herstellers',
      'Ausschließlich der Onlineshop eines Unternehmens',
    ],
    correctOptions: [0],
    explanation: 'Definition nach Kotler/Keller/Opresnik (2015).',
    source: 'Kapitel 5.1, PDF S. 20', conceptIds: ['mc-vertriebskanal'],
  },
  {
    id: 'qm5-31', chapterId: 'm5', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Ein Hersteller bezahlt für gesponserte Produktplatzierungen auf Amazon (Retail Media). Zu welcher Strategie gehört das?',
    options: ['Push-Strategie', 'Pull-Strategie', 'Disintermediation', 'Exklusiver Vertrieb'],
    correctOptions: [0],
    explanation: 'Retail Media ist eine digitale Form der Push-Strategie, ebenso exklusive Verträge wie „Prime-Exklusivprodukte“ oder „Only at Zalando“.',
    source: 'Kapitel 5.1, PDF S. 20', conceptIds: ['mc-retail-media', 'mc-push-pull'],
  },
  {
    id: 'qm5-32', chapterId: 'm5', type: 'multiple_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Wann ist die Push-Strategie laut Skript sinnvoll? (Mehrfachauswahl)',
    options: [
      'Wenn die Markentreue gering ist',
      'Wenn Kunden sich impulsiv im Geschäft entscheiden',
      'Wenn der Produktnutzen relativ klar ist',
      'Wenn Kunden stark in den Kauf involviert sind',
    ],
    correctOptions: [0, 1, 2],
    explanation: 'Stark involvierte, markentreue Kunden sprechen für die Pull-Strategie.',
    source: 'Kapitel 5.1, PDF S. 20', conceptIds: ['mc-push-pull', 'mc-involvement'],
  },
  {
    id: 'qm5-33', chapterId: 'm5', type: 'true_false', goal: 'fact', difficulty: 1,
    prompt: 'Unternehmen entscheiden sich in der Regel ausschließlich für entweder die Push- oder die Pull-Strategie.',
    correctBool: false,
    explanation: 'Falsch – in der Regel wenden Unternehmen beide Strategien gleichzeitig an.',
    source: 'Kapitel 5.1, PDF S. 20', conceptIds: ['mc-push-pull', 'mc-pull'],
  },
  {
    id: 'qm5-34', chapterId: 'm5', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Was beschreibt Search Engine Optimization (SEO)?',
    options: [
      'Die Optimierung von Webseiten für höhere Sichtbarkeit und ein besseres Ranking in Suchmaschinen',
      'Bezahlte Anzeigen auf Suchmaschinen-Ergebnisseiten',
      'Automatisierter Anzeigenhandel in Echtzeit',
      'Die erneute Ansprache ehemaliger Websitebesucher',
    ],
    correctOptions: [0],
    explanation: 'Bezahlte Einblendungen = SEA; Echtzeit-Anzeigenhandel = programmatische Werbung; erneute Ansprache = Retargeting.',
    source: 'Kapitel 5.1, PDF S. 21', conceptIds: ['mc-seo', 'mc-sea'],
  },
  {
    id: 'qm5-35', chapterId: 'm5', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Welche Aussage über Intermediäre trifft laut Skript zu?',
    options: [
      'Sie kaufen und verkaufen Sachgüter, bearbeiten diese aber nicht weiter.',
      'Sie stellen die Produkte selbst her.',
      'Sie veredeln die Waren grundsätzlich weiter.',
      'Sie übernehmen nie Risiken.',
    ],
    correctOptions: [0],
    explanation: 'Intermediäre verbinden die Waren oft mit relevanten Dienstleistungen und übernehmen u. a. Teile des Risikos.',
    source: 'Kapitel 5.1, PDF S. 21', conceptIds: ['mc-intermediaere', 'mc-handelsleistungen'],
  },
  {
    id: 'qm5-36', chapterId: 'm5', type: 'cloze', goal: 'understanding', difficulty: 2,
    prompt: 'Importeure liefern große Mengen, Endverbraucher kaufen wenige Stück – das ist eine ______ Diskrepanz. Dass Endverbraucher zusätzlich andere Lebensmittel mitnehmen wollen, ist eine ______ Diskrepanz.',
    clozeAnswers: [['quantitative', 'quantitativ'], ['qualitative', 'qualitativ']],
    explanation: 'Beide werden durch die Sortimentsgestaltung des Handels überbrückt.',
    source: 'Kapitel 5.1, PDF S. 21', conceptIds: ['mc-sortiment'],
  },
  {
    id: 'qm5-37', chapterId: 'm5', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Welche Beispiele nennt das Skript für Direct-to-Consumer (D2C)?',
    options: ['Adidas und „Social Brands“, die ausschließlich über Instagram verkaufen', 'Edeka und Rewe', 'Nordstrom Local', 'Karstadt und Kaufhof'],
    correctOptions: [0],
    explanation: 'Nordstrom Local ist das Gegenbeispiel zur Disintermediation; Edeka steht für vertikale Integration.',
    source: 'Kapitel 5.1, PDF S. 21', conceptIds: ['mc-d2c'],
  },
  {
    id: 'qm5-38', chapterId: 'm5', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie das externe Vertriebsorgan dem Beispiel aus dem Skript zu.',
    pairs: [
      { left: 'Vertragshändler', right: 'Automobilbranche' },
      { left: 'Franchisepartner', right: 'Fast-Food-Restaurants' },
      { left: 'Handelsvertreter', right: 'Kosmetikbranche' },
      { left: 'Kommissionär', right: 'Antiquitäten' },
      { left: 'Makler', right: 'Immobilien, Versicherungen' },
    ],
    explanation: 'Handelsvertreter, Kommissionäre und Makler sind Absatzhelfer (kein Eigentumserwerb).',
    source: 'Kapitel 5.2, PDF S. 22', conceptIds: ['mc-vertragshaendler', 'mc-franchising', 'mc-absatzhelfer-mittler'],
  },
  {
    id: 'qm5-39', chapterId: 'm5', type: 'multiple_choice', goal: 'fact', difficulty: 3,
    prompt: 'Wodurch unterscheiden sich die Absatzhelfer (Handelsvertreter, Kommissionäre, Makler) laut Skript? (Mehrfachauswahl)',
    options: [
      'Tätigkeit (Abschluss oder Vermittlung von Verträgen)',
      'Dauer (ständig oder von Fall zu Fall)',
      'Art des Vergütungsanspruchs (Fixum oder Provision)',
      'Eigentumserwerb an den Produkten',
    ],
    correctOptions: [0, 1, 2],
    explanation: 'Kein Absatzhelfer erwirbt Eigentum – das unterscheidet sie gemeinsam von den Absatzmittlern.',
    source: 'Kapitel 5.2, PDF S. 22', conceptIds: ['mc-absatzhelfer-mittler'],
  },
  {
    id: 'qm5-40', chapterId: 'm5', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'An wen verkauft der Großhandel laut Skript?',
    options: ['In großen Mengen an gewerbliche Nachfrager', 'An private Endverbraucher', 'Ausschließlich ins Ausland', 'Nur an Franchisenehmer'],
    correctOptions: [0],
    explanation: 'Kunden des Einzelhandels sind private Endverbraucher; beide zusammen sind Absatzmittler.',
    source: 'Kapitel 5.2, PDF S. 22', conceptIds: ['mc-absatzmittler'],
  },
  {
    id: 'qm5-41', chapterId: 'm5', type: 'true_false', goal: 'fact', difficulty: 1,
    prompt: 'Der direkte Vertrieb wird auch als nullstufiger Vertriebsweg bezeichnet.',
    correctBool: true,
    explanation: 'Richtig – zwischen Hersteller und Endverbraucher steht kein weiteres Vertriebsorgan.',
    source: 'Kapitel 5.2, PDF S. 23', conceptIds: ['mc-vertriebsweglaenge', 'mc-direkt-indirekt'],
  },
  {
    id: 'qm5-42', chapterId: 'm5', type: 'single_choice', goal: 'fact', difficulty: 2,
    prompt: 'Wie ordnet das Skript Pop-up-Stores ein?',
    options: [
      'Als alternative Varianten bzw. Mischformen neben den klassischen Vertriebswegen',
      'Als Form des exklusiven Vertriebs',
      'Als Absatzmittler',
      'Als Instrument der Preispolitik',
    ],
    correctOptions: [0],
    explanation: 'Neben null- bis mehrstufigen Wegen existieren alternative Varianten und Mischformen wie Pop-up-Stores.',
    source: 'Kapitel 5.2, PDF S. 23', conceptIds: ['mc-vertriebsweglaenge'],
  },
  {
    id: 'qm5-43', chapterId: 'm5', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Was beschreibt das Shop-in-Shop-Prinzip?',
    options: [
      'Ein großer Verkaufsraum wird in mehrere separate Bereiche aufgeteilt, um Waren in passender Atmosphäre anzubieten.',
      'Kunden bestellen online und holen im Geschäft ab.',
      'Ein Händler betreibt mehrere Onlineshops.',
      'Zwei Unternehmen werben gemeinsam.',
    ],
    correctOptions: [0],
    explanation: 'Beispiel: möve-Shop-in-Shops bei Karstadt/Kaufhof. Option 2 = Click & Collect.',
    source: 'Kapitel 5.3, PDF S. 23', conceptIds: ['mc-shop-in-shop', 'mc-click-collect'],
  },
  {
    id: 'qm5-44', chapterId: 'm5', type: 'single_choice', goal: 'application', difficulty: 1,
    prompt: 'Eine Kundin bestellt einen Laptop online und holt ihn anschließend im Markt ab. Wie heißt dieses Prinzip?',
    options: ['Click & Collect', 'Shop-in-Shop', 'Retargeting', 'Reverse Pricing'],
    correctOptions: [0],
    explanation: 'Click & Collect: digital bestellen, Ware persönlich im Geschäft erhalten.',
    source: 'Kapitel 5.3, PDF S. 23', conceptIds: ['mc-click-collect'],
  },
  {
    id: 'qm5-45', chapterId: 'm5', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie die Ausprägung der Breite des Vertriebssystems ihrer Beschreibung zu.',
    pairs: [
      { left: 'Einkanalsystem', right: 'Nutzung lediglich eines bestimmten Vertriebswegs' },
      { left: 'Multichannel-Marketing', right: 'Auf mehreren Kanälen präsent, um Kundensegmente zu erreichen' },
      { left: 'Omnichannel-Marketing', right: 'Alle Kanäle nahtlos vernetzt – durchgängiges, widerspruchsfreies Erlebnis' },
    ],
    explanation: 'Breite nach Homburg (2017).',
    source: 'Kapitel 5.3, PDF S. 23', conceptIds: ['mc-einkanal', 'mc-multi-omni', 'mc-omnichannel', 'mc-breite'],
  },
  {
    id: 'qm5-46', chapterId: 'm5', type: 'single_choice', goal: 'application', difficulty: 2,
    prompt: 'möve nutzt Flagship- und Outlet-Stores, einen Onlineshop, Shop-in-Shops bei Karstadt/Kaufhof, europäische Fachhändler und möve Professional für Hotels und Friseure. Wofür steht dieses Skript-Beispiel?',
    options: ['Mehrkanalvertrieb (Multichannel-Marketing)', 'Einkanalsystem', 'Exklusiven Vertrieb', 'Disintermediation'],
    correctOptions: [0],
    explanation: 'Mehrere Vertriebskanäle, um verschiedene Kundensegmente zu erreichen.',
    source: 'Kapitel 5.3, PDF S. 23', conceptIds: ['mc-multi-omni'],
  },
  {
    id: 'qm5-47', chapterId: 'm5', type: 'multiple_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Welche Punkte nennt das Skript als Nachteile des indirekten Vertriebs? (Mehrfachauswahl)',
    options: ['Kein direktes Feedback vom Markt', 'Handelsmargen', 'Abhängigkeit von Vertriebspartnern', 'Hoher eigener Aufwand', 'Geringere Kontrollmöglichkeiten'],
    correctOptions: [0, 1, 2, 4],
    explanation: 'Hoher Aufwand ist ein Nachteil des DIREKTEN Vertriebs; indirekter Vertrieb bedeutet geringeren Aufwand.',
    source: 'Kapitel 5.2, PDF S. 22', conceptIds: ['mc-indirekt'],
  },
  {
    id: 'qm5-48', chapterId: 'm5', type: 'single_choice', goal: 'understanding', difficulty: 1,
    prompt: 'Je mehr Vertriebsorgane auf einer Stufe eingesetzt werden, desto …',
    options: ['intensiver ist der Vertrieb', 'exklusiver ist der Vertrieb', 'länger ist der Vertriebsweg', 'geringer ist der Distributionsgrad'],
    correctOptions: [0],
    explanation: 'Mehr Organe auf einer Stufe = breiterer Vertriebsweg = intensiverer Vertrieb. Die Länge hängt dagegen von der Zahl der Stufen ab.',
    source: 'Kapitel 5.3, PDF S. 23', conceptIds: ['mc-distributionsgrad', 'mc-vertriebsweglaenge'],
  },
  {
    id: 'qm5-49', chapterId: 'm5', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie den Einflussfaktor auf die Wahl des Vertriebssystems dem passenden Aspekt zu.',
    pairs: [
      { left: 'Produkt', right: 'Wie erklärungsbedürftig? Transport- und lagerfähig?' },
      { left: 'Unternehmen', right: 'Größe, Finanzkraft, Erfahrung, Marktstellung, Strategie' },
      { left: 'Kunden', right: 'Einkaufsverhalten' },
      { left: 'Absatzmittler', right: 'Vertragliche Bindung, Flexibilität, Standort, Image, Beeinflussbarkeit' },
      { left: 'Umfeld', right: 'Technologie, Gesetzgebung, soziokulturelle Veränderungen' },
    ],
    explanation: 'Dazu Markt (Marktposition und Wachstumsraten der Kanäle) und Konkurrenz (deren Vertriebsstrategie).',
    source: 'Kapitel 5.3, PDF S. 24', conceptIds: ['mc-einflussfaktoren-vertrieb'],
  },
  {
    id: 'qm5-50', chapterId: 'm5', type: 'single_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Wie sollte der Vertrieb laut Skript verstanden und geplant werden?',
    options: [
      'Als markenbildendes Element des Marketingmix, im Einklang mit den übrigen Marketingmaßnahmen',
      'Unabhängig von Preis- und Kommunikationspolitik',
      'Ausschließlich nach den Kosten',
      'Nur als logistische Aufgabe ohne Bezug zur Marke',
    ],
    correctOptions: [0],
    explanation: 'Der Vertrieb soll der Leistung angemessen sein, der Zielgruppe entgegenkommen und das Image unterstützen.',
    source: 'Kapitel 5.1 und 5.3, PDF S. 20 und 24', conceptIds: ['mc-vertrieb-einklang'],
  },
  {
    id: 'qm5-51', chapterId: 'm5', type: 'true_false', goal: 'understanding', difficulty: 3,
    prompt: 'Werden im direkten Vertrieb Absatzhelfer wie Vertriebsagenturen oder Logistikdienstleister eingeschaltet, sind diese wirtschaftlich unabhängig.',
    correctBool: false,
    explanation: 'Falsch – im direkten Vertrieb eingeschaltete Absatzhelfer sind laut Skript NICHT wirtschaftlich unabhängig. Unabhängige externe Organe mit wesentlicher akquisitorischer Funktion kennzeichnen den indirekten Vertrieb.',
    source: 'Kapitel 5.2, PDF S. 22', conceptIds: ['mc-direkt-indirekt', 'mc-vertriebsagentur'],
  },
  {
    id: 'qm5-52', chapterId: 'm5', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Was sind Vertriebsorgane?',
    options: [
      'Alle unternehmensinternen oder -externen Personen, Abteilungen oder Institutionen, die Vertriebsaktivitäten direkt durchführen oder unterstützen',
      'Nur die Verkäufer im Außendienst',
      'Ausschließlich externe Händler',
      'Die Lieferfahrzeuge eines Unternehmens',
    ],
    correctOptions: [0],
    explanation: 'Die vertikale Gestaltung betrachtet die Stufen möglicher Vertriebsorgane.',
    source: 'Kapitel 5.2, PDF S. 22', conceptIds: ['mc-vertriebsorgane', 'mc-vertikale-gestaltung'],
  },
];
