import { Question } from '@/lib/types';

/** Fragen Kapitel 1 – Grundlagen des Marketings (PDF S. 1–6). */
export const questions1: Question[] = [
  // ======================= bestehende Fragen (IDs unverändert) =======================
  {
    id: 'qm1-01', chapterId: 'm1', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Wovon leitet sich der Begriff „Marketing“ ab?',
    options: ['Vom englischen „(to) market“ – Markt und vermarkten', 'Von „management“ – führen', 'Von „to make“ – herstellen', 'Vom lateinischen „mercatus“ allein'],
    correctOptions: [0],
    explanation: 'Marketing kommt vom englischen „(to) market“ und bedeutet gleichzeitig Markt und vermarkten. Der Markt ist Ziel- und Bezugsobjekt des Marketings.',
    source: 'Kapitel 1.1, PDF S. 1', conceptIds: ['mc-marketing'],
  },
  {
    id: 'qm1-02', chapterId: 'm1', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Auf einem Käufermarkt gilt …',
    options: [
      'Das Angebot ist größer als die Nachfrage – die Nachfrage ist der Engpass, der Nachfrager steht im Zentrum.',
      'Die Nachfrage ist größer als das Angebot – der Anbieter steht im Zentrum.',
      'Angebot und Nachfrage sind stets exakt gleich.',
      'Die Ressourcen sind unbegrenzt vorhanden.',
    ],
    correctOptions: [0],
    explanation: 'Käufermarkt: mehr Angebot als Nachfrage, die Käufer entscheiden frei (z. B. über 500 Mineralwässer in Deutschland). Die Nachfrage bildet den Engpass; Marketing soll ihn bewältigen, Kunden gewinnen und binden.',
    source: 'Kapitel 1.1, PDF S. 1', conceptIds: ['mc-kaeufermarkt'],
  },
  {
    id: 'qm1-03', chapterId: 'm1', type: 'true_false', goal: 'fact', difficulty: 1,
    prompt: 'Das Gratifikationsprinzip besagt, dass die im Tausch gehandelten Ressourcen knapp sind.',
    correctBool: false,
    explanation: 'Falsch – das ist das Knappheitsprinzip. Das Gratifikationsprinzip besagt, dass der Austausch für beide Seiten vorteilhaft sein soll (Nachfrager- und Anbieternutzen maximieren).',
    source: 'Kapitel 1.1, PDF S. 1', conceptIds: ['mc-gratifikation', 'mc-knappheit'],
  },
  {
    id: 'qm1-04', chapterId: 'm1', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche gehören zu den vier Ps des Marketingmix? (Mehrfachauswahl)',
    options: ['Product', 'Price', 'People', 'Place', 'Promotion'],
    correctOptions: [0, 1, 3, 4],
    explanation: 'Die vier Ps: Product, Price, Place, Promotion. „People“ gehört zu den zusätzlichen Ps für Dienstleistungen (People, Processes, Physical Facilities).',
    source: 'Kapitel 1.1 und 1.3, PDF S. 3 und 6', conceptIds: ['mc-marketingmix', 'mc-dienstleistungs-ps'],
  },
  {
    id: 'qm1-05', chapterId: 'm1', type: 'cloze', goal: 'fact', difficulty: 2,
    prompt: 'Die drei Kernbausteine des Marketingbegriffs sind der ______ (systematischer Planungsprozess), der ______ (Leitphilosophie) und der aktivitätenorientierte Marketingbegriff (Sozialtechnologie).',
    clozeAnswers: [['funktionale', 'funktionaler', 'funktionale Marketingbegriff', 'funktional'], ['führungsorientierte', 'führungsorientierter', 'führungsorientierte Marketingbegriff', 'führungsorientiert']],
    explanation: 'Funktional = Grundfunktion/Abteilung (Planungsprozess); führungsorientiert = Leitphilosophie; aktivitätenorientiert = Sozialtechnologie/„Werkzeugkasten“ Marketingmix.',
    source: 'Kapitel 1.1, PDF S. 2–3', conceptIds: ['mc-kernbausteine', 'mc-funktional', 'mc-fuehrung', 'mc-aktivitaet'],
  },
  {
    id: 'qm1-06', chapterId: 'm1', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie die drei Rs ihrer Bedeutung zu.',
    pairs: [
      { left: 'Recruitment', right: 'Kundenakquise durch Dialog und Interaktion' },
      { left: 'Retention', right: 'Kundenbindung durch Erhöhung der Kundenzufriedenheit' },
      { left: 'Recovery', right: 'Rückgewinnung abgewanderter Kunden durch gezielte Maßnahmen (z. B. persönliche Gespräche)' },
    ],
    explanation: 'Die drei Rs strukturieren den Marketingmix zusätzlich nach der Phase der Geschäftsbeziehung.',
    source: 'Kapitel 1.1, PDF S. 3', conceptIds: ['mc-drei-rs', 'mc-beziehung'],
  },
  {
    id: 'qm1-07', chapterId: 'm1', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erklären Sie den Unterschied zwischen transaktionalem Marketing und Beziehungsmarketing.',
    rubric: [
      { point: 'Transaktional: klassische Marktbearbeitung mit den vier Ps, reaktiv, Fokus auf Geschäftsabschlüsse', keywords: ['geschäftsabschl', 'abschluss', 'transaktion', 'reaktiv', 'vier ps', '4 ps'] },
      { point: 'Beziehungsmarketing: Kundenbeziehung an sich im Mittelpunkt (aktive Analyse, Gestaltung, Kontrolle)', keywords: ['kundenbeziehung', 'beziehung', 'gestaltung', 'analyse'] },
      { point: 'Fristigkeit: kurzfristig vs. langfristig', keywords: ['kurzfristig', 'langfristig'] },
      { point: 'Ziele/Strategie: Akquisition + Leistungsdarstellung vs. Bindung/Rückgewinnung + Dialog', keywords: ['bindung', 'rückgewinn', 'dialog', 'leistungsdarstellung'], weight: 0.5 },
    ],
    modelAnswer: 'Transaktionales Marketing ist die klassische Marktbearbeitung mit den vier Ps: Das Unternehmen blickt nach außen und reagiert auf das Marktgeschehen, um Geschäftsabschlüsse zu tätigen (reaktiv, kurzfristig, Ziel Kundenakquisition, Strategie Leistungsdarstellung). Beim Beziehungsmarketing steht nicht die einzelne Transaktion, sondern die Kundenbeziehung im Mittelpunkt – sie wird aktiv analysiert, gestaltet und kontrolliert (langfristig, Objekt Produkt und Interaktion, Ziele Akquisition, Bindung und Rückgewinnung, Strategie Dialog, zusätzliche Erfolgsgrößen Kundenwert und Kundendeckungsbeitrag).',
    explanation: 'Kern: Einzeltransaktion vs. dauerhafte Beziehung; die Erkenntnis stammt aus Dienstleistung und B2B.',
    source: 'Kapitel 1.1, PDF S. 3', conceptIds: ['mc-transaktional', 'mc-beziehung'],
  },
  {
    id: 'qm1-08', chapterId: 'm1', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Ein Unternehmen bietet vergleichbare Produkte deutlich günstiger als die Konkurrenz an und nutzt dafür Kostendegressionseffekte. Welche Strategie liegt vor?',
    options: ['Kostenführerstrategie', 'Qualitätsführerschaft (Differenzierungsstrategie)', 'Strategie der selektiven Qualitätsführerschaft', 'Points-of-Difference-Strategie'],
    correctOptions: [0],
    explanation: 'Kostenführerstrategie: vergleichbare Produkte zu geringerem Preis, über Kostendegression (Standardisierung, Verfahrensinnovation, effiziente Vertriebswege), damit trotz niedriger Preise zufriedenstellende Gewinne entstehen.',
    source: 'Kapitel 1.2, PDF S. 5', conceptIds: ['mc-kostenfuehrer', 'mc-kostendegression'],
  },
  {
    id: 'qm1-09', chapterId: 'm1', type: 'cloze', goal: 'understanding', difficulty: 2,
    prompt: 'Innerhalb des Wettbewerbsrahmens sind ______ die Attribute, hinsichtlich derer sich die Marke mit dem Wettbewerb die Waage hält, und ______ die Attribute, die besser sind als die Angebote der Konkurrenz.',
    clozeAnswers: [['Points of Parity', 'Point of Parity', 'PoP'], ['Points of Difference', 'Point of Difference', 'PoD']],
    explanation: 'Points of Parity = gleichauf; Points of Difference = besser (Keller/Swaminathan 2019). Beispiel PoD: Fiji Water (Herkunft, angeblich besondere Reinheit).',
    source: 'Kapitel 1.2, PDF S. 4', conceptIds: ['mc-pop-pod', 'mc-positionierung'],
  },
  {
    id: 'qm1-10', chapterId: 'm1', type: 'assignment', goal: 'fact', difficulty: 2,
    prompt: 'Bringen Sie die sechs Schritte des Marketingmanagements in die richtige Reihenfolge.',
    pairs: [
      { left: 'Situationsanalyse', right: 'Schritt 1' },
      { left: 'Marketingziele', right: 'Schritt 2' },
      { left: 'Marketingstrategie', right: 'Schritt 3' },
      { left: 'Marketinginstrumente', right: 'Schritt 4' },
      { left: 'Marketingimplementierung', right: 'Schritt 5' },
      { left: 'Marketingcontrolling', right: 'Schritt 6' },
    ],
    explanation: 'Reihenfolge: Situationsanalyse → Marketingziele → Marketingstrategie → Marketinginstrumente → Marketingimplementierung → Marketingcontrolling.',
    source: 'Kapitel 1.3, PDF S. 5–6', conceptIds: ['mc-6schritte'],
  },
  {
    id: 'qm1-11', chapterId: 'm1', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein Start-up bringt ein teures, hochwertiges Mineralwasser auf einen Käufermarkt mit über 500 Anbietern und will nur eine kleine, zahlungskräftige Zielgruppe ansprechen. Welche Strategierichtung aus der Matrix passt? Begründen Sie und nennen Sie einen möglichen Point of Difference.',
    rubric: [
      { point: 'Strategie der selektiven Qualitätsführerschaft (Nische, besondere Leistung, hoher Preis)', keywords: ['selektive qualit', 'selektiv', 'nische', 'teilmarkt'] },
      { point: 'Begründung: lukrative Nische, von größeren Unternehmen vernachlässigt; kein Preiskampf auf dem Gesamtmarkt', keywords: ['nische', 'vernachlässig', 'hoher preis', 'hohem preis', 'teilmarkt', 'qualität'] },
      { point: 'Point of Difference: besser als die Konkurrenz (z. B. Herkunft, besondere Reinheit wie Fiji)', keywords: ['point of difference', 'herkunft', 'reinheit', 'besser als'] },
      { point: 'Bezug Käufermarkt/Abhebung vom Wettbewerb', keywords: ['käufermarkt', 'abheb', 'wettbewerb', 'konkurrenz'], weight: 0.5 },
    ],
    modelAnswer: 'Passend ist die Strategie der selektiven Qualitätsführerschaft: Das Start-up bietet in einer lukrativen Nische, die von größeren Unternehmen vernachlässigt wird, besondere Leistungen zu hohem Preis an – wie Voss oder Fiji. Auf einem Käufermarkt mit über 500 Anbietern muss es sich klar abheben; ein Point of Difference (Attribut, das besser ist als die Konkurrenz) könnte z. B. die Herkunft oder eine besondere Reinheit sein, die gezielt über die Promotionsstrategie kommuniziert wird.',
    explanation: 'Teilmarkt + Qualitätsvorteil = selektive Qualitätsführerschaft. Gesamtmarkt + Qualität wäre die (allgemeine) Qualitätsführerschaft wie Volvic/Evian.',
    source: 'Kapitel 1.2, PDF S. 4–5', conceptIds: ['mc-selektive-qf', 'mc-strategiematrix', 'mc-pop-pod', 'mc-kaeufermarkt'],
  },

  // ======================= neue offene Fragen (IU-Prüfungsstil) =======================
  {
    id: 'qm1-12', chapterId: 'm1', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erläutern Sie, warum der Markt im Marketing zugleich Ziel- und Bezugsobjekt ist, und erklären Sie die beiden zentralen theoretischen Leitideen der Marketingwissenschaft.',
    rubric: [
      { point: 'Zielobjekt: Märkte schaffen und beeinflussen', keywords: ['schaffen', 'beeinflussen', 'zielobjekt', 'ziel'] },
      { point: 'Bezugsobjekt: Märkte geben die Rahmenbedingungen für Austauschprozesse vor', keywords: ['rahmenbedingung', 'bezugsobjekt', 'austauschprozess'] },
      { point: 'Gratifikationsprinzip: Austausch für beide Seiten vorteilhaft', keywords: ['gratifikation', 'beide seiten', 'vorteilhaft', 'nutzen maximieren'] },
      { point: 'Knappheitsprinzip: gehandelte Ressourcen sind knapp', keywords: ['knappheit', 'knapp', 'nicht unbegrenzt'] },
    ],
    modelAnswer: 'Der Markt ist Zielobjekt, weil Marketing Märkte schaffen und beeinflussen will, und Bezugsobjekt, weil Märkte die Rahmenbedingungen für das effiziente und effektive Gestalten von Austauschprozessen vorgeben. Ein Austausch kommt zustande, wenn zwei Parteien etwas besitzen, das für die jeweils andere so nützlich ist, dass sie sich dafür vom eigenen Eigentum trennt. Daraus folgen zwei Leitideen: Das Gratifikationsprinzip (der Austausch soll für beide Seiten vorteilhaft sein – Nachfrager- und Anbieternutzen maximieren) und das Knappheitsprinzip (die getauschten Ressourcen sind knapp, also nicht unbegrenzt vorhanden).',
    explanation: 'Doppelrolle des Marktes + beide Leitideen sind ein klassischer Einstieg in die Grundlagen.',
    source: 'Kapitel 1.1, PDF S. 1', conceptIds: ['mc-markt', 'mc-austausch', 'mc-gratifikation', 'mc-knappheit'],
  },
  {
    id: 'qm1-13', chapterId: 'm1', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Beschreiben Sie die Entwicklung des Marketingverständnisses von der Verkaufsorientierung bis zur Nachhaltigkeitsorientierung und ordnen Sie jeder Phase den prägenden zeitlichen Einfluss zu.',
    rubric: [
      { point: 'Ab ca. 1900/1950er–60er: Verkaufsorientierung (handwerklich, AIDA, 4 Ps)', keywords: ['verkaufsorientierung', 'handwerklich', 'aida'] },
      { point: '1970er: Marktorientierung (Nachfragemacht des Handels)', keywords: ['marktorientierung', 'nachfragemacht', 'handel'] },
      { point: '1980er: Wettbewerbsorientierung (globaler Wettbewerb, Positionierung)', keywords: ['wettbewerbsorientierung', 'strategische positionierung', 'strategisierung'] },
      { point: '1990er: Umfeldorientierung (Deepening, Broadening)', keywords: ['umfeldorientierung', 'deepening', 'broadening'] },
      { point: '2000er: Beziehungsorientierung (digitale Netzwerke, Kundenbeziehung)', keywords: ['beziehungsorientierung', 'digitale netzwerke', 'kundenbeziehung'] },
      { point: '2010er/2020er: Netzwerk-/digitale Wertschöpfung und Nachhaltigkeitsorientierung', keywords: ['wertschöpfung', 'digital', 'nachhaltigkeitsorientierung', 'nachhaltigkeit'] },
    ],
    modelAnswer: 'Ab ca. 1900 werden Verkaufs- und Kommunikationstechniken systematisch erforscht (z. B. AIDA), in den 1950er/60ern entsteht der Marketingmix als „4 Ps“ – ein handwerkliches, auf ein absatzpolitisches Werkzeug verkürztes Verständnis (Verkaufsorientierung). In den 1970ern wird die Nachfragemacht des Handels berücksichtigt; Kundenbedürfnisse werden befriedigt, um ökonomische Ziele zu erreichen (Marktorientierung). In den 1980ern rückt durch globalen Wettbewerb die strategische Positionierung in den Vordergrund (Wettbewerbsorientierung). In den 1990ern werden soziale/ökologische Ansprüche wichtiger (Deepening) und auch Nonprofit-Organisationen nutzen Marketing (Broadening) – Umfeldorientierung. In den 2000ern beeinflussen digitale Netzwerke den Markt, die Kundenbeziehung steht im Mittelpunkt (Beziehungsorientierung). In den 2010ern entstehen digitale Wertschöpfungsmodelle wie Uber, Netflix, Spotify (Netzwerk- und digitale Wertschöpfungsorientierung), in den 2020ern werden Nachhaltigkeit und soziale Verantwortung zentral (Nachhaltigkeitsorientierung).',
    explanation: 'Pro Phase: Zeitraum + Einfluss + Orientierung. Die Reihenfolge ist prüfungsrelevant.',
    source: 'Kapitel 1.1, PDF S. 1–2', conceptIds: ['mc-evolution', 'mc-verkaufsorientierung', 'mc-marktorientierung', 'mc-wettbewerbsorientierung', 'mc-umfeldorientierung', 'mc-beziehungsorientierung', 'mc-digitale-wertschoepfung', 'mc-nachhaltigkeitsorientierung'],
  },
  {
    id: 'qm1-14', chapterId: 'm1', type: 'open', goal: 'distinction', difficulty: 2,
    prompt: 'Was versteht man unter „Deepening“ und „Broadening“ des Marketings? Ordnen Sie beide zeitlich und der passenden Orientierung zu.',
    rubric: [
      { point: 'Deepening: soziale/ökologische Ansprüche und Nachhaltigkeit werden wichtiger', keywords: ['sozial', 'ökologisch', 'nachhaltig'] },
      { point: 'Broadening: Marketing auch von nicht kommerziellen Organisationen angewendet', keywords: ['nicht kommerziell', 'nichtkommerziell', 'non-profit', 'nonprofit', 'organisation'] },
      { point: 'Zeitraum 1990er', keywords: ['1990', '90er'] },
      { point: 'Umfeldorientierung (modernes, erweitertes Verständnis)', keywords: ['umfeldorientierung', 'erweitert', 'modern'] },
    ],
    modelAnswer: 'Beide prägen die 1990er-Jahre: Beim Deepening werden soziale und ökologische Ansprüche sowie Nachhaltigkeit wichtiger, Marketing wird also inhaltlich vertieft. Beim Broadening wird der Marketinggedanke zunehmend auch von nicht kommerziellen Organisationen angewendet, Marketing wird also auf neue Anwender ausgeweitet. Sie gehören zum modernen und erweiterten Verständnis (zwei Parteien befriedigen ihre Bedürfnisse durch Austauschprozesse) – der Umfeldorientierung.',
    explanation: 'Deepening = tiefer (Werte), Broadening = breiter (neue Anwender).',
    source: 'Kapitel 1.1, PDF S. 2', conceptIds: ['mc-deepening', 'mc-broadening', 'mc-umfeldorientierung'],
  },
  {
    id: 'qm1-15', chapterId: 'm1', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Zerlegen Sie die Marketingdefinition der AMA (2017) in ihre Bestandteile und erläutern Sie mindestens vier davon.',
    rubric: [
      { point: 'organizational function: Managementfunktion mit systematischer Planung', keywords: ['managementfunktion', 'systematische planung', 'organizational function'] },
      { point: 'set of processes: funktionsübergreifende Prozesse', keywords: ['funktionsübergreifend', 'prozesse', 'set of processes'] },
      { point: 'creating/communicating/delivering: analytisch und aktionsorientiert, kreative Problemlösungen', keywords: ['aktionsorientiert', 'kreativ', 'problemlösung', 'aufeinanderfolgend'] },
      { point: 'value to customers: Kundennutzen im Fokus', keywords: ['kundennutzen', 'value', 'bedürfnisse'] },
      { point: 'customer relationships: Beziehungsorientierung', keywords: ['beziehungsorientierung', 'langfristige beziehung', 'relationship'] },
      { point: 'benefit the organization / stakeholders: Wert- und Stakeholderorientierung', keywords: ['wertorientierung', 'stakeholder', 'anspruchsgruppen'] },
    ],
    modelAnswer: '„Organizational function“: Marketing ist eine Managementfunktion, die sich mit systematischer Planung befasst. „Set of processes“: Marktinformationen sind für fast alle Funktionen relevant, daher nutzt Marketing funktionsübergreifende Prozesse. „Creating, communicating, delivering“: Marketing ist analytisch und aktionsorientiert, schafft kreative Problemlösungen und umfasst zeitlich aufeinanderfolgende Tätigkeiten. „Value to customers“: Der Kundennutzen steht im Fokus. „Managing customer relationships“: Langfristige Beziehungen sind ein wichtiges Ziel (Beziehungsorientierung). „Benefit the organization“: Marketing unterstützt den Unternehmenszweck, meist finanzielle Ziele (Wertorientierung). „And its stakeholders“: Auch Auswirkungen auf externe Anspruchsgruppen wie Bürger oder Umweltgruppen werden berücksichtigt (Stakeholderorientierung).',
    explanation: 'Sieben Bestandteile – für volle Punktzahl mindestens vier korrekt mit Bedeutung erläutern.',
    source: 'Kapitel 1.1, PDF S. 2', conceptIds: ['mc-ama-merkmale', 'mc-marketing', 'mc-kundennutzen', 'mc-wertorientierung', 'mc-stakeholderorientierung', 'mc-beziehungsorientierung'],
  },
  {
    id: 'qm1-16', chapterId: 'm1', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erläutern Sie die drei Kernbausteine des Marketingbegriffs.',
    rubric: [
      { point: 'Funktional: systematischer Planungsprozess, Grundfunktion/Abteilung gleichrangig mit Produktion/Finanzierung', keywords: ['funktional', 'abteilung', 'grundfunktion', 'planungsprozess'] },
      { point: 'Führungsorientiert: Leitphilosophie, alle Funktionen am Markt ausrichten', keywords: ['führungsorientiert', 'leitphilosophie', 'denkhaltung', 'am markt ausgerichtet', 'leitkonzept'] },
      { point: 'Aktivitätenorientiert: Sozialtechnologie, Werkzeugkasten Marketingmix, Nachfrage gezielt beeinflussen', keywords: ['aktivitätenorientiert', 'sozialtechnologie', 'werkzeugkasten', 'marketingmix', 'nachfrage'] },
    ],
    modelAnswer: 'Der funktionale Marketingbegriff versteht Marketing als systematischen Planungsprozess: eine betriebswirtschaftliche Grundfunktion bzw. Abteilung, gleichrangig mit Produktion oder Finanzierung, die Kompetenzen wie Marktforschung, Marketing-Automation oder Kundenbindung aufbaut. Der führungsorientierte Marketingbegriff sieht Marketing als Leitphilosophie der Unternehmensführung: Alle betrieblichen Funktionen werden am Markt ausgerichtet und alle marktrelevanten Ressourcen koordiniert zur Schaffung von Kundennutzen eingesetzt – jeder Mitarbeiter soll Kundenbedürfnisse berücksichtigen. Der aktivitätenorientierte Marketingbegriff (Sozialtechnologie) fokussiert die Aktivitäten des Marketingmix als „Werkzeugkasten“, um die Nachfragesituation gezielt zu beeinflussen.',
    explanation: 'Name + Klammerbegriff + Erklärung je Baustein.',
    source: 'Kapitel 1.1, PDF S. 2–3', conceptIds: ['mc-kernbausteine', 'mc-funktional', 'mc-fuehrung', 'mc-aktivitaet'],
  },
  {
    id: 'qm1-17', chapterId: 'm1', type: 'open', goal: 'distinction', difficulty: 3,
    prompt: 'Grenzen Sie Transaktionsmarketing und Beziehungsmarketing anhand von fünf Kriterien voneinander ab.',
    rubric: [
      { point: 'Fristigkeit: kurzfristig vs. langfristig', keywords: ['kurzfristig', 'langfristig', 'fristigkeit'] },
      { point: 'Marketingobjekt: Produkt vs. Produkt und Interaktion', keywords: ['interaktion', 'marketingobjekt'] },
      { point: 'Marketingziel: Akquisition vs. Akquisition, Bindung, Rückgewinnung', keywords: ['bindung', 'rückgewinnung', 'akquisition'] },
      { point: 'Marketingstrategie: Leistungsdarstellung vs. Dialog', keywords: ['leistungsdarstellung', 'dialog'] },
      { point: 'Erfolgsgrößen: Absatz/Umsatz/Gewinn vs. zusätzlich Kundenwert/Kundendeckungsbeitrag', keywords: ['kundenwert', 'kundendeckungsbeitrag', 'erfolgsgrößen', 'deckungsbeitrag'] },
    ],
    modelAnswer: '1) Betrachtungsfristigkeit: Transaktionsmarketing kurzfristig, Beziehungsmarketing langfristig. 2) Marketingobjekt: Produkt vs. Produkt und Interaktion. 3) Marketingziel: Kundenakquisition vs. Kundenakquisition, -bindung und -rückgewinnung. 4) Marketingstrategie: Leistungsdarstellung vs. Dialog. 5) Ökonomische Erfolgs- und Steuerungsgrößen: Absatz, Umsatz, Gewinn, Deckungsbeitrag, Kosten vs. zusätzlich Kundenwert und Kundendeckungsbeitrag.',
    explanation: 'Die fünf Kriterien stammen aus der Vergleichstabelle im Skript.',
    source: 'Kapitel 1.1, PDF S. 3', conceptIds: ['mc-transaktional', 'mc-beziehung'],
  },
  {
    id: 'qm1-18', chapterId: 'm1', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Eine inhabergeführte Autowerkstatt verliert Stammkunden an eine Werkstattkette. Zeigen Sie mithilfe der drei Rs, wie sie ihren Marketingmix nach der Phase der Geschäftsbeziehung ausrichten kann.',
    rubric: [
      { point: 'Recruitment: Neukundengewinnung durch Dialog und Interaktion', keywords: ['recruitment', 'akquis', 'neukund', 'dialog'] },
      { point: 'Retention: Bindung durch höhere Kundenzufriedenheit', keywords: ['retention', 'bindung', 'zufriedenheit'] },
      { point: 'Recovery: Rückgewinnung abgewanderter Kunden, z. B. persönliche Gespräche', keywords: ['recovery', 'rückgewinn', 'abgewandert', 'persönliche gespräch'] },
      { point: 'Bezug Beziehungsmarketing: vertrauensvolle Beziehung statt nur Preis/Qualität', keywords: ['beziehung', 'vertrau', 'langfristig'], weight: 0.5 },
    ],
    modelAnswer: 'Die Werkstatt sollte Beziehungsmarketing betreiben, denn Werkstätten werden laut Skript nicht nur nach Preis und Qualität, sondern wegen der über Jahre aufgebauten vertrauensvollen Beziehung gewählt. Recruitment: neue Kunden durch Dialog und Interaktion gewinnen. Retention: bestehende Kunden durch höhere Zufriedenheit binden. Recovery: abgewanderte Stammkunden durch gezielte Maßnahmen wie persönliche Gespräche zurückgewinnen.',
    explanation: 'Die drei Rs strukturieren den Mix nach der Phase der Geschäftsbeziehung: Gewinnen – Halten – Zurückholen.',
    source: 'Kapitel 1.1, PDF S. 3', conceptIds: ['mc-drei-rs', 'mc-beziehung', 'mc-akquise'],
  },
  {
    id: 'qm1-19', chapterId: 'm1', type: 'open', goal: 'distinction', difficulty: 2,
    prompt: 'Erklären Sie den Unterschied zwischen der juristischen Markendefinition und der Marketingsicht auf Marken.',
    rubric: [
      { point: 'Juristisch (AMA 2017): Name, Begriff, Design, Symbol oder Merkmal, das Angebote eines Verkäufers von anderen unterscheidet', keywords: ['name', 'symbol', 'design', 'unterscheid', 'kennzeich', 'juristisch'] },
      { point: 'Juristische Sicht für Marketingmanager wenig hilfreich', keywords: ['wenig hilfreich', 'nicht hilfreich'] },
      { point: 'Marketingsicht: Wirkung – Werte vermitteln, Beziehung aufbauen, höhere Zahlungsbereitschaft', keywords: ['wirkung', 'werte', 'beziehung', 'zahlungsbereitschaft'] },
      { point: 'Kapferer: langfristiges Engagement für einzigartige Werte, Abhebung', keywords: ['kapferer', 'engagement', 'stand out', 'abheb'], weight: 0.5 },
    ],
    modelAnswer: 'Juristisch (AMA 2017) ist eine Marke ein Name, Begriff, Design, Symbol oder sonstiges Merkmal, das die Ware oder Dienstleistung eines Verkäufers von denen anderer unterscheidet – für Marketingmanager wenig hilfreich. Die Marketingsicht fokussiert die Wirkung von Marken: Vermittlung von Werten, Aufbau einer Beziehung mit dem Kunden und daraus resultierende erhöhte Zahlungsbereitschaft. Kapferer beschreibt die Marke als Namen, der ein langfristiges Engagement für einzigartige Werte symbolisiert, die Organisation, Person oder Produkt abheben.',
    explanation: 'Kennzeichnung (juristisch) vs. Wirkung (Marketing).',
    source: 'Kapitel 1.2, PDF S. 3–4', conceptIds: ['mc-marke', 'mc-marke-marketing'],
  },
  {
    id: 'qm1-20', chapterId: 'm1', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Was versteht man unter Brand Equity, wie lässt sie sich messen und welche Voraussetzungen müssen nach Aaker (1991) erfüllt sein, damit eine Marke Marketingvorteile bringt?',
    rubric: [
      { point: 'Marken schaffen Werte und stellen selbst einen Wert dar', keywords: ['schaffen werte', 'selbst einen wert', 'markenwert', 'wert'] },
      { point: 'Messung indirekt (qualitative/quantitative Marktforschung)', keywords: ['indirekt', 'marktforschung'] },
      { point: 'Messung direkt (Experimente, holistische Methoden)', keywords: ['direkt', 'experiment', 'holistisch'] },
      { point: 'Aaker: Marke (er)kennen, positive Assoziationen, Treue, als hochwertig wahrnehmen', keywords: ['kennen', 'assoziation', 'treu', 'hochwertig'] },
    ],
    modelAnswer: 'Brand Equity ist der Wert der Marke: In der Literatur herrscht Einigkeit, dass Marken Werte schaffen und damit selbst einen Wert darstellen. Gemessen wird sie indirekt durch qualitative und quantitative Marktforschung oder direkt durch Experimente und spezielle holistische Methoden. Voraussetzung für Marketingvorteile ist nach Aaker, dass Konsumenten die Marke (er)kennen, mit positiven Assoziationen verbinden, ihr treu sind und sie als hochwertig wahrnehmen.',
    explanation: 'Definition + zwei Messansätze + vier Voraussetzungen.',
    source: 'Kapitel 1.2, PDF S. 4', conceptIds: ['mc-brandequity', 'mc-markenvoraussetzungen'],
  },
  {
    id: 'qm1-21', chapterId: 'm1', type: 'open', goal: 'fact', difficulty: 2,
    prompt: 'Nennen Sie mindestens sechs reale Marketingvorteile, die eine starke Marke einem Unternehmen bietet.',
    rubric: [
      { point: 'Bessere Wahrnehmung der Produktleistung / stärkere Kundentreue', keywords: ['wahrnehmung der produktleistung', 'produktleistung', 'kundentreue', 'treue'] },
      { point: 'Geringere Verwundbarkeit (Wettbewerberaktivitäten, Marketingkrisen)', keywords: ['verwundbar', 'krise'] },
      { point: 'Größere Margen / höhere Marktrendite', keywords: ['marge', 'marktrendite', 'rendite'] },
      { point: 'Unelastische Reaktion auf Preiserhöhungen, elastische auf Preissenkungen', keywords: ['unelastisch', 'elastisch', 'preiserhöhung', 'preissenkung'] },
      { point: 'Handelskooperationen, effektivere Kommunikation, Lizenz-/Markenerweiterungschancen, Personalbeschaffung', keywords: ['handelskooperation', 'lizenz', 'markenerweiterung', 'personal', 'effektivität der marketingkommunikation', 'kommunikation'] },
    ],
    modelAnswer: 'Verbesserte Wahrnehmung der Produktleistung, stärkere Kundentreue, geringere Verwundbarkeit durch Marketingaktivitäten der Wettbewerber und durch Marketingkrisen, größere Margen, unelastischere Kundenreaktionen auf Preiserhöhungen, elastischere Reaktionen auf Preissenkungen, steigende Handelskooperationen und Unterstützungsleistungen, höhere Effektivität der Marketingkommunikation, Lizenzierungs- und Markenerweiterungschancen, leichtere Personalbeschaffung und -bindung sowie eine höhere Marktrendite.',
    explanation: 'Das Skript nennt 13 Vorteile; Elastizitätsrichtung beachten (Erhöhung → unelastisch, Senkung → elastisch).',
    source: 'Kapitel 1.2, PDF S. 4', conceptIds: ['mc-markenvorteile', 'mc-brandequity'],
  },
  {
    id: 'qm1-22', chapterId: 'm1', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein bekannter Markenhersteller setzt über Monate fast ausschließlich auf Preisreduktionen, um kurzfristig mehr zu verkaufen. Beurteilen Sie dieses Vorgehen aus Sicht der Markenführung.',
    rubric: [
      { point: 'Starke Marken entstehen durch einen konsistenten Marketingmix; jede Taktik ist markenbildend', keywords: ['konsistent', 'markenbildend', 'marketingmix'] },
      { point: 'Überbetonung kurzfristiger verkaufsfördernder Maßnahmen lässt die Marke an Wert verlieren', keywords: ['wert verlier', 'markenwert', 'schaden', 'verliert'] },
      { point: 'Gefährdet Markenvorteile (z. B. Margen, unelastische Reaktion auf Preiserhöhungen, Image)', keywords: ['marge', 'unelastisch', 'image', 'zahlungsbereitschaft', 'hochwertig'], weight: 0.5 },
    ],
    modelAnswer: 'Kritisch: Laut Skript werden starke Marken durch einen konsistenten Marketingmix aufgebaut – jede Taktik ist eine markenbildende Aktivität. Werden kurzfristige verkaufsfördernde Maßnahmen wie Preisreduktionen überbetont, kann die Marke an Wert verlieren. Damit gefährdet der Hersteller typische Markenvorteile wie größere Margen und die unelastische Reaktion der Kunden auf Preiserhöhungen; die Marke wird womöglich nicht mehr als hochwertig wahrgenommen.',
    explanation: 'Verknüpft Brand Equity mit der Warnung vor überbetonter Verkaufsförderung.',
    source: 'Kapitel 1.2, PDF S. 4', conceptIds: ['mc-konsistenter-mix', 'mc-markenvorteile', 'mc-brandequity'],
  },
  {
    id: 'qm1-23', chapterId: 'm1', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Erläutern Sie, wie eine Marke positioniert wird. Gehen Sie auf die vier Fragen nach Kapferer, die zwei Schritte der Positionierung sowie auf Points of Parity und Points of Difference ein.',
    rubric: [
      { point: 'Definition: bestimmen, wie die Marke im Vergleich zu Wettbewerbsangeboten wahrgenommen werden soll; Kern jeder Marketingstrategie', keywords: ['wahrgenommen', 'vergleich', 'kern jeder marketingstrategie', 'wettbewerbsangebot'] },
      { point: 'Vier Fragen: Zielgruppe, Wettbewerber, Wettbewerbsvorteil, wodurch konkret', keywords: ['zielgruppe', 'wettbewerber', 'wettbewerbsvorteil', 'konkret'] },
      { point: 'Zwei Schritte: relevante Wettbewerber ermitteln, Wettbewerbsvorteil bestimmen', keywords: ['relevante wettbewerber', 'ermittlung', 'bestimmung des wettbewerbsvorteil', 'zwei schritte'] },
      { point: 'Points of Parity (gleichauf) und Points of Difference (besser)', keywords: ['points of parity', 'points of difference', 'waage', 'besser'] },
    ],
    modelAnswer: 'Positionieren heißt zu bestimmen, wie die Marke von den Konsumenten im Vergleich zu Wettbewerbsangeboten wahrgenommen werden soll – der Kern jeder Marketingstrategie. Kapferer stellt vier Fragen: Wer ist unsere Zielgruppe? Wer sind unsere Wettbewerber? Was ist unser Wettbewerbsvorteil? Wodurch erzielen wir diesen konkret? Die Positionierung erfolgt in zwei Schritten: (1) relevante Wettbewerber ermitteln (gleiche Zielgruppe, vergleichbare Angebote; direkt und indirekt), (2) Wettbewerbsvorteil bestimmen. Innerhalb des Wettbewerbsrahmens legt man Points of Parity (Attribute, bei denen man gleichauf ist) und Points of Difference (Attribute, die besser sind als die Konkurrenz, z. B. Fiji Water: Herkunft, Reinheit) fest.',
    explanation: 'Umfassende Positionierungsfrage – alle vier Elemente abdecken.',
    source: 'Kapitel 1.2, PDF S. 4', conceptIds: ['mc-positionierung', 'mc-positionierungsfragen', 'mc-relevante-wettbewerber', 'mc-pop-pod'],
  },
  {
    id: 'qm1-24', chapterId: 'm1', type: 'open', goal: 'distinction', difficulty: 2,
    prompt: 'Was sind relevante Wettbewerber? Grenzen Sie dabei direkten von indirektem Wettbewerb ab und nennen Sie das Beispiel aus dem Skript.',
    rubric: [
      { point: 'Relevante Wettbewerber: gleiche Zielgruppe mit vergleichbaren Angeboten', keywords: ['gleiche zielgruppe', 'vergleichbar', 'zielgruppe'] },
      { point: 'Indirekter Wettbewerb: unterschiedliche Produkte, die gleiche Bedürfnisse erfüllen', keywords: ['unterschiedliche produkte', 'gleichen bedürfnisse', 'gleiche bedürfnisse', 'indirekt'] },
      { point: 'Direkter Wettbewerb: gleichartige Produkte', keywords: ['direkt'] },
      { point: 'Beispiel Gerolsteiner Naturell: stille Wasser direkt, Sprudel/andere Getränke indirekt', keywords: ['gerolsteiner', 'stille wasser', 'still', 'sprudel'] },
    ],
    modelAnswer: 'Relevante Wettbewerber sind Konkurrenten, die die gleiche Zielgruppe mit vergleichbaren Angeboten bedienen; dazu zählen direkte und indirekte Wettbewerber. Indirekter Wettbewerb besteht zwischen unterschiedlichen Produkten, die jedoch die gleichen Bedürfnisse erfüllen. Beispiel: Für Gerolsteiner Naturell (stilles Wasser) sind andere stille Wasser direkte Wettbewerber, sprudelnde Wasser und andere Getränke indirekte Wettbewerber.',
    explanation: 'Gleiches Bedürfnis, anderes Produkt = indirekt.',
    source: 'Kapitel 1.2, PDF S. 4', conceptIds: ['mc-relevante-wettbewerber', 'mc-indirekter-wettbewerb'],
  },
  {
    id: 'qm1-25', chapterId: 'm1', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Erläutern Sie die Matrix der vier Strategierichtungen und nennen Sie zu jeder Strategie ein Beispiel aus dem Skript.',
    rubric: [
      { point: 'Achsen: Marktabdeckung (gesamt/teil) × zentraler Vorteil (Qualität/Preis)', keywords: ['marktabdeckung', 'gesamt', 'teil', 'vorteil'] },
      { point: 'Qualitätsführerschaft (Gesamtmarkt, Leistungsvorteile) – Volvic, Evian', keywords: ['volvic', 'evian'] },
      { point: 'Selektive Qualitätsführerschaft (Nische, hoher Preis) – Voss, Fiji', keywords: ['voss', 'fiji', 'selektive qualit'] },
      { point: 'Aggressive Kostenführerschaft (Gesamtmarkt, niedrige Preise) – Frische Brise, Handelsmarken', keywords: ['aggressiv', 'frische brise', 'handelsmarke'] },
      { point: 'Selektive Kostenführerschaft (Teilmarkt günstig) – regionale Mineralwassermarken', keywords: ['selektive kosten', 'regional'] },
    ],
    modelAnswer: 'Weil es in gesättigten Märkten nur wenige Nischen gibt, wird die Nischenstrategie in die Dualität Kosten- vs. Qualitätsführerschaft einbezogen. Daraus entsteht eine Matrix aus Marktabdeckung (Gesamt- oder Teilmarkt) und zentralem Vorteil (Qualität oder Preis): Qualitätsführerschaft realisiert Leistungsvorteile (Qualität, Service) auf dem Gesamtmarkt (Volvic, Evian). Selektive Qualitätsführerschaft bietet in einer von Großen vernachlässigten, lukrativen Nische besondere Leistungen zu hohem Preis (Voss, Fiji). Aggressive Kostenführerschaft bietet niedrige Preise auf dem Gesamtmarkt (Frische Brise, Handelsmarken). Selektive Kostenführerschaft ist auf einem Teilmarkt besonders günstig (günstige regionale Mineralwassermarken).',
    explanation: 'Achsen + vier Felder + Beispiele = volle Punktzahl.',
    source: 'Kapitel 1.2, PDF S. 5', conceptIds: ['mc-strategiematrix', 'mc-qualitaetsfuehrer', 'mc-selektive-qf', 'mc-aggressive-kf', 'mc-selektive-kf', 'mc-nische'],
  },
  {
    id: 'qm1-26', chapterId: 'm1', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Eine kleine Brauerei verkauft ihr Mineralwasser ausschließlich in ihrer Region zu sehr niedrigen Preisen. Ein Konzern vertreibt bundesweit ein Discount-Wasser zum Tiefstpreis. Ordnen Sie beide Unternehmen in die Strategiematrix ein und begründen Sie den Unterschied.',
    rubric: [
      { point: 'Brauerei: Strategie der selektiven Kostenführerschaft (Teilmarkt, günstig)', keywords: ['selektive kostenführer', 'selektiv'] },
      { point: 'Konzern: Strategie der aggressiven Kostenführerschaft (Gesamtmarkt, niedrige Preise)', keywords: ['aggressive kostenführer', 'aggressiv'] },
      { point: 'Unterschied liegt in der Marktabdeckung (Teil- vs. Gesamtmarkt), Vorteil jeweils Preis', keywords: ['marktabdeckung', 'teilmarkt', 'gesamtmarkt', 'region'] },
    ],
    modelAnswer: 'Beide haben den zentralen Vorteil Preis. Die Brauerei ist nur auf einem Teilmarkt (Region) besonders günstig – Strategie der selektiven Kostenführerschaft (wie günstige regionale Mineralwassermarken). Der Konzern bietet niedrige Preise auf dem Gesamtmarkt – Strategie der aggressiven Kostenführerschaft (wie Handelsmarken). Der Unterschied liegt also in der Marktabdeckung.',
    explanation: 'Gleicher Vorteil, unterschiedliche Marktabdeckung → unterschiedliche Felder der Matrix.',
    source: 'Kapitel 1.2, PDF S. 5', conceptIds: ['mc-selektive-kf', 'mc-aggressive-kf', 'mc-strategiematrix'],
  },
  {
    id: 'qm1-27', chapterId: 'm1', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erklären Sie den Begriff Kostendegression und erläutern Sie, wie die Kostenführerstrategie diesen Effekt nutzt.',
    rubric: [
      { point: 'Stückkosten sinken mit jeder zusätzlich produzierten Einheit', keywords: ['stückkosten', 'sinken', 'zusätzlich produziert', 'einheit'] },
      { point: 'Kostenführer: vergleichbare Produkte zu geringerem Preis', keywords: ['geringerem preis', 'günstiger', 'billiger', 'vergleichbare produkte'] },
      { point: 'Quellen: Standardisierung, Verfahrensinnovation, effiziente Vertriebswege', keywords: ['standardisierung', 'verfahrensinnovation', 'vertriebswege'] },
      { point: 'Ziel: trotz niedriger Preise zufriedenstellende Gewinne', keywords: ['gewinn'] },
    ],
    modelAnswer: 'Kostendegression bedeutet, dass die Stückkosten eines Guts mit jeder zusätzlich produzierten Einheit sinken. Die Kostenführerstrategie bietet vergleichbare Produkte zu einem geringeren Preis an und nutzt dafür Kostendegressionseffekte – etwa durch Standardisierung, Verfahrensinnovation und effiziente Vertriebswege –, damit trotz niedriger Preise zufriedenstellende Gewinne entstehen.',
    explanation: 'Begriff + Verbindung zur Strategie.',
    source: 'Kapitel 1.2, PDF S. 5', conceptIds: ['mc-kostendegression', 'mc-kostenfuehrer'],
  },
  {
    id: 'qm1-28', chapterId: 'm1', type: 'open', goal: 'fact', difficulty: 2,
    prompt: 'Definieren Sie Marketingmanagement und nennen Sie die vier zentralen Orientierungspunkte sowie das Ziel des Marketingmanagements.',
    rubric: [
      { point: 'Umsetzung/Durchführung des modernen, erweiterten Marketingverständnisses in einem Unternehmen', keywords: ['umsetzung', 'durchführung', 'erweitert', 'konkreten unternehmen'] },
      { point: 'Orientierungspunkte: Unternehmen, Kunde, Wettbewerber, gesellschaftliches Umfeld', keywords: ['kunde', 'wettbewerber', 'gesellschaftliche', 'umfeld', 'unternehmen'] },
      { point: 'Ziel: Kundenbedürfnisse besser erfüllen als die Konkurrenz (aus Ressourcen + Umfeld)', keywords: ['besser', 'konkurrenz', 'ressourcen', 'bedürfnisse'] },
    ],
    modelAnswer: 'Marketingmanagement ist die Umsetzung und Durchführung des modernen, erweiterten Marketingverständnisses in einem konkreten Unternehmen (AMA: Ziele setzen, Aktivitäten planen und ausführen, Fortschritt messen). Es berücksichtigt vier Orientierungspunkte: das Unternehmen selbst, den Kunden, die Wettbewerber und das gesellschaftliche Umfeld. Ziel ist, aus Unternehmensressourcen und Umfeldgegebenheiten Aktivitäten abzuleiten, die die Kundenbedürfnisse besser erfüllen als die Konkurrenz.',
    explanation: 'Definition + vier Orientierungspunkte + Ziel.',
    source: 'Kapitel 1.3, PDF S. 5', conceptIds: ['mc-marketingmanagement'],
  },
  {
    id: 'qm1-29', chapterId: 'm1', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein Getränkehersteller möchte ein neues stilles Wasser speziell für Jugendliche einführen. Beschreiben Sie, was er in jedem der sechs Schritte des Marketingmanagements konkret tun sollte.',
    rubric: [
      { point: 'Situationsanalyse: Markt, Trends, Kunden, Wettbewerber analysieren (Lücke für Teenager)', keywords: ['situationsanalyse', 'analys', 'trends', 'wettbewerber'] },
      { point: 'Marketingziele: z. B. Marktanteil, Image, Zufriedenheit', keywords: ['marktanteil', 'ziel', 'image'] },
      { point: 'Marketingstrategie: Zielgruppe/Segment, Marktbearbeitung, Positionierung (z. B. „cool“, etwas teurer)', keywords: ['strategie', 'zielgruppe', 'segment', 'marktbearbeitung'] },
      { point: 'Marketinginstrumente: konkrete 4 Ps (Flasche, Preis, Vertriebswege, Social Media/Influencer)', keywords: ['instrumente', 'produkt', 'preis', 'distribution', 'promotion', 'social media', 'influencer'] },
      { point: 'Implementierung (Launch, Verantwortlichkeiten, Budgets) und Controlling (Zielerreichung prüfen, anpassen)', keywords: ['implementierung', 'launch', 'budget', 'controlling', 'zielerreichung', 'evaluation'] },
    ],
    modelAnswer: '1) Situationsanalyse: Getränkemarkt, Trends, Kundenverhalten und Wettbewerber analysieren – z. B. feststellen, dass es kaum Mineralwasser speziell für Teenager gibt. 2) Marketingziele: etwa 0,5 % Marktanteil, dazu psychografische Ziele wie Image. 3) Marketingstrategie: selektiv-differenzierte Marktbearbeitung, Zielgruppe Jugendliche 12–19 Jahre, Produkt soll als „cool“ gelten und etwas teurer sein. 4) Marketinginstrumente: Produkt (z. B. 0,75-l-Flasche, auffällige Farbe, Einzel- und 6er-Packung), Preis (z. B. 0,89 € / 4,99 €), Distribution (Supermärkte, Drogerien, Onlineshop, Schulen, Imbiss, Veranstaltungen), Promotion (Instagram/TikTok, Influencer). 5) Implementierung: Launch durch die zuständige Marketingabteilung mit Verantwortlichkeiten und Budgets. 6) Controlling: prüfen, ob das Marktanteilsziel erreicht wurde, und Maßnahmen ggf. anpassen.',
    explanation: 'Angelehnt an das Fallbeispiel „Sitt“/„isso“ im Skript.',
    source: 'Kapitel 1.3, PDF S. 5–6', conceptIds: ['mc-6schritte', 'mc-situationsanalyse', 'mc-marketingziele', 'mc-marketingstrategie', 'mc-marketinginstrumente', 'mc-implementierung', 'mc-controlling'],
  },
  {
    id: 'qm1-30', chapterId: 'm1', type: 'open', goal: 'fact', difficulty: 2,
    prompt: 'Welche Arten von Marketingzielen unterscheidet das Skript? Nennen Sie jeweils Beispiele.',
    rubric: [
      { point: 'Ökonomische Ziele: Rendite, Gewinn, Umsatz, Deckungsbeitrag', keywords: ['ökonomisch', 'rendite', 'gewinn', 'umsatz', 'deckungsbeitrag'] },
      { point: 'Psychografische Ziele: Kundenzufriedenheit, Image', keywords: ['psychografisch', 'zufriedenheit', 'image'] },
      { point: 'Soziale Ziele', keywords: ['sozial'] },
      { point: 'Umweltziele', keywords: ['umwelt'] },
    ],
    modelAnswer: 'Ökonomische Ziele (Rendite, Gewinn, Umsatz, Deckungsbeitrag), psychografische Ziele (Kundenzufriedenheit, Image), soziale Ziele und Umweltziele. Beispiel aus dem Skript: Für das Wasser „isso“ wird ein Marktanteil von 0,5 % angestrebt.',
    explanation: 'Vier Zielkategorien (Schritt 2 des Marketingmanagements).',
    source: 'Kapitel 1.3, PDF S. 6', conceptIds: ['mc-marketingziele'],
  },
  {
    id: 'qm1-31', chapterId: 'm1', type: 'open', goal: 'fact', difficulty: 1,
    prompt: 'Für Dienstleistungen wird der Marketingmix um drei Ps erweitert. Nennen und erklären Sie diese.',
    rubric: [
      { point: 'People: Dienstleistungspersonal', keywords: ['people', 'personal'] },
      { point: 'Processes: Dienstleistungserstellungsprozess', keywords: ['processes', 'prozess', 'erstellung'] },
      { point: 'Physical Facilities: physisch fassbare Leistungspotenziale, Räumlichkeiten', keywords: ['physical', 'räumlichkeit', 'physisch', 'fassbar'] },
    ],
    modelAnswer: 'People (das Dienstleistungspersonal), Processes (der Dienstleistungserstellungsprozess) und Physical Facilities (physisch fassbare Leistungspotenziale wie Räumlichkeiten).',
    explanation: 'Ergänzen die vier Ps im Schritt „Marketinginstrumente“.',
    source: 'Kapitel 1.3, PDF S. 6', conceptIds: ['mc-dienstleistungs-ps', 'mc-marketinginstrumente'],
  },

  // ======================= neue geschlossene Fragen =======================
  {
    id: 'qm1-32', chapterId: 'm1', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Welche Orientierung kennzeichnet das Marketingverständnis der 1980er-Jahre?',
    options: ['Wettbewerbsorientierung', 'Marktorientierung', 'Umfeldorientierung', 'Beziehungsorientierung'],
    correctOptions: [0],
    explanation: '1980er: verstärkter, auch globaler Wettbewerb – strategische Positionierung (Strategisierung) – langfristiges strategisches Verständnis = Wettbewerbsorientierung.',
    source: 'Kapitel 1.1, PDF S. 1', conceptIds: ['mc-wettbewerbsorientierung', 'mc-evolution'],
  },
  {
    id: 'qm1-33', chapterId: 'm1', type: 'assignment', goal: 'fact', difficulty: 2,
    prompt: 'Ordnen Sie dem Zeitraum die jeweilige Orientierung des Marketingverständnisses zu.',
    pairs: [
      { left: '1970er', right: 'Marktorientierung' },
      { left: '1980er', right: 'Wettbewerbsorientierung' },
      { left: '1990er', right: 'Umfeldorientierung' },
      { left: '2000er', right: 'Beziehungsorientierung' },
      { left: '2010er', right: 'Netzwerk- und digitale Wertschöpfungsorientierung' },
      { left: '2020er', right: 'Nachhaltigkeitsorientierung' },
    ],
    explanation: 'Davor (ab ca. 1900 und 1950er/60er): Verkaufsorientierung.',
    source: 'Kapitel 1.1, PDF S. 1–2', conceptIds: ['mc-evolution'],
  },
  {
    id: 'qm1-34', chapterId: 'm1', type: 'true_false', goal: 'fact', difficulty: 1,
    prompt: 'Der Begriff Marketing löste in den 1960er-Jahren in Deutschland den Begriff Absatzwirtschaft ab; dies markiert einen Paradigmenwechsel von Angebot zu Nachfrage.',
    correctBool: true,
    explanation: 'Richtig. Der Begriff entstand Anfang des 20. Jahrhunderts im angloamerikanischen Raum; der Übergang steht für den Wechsel vom Abverkauf produzierter Ware zur Orientierung am Kunden.',
    source: 'Kapitel 1.1, PDF S. 1', conceptIds: ['mc-absatzwirtschaft'],
  },
  {
    id: 'qm1-35', chapterId: 'm1', type: 'cloze', goal: 'fact', difficulty: 1,
    prompt: 'Das AIDA-Modell steht für Attention – ______ – Desire – ______.',
    clozeAnswers: [['Interest'], ['Action']],
    explanation: 'AIDA = Attention, Interest, Desire, Action – Beispiel für die ab ca. 1900 systematisch erforschten Verkaufs- und Kommunikationstechniken.',
    source: 'Kapitel 1.1, PDF S. 1', conceptIds: ['mc-aida', 'mc-verkaufsorientierung'],
  },
  {
    id: 'qm1-36', chapterId: 'm1', type: 'single_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Wofür steht der Bestandteil „in ways that benefit the organization“ der AMA-Definition?',
    options: [
      'Wertorientierung: Marketing unterstützt den Unternehmenszweck, meist finanzielle Ziele',
      'Stakeholderorientierung: Rücksicht auf externe Anspruchsgruppen',
      'Beziehungsorientierung: langfristige Kundenbeziehungen',
      'Managementfunktion mit systematischer Planung',
    ],
    correctOptions: [0],
    explanation: 'Wertorientierung: meist finanzielle Ziele (Umsatz, Gewinn, Rendite), auch nicht kommerzielle Ziele (Mitgliederzahl, Aufmerksamkeit) sind möglich.',
    source: 'Kapitel 1.1, PDF S. 2', conceptIds: ['mc-wertorientierung', 'mc-ama-merkmale'],
  },
  {
    id: 'qm1-37', chapterId: 'm1', type: 'cloze', goal: 'fact', difficulty: 1,
    prompt: 'Der Kundennutzen (auch ______ genannt) ist die Differenz von ______ und erhaltenem Wert aus Sicht des Kunden.',
    clozeAnswers: [['Nettonutzen'], ['Aufwand']],
    explanation: 'Kundennutzen = Nettonutzen = erhaltener Wert minus Aufwand aus Kundensicht.',
    source: 'Kapitel 1.1, PDF S. 2', conceptIds: ['mc-kundennutzen'],
  },
  {
    id: 'qm1-38', chapterId: 'm1', type: 'single_choice', goal: 'application', difficulty: 1,
    prompt: 'Ein Onlineshop verschickt nach jedem Kauf automatisch eine personalisierte E-Mail-Serie. Wie nennt man solche softwaregesteuerten Abläufe?',
    options: ['Marketing-Automation', 'Product Placement', 'Verbundwerbung', 'Marketingcontrolling'],
    correctOptions: [0],
    explanation: 'Marketing-Automation: automatisierte Abläufe zur Kundenansprache, gesteuert über Software – z. B. automatische E-Mail-Kampagnen nach einem Kauf.',
    source: 'Kapitel 1.1, PDF S. 3', conceptIds: ['mc-marketing-automation'],
  },
  {
    id: 'qm1-39', chapterId: 'm1', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie die Ausprägung dem Transaktions- oder dem Beziehungsmarketing zu.',
    pairs: [
      { left: 'Marketingstrategie: Dialog', right: 'Beziehungsmarketing' },
      { left: 'Marketingstrategie: Leistungsdarstellung', right: 'Transaktionsmarketing' },
      { left: 'Marketingobjekt: Produkt und Interaktion', right: 'Beziehungsmarketing' },
      { left: 'Betrachtungsfristigkeit: kurzfristig', right: 'Transaktionsmarketing' },
      { left: 'Erfolgsgrößen zusätzlich Kundenwert und Kundendeckungsbeitrag', right: 'Beziehungsmarketing' },
    ],
    explanation: 'Beziehungsmarketing: langfristig, Produkt + Interaktion, Akquisition/Bindung/Rückgewinnung, Dialog, zusätzlich Kundenwert. Transaktionsmarketing: kurzfristig, Produkt, Akquisition, Leistungsdarstellung, Absatz/Umsatz/Gewinn.',
    source: 'Kapitel 1.1, PDF S. 3', conceptIds: ['mc-transaktional', 'mc-beziehung'],
  },
  {
    id: 'qm1-40', chapterId: 'm1', type: 'multiple_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Welche Aussagen zur Positionierung treffen laut Skript zu? (Mehrfachauswahl)',
    options: [
      'Sie bestimmt, wie eine Marke im Vergleich zu Wettbewerbsangeboten wahrgenommen werden soll.',
      'Sie ist der Kern jeder Marketingstrategie.',
      'Sie erfolgt typischerweise in zwei Schritten: relevante Wettbewerber ermitteln, Wettbewerbsvorteil bestimmen.',
      'Relevante Wettbewerber sind nur Anbieter identischer Produkte.',
      'Points of Parity sind Attribute, die besser sind als die Konkurrenz.',
    ],
    correctOptions: [0, 1, 2],
    explanation: 'Relevante Wettbewerber umfassen direkten UND indirekten Wettbewerb. Besser als die Konkurrenz = Points of Difference; Points of Parity = gleichauf.',
    source: 'Kapitel 1.2, PDF S. 4', conceptIds: ['mc-positionierung', 'mc-relevante-wettbewerber', 'mc-pop-pod'],
  },
  {
    id: 'qm1-41', chapterId: 'm1', type: 'single_choice', goal: 'fact', difficulty: 2,
    prompt: 'Wie kann Brand Equity laut Skript gemessen werden?',
    options: [
      'Indirekt durch qualitative und quantitative Marktforschung oder direkt durch Experimente und holistische Methoden',
      'Ausschließlich über den Börsenwert des Unternehmens',
      'Nur über die Zahl der Werbekontakte',
      'Gar nicht – Brand Equity ist nicht messbar',
    ],
    correctOptions: [0],
    explanation: 'Zwei Wege: indirekt (Marktforschung) oder direkt (Experimente, spezielle holistische Methoden).',
    source: 'Kapitel 1.2, PDF S. 4', conceptIds: ['mc-brandequity'],
  },
  {
    id: 'qm1-42', chapterId: 'm1', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche der folgenden Punkte zählen laut Skript zu den realen Marketingvorteilen starker Marken? (Mehrfachauswahl)',
    options: [
      'Unelastischere Kundenreaktionen auf Preiserhöhungen',
      'Elastischere Kundenreaktionen auf Preiserhöhungen',
      'Leichtere Personalbeschaffung und -bindung',
      'Geringere Verwundbarkeit durch Marketingkrisen',
      'Größere Margen',
    ],
    correctOptions: [0, 2, 3, 4],
    explanation: 'Bei Preiserhöhungen reagieren Kunden starker Marken UNelastisch (sie bleiben); elastischer reagieren sie bei Preissenkungen.',
    source: 'Kapitel 1.2, PDF S. 4', conceptIds: ['mc-markenvorteile'],
  },
  {
    id: 'qm1-43', chapterId: 'm1', type: 'true_false', goal: 'fact', difficulty: 1,
    prompt: 'Indirekter Wettbewerb liegt vor, wenn unterschiedliche Produkte die gleichen Bedürfnisse erfüllen.',
    correctBool: true,
    explanation: 'Richtig – z. B. sind für Gerolsteiner Naturell sprudelnde Wasser und andere Getränke indirekte Wettbewerber.',
    source: 'Kapitel 1.2, PDF S. 4', conceptIds: ['mc-indirekter-wettbewerb'],
  },
  {
    id: 'qm1-44', chapterId: 'm1', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie die Strategie aus der Matrix dem Beispiel aus dem Skript zu.',
    pairs: [
      { left: 'Strategie der Qualitätsführerschaft', right: 'Volvic, Evian' },
      { left: 'Strategie der selektiven Qualitätsführerschaft', right: 'Voss, Fiji' },
      { left: 'Strategie der aggressiven Kostenführerschaft', right: 'Frische Brise, Handelsmarken' },
      { left: 'Strategie der selektiven Kostenführerschaft', right: 'Günstige regionale Mineralwassermarken' },
    ],
    explanation: 'Gesamtmarkt/Qualität · Teilmarkt/Qualität · Gesamtmarkt/Preis · Teilmarkt/Preis.',
    source: 'Kapitel 1.2, PDF S. 5', conceptIds: ['mc-strategiematrix', 'mc-qualitaetsfuehrer', 'mc-selektive-qf', 'mc-aggressive-kf', 'mc-selektive-kf'],
  },
  {
    id: 'qm1-45', chapterId: 'm1', type: 'single_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Warum wird die Nischenstrategie in die Dualität Kosten- vs. Qualitätsführerschaft einbezogen?',
    options: [
      'Weil es in gesättigten Märkten nur wenige Nischen gibt – so entsteht eine Matrix aus vier Strategierichtungen.',
      'Weil Nischen immer die höchsten Gewinne bringen.',
      'Weil Nischenanbieter grundsätzlich Kostenführer sind.',
      'Weil Nischen gesetzlich geschützt sind.',
    ],
    correctOptions: [0],
    explanation: 'Wenige Nischen in gesättigten Märkten → Integration in die Matrix (selektive Qualitäts- bzw. Kostenführerschaft).',
    source: 'Kapitel 1.2, PDF S. 5', conceptIds: ['mc-nische', 'mc-strategiematrix'],
  },
  {
    id: 'qm1-46', chapterId: 'm1', type: 'cloze', goal: 'fact', difficulty: 2,
    prompt: 'Eine abnehmergerichtete Strategie ist ein langfristiger ______, der durch die Realisierung eines oder mehrerer ______ in der Wahrnehmung der Kunden ihr Verhalten beeinflusst bzw. stimuliert.',
    clozeAnswers: [['Verhaltensplan'], ['Wettbewerbsvorteile', 'Wettbewerbsvorteil', 'Wettbewerbsvorteilen']],
    explanation: 'Definition nach Bruhn (2016); grundsätzlich: besser (Qualität) oder billiger (Kosten) als die Konkurrenz sein.',
    source: 'Kapitel 1.2, PDF S. 5', conceptIds: ['mc-abnehmergerichtet'],
  },
  {
    id: 'qm1-47', chapterId: 'm1', type: 'assignment', goal: 'application', difficulty: 2,
    prompt: 'Fallbeispiel „Sitt“/„isso“: Ordnen Sie die Maßnahme dem richtigen Schritt des Marketingmanagements zu.',
    pairs: [
      { left: 'Analyse von Getränkemarkt, Trends und Wettbewerb – kaum Wasser für Teenager', right: 'Situationsanalyse' },
      { left: 'Ziel: 0,5 % Marktanteil', right: 'Marketingziele' },
      { left: 'Zielgruppe Jugendliche 12–19 Jahre, Produkt soll „cool“ wirken', right: 'Marketingstrategie' },
      { left: '0,75-l-Flasche, 0,89 €, Instagram/TikTok, Influencer', right: 'Marketinginstrumente' },
      { left: 'Produktlaunch durch die Marketingabteilung', right: 'Marketingimplementierung' },
      { left: 'Prüfung, ob das Marktanteilsziel erreicht wurde', right: 'Marketingcontrolling' },
    ],
    explanation: 'Die Tabelle im Skript ordnet jedem Schritt Inhalt und Beispiel zu.',
    source: 'Kapitel 1.3, PDF S. 5–6', conceptIds: ['mc-6schritte', 'mc-situationsanalyse', 'mc-marketingziele', 'mc-marketingstrategie', 'mc-marketinginstrumente', 'mc-implementierung', 'mc-controlling'],
  },
  {
    id: 'qm1-48', chapterId: 'm1', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'In welchem Schritt des Marketingmanagements werden Märkte, Marktsegmente und die Marktbearbeitungsstrategie festgelegt?',
    options: ['Marketingstrategie', 'Marketinginstrumente', 'Situationsanalyse', 'Marketingimplementierung'],
    correctOptions: [0],
    explanation: 'Marketingstrategie = strategische Marketingplanung (langfristiger Verhaltensplan). Die Instrumente (4 Ps) sind die operative Planung.',
    source: 'Kapitel 1.3, PDF S. 6', conceptIds: ['mc-marketingstrategie', 'mc-marketinginstrumente'],
  },
  {
    id: 'qm1-49', chapterId: 'm1', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche Ps ergänzen den Marketingmix speziell für Dienstleistungen? (Mehrfachauswahl)',
    options: ['People', 'Processes', 'Physical Facilities', 'Promotion', 'Packaging'],
    correctOptions: [0, 1, 2],
    explanation: 'People, Processes, Physical Facilities. Promotion gehört zu den klassischen vier Ps; „Packaging“ ist kein P des Skripts.',
    source: 'Kapitel 1.3, PDF S. 6', conceptIds: ['mc-dienstleistungs-ps'],
  },
  {
    id: 'qm1-50', chapterId: 'm1', type: 'true_false', goal: 'fact', difficulty: 1,
    prompt: 'Ein Marktsegment ist ein Teil eines Markts, der bestimmte Merkmale aufweist und relativ heterogen ist.',
    correctBool: false,
    explanation: 'Falsch – ein Marktsegment ist relativ HOMOGEN.',
    source: 'Kapitel 1.3, PDF S. 6', conceptIds: ['mc-marktsegment'],
  },
  {
    id: 'qm1-51', chapterId: 'm1', type: 'single_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welcher ist der dritte der vier groben Schritte, in denen Marketingmanager Marken aufbauen (Kotler/Keller/Opresnik 2015)?',
    options: [
      'Die Markenleistung wird gemessen und interpretiert.',
      'Die Markenpositionierung wird identifiziert und aufgebaut.',
      'Das Markenmarketing wird geplant und umgesetzt.',
      'Der Markenwert wird aufgebaut und aufrechterhalten.',
    ],
    correctOptions: [0],
    explanation: 'Reihenfolge: 1. Positionierung, 2. Markenmarketing planen/umsetzen, 3. Markenleistung messen/interpretieren, 4. Markenwert aufbauen/erhalten.',
    source: 'Kapitel 1.2, PDF S. 3', conceptIds: ['mc-markenaufbau'],
  },
  {
    id: 'qm1-52', chapterId: 'm1', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erläutern Sie, warum Markenführung keine einheitliche Definition hat und warum Marken nicht mit Produkten gleichgesetzt werden dürfen.',
    rubric: [
      { point: 'Branding wurde pragmatisch in Werbeagenturen entwickelt, nicht in akademischer Theorie', keywords: ['werbeagentur', 'agentur', 'pragmatisch', 'nicht in akademischer'] },
      { point: 'Agenturen nutzen eigene Markenmodelle → keine einheitliche Definition', keywords: ['eigene markenmodell', 'keine einheitliche', 'markenmodell'] },
      { point: 'Marken haben ein Eigenleben: auch Veranstaltungen, Dienstleistungen, Menschen, Orte', keywords: ['eigenleben', 'veranstaltung', 'menschen', 'orte', 'dienstleistung'] },
      { point: 'Beispiel: Rock am Ring, Städtemarketing', keywords: ['rock am ring', 'städtemarketing'], weight: 0.5 },
    ],
    modelAnswer: 'Markenführung (Branding) wurzelt nicht in akademischer Theorie, sondern wurde pragmatisch und schrittweise in Werbeagenturen entwickelt; die großen Agenturen nutzen bis heute eigene Markenmodelle – deshalb gibt es keine einheitliche Definition. Marken dürfen nicht mit Produkten gleichgesetzt werden, weil sie ein „Eigenleben“ entwickelt haben und heute auch für Veranstaltungen, Dienstleistungen, Menschen und Orte verwendet werden, z. B. das Musikfestival „Rock am Ring“ oder Städtemarketing.',
    explanation: 'Herkunft aus der Agenturpraxis + Marke ≠ Produkt.',
    source: 'Kapitel 1.2, PDF S. 3', conceptIds: ['mc-branding'],
  },
  {
    id: 'qm1-53', chapterId: 'm1', type: 'true_false', goal: 'fact', difficulty: 1,
    prompt: 'Beim Business-to-Business-Marketing (B2B) sind die Konsumenten keine privaten Endverbraucher, sondern Organisationen.',
    correctBool: true,
    explanation: 'Richtig – B2B-Marketing richtet sich an Organisationen.',
    source: 'Kapitel 1.1, PDF S. 3', conceptIds: ['mc-b2b'],
  },
  {
    id: 'qm1-54', chapterId: 'm1', type: 'single_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Aus welchen Bereichen stammt laut Skript die Erkenntnis, die zum Paradigmenwechsel vom Transaktions- zum Beziehungsmarketing führte?',
    options: ['Aus Dienstleistung und B2B', 'Aus dem Massenkonsumgütermarketing', 'Aus der Preistheorie', 'Aus dem Innovationsmanagement'],
    correctOptions: [0],
    explanation: 'Dienstleister (Friseur, Autowerkstatt, Steuerberater) und B2B-Anbieter werden auch wegen über Jahre aufgebauter vertrauensvoller Beziehungen gewählt – nicht nur nach Preis und Qualität.',
    source: 'Kapitel 1.1, PDF S. 3', conceptIds: ['mc-beziehung', 'mc-b2b'],
  },
];
