import { Question } from '@/lib/types';

/** Fragen Kapitel 4 – Preispolitik (PDF S. 16–20). */
export const questions4: Question[] = [
  // ======================= bestehende Fragen (IDs unverändert) =======================
  {
    id: 'qm4-01', chapterId: 'm4', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Warum wird die Preispolitik auch „Kontrahierungspolitik“ genannt?',
    options: [
      'Weil sie neben der Höhe des Preises auch weitere Bedingungen wie Zahlungsbedingungen und Rabatte umfasst',
      'Weil sie nur den Listenpreis festlegt',
      'Weil sie ausschließlich Verträge mit Lieferanten regelt',
      'Weil sie sich nur auf den B2C-Bereich bezieht',
    ],
    correctOptions: [0],
    explanation: 'Preispolitik befasst sich mit der Höhe des Preises und weiteren Bedingungen (Zahlungsbedingungen, Rabatte) – daher Kontrahierungspolitik.',
    source: 'Kapitel 4.1, PDF S. 16', conceptIds: ['mc-preispolitik'],
  },
  {
    id: 'qm4-02', chapterId: 'm4', type: 'cloze', goal: 'understanding', difficulty: 2,
    prompt: 'Die Zahlungsbereitschaft des anvisierten Kundensegments definiert die Preis______; die Gesamtkosten bilden die Preis______.',
    clozeAnswers: [['obergrenze', 'Obergrenze'], ['untergrenze', 'Untergrenze']],
    explanation: 'Käufer → Preisobergrenze; Kosten → Preisuntergrenze. Dazwischen liegt der preispolitische Spielraum.',
    source: 'Kapitel 4.1, PDF S. 16', conceptIds: ['mc-einflussfaktoren-preis'],
  },
  {
    id: 'qm4-03', chapterId: 'm4', type: 'true_false', goal: 'fact', difficulty: 1,
    prompt: 'Ein Preis von 2,99 € statt 3,00 € nutzt aus, dass Kunden dazu tendieren, Nachkommastellen zu ignorieren (Schwellenpreis).',
    correctBool: true,
    explanation: 'Richtig – psychologischer Effekt der Preiswahrnehmung.',
    source: 'Kapitel 4.1, PDF S. 16', conceptIds: ['mc-einflussfaktoren-preis'],
  },
  {
    id: 'qm4-04', chapterId: 'm4', type: 'assignment', goal: 'distinction', difficulty: 3,
    prompt: 'Ordnen Sie die Preis-Absatz-Funktion ihrem Kennzeichen zu.',
    pairs: [
      { left: 'Lineare PAF x(p) = a – b · p', right: 'Idealtypisch im Monopol; Sättigungsmenge a und Maximalpreis a/b' },
      { left: 'Multiplikatives Modell x(p) = a · p^(–b)', right: 'Achsen werden nicht geschnitten – keine Sättigungsmenge, kein Maximalpreis' },
      { left: 'Gutenberg-Modell', right: 'Doppelt geknickt – im mittleren Bereich eine Art Monopol' },
    ],
    explanation: 'Linear = Monopol-Idealtyp; multiplikativ = ohne Achsenschnitte; Gutenberg = unvollkommener Markt mit Wettbewerbern.',
    source: 'Kapitel 4.1, PDF S. 17', conceptIds: ['mc-paf', 'mc-paf-linear', 'mc-paf-mult', 'mc-gutenberg'],
  },
  {
    id: 'qm4-05', chapterId: 'm4', type: 'single_choice', goal: 'application', difficulty: 2,
    prompt: 'Apple verkauft Smartphones erfolgreich zu hohen Preisen; in einem mittleren Preisbereich ändert sich die Absatzmenge trotz höherer Preise wenig. Welches Modell beschreibt das?',
    options: ['Gutenberg-Modell', 'Lineare Preis-Absatz-Funktion', 'Multiplikatives Preis-Absatz-Modell', 'Break-even-Analyse'],
    correctOptions: [0],
    explanation: 'Gutenberg: doppelt geknickt; im mittleren Bereich entsteht durch erfolgreiche Markenpolitik eine Art Monopol.',
    source: 'Kapitel 4.1, PDF S. 17', conceptIds: ['mc-gutenberg'],
  },
  {
    id: 'qm4-06', chapterId: 'm4', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Ein Hersteller führt ein innovatives Produkt zu einem sehr hohen Preis ein und senkt ihn, sobald Innovatoren und Frühadopter versorgt sind. Welche Strategie ist das?',
    options: ['Skimmingstrategie', 'Penetrationsstrategie', 'Preisfolgerschaft', 'Preiskampf'],
    correctOptions: [0],
    explanation: 'Skimming (Abschöpfung): hohe Einführungspreise schöpfen die Preisbereitschaft früher Segmente ab, danach Preissenkung für die frühe und späte Mehrheit.',
    source: 'Kapitel 4.2, PDF S. 18', conceptIds: ['mc-preisabfolge'],
  },
  {
    id: 'qm4-07', chapterId: 'm4', type: 'cloze', goal: 'distinction', difficulty: 2,
    prompt: 'Die ______strategie durchdringt den Markt mit geringen Einführungspreisen und erhöht die Preise danach; die ______strategie startet mit sehr hohen Preisen und senkt sie später.',
    clozeAnswers: [['Penetrations', 'Penetration'], ['Skimming', 'Abschöpfungs', 'Abschöpfung']],
    explanation: 'Penetration: niedrig → hoch (z. B. Rasierer günstig, Klingen teuer). Skimming: hoch → niedrig (z. B. iPhone 7: 759 → 629 €).',
    source: 'Kapitel 4.2, PDF S. 18', conceptIds: ['mc-preisabfolge'],
  },
  {
    id: 'qm4-08', chapterId: 'm4', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche der folgenden sind Formen der Preisdifferenzierung? (Mehrfachauswahl)',
    options: ['Zeitliche Preisdifferenzierung', 'Räumliche Preisdifferenzierung', 'Personelle Preisdifferenzierung', 'Kostenorientierte Preisdifferenzierung', 'Preisbündelung'],
    correctOptions: [0, 1, 2, 4],
    explanation: 'Formen: mengenmäßig, zeitlich, räumlich, personell, leistungsbezogen; Sonderform Preisbündelung. „Kostenorientiert“ ist ein Verfahren der Preisbestimmung.',
    source: 'Kapitel 4.2, PDF S. 18–19', conceptIds: ['mc-preisdiff'],
  },
  {
    id: 'qm4-09', chapterId: 'm4', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie die vier Rabattarten ihrer Beschreibung zu.',
    pairs: [
      { left: 'Funktionsrabatt', right: 'Gegenleistung für vom Handel übernommene Funktionen (Lagerung, Präsentation, Kundenkontakt)' },
      { left: 'Mengenrabatt', right: 'Rabatt auf die Bestellung größerer Mengen durch das Handelsunternehmen' },
      { left: 'Zeitrabatt', right: 'Abhängig von der Bestellzeit, z. B. vor der Saison (Sonderform Skonto)' },
      { left: 'Treuerabatt', right: 'Belohnung für langfristige und kontinuierliche Bestellungen' },
    ],
    explanation: 'Vier Typen von Rabatten nach Walsh/Deseniss/Kilian (2013).',
    source: 'Kapitel 4.3, PDF S. 20', conceptIds: ['mc-rabatte'],
  },
  {
    id: 'qm4-10', chapterId: 'm4', type: 'open', goal: 'distinction', difficulty: 2,
    prompt: 'Grenzen Sie kostenorientierte und marktorientierte Preisbestimmung voneinander ab. Nennen Sie Vor- und Nachteile sowie die marktorientierten Verfahren aus dem Skript.',
    rubric: [
      { point: 'Kostenorientiert: Kostenrechnung, Preis = Stückkosten + branchen-/firmenüblicher Aufschlag', keywords: ['stückkosten', 'aufschlag', 'kostenrechnung'] },
      { point: 'Vorteile: intuitiv, verbreitet, schnell, kostengünstig, transparent, als fair wahrgenommen', keywords: ['intuitiv', 'schnell', 'transparent', 'fair', 'kostengünstig'] },
      { point: 'Nachteil: vernachlässigt Nachfrage und Wettbewerb', keywords: ['vernachlässigt', 'nachfrage', 'wettbewerb'] },
      { point: 'Marktorientiert: Reaktionen der Marktteilnehmer; praxisgerechter; Break-even, Perceived-Value-Pricing, Cournot-Preis', keywords: ['marktteilnehmer', 'reaktion', 'break-even', 'perceived', 'cournot', 'praxis'] },
    ],
    modelAnswer: 'Die kostenorientierte Preisbestimmung nutzt vornehmlich die Kostenrechnung: Preis = Stückkosten plus branchen- oder firmenüblicher Aufschlag. Sie ist die intuitivste Art, weit verbreitet, schnell, kostengünstig und transparent und wird von Konsumenten als fair wahrgenommen, vernachlässigt aber jegliche nachfrage- und wettbewerbsbezogenen Aspekte. Die marktorientierte Preisbestimmung orientiert sich an den Reaktionen der Marktteilnehmer (Kunden/Nachfrage und Preisverhalten der Konkurrenz) und wird den Anforderungen der Praxis besser gerecht. Verfahren: Break-even-Analyse (erforderliche Absatzmenge bei gegebenem Preis bis zur Gewinnschwelle), Perceived-Value-Pricing (Preis nach empfundenem Wert aus Kundensicht) und Cournot-Preis (gewinnmaximaler Preis mithilfe der Preis-Absatz-Funktion).',
    explanation: 'Kosten + Aufschlag vs. Orientierung am Markt.',
    source: 'Kapitel 4.3, PDF S. 19', conceptIds: ['mc-kostenorientiert', 'mc-marktorientiert'],
  },
  {
    id: 'qm4-11', chapterId: 'm4', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Eine Fluggesellschaft verlangt für denselben Sitzplatz je nach Buchungszeitpunkt und Auslastung unterschiedliche Preise. Ordnen Sie dieses Vorgehen den Preismodellen und Formen der Preisdifferenzierung aus dem Skript zu und begründen Sie, warum es hier sinnvoll ist.',
    rubric: [
      { point: 'Yield Management (Nachfrage erlösmaximal mit Kapazitäten synchronisieren; ursprünglich von Fluglinien)', keywords: ['yield'] },
      { point: 'Dynamic Pricing (automatische Anpassung je nach Nachfrage, Frühbucher/Last-Minute)', keywords: ['dynamic', 'frühbucher', 'last-minute', 'nachfrageintensität'] },
      { point: 'Zeitliche Preisdifferenzierung (Auslastung der Kapazitäten)', keywords: ['zeitlich', 'auslastung', 'kapazität'] },
      { point: 'Bedingungen erfüllt: fixe Kapazitäten, nicht lagerbar, hohe Fixkosten, Nachfrageschwankungen, Vorausbuchung', keywords: ['fixe kapazität', 'nicht lagerbar', 'fixkosten', 'vorausbuchung', 'schwankung'] },
    ],
    modelAnswer: 'Es handelt sich um Yield Management: Die Nachfrage soll erlösmaximal mit den vorhandenen Kapazitäten synchronisiert werden – das Modell wurde ursprünglich von Fluglinien entwickelt. Die automatische Preisanpassung nach Nachfrageintensität (Frühbucher- und Last-Minute-Preise) entspricht Dynamic Pricing; dahinter steht zeitliche Preisdifferenzierung zur bestmöglichen Auslastung. Sinnvoll ist es, weil die Bedingungen erfüllt sind: fixe Kapazitäten (Sitzplätze), nicht lagerbare Güter (ein leerer Sitz ist nach dem Abflug wertlos), hohe Fixkosten bei geringen variablen Kosten, starke Nachfrageschwankungen, Vorausbuchung und mögliche Preisdifferenzierung.',
    explanation: 'Fluglinien sind das Ursprungsbeispiel des Yield Managements.',
    source: 'Kapitel 4.2–4.3, PDF S. 18–19', conceptIds: ['mc-yield', 'mc-dynamic', 'mc-preisdiff'],
  },

  // ======================= neue offene Fragen =======================
  {
    id: 'qm4-12', chapterId: 'm4', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erläutern Sie, was unter Preispolitik zu verstehen ist, warum sie eine besondere Stellung im Marketing hat und an welchen Zielen sie sich ausrichtet.',
    rubric: [
      { point: 'Alle Entscheidungen zur Festlegung eines Entgelts (Homburg 2017), inkl. Zahlungsbedingungen/Rabatte → Kontrahierungspolitik', keywords: ['entgelt', 'zahlungsbedingung', 'rabatt', 'kontrahierung'] },
      { point: 'Preise als Indikator der Marktstellung, direkter Einfluss auf Umsatz und Gewinn', keywords: ['marktstellung', 'umsatz', 'gewinn', 'indikator'] },
      { point: 'Komplexe Managementaufgabe mit strategischen und operativen Parametern', keywords: ['strategisch', 'operativ', 'managementaufgabe'] },
      { point: 'Ziele: Unternehmensziele, handelsbezogene und konsumentenbezogene Ziele', keywords: ['unternehmensziel', 'handelsbezogen', 'konsumentenbezogen', 'preiswahrnehmung', 'präsenz'] },
    ],
    modelAnswer: 'Preispolitik umfasst alle Entscheidungen, die sich mit der Festlegung eines Entgelts für in Anspruch genommene Leistungen befassen (Homburg 2017) – nicht nur die Preishöhe, sondern auch Bedingungen wie Zahlungsbedingungen und Rabatte, daher auch Kontrahierungspolitik. Preise sind ein wesentlicher Indikator für die Marktstellung und wirken direkt auf Umsatz und Gewinn; die Preispolitik ist eine komplexe Managementaufgabe mit strategischen und operativen Entscheidungsparametern. Sie richtet sich nach den Unternehmenszielen (Umsatz, Gewinn, Marktanteil, Rentabilität) sowie nach handelsbezogenen (z. B. mehr Präsenz in Handelskanälen) und konsumentenbezogenen Zielen (z. B. Beeinflussung der Preiswahrnehmung).',
    explanation: 'Kernpunkte laut Skript: Definition, Stellung, Ziele.',
    source: 'Kapitel 4.1, PDF S. 16', conceptIds: ['mc-preispolitik'],
  },
  {
    id: 'qm4-13', chapterId: 'm4', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Erläutern Sie die fünf Einflussfaktoren der Preisfestlegung jeweils mit Beispiel.',
    rubric: [
      { point: 'Käufer: Zahlungsbereitschaft = Preisobergrenze (Starbucks)', keywords: ['zahlungsbereitschaft', 'obergrenze', 'starbucks'] },
      { point: 'Kosten: Gesamtkosten = Preisuntergrenze', keywords: ['gesamtkosten', 'untergrenze', 'kosten decken'] },
      { point: 'Konkurrenz: Preiswürdigkeit, Vergleichsportale, Preiskorridor, Monitoring', keywords: ['konkurrenz', 'vergleichsportal', 'idealo', 'preiskorridor', 'monitoring'] },
      { point: 'Externe Rahmenbedingungen: Handelsstruktur, Gesamtwirtschaft, Saison', keywords: ['handelsstruktur', 'gesamtwirtschaft', 'saison'] },
      { point: 'Psychologische Effekte: Nachkommastellen ignoriert, Schwellenpreise (2,99 €)', keywords: ['psychologisch', 'schwellenpreis', 'nachkommastelle', '2,99'] },
    ],
    modelAnswer: '1) Käufer: Die Zahlungsbereitschaft des anvisierten Kundensegments definiert die Preisobergrenze; wahrgenommener Nutzen und Herstellerkosten müssen nicht zusammenhängen (Milchkaffee bei Starbucks 10–30 % teurer als im unabhängigen Café). 2) Kosten: Der Preis soll über die Lebensdauer die Kosten decken und einen Gewinnbeitrag bringen – die Gesamtkosten bilden die Preisuntergrenze. 3) Konkurrenzsituation: Konsumenten beziehen Wettbewerbspreise in die Preiswürdigkeit ein; Vergleichsportale (Idealo, Google Shopping) erhöhen die Transparenz, es entsteht ein Preiskorridor, oft per Preis-Monitoring überwacht. 4) Externe Rahmenbedingungen: Handelsstruktur (Discounter vs. exklusiver Partner), gesamtwirtschaftliche Situation, saisonale Schwankungen. 5) Psychologische Effekte: Kunden ignorieren Nachkommastellen, was Schwellenpreise wie 2,99 € ausnutzen.',
    explanation: 'Fünf Faktoren mit Beispielen.',
    source: 'Kapitel 4.1, PDF S. 16', conceptIds: ['mc-einflussfaktoren-preis'],
  },
  {
    id: 'qm4-14', chapterId: 'm4', type: 'transfer', goal: 'application', difficulty: 2,
    prompt: 'Eine Kaffeehauskette verlangt für einen Milchkaffee deutlich mehr als ein unabhängiges Café, obwohl ihre Herstellkosten kaum höher sind. Erklären Sie mit dem Skript, warum das funktionieren kann.',
    rubric: [
      { point: 'Preisobergrenze wird durch die Zahlungsbereitschaft des Kundensegments definiert', keywords: ['zahlungsbereitschaft', 'obergrenze'] },
      { point: 'Wahrgenommener Nutzen und reale Herstellerkosten müssen nicht zusammenhängen', keywords: ['wahrgenommen', 'nutzen', 'herstellerkosten', 'nicht zusammenhängen'] },
      { point: 'Kosten bilden nur die Untergrenze', keywords: ['untergrenze', 'kosten'] },
      { point: 'Beispiel Starbucks (10–30 % teurer)', keywords: ['starbucks', '10', '30'], weight: 0.5 },
    ],
    modelAnswer: 'Die Preisobergrenze ergibt sich aus der Zahlungsbereitschaft des anvisierten Kundensegments, nicht aus den Kosten – die Gesamtkosten bilden nur die Preisuntergrenze. Der wahrgenommene Nutzen (z. B. durch Marke und Erlebnis) und die realen Herstellerkosten müssen nicht zusammenhängen. Genau das zeigt das Skript-Beispiel: Ein Milchkaffee bei Starbucks ist 10–30 % teurer als im unabhängigen Café.',
    explanation: 'Zahlungsbereitschaft statt Kosten bestimmt die Obergrenze.',
    source: 'Kapitel 4.1, PDF S. 16', conceptIds: ['mc-einflussfaktoren-preis'],
  },
  {
    id: 'qm4-15', chapterId: 'm4', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Was ist eine Preis-Absatz-Funktion, auf welcher Datenbasis wird sie ermittelt und wozu dient sie?',
    rubric: [
      { point: 'Mathematisch-analytischer Ansatz der mikroökonomischen Preistheorie, bildet Konsumentenreaktionen auf Preisänderungen ab', keywords: ['mikroökonom', 'preistheorie', 'konsumentenreaktion', 'mathematisch'] },
      { point: 'Funktionaler Zusammenhang zwischen Preis und in einem Zeitraum abgesetzter Menge', keywords: ['zusammenhang', 'abgesetzte menge', 'preis und menge', 'zeitraum'] },
      { point: 'Datenbasis: Rechnungswesen, Kundenbefragungen, Nutzerverhalten, E-Commerce-Verkaufsdaten', keywords: ['rechnungswesen', 'kundenbefragung', 'nutzerverhalten', 'verkaufsdaten', 'datenbasis'] },
      { point: 'Zweck: Prognose, welche Mengen zu welchen Preisen verkauft werden können', keywords: ['prognose'] },
    ],
    modelAnswer: 'Die Preis-Absatz-Funktion ist ein mathematisch-analytischer Ansatz aus der mikroökonomischen Preistheorie, der Konsumentenreaktionen auf Preisänderungen abbildet: den funktionalen Zusammenhang zwischen dem Preis eines Produkts und der in einem gewissen Zeitraum abgesetzten Menge. Sie wird auf Grundlage einer ausreichend großen Datenbasis ermittelt (Rechnungswesen, Kundenbefragungen, Analyse von Nutzerverhalten, E-Commerce-Verkaufsdaten) und dient der Prognose, welche Mengen zu welchen Preisen verkauft werden können.',
    explanation: 'Kernpunkte laut Skript: Definition, Datenbasis, Zweck.',
    source: 'Kapitel 4.1, PDF S. 17', conceptIds: ['mc-paf'],
  },
  {
    id: 'qm4-16', chapterId: 'm4', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erklären Sie die lineare Preis-Absatz-Funktion x(p) = a – b · p und die Bedeutung der Parameter a, b und a/b.',
    rubric: [
      { point: 'Idealtypische Betrachtung im Monopol; Nachfrage sinkt mit steigendem Preis', keywords: ['monopol', 'sinkt', 'steigendem preis'] },
      { point: 'a = maximale Sättigungsmenge (Absatz bei Preis 0)', keywords: ['sättigungsmenge', 'preis 0', 'preis null'] },
      { point: 'b = wie stark der Markt auf Preisänderungen reagiert', keywords: ['reagiert', 'preisänderung', 'reaktion'] },
      { point: 'a/b = Maximalpreis (keine Nachfrage mehr)', keywords: ['maximalpreis', 'keine nachfrage'] },
    ],
    modelAnswer: 'Die lineare PAF ist eine idealtypische Betrachtung im Monopol: Die Nachfrage sinkt mit steigendem Preis. a ist die maximale Sättigungsmenge, also der Absatz bei einem Preis von 0; b verdeutlicht, wie stark der Markt auf Preisänderungen reagiert; a/b ist der Maximalpreis, bei dem keine Nachfrage mehr existiert.',
    explanation: 'Parameter der linearen PAF.',
    source: 'Kapitel 4.1, PDF S. 17', conceptIds: ['mc-paf-linear'],
  },
  {
    id: 'qm4-17', chapterId: 'm4', type: 'open', goal: 'distinction', difficulty: 3,
    prompt: 'Vergleichen Sie die lineare Preis-Absatz-Funktion, das multiplikative Preis-Absatz-Modell und das Gutenberg-Modell hinsichtlich Marktannahme, Verlauf und Besonderheiten.',
    rubric: [
      { point: 'Linear: Monopol, Gerade, Sättigungsmenge a und Maximalpreis a/b', keywords: ['linear', 'monopol', 'sättigungsmenge', 'maximalpreis'] },
      { point: 'Multiplikativ: Ausgangspreis berücksichtigt (je niedriger, desto stärker wirken Änderungen), keine Achsenschnitte', keywords: ['multiplikativ', 'ausgangspreis', 'achsen', 'keine sättigungsmenge', 'normierungsparameter'] },
      { point: 'Gutenberg: unvollkommener Markt mit Wettbewerbern, doppelt geknickt', keywords: ['gutenberg', 'unvollkommen', 'wettbewerber', 'doppelt geknickt'] },
      { point: 'Gutenberg-Mittelbereich: Art Monopol – Menge ändert sich trotz höherer Preise wenig (Markenpolitik, Apple)', keywords: ['mittleren bereich', 'monopol', 'wenig', 'markenpolitik', 'apple'] },
    ],
    modelAnswer: 'Die lineare PAF (x = a – b·p) ist eine idealtypische Betrachtung im Monopol; die Nachfrage sinkt gleichmäßig mit steigendem Preis, mit Sättigungsmenge a und Maximalpreis a/b. Das multiplikative Modell (x = a·p^(–b)) berücksichtigt zusätzlich den Ausgangspreis – je niedriger er ist, desto stärker wirken Preisänderungen; die Kurve schneidet die Achsen nicht, es gibt also keine Sättigungsmenge und keinen Maximalpreis (a = Normierungsparameter, b = Preisabhängigkeit). Das Gutenberg-Modell reflektiert den unvollkommenen Markt mit Wettbewerbern: Die Funktion ist doppelt geknickt; oben und unten sinkt die Nachfrage ähnlich linear, im mittleren Bereich entsteht eine Art Monopol, in dem sich die Absatzmenge trotz höherer Preise wenig ändert – etwa durch erfolgreiche Markenpolitik wie bei Apple.',
    explanation: 'Drei Modelle im direkten Vergleich.',
    source: 'Kapitel 4.1, PDF S. 17', conceptIds: ['mc-paf-linear', 'mc-paf-mult', 'mc-gutenberg', 'mc-paf'],
  },
  {
    id: 'qm4-18', chapterId: 'm4', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Beschreiben Sie den Prozess der Preisfestlegung nach Bruhn (2016) und erläutern Sie die vier zentralen Preisinstrumente.',
    rubric: [
      { point: 'Preise müssen über den Lebenszyklus mehrmals angepasst werden → systematischer Prozess', keywords: ['mehrmals', 'lebenszyklus', 'systematisch'] },
      { point: 'Schritte: Spielraum analysieren, Ziele festlegen, Strategie entwickeln, Instrumente einsetzen, Preiskontrolle', keywords: ['spielraum', 'zielsetzung', 'strategieentwicklung', 'instrumente', 'preiskontrolle'] },
      { point: 'Instrumente: Preise, Preisnachlässe (Rabatte, Boni, Skonti), Preiszuschläge', keywords: ['preisnachlass', 'rabatt', 'boni', 'skonti', 'preiszuschlag'] },
      { point: 'Zugaben von Geld-/Sachwerten/Dienstleistungen – v. a. an den Handel, Akzeptanz der Preise', keywords: ['zugabe', 'handel', 'akzeptanz', 'verkostung', 'displaymaterial'] },
    ],
    modelAnswer: 'Da Preise über den Produktlebenszyklus mehrmals angepasst werden müssen, erfolgt die Festlegung als systematischer Planungsprozess: 1. Analyse des preispolitischen Spielraums (Preiskorridor zwischen Unter- und Obergrenze), 2. Festlegung spezifischer preispolitischer Zielsetzungen, 3. preispolitische Strategieentwicklung, 4. Einsatz der Preisinstrumente, 5. Preiskontrolle (fortlaufende Überwachung von Handelsabgabe-, Endverbraucher- und Konkurrenzpreisen). Die vier Instrumente sind: (1) Preise, (2) Preisnachlässe (Rabatte, Boni, Skonti), (3) Preiszuschläge (z. B. für Sonderleistungen oder bestimmte Lieferzeiten) und (4) Zugaben von Geld- und Sachwerten sowie Dienstleistungen, die sich vor allem an den Handel richten und die Akzeptanz der geforderten Preise unterstützen sollen (z. B. Verkostungen, Displaymaterial).',
    explanation: 'Kernpunkte laut Skript: Fünf Prozessschritte, vier Instrumente.',
    source: 'Kapitel 4.1, PDF S. 17–18', conceptIds: ['mc-preisprozess', 'mc-preisinstrumente'],
  },
  {
    id: 'qm4-19', chapterId: 'm4', type: 'open', goal: 'fact', difficulty: 1,
    prompt: 'Was versteht man unter Preiskontrolle und welche Preise werden dabei überwacht?',
    rubric: [
      { point: 'Fortlaufende Begleitung des Preisprozesses', keywords: ['fortlaufend', 'begleit', 'laufend'] },
      { point: 'Überwacht Handelsabgabepreis, Endverbraucherpreis, Konkurrenzpreise', keywords: ['handelsabgabepreis', 'endverbraucherpreis', 'konkurrenzpreis'] },
      { point: 'Zeigt rechtzeitig an, wann eine Preiskorrektur notwendig wird', keywords: ['preiskorrektur', 'rechtzeitig'] },
    ],
    modelAnswer: 'Die Preiskontrolle begleitet den Prozess der Preisfestlegung fortlaufend: Sie überwacht Handelsabgabepreis, Endverbraucherpreis und Konkurrenzpreise und zeigt rechtzeitig an, wann eine Preiskorrektur notwendig wird.',
    explanation: 'Fünfter Schritt des Preisprozesses.',
    source: 'Kapitel 4.1, PDF S. 18', conceptIds: ['mc-preisprozess'],
  },
  {
    id: 'qm4-20', chapterId: 'm4', type: 'open', goal: 'fact', difficulty: 2,
    prompt: 'Erläutern Sie die drei Strategien der Preispositionierung mit den Beispielen aus dem Skript.',
    rubric: [
      { point: 'Preispositionierung bezieht sich auf die Höhe des Preises', keywords: ['höhe des preises', 'preishöhe'] },
      { point: 'Hochpreisstrategie: Spitzenqualität zu Premiumpreisen (BoConcept, Seyfarth)', keywords: ['hochpreis', 'premium', 'spitzenqualität', 'boconcept', 'seyfarth'] },
      { point: 'Mittelpreisstrategie: mittleres Preisniveau, Standardqualität (Höffner, Kraft, XXXL)', keywords: ['mittelpreis', 'standardqualität', 'höffner', 'xxxl'] },
      { point: 'Niedrigpreisstrategie: Mindestqualität zu sehr geringen Preisen (Roller, Poco, Sconto)', keywords: ['niedrigpreis', 'mindestqualität', 'roller', 'poco', 'sconto'] },
    ],
    modelAnswer: 'Die Preispositionierung bezieht sich auf die Höhe des Preises. Hochpreisstrategie: Spitzenqualität zu Premiumpreisen, z. B. Designmöbelstudios wie BoConcept oder Seyfarth. Mittelpreisstrategie: mittleres Preisniveau bei Standardqualität, z. B. Vollsortimenter wie Höffner, Kraft oder die XXXL-Marken der Lutz-Gruppe (größter Marktanteil). Niedrigpreisstrategie: Mindestqualität zu sehr geringen Preisen, z. B. Möbeldiscounter wie Roller, Poco, Sconto.',
    explanation: 'Drei Positionierungsstrategien mit Möbel-Beispielen.',
    source: 'Kapitel 4.2, PDF S. 18', conceptIds: ['mc-preispositionierung'],
  },
  {
    id: 'qm4-21', chapterId: 'm4', type: 'open', goal: 'distinction', difficulty: 2,
    prompt: 'Erläutern Sie die drei Strategien des Preiswettbewerbs mit Beispielen und grenzen Sie sie von den Strategien der Preispositionierung ab.',
    rubric: [
      { point: 'Preiswettbewerb: ob und wie sich ein Unternehmen an der Konkurrenz orientiert (vs. Positionierung = Preishöhe)', keywords: ['konkurrenz', 'orientiert', 'verhalten der konkurrenz', 'höhe'] },
      { point: 'Preisführerschaft: sehr hoher Preis, durch Marke/Qualität gerechtfertigt, Orientierung für den Wettbewerb (Apple iPhone X)', keywords: ['preisführerschaft', 'orientierung', 'apple', 'iphone'] },
      { point: 'Preiskampf: niedrigster Preis am Markt (Lebensmitteldiscounter)', keywords: ['preiskampf', 'niedrigsten preis', 'discounter'] },
      { point: 'Preisfolgerschaft: Reaktion auf den Marktführer ohne eigene Planung (Aldi → Norma, Netto)', keywords: ['preisfolgerschaft', 'reaktion', 'marktführer', 'aldi', 'norma', 'netto'] },
    ],
    modelAnswer: 'Strategien des Preiswettbewerbs beziehen sich darauf, ob und wie sich ein Unternehmen am Verhalten der Konkurrenz orientiert – die Preispositionierung dagegen auf die Höhe des Preises. Preisführerschaft: ein sehr hoher, durch Marke und Qualität gerechtfertigter Preis, der dem Wettbewerb als Orientierung dient (Apple iPhone X ab 999 Dollar; Apples Durchschnittspreis ca. dreimal so hoch wie bei Samsung). Preiskampf: das Gegenteil – das Bestreben, den niedrigsten Preis am Markt zu fordern, typisch für Lebensmitteldiscounter. Preisfolgerschaft: Reaktion auf die Preise des Marktführers, ohne die Preise selbst strategisch zu planen (senkt Aldi die Preise, ziehen Norma, Netto usw. nach).',
    explanation: 'Zwei unterschiedliche Strategiedimensionen.',
    source: 'Kapitel 4.2, PDF S. 18', conceptIds: ['mc-preiswettbewerb', 'mc-preispositionierung'],
  },
  {
    id: 'qm4-22', chapterId: 'm4', type: 'open', goal: 'distinction', difficulty: 3,
    prompt: 'Grenzen Sie Skimming- und Penetrationsstrategie voneinander ab, nennen Sie je ein Skript-Beispiel und zeigen Sie am Netflix-Fall, dass Preisstrategien auch scheitern können.',
    rubric: [
      { point: 'Preisabfolge: Preisentwicklung im Produktlebenszyklus', keywords: ['preisabfolge', 'lebenszyklus', 'preisentwicklung'] },
      { point: 'Skimming: sehr hohe Einführungspreise, Preisbereitschaft von Innovatoren/Frühadoptern abschöpfen, später senken (iPhone 7: 759 → 629 €)', keywords: ['skimming', 'abschöpf', 'innovatoren', 'iphone', '759', '629'] },
      { point: 'Penetration: geringe Preise zur schnellen Marktdurchdringung, danach erhöhen (Rasierer günstig, Klingen teuer)', keywords: ['penetration', 'durchdring', 'rasierer', 'klingen'] },
      { point: 'Netflix 2011: Preiserhöhung um 60 % → 800.000 Kunden und 77 % des Börsenwerts verloren', keywords: ['netflix', '60', '800.000', '77'] },
    ],
    modelAnswer: 'Beide sind Strategien der Preisabfolge, also der Preisentwicklung im Produktlebenszyklus. Skimming (Abschöpfung): Sehr hohe Einführungspreise nutzen die Preisbereitschaft von Innovatoren und Frühadoptern, um schnell Gewinne abzuschöpfen; sind diese Segmente gesättigt, sinkt der Preis für die frühe und späte Mehrheit – Apple senkte den iPhone-7-Preis mit Vorstellung von iPhone 8 und X von 759 auf 629 Euro. Penetration folgt der umgekehrten Logik: mit geringen Preisen den Markt so schnell wie möglich durchdringen und die Preise danach erhöhen – z. B. Rasierer günstig, Nachfüllpacks mit Klingen teuer. Dass Preisstrategien scheitern können, zeigt Netflix: 2011 versuchte das Unternehmen durch Entkopplung von DVD-Verleih und Streaming eine Preiserhöhung von 60 % und verlor 800.000 Kunden und 77 % des Börsenwerts.',
    explanation: 'Hoch → runter vs. niedrig → hoch, plus Risiko.',
    source: 'Kapitel 4.2, PDF S. 18', conceptIds: ['mc-preisabfolge', 'mc-diffusion'],
  },
  {
    id: 'qm4-23', chapterId: 'm4', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Was versteht man unter Preisdifferenzierung und warum ist sie sinnvoll? Erläutern Sie alle Formen einschließlich der Sonderform mit je einem Beispiel aus dem Skript.',
    rubric: [
      { point: 'Unterschiedliche Preise für verschiedene Segmente, weil Zahlungsbereitschaften unterschiedlich sind', keywords: ['unterschiedliche preise', 'segment', 'zahlungsbereitschaft'] },
      { point: 'Mengenmäßig (Kartenmacherei) und zeitlich (Kinotag)', keywords: ['mengenmäßig', 'kartenmacherei', 'zeitlich', 'kinotag', 'kino'] },
      { point: 'Räumlich (Benzin in Stadtstaaten) und personell (Jugendkonto, Seniorenmenüs)', keywords: ['räumlich', 'benzin', 'personell', 'jugendkonto', 'senior', 'student'] },
      { point: 'Leistungsbezogen (gebundenes Buch/Taschenbuch/E-Book)', keywords: ['leistungsbezogen', 'taschenbuch', 'e-book', 'gebundene'] },
      { point: 'Preisbündelung als Sonderform (MagentaEINS)', keywords: ['bündelung', 'paketpreis', 'magenta'] },
    ],
    modelAnswer: 'Preisdifferenzierung ist die Forderung unterschiedlicher Preise für verschiedene Marktsegmente – sinnvoll, weil die Segmente unterschiedliche Zahlungsbereitschaften haben. Mengenmäßig: geringere Durchschnittspreise bei höheren Abnahmemengen (Kartenmacherei: 5 Einladungen 3,63 €/Stück, bei 500 nur 1,35 €), gibt Kostenvorteile weiter und regt größere Bestellungen an. Zeitlich: bestmögliche Auslastung vorhandener Kapazitäten (Kinotag am Wochenanfang, günstigere Nachmittagsvorstellungen). Räumlich: Preise nach geografischen Aspekten (Benzin ist in Hamburg, Bremen und Berlin wegen stärkerer Konkurrenz günstiger als in Thüringen und Baden-Württemberg). Personell: Vergünstigungen für Gruppen wie Studenten oder Senioren (kostenloses Jugendkonto der Sparkassen, Seniorenmenüs). Leistungsbezogen: geringfügige Leistungsänderungen erzeugen Preisklassen (gebundene Ausgabe, Taschenbuch, E-Book). Sonderform Preisbündelung: mehrere Leistungen zu einem günstigeren Paketpreis (MagentaEINS der Telekom).',
    explanation: 'Kernpunkte laut Skript: Segmente haben unterschiedliche Zahlungsbereitschaften; mengenmäßig, zeitlich, räumlich, personell, leistungsbezogen und Preisbündelung als Sonderform.',
    source: 'Kapitel 4.2, PDF S. 18–19', conceptIds: ['mc-preisdiff'],
  },
  {
    id: 'qm4-24', chapterId: 'm4', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein Fitnessstudio bietet (a) Studierenden einen Rabatt, (b) vormittags günstigere Tarife, (c) bei einem Jahresvertrag einen niedrigeren Monatspreis als bei Monatsverträgen und (d) eine teurere Premium-Mitgliedschaft mit Sauna an. Ordnen Sie die Maßnahmen den Formen der Preisdifferenzierung zu.',
    rubric: [
      { point: '(a) Personelle Preisdifferenzierung', keywords: ['personell'] },
      { point: '(b) Zeitliche Preisdifferenzierung (Auslastung)', keywords: ['zeitlich'] },
      { point: '(c) Mengenmäßige Preisdifferenzierung (größere Abnahmemenge, geringerer Durchschnittspreis)', keywords: ['mengenmäßig', 'menge'] },
      { point: '(d) Leistungsbezogene Preisdifferenzierung', keywords: ['leistungsbezogen', 'leistung'] },
    ],
    modelAnswer: '(a) Studierendenrabatt = personelle Preisdifferenzierung (Vergünstigung für eine Personengruppe). (b) Günstigere Vormittagstarife = zeitliche Preisdifferenzierung zur besseren Auslastung der Kapazitäten (wie Nachmittagsvorstellungen im Kino). (c) Jahresvertrag mit niedrigerem Monatspreis = mengenmäßige Preisdifferenzierung (geringerer Durchschnittspreis bei höherer Abnahmemenge). (d) Premium-Mitgliedschaft mit Sauna = leistungsbezogene Preisdifferenzierung (veränderte Leistung erzeugt eine andere Preisklasse).',
    explanation: 'Anwendung der Formen auf einen neuen Fall.',
    source: 'Kapitel 4.2, PDF S. 18–19', conceptIds: ['mc-preisdiff'],
  },
  {
    id: 'qm4-25', chapterId: 'm4', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Erläutern Sie Yield Management und nennen Sie die sechs Bedingungen, unter denen es sinnvoll ist, sowie typische Einsatzbereiche.',
    rubric: [
      { point: 'Nachfrage erlösmaximal mit vorhandenen Kapazitäten synchronisieren; von Fluglinien entwickelt', keywords: ['erlösmaximal', 'kapazität', 'synchronis', 'fluglinie'] },
      { point: 'Fixe Kapazitäten, nicht lagerbare Güter', keywords: ['fixe kapazität', 'nicht lagerbar'] },
      { point: 'Hohe Fixkosten/geringe variable Kosten, starke Nachfrageschwankungen', keywords: ['fixkosten', 'variable kosten', 'nachfrageschwankung'] },
      { point: 'Vorausbuchung, Preisdifferenzierung möglich', keywords: ['vorausbuchung', 'preisdifferenzierung'] },
      { point: 'Einsatz: Hotels, Transportunternehmen, Konzerttickets', keywords: ['hotel', 'transport', 'konzert'] },
    ],
    modelAnswer: 'Beim Yield Management soll die Nachfrage erlösmaximal mit den vorhandenen Kapazitäten synchronisiert werden; ursprünglich wurde es von Fluglinien entwickelt. Sinnvoll ist es bei (1) fixen Kapazitäten, (2) nicht lagerbaren Gütern, (3) hohen Fixkosten und geringen variablen Kosten, (4) starken Nachfrageschwankungen, (5) Vorausbuchung und (6) möglicher Preisdifferenzierung. Typische Bereiche sind Hotels, Transportunternehmen und Konzerttickets.',
    explanation: 'Laut Skript (S. 19): fixe Kapazitäten, nicht lagerbare Güter, hohe Fixkosten und geringe variable Kosten, starke Nachfrageschwankungen, Vorausbuchung, Preisdifferenzierung möglich. Einsatz insbesondere bei Hotels, Transportunternehmen und Konzerttickets.',
    source: 'Kapitel 4.3, PDF S. 19', conceptIds: ['mc-yield', 'mc-dynamic', 'mc-auction', 'mc-reverse'],
  },
  {
    id: 'qm4-26', chapterId: 'm4', type: 'open', goal: 'distinction', difficulty: 2,
    prompt: 'Grenzen Sie Dynamic Pricing, Auction Pricing und Reverse Pricing voneinander ab und nennen Sie die Beispiele aus dem Skript.',
    rubric: [
      { point: 'Dynamic Pricing: Preise ändern sich automatisch nach Nachfrageintensität, Algorithmen (Uber zu Stoßzeiten)', keywords: ['automatisch', 'nachfrageintensität', 'algorithm', 'uber'] },
      { point: 'Auction Pricing: Preis durch Auktion (eBay)', keywords: ['auktion', 'ebay'] },
      { point: 'Auction-Nachteil: Preise ggf. unter Herstellerkosten, Gestaltungsbereich aufgegeben', keywords: ['herstellerkosten', 'aufgegeben', 'unter den kosten'] },
      { point: 'Reverse Pricing: Kunden nennen Bedürfnisse und Preisvorstellungen, Unternehmen bieten (kundenorientierte Preisdifferenzierung)', keywords: ['preisvorstellung', 'kunden geben', 'umgekehrt', 'angebote ab', 'individuell'] },
    ],
    modelAnswer: 'Beim Dynamic Pricing verändern sich die Verkaufspreise automatisch je nach Nachfrageintensität; der optimale Preis wird über Algorithmen bestimmt (z. B. Frühbucher- und Last-Minute-Nachlässe, höhere Uber-Kosten zu Stoßzeiten). Beim Auction Pricing wird der Preis durch Auktionen ermittelt (eBay): Unternehmen müssen sich nicht mit Preispolitik beschäftigen, aber die Preise können unter den Herstellerkosten liegen – ein wichtiger Gestaltungsbereich des Marketingmix wird aufgegeben. Beim Reverse Pricing gilt das umgekehrte Prinzip: Kunden geben im Internet ihre Bedürfnisse (z. B. Hotel, Handwerkerleistung) und Preisvorstellungen an, Unternehmen machen passende Angebote – sehr individuelle Preise im Sinne einer kundenorientierten Preisdifferenzierung.',
    explanation: 'Drei innovative Preismodelle im Vergleich.',
    source: 'Kapitel 4.3, PDF S. 19', conceptIds: ['mc-dynamic', 'mc-auction', 'mc-reverse'],
  },
  {
    id: 'qm4-27', chapterId: 'm4', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Was ist Konditionenpolitik, warum spielt sie besonders im B2B-Bereich eine große Rolle und welche Elemente gehören dazu?',
    rubric: [
      { point: 'Festgelegte Endpreise werden nicht unbedingt tatsächlich entrichtet', keywords: ['nicht tatsächlich', 'endpreis', 'entrichten'] },
      { point: 'Besonders wichtig im B2B-Bereich', keywords: ['b2b'] },
      { point: 'Elemente: Absatzkredite, Lieferungs- und Zahlungsbedingungen, Rabatte', keywords: ['absatzkredit', 'lieferungs', 'zahlungsbedingung', 'rabatt'] },
      { point: 'Absatzkredite ermöglichen/erleichtern den Kauf', keywords: ['ermöglichen', 'erleichtern'] },
    ],
    modelAnswer: 'Die Festlegung der Endpreise bedeutet nicht, dass Konsumenten diese auch tatsächlich entrichten – besonders im B2B-Bereich wird über Konditionen verhandelt, daher spielt die Konditionenpolitik dort eine große Rolle. Dazu zählen Absatzkredite (durch sie ermöglichen oder erleichtern Unternehmen potenziellen Kunden den Kauf der eigenen Erzeugnisse), Lieferungs- und Zahlungsbedingungen sowie Rabatte (Funktions-, Mengen-, Zeit- und Treuerabatte).',
    explanation: 'Kernpunkte laut Skript: Endpreise werden nicht immer tatsächlich entrichtet, v. a. im B2B wichtig; Absatzkredite, Lieferungs- und Zahlungsbedingungen, Rabatte.',
    source: 'Kapitel 4.3, PDF S. 19–20', conceptIds: ['mc-konditionenpolitik', 'mc-rabatte'],
  },
  {
    id: 'qm4-28', chapterId: 'm4', type: 'open', goal: 'fact', difficulty: 2,
    prompt: 'Erläutern Sie die vier Typen von Rabatten nach Walsh/Deseniss/Kilian (2013) und ordnen Sie Skonto und Boni ein.',
    rubric: [
      { point: 'Funktionsrabatt: für vom Handel übernommene Funktionen (Lagerung, Präsentation, Kundenkontakt)', keywords: ['funktionsrabatt', 'lagerung', 'präsentation', 'kundenkontakt'] },
      { point: 'Mengenrabatt: für größere Bestellmengen', keywords: ['mengenrabatt', 'größerer mengen', 'menge'] },
      { point: 'Zeitrabatt: nach Bestellzeit (vor der Saison); Skonto = Sonderform für frühe Zahlung', keywords: ['zeitrabatt', 'bestellzeit', 'saison', 'skonto', 'frühzeitig'] },
      { point: 'Treuerabatt: für langfristige, kontinuierliche Bestellungen', keywords: ['treuerabatt', 'langfristig', 'kontinuierlich'] },
      { point: 'Boni: rückwirkende Nachlässe am Ende einer Abrechnungsperiode', keywords: ['boni', 'rückwirkend', 'abrechnungsperiode'], weight: 0.5 },
    ],
    modelAnswer: 'Funktionsrabatte sind die Gegenleistung für vom Handel übernommene Funktionen wie Lagerung, Präsentation oder Kundenkontakt. Mengenrabatte gibt es für die Bestellung größerer Mengen durch das Handelsunternehmen. Zeitrabatte hängen von der Bestellzeit ab, z. B. vor der Saison; Skonto ist eine Sonderform für eine frühzeitige Zahlung. Treuerabatte belohnen langfristige und kontinuierliche Bestellungen. Boni sind dagegen rückwirkende Nachlässe am Ende einer Abrechnungsperiode, etwa über eine Kundenkarte; Rabatte, Boni und Skonti zählen zu den Preisnachlässen.',
    explanation: 'Kernpunkte laut Skript: Vier Rabattarten, Einordnung von Skonto und Boni.',
    source: 'Kapitel 4.1 und 4.3, PDF S. 17 und 20', conceptIds: ['mc-rabatte', 'mc-preisinstrumente'],
  },
  {
    id: 'qm4-29', chapterId: 'm4', type: 'transfer', goal: 'application', difficulty: 2,
    prompt: 'Hersteller A bringt eine neue Spielkonsole zu einem sehr hohen Preis heraus und senkt ihn nach einem Jahr deutlich. Hersteller B verkauft Drucker sehr günstig, die passenden Tintenpatronen aber teuer. Welche Strategien der Preisabfolge verfolgen A und B?',
    rubric: [
      { point: 'A: Skimmingstrategie – hoher Einführungspreis für Innovatoren/Frühadopter, später Senkung für die Mehrheit', keywords: ['skimming', 'abschöpf'] },
      { point: 'B: Penetrationslogik – niedriger Einstiegspreis zur schnellen Marktdurchdringung, Erlöse über Verbrauchsmaterial', keywords: ['penetration', 'durchdring'] },
      { point: 'Analogie zum Skript-Beispiel Rasierer günstig/Klingen teuer bzw. iPhone-Preissenkung', keywords: ['rasierer', 'klingen', 'iphone'], weight: 0.5 },
    ],
    modelAnswer: 'Hersteller A verfolgt die Skimmingstrategie: Ein sehr hoher Einführungspreis schöpft die Preisbereitschaft von Innovatoren und Frühadoptern ab; sind diese Segmente gesättigt, wird der Preis für die frühe und späte Mehrheit gesenkt (wie Apple beim iPhone 7). Hersteller B nutzt die Logik der Penetrationsstrategie wie im Skript-Beispiel Rasierer/Klingen: Mit einem geringen Einstiegspreis wird der Markt schnell durchdrungen, verdient wird anschließend über die teuren Nachfüllprodukte.',
    explanation: 'Übertragung der Skript-Beispiele auf neue Fälle.',
    source: 'Kapitel 4.2, PDF S. 18', conceptIds: ['mc-preisabfolge'],
  },
  {
    id: 'qm4-30', chapterId: 'm4', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein Hersteller kalkuliert seine Preise ausschließlich als Stückkosten plus 20 % Aufschlag. Die Konkurrenz bietet vergleichbare Produkte deutlich günstiger an, und viele Kunden halten das Produkt ohnehin für weniger wertvoll. Beurteilen Sie das Vorgehen und empfehlen Sie Verfahren aus dem Skript.',
    rubric: [
      { point: 'Kostenorientierte Preisbestimmung erkannt', keywords: ['kostenorientiert', 'stückkosten', 'aufschlag'] },
      { point: 'Problem: vernachlässigt Nachfrage (Zahlungsbereitschaft/empfundener Wert) und Wettbewerb (Konkurrenzpreise)', keywords: ['vernachlässigt', 'nachfrage', 'wettbewerb', 'konkurrenz'] },
      { point: 'Empfehlung: marktorientierte Preisbestimmung, z. B. Perceived-Value-Pricing', keywords: ['marktorientiert', 'perceived', 'empfundenen wert'] },
      { point: 'Ergänzend: Break-even-Analyse / Cournot-Preis', keywords: ['break-even', 'gewinnschwelle', 'cournot'] },
    ],
    modelAnswer: 'Der Hersteller nutzt die kostenorientierte Preisbestimmung (Stückkosten plus Aufschlag). Sie ist zwar einfach, schnell und transparent, vernachlässigt aber jegliche nachfrage- und wettbewerbsbezogenen Aspekte – genau das zeigt sich hier: Die Konkurrenz ist günstiger, und der empfundene Wert der Kunden liegt unter dem Preis. Empfehlenswert ist eine marktorientierte Preisbestimmung: Perceived-Value-Pricing richtet den Preis am empfundenen Wert aus Kundensicht aus; eine Break-even-Analyse zeigt, welche Absatzmenge bei einem marktfähigen Preis zur Gewinnschwelle nötig ist; der Cournot-Preis ermittelt mithilfe der Preis-Absatz-Funktion den gewinnmaximalen Preis.',
    explanation: 'Schwäche der Kostenorientierung im Wettbewerb.',
    source: 'Kapitel 4.3, PDF S. 19', conceptIds: ['mc-kostenorientiert', 'mc-marktorientiert', 'mc-einflussfaktoren-preis'],
  },
  {
    id: 'qm4-31', chapterId: 'm4', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Was versteht man unter dem langfristigen Kundenwert (Customer Lifetime Value) und wie hängt er mit dem kostenlosen Jugendkonto der Sparkassen zusammen?',
    rubric: [
      { point: 'CLV: Wert eines Kunden über die gesamte Zeit seiner Kundschaft', keywords: ['gesamte zeit', 'kundschaft', 'über die gesamte'] },
      { point: 'Jugendkonto = personelle Preisdifferenzierung', keywords: ['personell', 'personengruppe', 'jugend'] },
      { point: 'Ziel: Maximierung des langfristigen Kundenwerts (heute kostenlos, später wertvoller Kunde)', keywords: ['maximierung', 'langfristig', 'kundenwert', 'später'] },
    ],
    modelAnswer: 'Der Customer Lifetime Value ist der Wert, den ein Kunde über die gesamte Zeit seiner Kundschaft für ein Unternehmen darstellt. Das kostenlose Jugendkonto der Sparkassen ist eine personelle Preisdifferenzierung: Jugendliche erhalten eine Vergünstigung, damit sie als Kunden gewonnen werden und der langfristige Kundenwert maximiert wird – die Bank verzichtet heute auf Erlöse, um über die gesamte Kundenbeziehung mehr zu verdienen.',
    explanation: 'Kernpunkte laut Skript: Customer Lifetime Value = Wert eines Kunden über die gesamte Zeit seiner Kundschaft; Beispiel kostenloses Jugendkonto der Sparkassen (personelle Preisdifferenzierung).',
    source: 'Kapitel 4.2, PDF S. 19', conceptIds: ['mc-clv', 'mc-preisdiff'],
  },

  // ======================= neue geschlossene Fragen =======================
  {
    id: 'qm4-32', chapterId: 'm4', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Welche Beispiele nennt das Skript für externe Rahmenbedingungen der Preisfestlegung?',
    options: [
      'Handelsstruktur, gesamtwirtschaftliche Situation, saisonale Nachfrageschwankungen',
      'Stückkosten und Gewinnaufschlag',
      'Schwellenpreise und Nachkommastellen',
      'Zahlungsbereitschaft des Kundensegments',
    ],
    correctOptions: [0],
    explanation: 'Externe Rahmenbedingungen: Handelsstruktur (z. B. Discounter vs. exklusiver Partner), Gesamtwirtschaft, Saisonalität.',
    source: 'Kapitel 4.1, PDF S. 16', conceptIds: ['mc-einflussfaktoren-preis'],
  },
  {
    id: 'qm4-33', chapterId: 'm4', type: 'true_false', goal: 'understanding', difficulty: 2,
    prompt: 'Laut Skript müssen der wahrgenommene Nutzen eines Produkts und die realen Herstellerkosten eng zusammenhängen.',
    correctBool: false,
    explanation: 'Falsch – sie müssen NICHT zusammenhängen (Beispiel Starbucks).',
    source: 'Kapitel 4.1, PDF S. 16', conceptIds: ['mc-einflussfaktoren-preis'],
  },
  {
    id: 'qm4-34', chapterId: 'm4', type: 'single_choice', goal: 'fact', difficulty: 2,
    prompt: 'Was beschreibt der Quotient a/b bei der linearen Preis-Absatz-Funktion x(p) = a – b · p?',
    options: ['Den Maximalpreis, bei dem keine Nachfrage mehr existiert', 'Die maximale Sättigungsmenge', 'Die Preisabhängigkeit der Absatzmenge', 'Den gewinnmaximalen Preis'],
    correctOptions: [0],
    explanation: 'a = Sättigungsmenge (Absatz bei Preis 0); a/b = Maximalpreis (Absatz 0).',
    source: 'Kapitel 4.1, PDF S. 17', conceptIds: ['mc-paf-linear'],
  },
  {
    id: 'qm4-35', chapterId: 'm4', type: 'cloze', goal: 'fact', difficulty: 2,
    prompt: 'Bei der linearen Preis-Absatz-Funktion ist a die maximale ______ (Absatz bei Preis 0); der Preis, bei dem keine Nachfrage mehr existiert, heißt ______.',
    clozeAnswers: [['Sättigungsmenge'], ['Maximalpreis']],
    explanation: 'a = Sättigungsmenge, a/b = Maximalpreis.',
    source: 'Kapitel 4.1, PDF S. 17', conceptIds: ['mc-paf-linear'],
  },
  {
    id: 'qm4-36', chapterId: 'm4', type: 'single_choice', goal: 'fact', difficulty: 3,
    prompt: 'Welche Bedeutung hat der Parameter a im multiplikativen Preis-Absatz-Modell x(p) = a · p^(–b)?',
    options: [
      'Normierungsparameter: verkaufte Menge bei einem Preis von einer Geldeinheit',
      'Maximale Sättigungsmenge bei Preis 0',
      'Maximalpreis',
      'Stärke der Konkurrenzreaktion',
    ],
    correctOptions: [0],
    explanation: 'Im multiplikativen Modell gibt es weder Sättigungsmenge noch Maximalpreis; a ist ein Normierungsparameter, b indiziert die Preisabhängigkeit.',
    source: 'Kapitel 4.1, PDF S. 17', conceptIds: ['mc-paf-mult'],
  },
  {
    id: 'qm4-37', chapterId: 'm4', type: 'assignment', goal: 'fact', difficulty: 2,
    prompt: 'Bringen Sie die Schritte des Prozesses der Preisfestlegung (Bruhn 2016) in die richtige Reihenfolge.',
    pairs: [
      { left: 'Analyse des preispolitischen Spielraums', right: 'Schritt 1' },
      { left: 'Festlegung spezifischer preispolitischer Zielsetzungen', right: 'Schritt 2' },
      { left: 'Preispolitische Strategieentwicklung', right: 'Schritt 3' },
      { left: 'Einsatz der Preisinstrumente', right: 'Schritt 4' },
      { left: 'Preiskontrolle', right: 'Schritt 5' },
    ],
    explanation: 'Spielraum → Ziele → Strategie → Instrumente → Kontrolle.',
    source: 'Kapitel 4.1, PDF S. 17', conceptIds: ['mc-preisprozess'],
  },
  {
    id: 'qm4-38', chapterId: 'm4', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche gehören zu den vier zentralen Preisinstrumenten? (Mehrfachauswahl)',
    options: ['Preise', 'Preisnachlässe (Rabatte, Boni, Skonti)', 'Preiszuschläge', 'Zugabe von Geld- und Sachwerten sowie Dienstleistungen', 'Plakatwerbung'],
    correctOptions: [0, 1, 2, 3],
    explanation: 'Plakatwerbung ist ein Kommunikationsinstrument.',
    source: 'Kapitel 4.1, PDF S. 17', conceptIds: ['mc-preisinstrumente'],
  },
  {
    id: 'qm4-39', chapterId: 'm4', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Was sind Boni?',
    options: [
      'Rückwirkende Nachlässe am Ende einer Abrechnungsperiode, etwa über eine Kundenkarte',
      'Nachlässe für eine frühzeitige Zahlung',
      'Aufschläge für Sonderleistungen',
      'Kredite, die den Kauf ermöglichen',
    ],
    correctOptions: [0],
    explanation: 'Frühe Zahlung = Skonto; Aufschläge = Preiszuschläge; Kredite = Absatzkredite.',
    source: 'Kapitel 4.1, PDF S. 17', conceptIds: ['mc-preisinstrumente', 'mc-rabatte'],
  },
  {
    id: 'qm4-40', chapterId: 'm4', type: 'single_choice', goal: 'understanding', difficulty: 2,
    prompt: 'An wen richtet sich das Preisinstrument „Zugabe von Geld- und Sachwerten sowie Dienstleistungen“ vor allem?',
    options: [
      'An den Handel – es soll die Akzeptanz der geforderten Preise unterstützen (z. B. Verkostungen, Displaymaterial)',
      'Ausschließlich an Endverbraucher',
      'An die eigenen Mitarbeiter',
      'An die Konkurrenz',
    ],
    correctOptions: [0],
    explanation: 'Zugaben richten sich vor allem an den Handel.',
    source: 'Kapitel 4.1, PDF S. 17', conceptIds: ['mc-preisinstrumente'],
  },
  {
    id: 'qm4-41', chapterId: 'm4', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie die Strategie der Preispositionierung dem Beispiel aus der Möbelbranche zu.',
    pairs: [
      { left: 'Hochpreisstrategie', right: 'BoConcept, Seyfarth' },
      { left: 'Mittelpreisstrategie', right: 'Höffner, Kraft, XXXL-Marken der Lutz-Gruppe' },
      { left: 'Niedrigpreisstrategie', right: 'Roller, Poco, Sconto' },
    ],
    explanation: 'Designmöbelstudios – Vollsortimenter – Möbeldiscounter.',
    source: 'Kapitel 4.2, PDF S. 18', conceptIds: ['mc-preispositionierung'],
  },
  {
    id: 'qm4-42', chapterId: 'm4', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie die Strategie des Preiswettbewerbs dem Beispiel zu.',
    pairs: [
      { left: 'Preisführerschaft', right: 'Apple iPhone X ab 999 Dollar' },
      { left: 'Preiskampf', right: 'Lebensmitteldiscounter wollen den niedrigsten Preis' },
      { left: 'Preisfolgerschaft', right: 'Senkt Aldi die Preise, ziehen Norma und Netto nach' },
    ],
    explanation: 'Führen – Kämpfen – Folgen.',
    source: 'Kapitel 4.2, PDF S. 18', conceptIds: ['mc-preiswettbewerb'],
  },
  {
    id: 'qm4-43', chapterId: 'm4', type: 'single_choice', goal: 'application', difficulty: 2,
    prompt: 'Apple senkte den Preis des iPhone 7 mit Vorstellung von iPhone 8 und X von 759 auf 629 Euro. Für welche Strategie ist das ein Beispiel?',
    options: ['Skimmingstrategie', 'Penetrationsstrategie', 'Preiskampf', 'Räumliche Preisdifferenzierung'],
    correctOptions: [0],
    explanation: 'Erst hoher Preis für Innovatoren und Frühadopter, dann Senkung für die Mehrheit.',
    source: 'Kapitel 4.2, PDF S. 18', conceptIds: ['mc-preisabfolge'],
  },
  {
    id: 'qm4-44', chapterId: 'm4', type: 'true_false', goal: 'fact', difficulty: 2,
    prompt: 'Netflix verlor 2011 nach einer Preiserhöhung von 60 % (Entkopplung von DVD-Verleih und Streaming) 800.000 Kunden und 77 % des Börsenwerts.',
    correctBool: true,
    explanation: 'Richtig – Beispiel dafür, dass Strategien der Preisabfolge nicht immer erfolgreich sind.',
    source: 'Kapitel 4.2, PDF S. 18', conceptIds: ['mc-preisabfolge'],
  },
  {
    id: 'qm4-45', chapterId: 'm4', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie das Skript-Beispiel der Form der Preisdifferenzierung zu.',
    pairs: [
      { left: 'Kartenmacherei: 3,63 € bei 5 Stück, 1,35 € bei 500 Stück', right: 'mengenmäßig' },
      { left: 'Kinotag am Wochenanfang', right: 'zeitlich' },
      { left: 'Benzin in Stadtstaaten günstiger als in Flächenländern', right: 'räumlich' },
      { left: 'Seniorenmenüs mit kleineren Portionen', right: 'personell' },
      { left: 'Gebundene Ausgabe, Taschenbuch und E-Book', right: 'leistungsbezogen' },
    ],
    explanation: 'Fünf Formen der Preisdifferenzierung mit Skript-Beispielen.',
    source: 'Kapitel 4.2, PDF S. 18–19', conceptIds: ['mc-preisdiff'],
  },
  {
    id: 'qm4-46', chapterId: 'm4', type: 'single_choice', goal: 'application', difficulty: 1,
    prompt: 'Der MagentaEINS-Tarif der Telekom bietet mehrere Leistungen zu einem günstigeren Paketpreis an. Wie nennt man das?',
    options: ['Preisbündelung', 'Penetrationsstrategie', 'Reverse Pricing', 'Treuerabatt'],
    correctOptions: [0],
    explanation: 'Preisbündelung ist die Sonderform der Preisdifferenzierung.',
    source: 'Kapitel 4.2, PDF S. 19', conceptIds: ['mc-preisdiff'],
  },
  {
    id: 'qm4-47', chapterId: 'm4', type: 'single_choice', goal: 'fact', difficulty: 2,
    prompt: 'Was leistet die Break-even-Analyse?',
    options: [
      'Sie bezieht die erforderliche Absatzmenge bei einem gegebenen Preis ein, um die Gewinnschwelle zu erreichen.',
      'Sie bestimmt den Preis nach dem empfundenen Wert aus Kundensicht.',
      'Sie ermittelt den gewinnmaximalen Preis mithilfe der Preis-Absatz-Funktion.',
      'Sie addiert einen Aufschlag auf die Stückkosten.',
    ],
    correctOptions: [0],
    explanation: 'Option 2 = Perceived-Value-Pricing, Option 3 = Cournot-Preis, Option 4 = kostenorientierte Preisbestimmung.',
    source: 'Kapitel 4.3, PDF S. 19', conceptIds: ['mc-marktorientiert'],
  },
  {
    id: 'qm4-48', chapterId: 'm4', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie das Verfahren der marktorientierten Preisbestimmung seiner Beschreibung zu.',
    pairs: [
      { left: 'Break-even-Analyse', right: 'Erforderliche Absatzmenge bei gegebenem Preis bis zur Gewinnschwelle' },
      { left: 'Perceived-Value-Pricing', right: 'Preisbildung nach dem empfundenen Wert aus Kundensicht' },
      { left: 'Cournot-Preis', right: 'Gewinnmaximaler Preis unter Verwendung der Preis-Absatz-Funktion' },
    ],
    explanation: 'Drei marktorientierte Verfahren.',
    source: 'Kapitel 4.3, PDF S. 19', conceptIds: ['mc-marktorientiert'],
  },
  {
    id: 'qm4-49', chapterId: 'm4', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Unter welchen Bedingungen ist Yield Management laut Skript sinnvoll? (Mehrfachauswahl)',
    options: ['Fixe Kapazitäten', 'Nicht lagerbare Güter', 'Hohe Fixkosten und geringe variable Kosten', 'Möglichst konstante Nachfrage ohne Schwankungen', 'Vorausbuchung'],
    correctOptions: [0, 1, 2, 4],
    explanation: 'Erforderlich sind STARKE Nachfrageschwankungen – nicht konstante Nachfrage. Sechste Bedingung: Preisdifferenzierung möglich.',
    source: 'Kapitel 4.3, PDF S. 19', conceptIds: ['mc-yield'],
  },
  {
    id: 'qm4-50', chapterId: 'm4', type: 'single_choice', goal: 'application', difficulty: 1,
    prompt: 'Uber verlangt zu Stoßzeiten automatisch höhere Preise. Welches Preismodell ist das?',
    options: ['Dynamic Pricing', 'Auction Pricing', 'Reverse Pricing', 'Kostenorientierte Preisbestimmung'],
    correctOptions: [0],
    explanation: 'Dynamic Pricing: Preise verändern sich automatisch je nach Nachfrageintensität.',
    source: 'Kapitel 4.3, PDF S. 19', conceptIds: ['mc-dynamic'],
  },
  {
    id: 'qm4-51', chapterId: 'm4', type: 'true_false', goal: 'understanding', difficulty: 2,
    prompt: 'Ein Nachteil des Auction Pricing ist, dass die Verkaufspreise unter den Herstellerkosten liegen können.',
    correctBool: true,
    explanation: 'Richtig – zudem wird ein wichtiger Gestaltungsbereich des Marketingmix aufgegeben. Vorteil: Man muss sich nicht mit Preispolitik beschäftigen.',
    source: 'Kapitel 4.3, PDF S. 19', conceptIds: ['mc-auction'],
  },
  {
    id: 'qm4-52', chapterId: 'm4', type: 'single_choice', goal: 'fact', difficulty: 2,
    prompt: 'Wie funktioniert Reverse Pricing?',
    options: [
      'Kunden nennen im Internet Bedürfnisse und Preisvorstellungen, Unternehmen geben entsprechende Angebote ab.',
      'Der Preis wird durch Versteigerung ermittelt.',
      'Der Preis passt sich automatisch der Nachfrage an.',
      'Der Preis sinkt mit steigender Abnahmemenge.',
    ],
    correctOptions: [0],
    explanation: 'Reverse Pricing = umgekehrtes Prinzip, sehr individuelle Preise (kundenorientierte Preisdifferenzierung).',
    source: 'Kapitel 4.3, PDF S. 19', conceptIds: ['mc-reverse'],
  },
  {
    id: 'qm4-53', chapterId: 'm4', type: 'cloze', goal: 'fact', difficulty: 2,
    prompt: 'Zur Konditionenpolitik zählen ______, Lieferungs- und Zahlungsbedingungen sowie ______.',
    clozeAnswers: [['Absatzkredite', 'Absatzkredit'], ['Rabatte', 'Rabatt']],
    explanation: 'Konditionenpolitik: Absatzkredite, Lieferungs- und Zahlungsbedingungen, Rabatte – besonders wichtig im B2B.',
    source: 'Kapitel 4.3, PDF S. 20', conceptIds: ['mc-konditionenpolitik'],
  },
  {
    id: 'qm4-54', chapterId: 'm4', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Skonto ist laut Skript eine Sonderform des …',
    options: ['Zeitrabatts', 'Mengenrabatts', 'Treuerabatts', 'Funktionsrabatts'],
    correctOptions: [0],
    explanation: 'Skonto = Sonderform des Zeitrabatts für eine frühzeitige Zahlung.',
    source: 'Kapitel 4.3, PDF S. 20', conceptIds: ['mc-rabatte'],
  },
  {
    id: 'qm4-55', chapterId: 'm4', type: 'true_false', goal: 'fact', difficulty: 1,
    prompt: 'Ein Funktionsrabatt ist eine Gegenleistung für Funktionen, die der Handel übernimmt – etwa Lagerung, Präsentation oder Kundenkontakt.',
    correctBool: true,
    explanation: 'Richtig.',
    source: 'Kapitel 4.3, PDF S. 20', conceptIds: ['mc-rabatte'],
  },
  {
    id: 'qm4-56', chapterId: 'm4', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Was versteht das Skript unter dem preispolitischen Spielraum?',
    options: [
      'Den Preiskorridor zwischen Preisuntergrenze und Preisobergrenze',
      'Die Spanne zwischen Einkaufs- und Verkaufspreis des Handels',
      'Die Zahl der möglichen Rabattarten',
      'Den Zeitraum bis zur nächsten Preiserhöhung',
    ],
    correctOptions: [0],
    explanation: 'Seine Analyse ist Schritt 1 des Prozesses der Preisfestlegung.',
    source: 'Kapitel 4.1, PDF S. 17', conceptIds: ['mc-preisprozess'],
  },
];
