import { Question } from '@/lib/types';

/** Textfragen zu Kapitel 1–3 (Grundlagen, Produktpolitik, Kommunikationspolitik). */
export const questions13: Question[] = [
  // ================= Kapitel 1: Grundlagen =================
  {
    id: 'qm1-01', chapterId: 'm1', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Wovon leitet sich der Begriff „Marketing“ ab?',
    options: ['Von „(to) market“ – Markt und vermarkten', 'Von „management“ – führen', 'Von „to make“ – herstellen', 'Vom lateinischen „mercatus“ allein'],
    correctOptions: [0],
    explanation: 'Marketing kommt von „(to) market“: Markt und vermarkten. Der Markt ist zugleich Ziel- und Bezugsobjekt des Marketings.',
    source: 'Kapitel 1.1, PDF S. 1', conceptIds: ['mc-marketing'],
  },
  {
    id: 'qm1-02', chapterId: 'm1', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Auf einem Käufermarkt gilt …',
    options: [
      'Das Angebot ist größer als die Nachfrage – der Nachfrager steht im Zentrum.',
      'Die Nachfrage ist größer als das Angebot – der Anbieter steht im Zentrum.',
      'Angebot und Nachfrage sind stets exakt gleich.',
      'Es gibt weder Angebot noch Nachfrage.',
    ],
    correctOptions: [0],
    explanation: 'Käufermarkt: Angebot > Nachfrage, die Nachfrage ist der Engpass, der Nachfrager steht im Zentrum des modernen Marketings. Die meisten Märkte sind heute Käufermärkte.',
    source: 'Kapitel 1.1, PDF S. 1–2', conceptIds: ['mc-kaeufermarkt'],
  },
  {
    id: 'qm1-03', chapterId: 'm1', type: 'true_false', goal: 'fact', difficulty: 1,
    prompt: 'Das Gratifikationsprinzip besagt, dass die im Tausch gehandelten Ressourcen knapp sind.',
    correctBool: false,
    explanation: 'Falsch – das ist das Knappheitsprinzip. Das Gratifikationsprinzip besagt, dass der Austausch für beide Seiten vorteilhaft sein soll.',
    source: 'Kapitel 1.1, PDF S. 1', conceptIds: ['mc-gratifikation', 'mc-knappheit'],
  },
  {
    id: 'qm1-04', chapterId: 'm1', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche gehören zu den vier Ps des Marketingmix? (Mehrfachauswahl)',
    options: ['Product', 'Price', 'People', 'Place', 'Promotion'],
    correctOptions: [0, 1, 3, 4],
    explanation: 'Die vier Ps: Product, Price, Place, Promotion. „People“ gehört zu den drei zusätzlichen Ps für Dienstleistungen (People, Processes, Physical Facilities).',
    source: 'Kapitel 1.1, PDF S. 2', conceptIds: ['mc-marketingmix'],
  },
  {
    id: 'qm1-05', chapterId: 'm1', type: 'cloze', goal: 'fact', difficulty: 2,
    prompt: 'Die drei Kernbausteine des Marketingbegriffs sind der ______ (Abteilung/Prozess), der ______ (Leitphilosophie) und der aktivitätenorientierte Marketingbegriff (Werkzeugkasten).',
    clozeAnswers: [['funktionale', 'funktionaler', 'funktionale Marketingbegriff'], ['führungsorientierte', 'führungsorientierter', 'führungsorientierte Marketingbegriff']],
    explanation: 'Funktional = Grundfunktion/Abteilung; führungsorientiert = Leitphilosophie; aktivitätenorientiert = Sozialtechnologie/Marketingmix.',
    source: 'Kapitel 1.1, PDF S. 2–3', conceptIds: ['mc-funktional', 'mc-fuehrung', 'mc-aktivitaet'],
  },
  {
    id: 'qm1-06', chapterId: 'm1', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordne die drei Rs des Beziehungsmarketings ihrer Bedeutung zu.',
    pairs: [
      { left: 'Recruitment', right: 'Akquise neuer Kunden' },
      { left: 'Retention', right: 'Bindung bestehender Kunden durch Zufriedenheit' },
      { left: 'Recovery', right: 'Rückgewinnung abgewanderter Kunden' },
    ],
    explanation: 'Die drei Rs strukturieren den Marketingmix nach der Phase der Geschäftsbeziehung: Recruitment, Retention, Recovery.',
    source: 'Kapitel 1.1, PDF S. 3', conceptIds: ['mc-drei-rs', 'mc-beziehung'],
  },
  {
    id: 'qm1-07', chapterId: 'm1', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erkläre den Unterschied zwischen transaktionalem Marketing und Beziehungsmarketing.',
    rubric: [
      { point: 'Transaktional: Fokus auf einzelne Geschäftsabschlüsse, kurzfristig, vier Ps', keywords: ['transaktion', 'abschluss', 'kurzfristig', 'einzeln', '4 ps', 'vier ps'] },
      { point: 'Beziehungsmarketing: Kundenbeziehung im Mittelpunkt, langfristig', keywords: ['beziehung', 'langfristig', 'kundenbeziehung', 'bindung', 'dialog'] },
      { point: 'Herkunft: Dienstleistung/B2B', keywords: ['dienstleistung', 'b2b'], weight: 0.5 },
    ],
    modelAnswer: 'Transaktionales Marketing betrachtet einzelne Geschäftsabschlüsse und bearbeitet den Markt kurzfristig mit den vier Ps. Beim Beziehungsmarketing steht dagegen die langfristige Kundenbeziehung im Mittelpunkt – sie wird aktiv analysiert, gestaltet und gepflegt. Diese Sicht stammt aus Dienstleistung und B2B, wo dauerhafte Beziehungen (z. B. zur Werkstatt) typisch sind.',
    explanation: 'Kern: Einzeltransaktion vs. dauerhafte Beziehung; Paradigmenwechsel im Marketing.',
    source: 'Kapitel 1.1, PDF S. 3', conceptIds: ['mc-transaktional', 'mc-beziehung'],
  },
  {
    id: 'qm1-08', chapterId: 'm1', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Ein Unternehmen bietet vergleichbare Produkte deutlich günstiger als die Konkurrenz an und nutzt dafür Kostendegressionseffekte. Welche Strategie liegt vor?',
    options: ['Kostenführerstrategie', 'Qualitätsführerschaft', 'Nischenstrategie', 'Points-of-Difference-Strategie'],
    correctOptions: [0],
    explanation: 'Kostenführerschaft: gleiche Produkte günstiger, über Kostendegression (Standardisierung, effiziente Vertriebswege). Qualitätsführerschaft setzt dagegen auf Differenzierung (besser sein).',
    source: 'Kapitel 1.2, PDF S. 4', conceptIds: ['mc-kostenfuehrer', 'mc-qualitaetsfuehrer'],
  },
  {
    id: 'qm1-09', chapterId: 'm1', type: 'cloze', goal: 'understanding', difficulty: 2,
    prompt: 'Bei der Positionierung sind ______ die Attribute, bei denen die Marke mit dem Wettbewerb gleichauf ist, und ______ die Attribute, die besser sind als die Konkurrenz.',
    clozeAnswers: [['Points of Parity', 'points of parity', 'pop'], ['Points of Difference', 'points of difference', 'pod']],
    explanation: 'Points of Parity = gleichauf; Points of Difference = besser als die Konkurrenz.',
    source: 'Kapitel 1.2, PDF S. 4', conceptIds: ['mc-pop-pod', 'mc-positionierung'],
  },
  {
    id: 'qm1-10', chapterId: 'm1', type: 'assignment', goal: 'fact', difficulty: 3,
    prompt: 'Bringe die sechs Schritte des Marketingmanagements in die richtige Reihenfolge (Zuordnung Schritt → Position).',
    pairs: [
      { left: 'Situationsanalyse', right: 'Schritt 1' },
      { left: 'Marketingziele', right: 'Schritt 2' },
      { left: 'Marketingstrategie', right: 'Schritt 3' },
      { left: 'Marketinginstrumente (4 Ps)', right: 'Schritt 4' },
      { left: 'Implementierung', right: 'Schritt 5' },
      { left: 'Controlling', right: 'Schritt 6' },
    ],
    explanation: 'Reihenfolge: Analyse → Ziele → Strategie → Instrumente → Implementierung → Controlling.',
    source: 'Kapitel 1.3, PDF S. 5–6', conceptIds: ['mc-6schritte', 'mc-marketingmanagement'],
  },
  {
    id: 'qm1-11', chapterId: 'm1', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein Start-up bringt teures, hochwertiges Mineralwasser auf einen Käufermarkt mit über 500 Wettbewerbern. Wie sollte es sich positionieren? Nenne Grundstrategie und je einen möglichen Point of Difference.',
    rubric: [
      { point: 'Qualitäts-/Differenzierungsstrategie (nicht Preis)', keywords: ['qualitaet', 'differenzier', 'premium', 'hochpreis'] },
      { point: 'Konkreter Point of Difference (Herkunft, Reinheit, Design, Nachhaltigkeit)', keywords: ['herkunft', 'reinheit', 'design', 'nachhaltig', 'marke', 'quelle'] },
      { point: 'Bezug Käufermarkt / Abgrenzung vom Wettbewerb', keywords: ['wettbewerb', 'abgrenz', 'kaeufermarkt', 'sichtbar'], weight: 0.5 },
    ],
    modelAnswer: 'Bei über 500 Anbietern lohnt kein Preiskampf; das Start-up sollte auf Qualitätsführerschaft/Differenzierung setzen. Als Point of Difference eignen sich eine besondere Herkunft/Reinheit (wie Fiji Water), ein auffälliges Design oder glaubwürdige Nachhaltigkeit. So hebt es sich im Käufermarkt sichtbar von der Konkurrenz ab und rechtfertigt den höheren Preis.',
    explanation: 'Im gesättigten Käufermarkt schafft ein klarer Point of Difference die nötige Sichtbarkeit; Differenzierung statt Preiskampf.',
    source: 'Kapitel 1.2, PDF S. 4', conceptIds: ['mc-positionierung', 'mc-qualitaetsfuehrer', 'mc-pop-pod'],
  },

  // ================= Kapitel 2: Produktpolitik =================
  {
    id: 'qm2-01', chapterId: 'm2', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Warum spricht man in der Produktpolitik häufig auch von „Leistungspolitik“?',
    options: [
      'Weil Produkte materiell UND immateriell (z. B. digitale Güter, Dienstleistungen) sein können',
      'Weil nur Dienstleistungen gemeint sind',
      'Weil es ausschließlich um die Leistung der Mitarbeiter geht',
      'Weil der Begriff Produkt gesetzlich verboten ist',
    ],
    correctOptions: [0],
    explanation: 'Wegen der Vielfalt materieller und immaterieller Produkte (Streaming, digitale Güter, Dienstleistungen) wird oft der umfassendere Begriff „Leistungspolitik“ verwendet.',
    source: 'Kapitel 2.1, PDF S. 6–7', conceptIds: ['mc-produktpolitik', 'mc-produkt'],
  },
  {
    id: 'qm2-02', chapterId: 'm2', type: 'cloze', goal: 'fact', difficulty: 1,
    prompt: 'Ein Produkt ist ein Bündel von ______ (Ausstattung, Funktionen, Nutzen, Verwendung). Der ______ ist, was der Kunde davon hat; die Leistung ist, was das Unternehmen bietet.',
    clozeAnswers: [['Attributen', 'attributen', 'eigenschaften'], ['Nutzen', 'nutzen']],
    explanation: 'Produkt = Bündel von Attributen. Nutzen = Kundensicht, Leistung = Unternehmenssicht.',
    source: 'Kapitel 2.1, PDF S. 7', conceptIds: ['mc-produkt', 'mc-grundnutzen'],
  },
  {
    id: 'qm2-03', chapterId: 'm2', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordne den Gütertyp nach Kaufgewohnheit dem passenden Beispiel zu.',
    pairs: [
      { left: 'Convenience Good', right: 'Brot, Shampoo – mühelos, regelmäßig gekauft' },
      { left: 'Shopping Good', right: 'Kleidung, Möbel – mit Vergleichsaufwand' },
      { left: 'Specialty Good', right: 'Antiquität, Luxusuhr – einzigartig, hoher Aufwand' },
      { left: 'Unsought Good', right: 'Versicherung – nicht aktiv nachgefragt' },
    ],
    explanation: 'Die vier Kaufgewohnheits-Typen: Convenience, Shopping, Specialty und Unsought Goods.',
    source: 'Kapitel 2.1, PDF S. 8', conceptIds: ['mc-kaufgewohnheit'],
  },
  {
    id: 'qm2-04', chapterId: 'm2', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Ein Hersteller ändert das Design und den Geschmack seines Riegels; die alte Variante verschwindet aus dem Sortiment. Was liegt vor?',
    options: ['Produktvariation', 'Produktdifferenzierung', 'Produktelimination', 'Produktinnovation'],
    correctOptions: [0],
    explanation: 'Produktvariation: Nutzenkomponenten werden verändert, die Basisfunktion bleibt, die alte Version wird ersetzt. Bei Differenzierung blieben beide Varianten im Programm.',
    source: 'Kapitel 2.2, PDF S. 8–9', conceptIds: ['mc-produktvariation', 'mc-produktdiff'],
  },
  {
    id: 'qm2-05', chapterId: 'm2', type: 'true_false', goal: 'distinction', difficulty: 2,
    prompt: 'Bei der Produktdifferenzierung wird das Produktprogramm breiter, weil die neue Variante ZUSÄTZLICH zur bestehenden angeboten wird.',
    correctBool: true,
    explanation: 'Richtig. Produktdifferenzierung spricht ein neues Segment an, beide Versionen bleiben – das Programm erweitert sich. (Variation ersetzt dagegen.)',
    source: 'Kapitel 2.2, PDF S. 9', conceptIds: ['mc-produktdiff', 'mc-produktvariation'],
  },
  {
    id: 'qm2-06', chapterId: 'm2', type: 'cloze', goal: 'fact', difficulty: 2,
    prompt: 'Im Produktprogramm bezeichnet die ______ die Anzahl der Produktlinien und die ______ die Zahl der Produkte pro Linie.',
    clozeAnswers: [['Programmbreite', 'breite'], ['Programmtiefe', 'tiefe']],
    explanation: 'Breite = Anzahl Linien; Tiefe = Produkte je Linie.',
    source: 'Kapitel 2.2, PDF S. 9', conceptIds: ['mc-programmbreite'],
  },
  {
    id: 'qm2-07', chapterId: 'm2', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche Anforderungen soll eine gute Produktverpackung erfüllen? (Mehrfachauswahl)',
    options: ['Das Produkt schützen', 'Werblich anpreisen', 'Anwenderfreundlich sein', 'Möglichst teuer sein', 'Ökologisch entsorgbar sein'],
    correctOptions: [0, 1, 2, 4],
    explanation: 'Eine gute Verpackung schützt, preist an, ist anwenderfreundlich und ökologisch entsorgbar. „Möglichst teuer“ ist kein Ziel.',
    source: 'Kapitel 2.2, PDF S. 9', conceptIds: ['mc-verpackung'],
  },
  {
    id: 'qm2-08', chapterId: 'm2', type: 'assignment', goal: 'fact', difficulty: 3,
    prompt: 'Ordne die Phase des Produktlebenszyklus ihrer typischen Marketing-Aktivität zu.',
    pairs: [
      { left: 'Einführung', right: 'Nachfrage stimulieren' },
      { left: 'Wachstum', right: 'Kampf um Marktanteile über Preis und Konditionen' },
      { left: 'Reife', right: 'Erhöhung der Werbeausgaben, Produktdifferenzierung' },
      { left: 'Sättigung', right: 'Preissenkungen' },
      { left: 'Verfall', right: 'Produkt wird nicht mehr unterstützt' },
    ],
    explanation: 'Die fünf Phasen mit ihren typischen Aktivitäten – in der Reifephase sind Erfahrungskurven-/Skaleneffekte am höchsten.',
    source: 'Kapitel 2.3, PDF S. 10', conceptIds: ['mc-lebenszyklus'],
  },
  {
    id: 'qm2-09', chapterId: 'm2', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Warum reicht der klassische Produktlebenszyklus nicht aus, um Technologiesprünge zu erklären, und was leistet das S-Kurvenkonzept zusätzlich?',
    rubric: [
      { point: 'Lebenszyklus nutzt v. a. die Variable Zeit', keywords: ['zeit', 'variable', 'lebenszyklus'] },
      { point: 'S-Kurve: Leistungsfähigkeit über F&E-Aufwand', keywords: ['leistungsfaehigkeit', 'forschung', 'entwicklung', 'aufwand', 'f&e'] },
      { point: 'Technologische Diskontinuität / Grenze / Ablösung', keywords: ['grenze', 'diskontinuitaet', 'abloesung', 'neue technologie', 'sprung'] },
    ],
    modelAnswer: 'Der Produktlebenszyklus erklärt den Verlauf hauptsächlich über die Zeit und blendet aus, dass eine Technologie an eine Leistungsgrenze stößt. Das S-Kurvenkonzept (Foster) trägt stattdessen die Leistungsfähigkeit über die kumulierten F&E-Aufwendungen ab: Jede Technologie flacht an ihrer Grenze ab und wird durch eine neue mit höherem Potenzial abgelöst. So sensibilisiert es das Innovationsmanagement für technologische Diskontinuitäten (Sprünge).',
    explanation: 'Kern: Zeit vs. F&E-Aufwand als Erklärungsvariable; die S-Kurve zeigt Grenzen und Technologiewechsel.',
    source: 'Kapitel 2.3, PDF S. 10', conceptIds: ['mc-skurve', 'mc-lebenszyklus'],
  },
  {
    id: 'qm2-10', chapterId: 'm2', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Was beschreibt der Diffusionsprozess (im Gegensatz zum Adoptionsprozess)?',
    options: [
      'Die kumulierte Übernahme einer Neuerung im gesamten Markt über die Zeit',
      'Die fünf Phasen der Übernahme bei einer einzelnen Person',
      'Die technische Entwicklung eines Produkts im Labor',
      'Die Preisentwicklung über den Lebenszyklus',
    ],
    correctOptions: [0],
    explanation: 'Diffusion = kumulierte Adoption im Markt (S-förmig). Adoption = individuelle Übernahme in fünf Phasen (Aufmerksamkeit, Interesse, Bewertung, Versuch, Annahme).',
    source: 'Kapitel 2.3, PDF S. 11', conceptIds: ['mc-diffusion', 'mc-adoption'],
  },
  {
    id: 'qm2-11', chapterId: 'm2', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein Tech-Unternehmen bringt eine neue Smartwatch heraus. Wie kann es die frühen Adopterkategorien gezielt nutzen, um die Diffusion zu beschleunigen?',
    rubric: [
      { point: 'Innovatoren/Frühadopter zuerst ansprechen', keywords: ['innovatoren', 'fruehadopter', 'frueh', 'zuerst'] },
      { point: 'Sie sind Multiplikatoren/Influencer', keywords: ['multiplikator', 'influencer', 'meinungsfuehrer', 'weiterempfehl'] },
      { point: 'Ziel: frühe/späte Mehrheit nachziehen (Diffusion beschleunigen)', keywords: ['mehrheit', 'diffusion', 'verbreit', 'sog', 'nachziehen'] },
    ],
    modelAnswer: 'Das Unternehmen sollte zuerst die Innovatoren und Frühadopter gewinnen (z. B. über Tech-Communities, Influencer, exklusive Vorabmodelle). Da diese Gruppen einflussreiche Multiplikatoren sind, tragen ihre Empfehlungen die Neuerung zur frühen und späten Mehrheit. So beschleunigt sich die Diffusion, weil die große Masse den frühen Segmenten folgt.',
    explanation: 'Frühe Adopter sind der Hebel: Über ihre Multiplikatorwirkung erreicht man die Mehrheit und beschleunigt die S-Kurve der Diffusion.',
    source: 'Kapitel 2.3, PDF S. 11', conceptIds: ['mc-diffusion', 'mc-adoption'],
  },

  // ================= Kapitel 3: Kommunikationspolitik =================
  {
    id: 'qm3-01', chapterId: 'm3', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Welche drei Aufgaben hat die Kommunikationspolitik grundsätzlich?',
    options: ['Informieren, überzeugen, erinnern', 'Produzieren, lagern, liefern', 'Kaufen, verkaufen, tauschen', 'Planen, steuern, kontrollieren'],
    correctOptions: [0],
    explanation: 'Kommunikationspolitik soll Konsumenten informieren, überzeugen und erinnern – im Sinne der Unternehmensziele.',
    source: 'Kapitel 3.1, PDF S. 11–12', conceptIds: ['mc-kommunikationspolitik'],
  },
  {
    id: 'qm3-02', chapterId: 'm3', type: 'true_false', goal: 'distinction', difficulty: 2,
    prompt: 'Marktanteil, Absatz und Rentabilität sind reine (vorökonomische) Kommunikationsziele.',
    correctBool: false,
    explanation: 'Falsch. Das sind ökonomische Ziele (betreffen den Marketingmix als Ganzes). Reine Kommunikationsziele sind vorökonomisch: Kategoriebedürfnis, Bekanntheit/Image, Einstellungen, Kaufabsicht.',
    source: 'Kapitel 3.1, PDF S. 12', conceptIds: ['mc-komm-ziele'],
  },
  {
    id: 'qm3-03', chapterId: 'm3', type: 'cloze', goal: 'fact', difficulty: 2,
    prompt: 'Der Kommunikationsmix umfasst ______ Werkzeuge, davon vier massenmediale und vier ______.',
    clozeAnswers: [['acht', '8'], ['persönliche', 'persoenliche', 'persönlich']],
    explanation: 'Acht Werkzeuge: massenmedial (Werbung, Verkaufsförderung, Sponsoring/Event, PR) und persönlich (Direktmarketing, interaktives Marketing, Mund-zu-Mund, persönlicher Verkauf).',
    source: 'Kapitel 3.2, PDF S. 13', conceptIds: ['mc-kommmix'],
  },
  {
    id: 'qm3-04', chapterId: 'm3', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordne das Kommunikationsinstrument der richtigen Kategorie zu.',
    pairs: [
      { left: 'Werbung', right: 'massenmedial' },
      { left: 'Public Relations', right: 'massenmedial' },
      { left: 'Persönlicher Verkauf', right: 'persönlich' },
      { left: 'Mund-zu-Mund-Kommunikation', right: 'persönlich' },
    ],
    explanation: 'Massenmedial: Werbung, Verkaufsförderung, Sponsoring/Event, PR. Persönlich: Direktmarketing, interaktives Marketing, Mund-zu-Mund, persönlicher Verkauf.',
    source: 'Kapitel 3.2, PDF S. 13–16', conceptIds: ['mc-kommmix', 'mc-werbung', 'mc-pr', 'mc-persoenlicher-verkauf', 'mc-wom'],
  },
  {
    id: 'qm3-05', chapterId: 'm3', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Ein Unternehmen verteilt zeitlich befristete Coupons und Warenproben, um kurzfristig den Absatz anzukurbeln. Welches Instrument ist das?',
    options: ['Verkaufsförderung', 'Public Relations', 'Sponsoring', 'Persönlicher Verkauf'],
    correctOptions: [0],
    explanation: 'Verkaufsförderung: kurzfristige, greifbare Kaufanreize (Coupons, Proben, Rabatte). Zu häufiger Einsatz kann dem Markenwert schaden.',
    source: 'Kapitel 3.2, PDF S. 14', conceptIds: ['mc-verkaufsfoerderung'],
  },
  {
    id: 'qm3-06', chapterId: 'm3', type: 'multiple_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Welche Aussagen zur Werbung treffen zu? (Mehrfachauswahl)',
    options: [
      'Sie ist unpersönlich und wird von einem genannten Auftraggeber bezahlt',
      'Sie hat eine große Reichweite',
      'Sie ermöglicht individuelle Ansprache jedes Einzelnen',
      'Ihre Wirkung ist oft schwer messbar',
    ],
    correctOptions: [0, 1, 3],
    explanation: 'Werbung ist unpersönlich, bezahlt, reichweitenstark, aber schwer messbar und OHNE individuelle Ansprache. Individuelle Ansprache leisten persönliche Instrumente.',
    source: 'Kapitel 3.2, PDF S. 13–14', conceptIds: ['mc-werbung'],
  },
  {
    id: 'qm3-07', chapterId: 'm3', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Warum gilt Public Relations (PR) als besonders glaubwürdig, und wie unterscheidet sie sich von Werbung?',
    rubric: [
      { point: 'PR beeinflusst die öffentliche Meinung / pflegt Stakeholder', keywords: ['öffentlich', 'oeffentlich', 'meinung', 'stakeholder', 'image'] },
      { point: 'Höhere Glaubwürdigkeit als Werbung', keywords: ['glaubwürdig', 'glaubwuerdig', 'vertrauen'] },
      { point: 'Erreicht auch Werbeverweigerer / erzählt Geschichten', keywords: ['verweiger', 'meidet', 'geschichte', 'story'], weight: 0.5 },
    ],
    modelAnswer: 'PR ist transparente Kommunikation mit allen Anspruchsgruppen, um die öffentliche Meinung zu beeinflussen und das Image zu pflegen. Sie wirkt glaubwürdiger als Werbung, weil sie nicht als bezahlte Eigenwerbung wahrgenommen wird, sondern über redaktionelle Beiträge und „Geschichten“ transportiert wird. Dadurch erreicht sie auch Konsumenten, die klassische Werbung meiden.',
    explanation: 'Kern: PR = Beeinflussung der öffentlichen Meinung mit hoher Glaubwürdigkeit; Werbung = bezahlte, unpersönliche Präsentation.',
    source: 'Kapitel 3.2, PDF S. 15', conceptIds: ['mc-pr', 'mc-werbung'],
  },
  {
    id: 'qm3-08', chapterId: 'm3', type: 'assignment', goal: 'understanding', difficulty: 2,
    prompt: 'Ordne die digitale Kennzahl ihrer Bedeutung zu.',
    pairs: [
      { left: 'Click-Through-Rate (CTR)', right: 'Wie oft eine Anzeige angeklickt wird' },
      { left: 'Conversion Rate', right: 'Anteil der Besucher, die eine Zielhandlung ausführen' },
      { left: 'Engagement Rate', right: 'Wie aktiv Nutzer reagieren (Likes, Shares, Kommentare)' },
    ],
    explanation: 'CTR = Klickhäufigkeit; Conversion Rate = Zielhandlungen; Engagement Rate = Interaktionsaktivität. Wichtig für die Ergebnismessung (Schritt 7 der Kommunikationsplanung).',
    source: 'Kapitel 3.1, PDF S. 12–13', conceptIds: ['mc-kpis', 'mc-8schritte-komm'],
  },
  {
    id: 'qm3-09', chapterId: 'm3', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein junges D2C-Modelabel hat ein kleines Budget und will schnell bekannt werden. Welche zwei Kommunikationsinstrumente würdest du empfehlen und warum?',
    rubric: [
      { point: 'Mund-zu-Mund / Influencer-Marketing (Word-of-Mouth)', keywords: ['influencer', 'mund-zu-mund', 'word-of-mouth', 'viral', 'buzz', 'empfehl'] },
      { point: 'Interaktives Marketing / Social Media / suchgebundene Anzeigen', keywords: ['interaktiv', 'social media', 'sea', 'suchgebunden', 'online'] },
      { point: 'Begründung: hohe Wirkung/Glaubwürdigkeit bei geringen Kosten', keywords: ['gering', 'kosten', 'budget', 'glaubwürdig', 'zielgruppe', 'effizient'] },
    ],
    modelAnswer: 'Bei kleinem Budget bieten sich Mund-zu-Mund- bzw. Influencer-Marketing und interaktives Marketing (Social Media, suchgebundene Anzeigen) an. Word-of-Mouth ist wegen der persönlichen Bindung sehr einflussreich und kann viral kostengünstig Reichweite schaffen; interaktives Marketing erlaubt eine präzise, messbare Ansprache der Zielgruppe zu geringen Kosten. Teure Massenwerbung wäre für ein Start-up ineffizient.',
    explanation: 'Für Start-ups mit knappem Budget sind Word-of-Mouth/Influencer und interaktives/Social-Media-Marketing effizient und glaubwürdig.',
    source: 'Kapitel 3.2, PDF S. 16', conceptIds: ['mc-wom', 'mc-interaktiv', 'mc-kommmix'],
  },
];
