import { Question } from '@/lib/types';

/** Textfragen zu Kapitel 4–5 (Preispolitik, Distributionspolitik). */
export const questions45: Question[] = [
  // ================= Kapitel 4: Preispolitik =================
  {
    id: 'qm4-01', chapterId: 'm4', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Warum wird die Preispolitik auch „Kontrahierungspolitik“ genannt?',
    options: [
      'Weil sie neben dem Preis auch Zahlungsbedingungen und Rabatte umfasst',
      'Weil sie nur den Listenpreis festlegt',
      'Weil sie ausschließlich Verträge mit Lieferanten regelt',
      'Weil sie sich nur auf B2C bezieht',
    ],
    correctOptions: [0],
    explanation: 'Kontrahierungspolitik umfasst alle Entscheidungen zum Entgelt – Preishöhe UND weitere Konditionen wie Zahlungsbedingungen und Rabatte.',
    source: 'Kapitel 4.1, PDF S. 17', conceptIds: ['mc-preispolitik'],
  },
  {
    id: 'qm4-02', chapterId: 'm4', type: 'cloze', goal: 'understanding', difficulty: 2,
    prompt: 'Die Zahlungsbereitschaft der Kunden bildet die Preis______; die Gesamtkosten bilden die Preis______.',
    clozeAnswers: [['obergrenze', 'Obergrenze'], ['untergrenze', 'Untergrenze']],
    explanation: 'Käufer/Zahlungsbereitschaft = Obergrenze; Kosten = Untergrenze. Dazwischen liegt der Preiskorridor.',
    source: 'Kapitel 4.1, PDF S. 17', conceptIds: ['mc-preisgrenzen'],
  },
  {
    id: 'qm4-03', chapterId: 'm4', type: 'true_false', goal: 'fact', difficulty: 1,
    prompt: 'Ein Preis von 2,99 € statt 3,00 € nutzt den psychologischen Effekt des Schwellenpreises.',
    correctBool: true,
    explanation: 'Richtig. Kunden ignorieren Nachkommastellen; Preise knapp unter einer Schwelle (2,99 €) wirken deutlich günstiger.',
    source: 'Kapitel 4.1, PDF S. 17', conceptIds: ['mc-schwellenpreis'],
  },
  {
    id: 'qm4-04', chapterId: 'm4', type: 'assignment', goal: 'distinction', difficulty: 3,
    prompt: 'Ordne die Preis-Absatz-Funktion ihrem Kennzeichen zu.',
    pairs: [
      { left: 'Lineare PAF x(p)=a−b·p', right: 'Gerade mit Sättigungsmenge a und Maximalpreis a/b (Monopol)' },
      { left: 'Multiplikative PAF x(p)=a·p^(−b)', right: 'Schneidet die Achsen nicht – kein Maximalpreis, keine Sättigungsmenge' },
      { left: 'Gutenberg-Modell', right: 'Doppelt geknickt – monopolistischer Mittelbereich' },
    ],
    explanation: 'Linear = Gerade (Monopol); multiplikativ = keine Achsenschnitte; Gutenberg = doppelt geknickt (unvollkommener Markt).',
    source: 'Kapitel 4.3, PDF S. 18', conceptIds: ['mc-paf', 'mc-paf-linear', 'mc-paf-mult', 'mc-gutenberg'],
  },
  {
    id: 'qm4-05', chapterId: 'm4', type: 'single_choice', goal: 'application', difficulty: 2,
    prompt: 'Apple kann Smartphones trotz hoher Preise in großer Menge verkaufen – die Absatzmenge reagiert im mittleren Bereich kaum auf Preisänderungen. Welche PAF beschreibt das?',
    options: ['Gutenberg-Modell', 'Lineare Preis-Absatz-Funktion', 'Multiplikatives Modell ohne Knick', 'Break-even-Funktion'],
    correctOptions: [0],
    explanation: 'Das Gutenberg-Modell hat einen monopolistischen Mittelbereich (Markentreue): Die Menge bleibt trotz höherer Preise stabil – typisch für starke Marken wie Apple.',
    source: 'Kapitel 4.3, PDF S. 18', conceptIds: ['mc-gutenberg'],
  },
  {
    id: 'qm4-06', chapterId: 'm4', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Ein Hersteller führt ein innovatives Produkt zu einem hohen Preis ein und senkt ihn später schrittweise. Welche Strategie ist das?',
    options: ['Skimmingstrategie', 'Penetrationsstrategie', 'Preisfolgerschaft', 'Penetration mit Preisbündelung'],
    correctOptions: [0],
    explanation: 'Skimming: hoher Einführungspreis schöpft die Zahlungsbereitschaft der Innovatoren/Frühadopter ab, danach wird gesenkt. Penetration wäre umgekehrt (niedrig → hoch).',
    source: 'Kapitel 4.2, PDF S. 19', conceptIds: ['mc-skimming'],
  },
  {
    id: 'qm4-07', chapterId: 'm4', type: 'cloze', goal: 'distinction', difficulty: 2,
    prompt: 'Die ______strategie startet mit niedrigen Einführungspreisen zur schnellen Marktdurchdringung; die ______strategie startet mit hohen Preisen und senkt sie später.',
    clozeAnswers: [['Penetration', 'penetration', 'Penetrations'], ['Skimming', 'skimming', 'Skimming']],
    explanation: 'Penetration: niedrig → hoch (Marktdurchdringung). Skimming: hoch → niedrig (Abschöpfung).',
    source: 'Kapitel 4.2, PDF S. 19', conceptIds: ['mc-skimming'],
  },
  {
    id: 'qm4-08', chapterId: 'm4', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche sind Formen der Preisdifferenzierung? (Mehrfachauswahl)',
    options: ['Zeitliche Differenzierung', 'Räumliche Differenzierung', 'Personelle Differenzierung', 'Kostenorientierte Differenzierung', 'Preisbündelung'],
    correctOptions: [0, 1, 2, 4],
    explanation: 'Preisdifferenzierung: mengenmäßig, zeitlich, räumlich, personell, leistungsbezogen; Sonderform Preisbündelung. „Kostenorientiert“ ist eine Preisbestimmungsmethode, keine Differenzierungsform.',
    source: 'Kapitel 4.2, PDF S. 19', conceptIds: ['mc-preisdiff'],
  },
  {
    id: 'qm4-09', chapterId: 'm4', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordne die vier Rabattarten ihrer Beschreibung zu.',
    pairs: [
      { left: 'Funktionsrabatt', right: 'Gegenleistung für vom Handel übernommene Funktionen' },
      { left: 'Mengenrabatt', right: 'Nachlass für die Abnahme größerer Mengen' },
      { left: 'Zeitrabatt (Skonto)', right: 'Nachlass für Bestellzeitpunkt bzw. frühe Zahlung' },
      { left: 'Treuerabatt', right: 'Nachlass für kontinuierliche Bestellungen' },
    ],
    explanation: 'Vier Rabattarten: Funktions-, Mengen-, Zeit- (Skonto als Sonderform) und Treuerabatt.',
    source: 'Kapitel 4.3, PDF S. 20', conceptIds: ['mc-rabatte'],
  },
  {
    id: 'qm4-10', chapterId: 'm4', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erkläre den Unterschied zwischen kostenorientierter und marktorientierter Preisbestimmung und nenne je einen Vor- oder Nachteil.',
    rubric: [
      { point: 'Kostenorientiert: Stückkosten + Aufschlag', keywords: ['kosten', 'aufschlag', 'stückkosten', 'stueckkosten', 'zuschlag'] },
      { point: 'Marktorientiert: an Marktreaktion/Zahlungsbereitschaft orientiert', keywords: ['markt', 'zahlungsbereitschaft', 'perceived value', 'break-even', 'nachfrage'] },
      { point: 'Vor-/Nachteil genannt', keywords: ['einfach', 'fair', 'ignoriert', 'aufwändig', 'aufwendig', 'genauer'], weight: 0.5 },
    ],
    modelAnswer: 'Bei der kostenorientierten Preisbestimmung wird auf die Stückkosten ein Gewinnaufschlag addiert – einfach und fair, aber sie ignoriert die Marktsituation und Zahlungsbereitschaft. Die marktorientierte Bestimmung richtet sich an Marktreaktionen aus (z. B. Perceived-Value-Pricing, Break-even-Analyse, Cournot-Preis) – sie ist marktgerechter, aber aufwändiger und erfordert gute Marktkenntnis.',
    explanation: 'Kern: Kosten + Aufschlag (einfach, aber marktfern) vs. Orientierung an Nachfrage/Wahrnehmung (marktgerecht, aber aufwändiger).',
    source: 'Kapitel 4.3, PDF S. 19–20', conceptIds: ['mc-preisbestimmung'],
  },
  {
    id: 'qm4-11', chapterId: 'm4', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Eine Fluggesellschaft verlangt für denselben Sitzplatz je nach Buchungszeitpunkt und Auslastung unterschiedliche Preise. Ordne dieses Vorgehen ein (Modell + Art der Preisdifferenzierung) und begründe den Nutzen.',
    rubric: [
      { point: 'Yield Management / Dynamic Pricing', keywords: ['yield', 'dynamic', 'auslastung', 'kapazität', 'kapazitaet'] },
      { point: 'Zeitliche Preisdifferenzierung', keywords: ['zeitlich', 'zeitpunkt', 'differenzierung'] },
      { point: 'Nutzen: unterschiedliche Zahlungsbereitschaften ausschöpfen / Erlös maximieren', keywords: ['zahlungsbereitschaft', 'erlös', 'erloes', 'auslastung', 'gewinn', 'maximier'] },
    ],
    modelAnswer: 'Das ist Yield Management bzw. Dynamic Pricing kombiniert mit zeitlicher Preisdifferenzierung: Der Preis variiert nach Buchungszeitpunkt und Kapazitätsauslastung. Nutzen: Die Airline schöpft unterschiedliche Zahlungsbereitschaften ab (Frühbucher vs. Last-Minute) und maximiert bei begrenzter Kapazität den Gesamterlös, statt alle Plätze zum gleichen Preis zu verkaufen.',
    explanation: 'Yield Management/Dynamic Pricing + zeitliche Differenzierung: Erlösoptimierung bei fixer Kapazität durch Ausschöpfen der Zahlungsbereitschaften.',
    source: 'Kapitel 4.2–4.3, PDF S. 19–20', conceptIds: ['mc-innovpricing', 'mc-preisdiff'],
  },

  // ================= Kapitel 5: Distributionspolitik =================
  {
    id: 'qm5-01', chapterId: 'm5', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Aus welchen zwei Komponenten besteht die Distributionspolitik?',
    options: [
      'Akquisitorische und logistische Komponente',
      'Preisliche und werbliche Komponente',
      'Materielle und immaterielle Komponente',
      'Interne und externe Kommunikation',
    ],
    correctOptions: [0],
    explanation: 'Akquisitorisch = das Vertriebssystem effizient/effektiv gestalten; logistisch = adäquater Zugriff der Konsumenten auf die Leistung.',
    source: 'Kapitel 5.1, PDF S. 20–21', conceptIds: ['mc-distribution'],
  },
  {
    id: 'qm5-02', chapterId: 'm5', type: 'true_false', goal: 'distinction', difficulty: 2,
    prompt: 'Bei der Pull-Strategie richtet der Hersteller seine Kommunikation direkt an die Endkunden, damit diese das Produkt beim Handel nachfragen.',
    correctBool: true,
    explanation: 'Richtig. Pull erzeugt einen Nachfragesog beim Endkunden (SEO, Social Media, TV-Werbung). Push „drückt“ die Ware dagegen über Rabatte in den Handel.',
    source: 'Kapitel 5.1, PDF S. 21', conceptIds: ['mc-push-pull'],
  },
  {
    id: 'qm5-03', chapterId: 'm5', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordne die Überbrückungsfunktion des Handels dem passenden Beispiel zu.',
    pairs: [
      { left: 'Räumliche Überbrückung', right: 'Transport der Bananen aus Südamerika nach Europa' },
      { left: 'Zeitliche Überbrückung', right: 'Lagerung und Nachreifung bis zum Verkauf' },
      { left: 'Sortimentsgestaltung', right: 'Bündelung vieler Hersteller zu einem passenden Angebot' },
    ],
    explanation: 'Der Handel schafft Wert durch Überbrückung räumlicher, zeitlicher und sortimentsbezogener (quantitativer/qualitativer) Diskrepanzen.',
    source: 'Kapitel 5.1, PDF S. 21–22', conceptIds: ['mc-ueberbrueckung'],
  },
  {
    id: 'qm5-04', chapterId: 'm5', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Edeka betreibt eine eigene Bananenreiferei und übernimmt damit eine vorgelagerte Wertschöpfungsstufe. Wie heißt dieses Vorgehen?',
    options: ['Vertikale Integration', 'Disintermediation', 'Horizontale Integration', 'Franchising'],
    correctOptions: [0],
    explanation: 'Vertikale Integration: Ein Unternehmen gliedert vor-/nachgelagerte Stufen ein. Disintermediation wäre das Ausschalten von Intermediären (z. B. D2C).',
    source: 'Kapitel 5.2, PDF S. 22', conceptIds: ['mc-vertikale-integration', 'mc-disintermediation'],
  },
  {
    id: 'qm5-05', chapterId: 'm5', type: 'cloze', goal: 'fact', difficulty: 2,
    prompt: 'Beim ______ Vertrieb verkauft das Unternehmen selbst an die Endkunden; beim ______ Vertrieb werden externe Marktakteure mit akquisitorischer Funktion eingeschaltet.',
    clozeAnswers: [['direkten', 'direkt'], ['indirekten', 'indirekt']],
    explanation: 'Direkter Vertrieb: Unternehmen → Endkunde (nullstufig). Indirekter Vertrieb: über externe Absatzmittler/-helfer.',
    source: 'Kapitel 5.2, PDF S. 22', conceptIds: ['mc-direkt-indirekt'],
  },
  {
    id: 'qm5-06', chapterId: 'm5', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Was unterscheidet einen Absatzhelfer von einem Absatzmittler?',
    options: [
      'Der Absatzhelfer erwirbt kein Eigentum an den Produkten, der Absatzmittler schon',
      'Der Absatzhelfer erwirbt Eigentum, der Absatzmittler nicht',
      'Beide erwerben immer Eigentum',
      'Beide erwerben nie Eigentum',
    ],
    correctOptions: [0],
    explanation: 'Absatzhelfer (Handelsvertreter, Kommissionäre, Makler) erwerben KEIN Eigentum; Absatzmittler (Groß-/Einzelhandel) erwerben Eigentum an der Ware.',
    source: 'Kapitel 5.2, PDF S. 22–23', conceptIds: ['mc-absatzhelfer-mittler'],
  },
  {
    id: 'qm5-07', chapterId: 'm5', type: 'true_false', goal: 'distinction', difficulty: 2,
    prompt: 'Omnichannel bedeutet lediglich, auf mehreren Kanälen präsent zu sein, ohne sie miteinander zu verbinden.',
    correctBool: false,
    explanation: 'Falsch. Das beschreibt Multichannel. Omnichannel vernetzt alle Kanäle konsistent zu einem nahtlosen Erlebnis (z. B. Click & Collect).',
    source: 'Kapitel 5.3, PDF S. 23', conceptIds: ['mc-multi-omni'],
  },
  {
    id: 'qm5-08', chapterId: 'm5', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordne den Distributionsgrad dem passenden Gütertyp zu.',
    pairs: [
      { left: 'Intensiver Vertrieb', right: 'Convenience Goods – sehr viele Vertriebspartner' },
      { left: 'Selektiver Vertrieb', right: 'Shopping Goods – mehrere Vertriebspartner' },
      { left: 'Exklusiver Vertrieb', right: 'Specialty Goods – wenige Vertriebspartner' },
    ],
    explanation: 'Intensiv = viele Partner (Convenience), selektiv = mehrere (Shopping), exklusiv = wenige (Specialty/teuer).',
    source: 'Kapitel 5.3, PDF S. 23', conceptIds: ['mc-distributionsgrad'],
  },
  {
    id: 'qm5-09', chapterId: 'm5', type: 'multiple_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Welche Aussagen zum direkten Vertrieb treffen zu? (Mehrfachauswahl)',
    options: [
      'Enge Kundenbeziehung und hohe Kontrolle',
      'Kein Anfall von Handelsmargen an Dritte',
      'Geringer eigener Aufwand',
      'Höherer eigener Aufwand für Logistik und Verkauf',
    ],
    correctOptions: [0, 1, 3],
    explanation: 'Direkter Vertrieb: enge Beziehung, volle Kontrolle, keine Handelsmargen – aber hoher eigener Aufwand. „Geringer Aufwand“ ist gerade der Vorteil des indirekten Vertriebs.',
    source: 'Kapitel 5.2, PDF S. 22', conceptIds: ['mc-direkt-indirekt'],
  },
  {
    id: 'qm5-10', chapterId: 'm5', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Erläutere die Idee der Disintermediation und nenne einen Vorteil sowie ein mögliches Risiko für den Hersteller.',
    rubric: [
      { point: 'Disintermediation = Ausschaltung von Intermediären (z. B. D2C/E-Commerce)', keywords: ['intermediär', 'intermediaer', 'ausschalt', 'd2c', 'direct-to-consumer', 'e-commerce'] },
      { point: 'Vorteil: Handelsmarge sparen / mehr Kontrolle / Kundendaten', keywords: ['marge', 'kontrolle', 'daten', 'kundenbeziehung', 'sparen'] },
      { point: 'Risiko: eigener Aufwand / Logistik / Verlust der Handelsreichweite', keywords: ['aufwand', 'logistik', 'reichweite', 'risiko', 'kosten'] },
    ],
    modelAnswer: 'Disintermediation bedeutet, Zwischenhändler auszuschalten und direkt an Endkunden zu verkaufen (Direct-to-Consumer über E-Commerce). Vorteil: Der Hersteller spart die Handelsmarge, gewinnt Kontrolle über Marke und Preise und erhält direkte Kundendaten/-beziehungen. Risiko: Er muss Logistik, Vertrieb und Kundenservice selbst aufbauen (hoher Aufwand) und verliert die etablierte Reichweite des Handels.',
    explanation: 'Kern: Zwischenhändler ausschalten (D2C) – spart Marge und erhöht Kontrolle, verlagert aber Aufwand und Reichweitenrisiko auf den Hersteller.',
    source: 'Kapitel 5.2, PDF S. 22', conceptIds: ['mc-disintermediation', 'mc-direkt-indirekt'],
  },
  {
    id: 'qm5-11', chapterId: 'm5', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein Hersteller exklusiver Uhren überlegt, wie er vertreiben soll. Empfehle einen Distributionsgrad und eine vertikale Vertriebsform und begründe die Wahl.',
    rubric: [
      { point: 'Exklusiver Vertrieb (wenige Partner)', keywords: ['exklusiv', 'wenige', 'specialty'] },
      { point: 'Direkter Vertrieb oder wenige ausgewählte Absatzmittler', keywords: ['direkt', 'ausgewählt', 'ausgewaehlt', 'boutique', 'flagship', 'wenige haendler'] },
      { point: 'Begründung: Kontrolle, Prestige, Markenbild', keywords: ['kontrolle', 'prestige', 'marke', 'image', 'hochpreis', 'erlebnis'] },
    ],
    modelAnswer: 'Für exklusive Uhren passt ein exklusiver Vertrieb über sehr wenige, sorgfältig ausgewählte Partner – idealerweise ergänzt durch direkten Vertrieb (eigene Boutiquen/Flagship-Stores oder Online-Shop). So behält der Hersteller die Kontrolle über Preis, Präsentation und Beratung, schützt das Prestige der Marke und bietet ein hochwertiges Kauferlebnis, das zum teuren Specialty Good passt.',
    explanation: 'Teure Specialty Goods → exklusiver Vertrieb + möglichst direkte/kontrollierte Wege, um Marke und Prestige zu schützen.',
    source: 'Kapitel 5.2–5.3, PDF S. 22–23', conceptIds: ['mc-distributionsgrad', 'mc-direkt-indirekt'],
  },
];
