import { Question } from '@/lib/types';

/** Fragen Kapitel 3 – Kommunikationspolitik (PDF S. 11–16). */
export const questions3: Question[] = [
  // ======================= bestehende Fragen (IDs unverändert) =======================
  {
    id: 'qm3-01', chapterId: 'm3', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Mit welchem Ziel tritt die Marketingkommunikation in Dialog mit den Konsumenten?',
    options: [
      'Um sie über Produkte und Marken zu informieren, von ihnen zu überzeugen und an sie zu erinnern',
      'Um Produkte zu produzieren, zu lagern und zu liefern',
      'Um Preise zu kalkulieren und Rabatte festzulegen',
      'Um Vertriebspartner auszuwählen',
    ],
    correctOptions: [0],
    explanation: 'Aufgaben der Marketingkommunikation: informieren, überzeugen, erinnern.',
    source: 'Kapitel 3.1, PDF S. 11', conceptIds: ['mc-komm-aufgaben', 'mc-kommunikationspolitik'],
  },
  {
    id: 'qm3-02', chapterId: 'm3', type: 'true_false', goal: 'distinction', difficulty: 2,
    prompt: 'Marktanteil, Kundenzahl, Absatz und Rentabilität sind reine (vorökonomische) Kommunikationsziele.',
    correctBool: false,
    explanation: 'Falsch – das sind wirtschaftliche Ziele, die sich auf den Marketingmix als Ganzes beziehen. Reine Kommunikationsziele sind potenzialbezogen: Kategoriebedürfnis, Bekanntheitsgrad und Image, Einstellungen, Kaufabsicht.',
    source: 'Kapitel 3.1, PDF S. 11', conceptIds: ['mc-komm-ziele'],
  },
  {
    id: 'qm3-03', chapterId: 'm3', type: 'cloze', goal: 'fact', difficulty: 1,
    prompt: 'Der Marketingkommunikationsmix besteht aus ______ Werkzeugen, davon vier massenmediale und vier ______.',
    clozeAnswers: [['acht', '8'], ['persönliche', 'persönlich']],
    explanation: 'Massenmedial: Werbung, Verkaufsförderung, Sponsoring & Events, PR. Persönlich: Direktmarketing, interaktives Marketing, Mund-zu-Mund-Kommunikation, persönlicher Verkauf.',
    source: 'Kapitel 3.2, PDF S. 13 und 16', conceptIds: ['mc-kommmix'],
  },
  {
    id: 'qm3-04', chapterId: 'm3', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie das Kommunikationsinstrument der richtigen Kategorie zu.',
    pairs: [
      { left: 'Werbung', right: 'massenmedial' },
      { left: 'Public Relations', right: 'massenmedial' },
      { left: 'Sponsoring & Eventmarketing', right: 'massenmedial' },
      { left: 'Persönlicher Verkauf', right: 'persönlich' },
      { left: 'Mund-zu-Mund-Kommunikation', right: 'persönlich' },
      { left: 'Interaktives Marketing', right: 'persönlich' },
    ],
    explanation: 'Vier massenmediale (Werbung, Verkaufsförderung, Sponsoring & Events, PR) und vier persönliche Instrumente (Direktmarketing, interaktives Marketing, WoM, persönlicher Verkauf).',
    source: 'Kapitel 3.2, PDF S. 13', conceptIds: ['mc-kommmix', 'mc-massenmedial', 'mc-persoenliche-komm'],
  },
  {
    id: 'qm3-05', chapterId: 'm3', type: 'single_choice', goal: 'distinction', difficulty: 2,
    prompt: 'Ein Unternehmen verteilt zeitlich befristete Coupons und Warenproben, um kurzfristig den Absatz anzukurbeln. Welches Instrument ist das?',
    options: ['Verkaufsförderung', 'Public Relations', 'Sponsoring', 'Persönlicher Verkauf'],
    correctOptions: [0],
    explanation: 'Verkaufsförderung: kurzfristige Anregung von Verkauf durch gezielte Anreize (Warenproben, Coupons, Preisnachlässe …).',
    source: 'Kapitel 3.2, PDF S. 13', conceptIds: ['mc-verkaufsfoerderung'],
  },
  {
    id: 'qm3-06', chapterId: 'm3', type: 'multiple_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Welche Aussagen zur Werbung treffen laut Skript zu? (Mehrfachauswahl)',
    options: [
      'Sie ist eine unpersönliche, durch einen explizit genannten Auftraggeber bezahlte Präsentation von Produkten.',
      'Sie bietet volle Kontrolle über die Produktpräsentation.',
      'Sie ermöglicht die individuelle Ansprache jedes Einzelnen.',
      'Ihre Effizienz und Effektivität sind schwer messbar.',
    ],
    correctOptions: [0, 1, 3],
    explanation: 'Werbung erlaubt KEINE individuelle Ansprache – das leisten persönliche Instrumente.',
    source: 'Kapitel 3.2, PDF S. 13', conceptIds: ['mc-werbung'],
  },
  {
    id: 'qm3-07', chapterId: 'm3', type: 'open', goal: 'distinction', difficulty: 2,
    prompt: 'Warum gilt Public Relations als besonders glaubwürdig und wie unterscheidet sie sich von Werbung? Nennen Sie auch einen Nachteil der PR.',
    rubric: [
      { point: 'PR: transparente Kommunikation mit allen Anspruchsgruppen, beeinflusst öffentliche Meinung, Ziel Image', keywords: ['anspruchsgruppen', 'öffentliche meinung', 'transparent', 'image', 'stakeholder'] },
      { point: 'Höheres Vertrauen und Glaubwürdigkeit als Werbung; erreicht auch Massenmedien-Meider', keywords: ['glaubwürdig', 'vertrauen', 'massenmedien meiden'] },
      { point: 'Werbung: unpersönlich, bezahlt, explizit genannter Auftraggeber', keywords: ['bezahlt', 'auftraggeber', 'unpersönlich'] },
      { point: 'Nachteil: wenig Kontrolle über Darstellung / nicht beliebig wiederholbar', keywords: ['wenig kontrolle', 'kontrolle', 'nicht beliebig', 'nachrichtenwert'] },
    ],
    modelAnswer: 'PR (Öffentlichkeitsarbeit) versucht durch gezielte, transparente Kommunikation den Dialog mit allen Anspruchsgruppen aufzunehmen und so die öffentliche Meinung zu beeinflussen; Ziel ist ein besseres Unternehmensimage. Im Gegensatz zur Werbung – der unpersönlichen, von einem explizit genannten Auftraggeber bezahlten Präsentation von Produkten – genießt PR höheres Vertrauen und Glaubwürdigkeit und erreicht auch Konsumenten, die Massenmedien meiden. Nachteil: Das Unternehmen hat wenig Kontrolle darüber, ob und wie die Botschaft dargestellt wird, und wegen des Nachrichtenwerts sind die Maßnahmen nicht beliebig oft wiederholbar.',
    explanation: 'Glaubwürdigkeit (PR) vs. Kontrolle (Werbung).',
    source: 'Kapitel 3.2, PDF S. 13–14', conceptIds: ['mc-pr', 'mc-werbung', 'mc-stakeholder'],
  },
  {
    id: 'qm3-08', chapterId: 'm3', type: 'assignment', goal: 'understanding', difficulty: 2,
    prompt: 'Ordnen Sie die digitale Kennzahl ihrer Bedeutung zu.',
    pairs: [
      { left: 'Click-Through-Rate (CTR)', right: 'Klickhäufigkeit von Anzeigen (Banner gesehen, 1 % klickt)' },
      { left: 'Conversion Rate', right: 'Anteil der Besucher, die Zielhandlungen ausführen (100 Besucher, 5 Käufe = 5 %)' },
      { left: 'Engagement Rate', right: 'Wie aktiv Nutzer reagieren (Kommentare, Shares, Likes pro Post)' },
    ],
    explanation: 'Digitale Messgrößen zur Messung der Kommunikationsergebnisse (Schritt 7).',
    source: 'Kapitel 3.1, PDF S. 12', conceptIds: ['mc-kpis', 'mc-ctr', 'mc-conversion', 'mc-engagement'],
  },
  {
    id: 'qm3-09', chapterId: 'm3', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Ein junges Modelabel, das direkt online verkauft, hat ein sehr kleines Budget und will schnell bekannt werden. Empfehlen Sie zwei Kommunikationsinstrumente und begründen Sie mit Vor- und Nachteilen aus dem Skript, warum klassische Werbung weniger geeignet ist.',
    rubric: [
      { point: 'Mund-zu-Mund/Influencer-Marketing: sehr einflussreich durch persönliche Bindung, zeitnah, Glaubwürdigkeit reichweitenstarker Personen', keywords: ['mund-zu-mund', 'influencer', 'word-of-mouth', 'viral', 'buzz', 'einflussreich'] },
      { point: 'Interaktives Marketing (Social Media, Retargeting, suchgebundene Anzeigen): individuelle Ansprache, Interessen über Daten ermittelbar', keywords: ['interaktiv', 'social media', 'retargeting', 'suchgebunden', 'individuell', 'daten'] },
      { point: 'Alternativ PR: vergleichsweise geringe Kosten, hohe Glaubwürdigkeit', keywords: ['pr', 'public relations', 'geringe kosten', 'glaubwürdig'], weight: 0.5 },
      { point: 'Werbung: hohe Kosten, keine individuelle Ansprache, schwer messbar', keywords: ['hohe kosten', 'teuer', 'keine individuelle', 'schwer messbar'] },
    ],
    modelAnswer: 'Geeignet sind Mund-zu-Mund-Kommunikation bzw. Influencer-Marketing und interaktives Marketing. WoM ist wegen der persönlichen Bindung sehr einflussreich und zeitnah; über Influencer nutzt das Label die authentische Stimme und Glaubwürdigkeit reichweitenstarker Personen und kann einen viralen Effekt erzielen. Interaktives Marketing (Social Media, Retargeting, suchgebundene Anzeigen) erlaubt individuelle Ansprache, und über digitale Daten lassen sich die Interessen der Konsumenten ermitteln. Auch PR wäre wegen vergleichsweise geringer Kosten und hoher Glaubwürdigkeit denkbar. Klassische Werbung ist dagegen teuer, erlaubt keine individuelle Ansprache, und ihre Effizienz ist schwer messbar – für ein kleines Budget ungeeignet. Nachteil von WoM: begrenzte Einflussmöglichkeiten und schwer messbare Wirkung.',
    explanation: 'Instrumentenwahl hängt u. a. vom verfügbaren Budget ab (Faktor 6 der Medienkombination).',
    source: 'Kapitel 3.1–3.2, PDF S. 12–15', conceptIds: ['mc-wom', 'mc-influencer', 'mc-interaktiv', 'mc-werbung', 'mc-medienkombination'],
  },

  // ======================= neue offene Fragen =======================
  {
    id: 'qm3-10', chapterId: 'm3', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Definieren Sie Kommunikationspolitik und erläutern Sie, warum Kommunikationsaktivitäten integriert und medienneutral geplant werden sollten.',
    rubric: [
      { point: 'Definition: Informationen gestalten und übermitteln, um Konsumenten im Sinne der Unternehmensziele zu beeinflussen (Homburg 2017)', keywords: ['gestaltet', 'übermittelt', 'informationen', 'beeinfluss', 'unternehmensziele'] },
      { point: 'Kohärente Kommunikation macht Marken bekannt und füllt sie mit Inhalt (Markenassoziationen)', keywords: ['kohärent', 'bekannt', 'markenassoziation', 'inhalt'] },
      { point: 'Integration: Aktivitäten aufeinander abstimmen, stimmige Botschaften/Positionierung', keywords: ['integriert', 'abgestimmt', 'stimmig', 'positionierung'] },
      { point: 'Medienneutral: alle Kanäle objektiv nach Effektivität (Nutzen) und Effizienz (Aufwand) bewerten', keywords: ['medienneutral', 'effektivität', 'effizienz', 'objektiv'] },
    ],
    modelAnswer: 'Kommunikationspolitik gestaltet und übermittelt Informationen, um die Konsumenten im Sinne der Unternehmensziele zu beeinflussen (Homburg 2017). Eine kohärente Marketingkommunikation macht Marken bekannt und füllt sie mit Inhalt, schafft also Markenassoziationen – das gelingt nur mit stimmigen Botschaften und strategischer Positionierung. Deshalb müssen die Kommunikationsaktivitäten integriert und aufeinander abgestimmt werden. Medienneutrale Planung heißt, alle Kommunikationsoptionen und -kanäle objektiv nach ihrer Effektivität (Nutzen) und Effizienz (betriebener Aufwand) zu bewerten.',
    explanation: 'Definition + Integration + Medienneutralität.',
    source: 'Kapitel 3.1, PDF S. 11', conceptIds: ['mc-kommunikationspolitik', 'mc-integrierte-kommunikation', 'mc-medienneutral'],
  },
  {
    id: 'qm3-11', chapterId: 'm3', type: 'open', goal: 'distinction', difficulty: 2,
    prompt: 'Grenzen Sie ökonomische und vorökonomische Kommunikationsziele voneinander ab und nennen Sie die vier reinen Kommunikationsziele.',
    rubric: [
      { point: 'Ökonomische (wirtschaftliche) Ziele: Marktanteil, Kundenzahl, Absatz, Rentabilität – beziehen sich auf den Marketingmix als Ganzes', keywords: ['marktanteil', 'absatz', 'rentabilität', 'kundenzahl', 'marketingmix als ganzes'] },
      { point: 'Vorökonomische (potenzialbezogene) Ziele = reine Kommunikationsziele', keywords: ['vorökonomisch', 'potenzialbezogen', 'reine kommunikationsziele'] },
      { point: 'Kategoriebedürfnis; Bekanntheitsgrad und Image', keywords: ['kategoriebedürfnis', 'bekanntheit', 'image'] },
      { point: 'Einstellungen der Nachfrager; Kaufabsicht', keywords: ['einstellung', 'kaufabsicht'] },
    ],
    modelAnswer: 'Ökonomische (wirtschaftliche) Ziele wie Marktanteil, Kundenzahl, Absatz und Rentabilität beziehen sich auf den Marketingmix als Ganzes und lassen sich nicht allein der Kommunikation zurechnen. Nur die vorökonomischen (potenzialbezogenen) Ziele sind reine Kommunikationsziele: Kategoriebedürfnis, Bekanntheitsgrad und Image, Einstellungen der Nachfrager zum Unternehmen und zu den Produkten sowie die Kaufabsicht.',
    explanation: 'Abgrenzung + vier reine Kommunikationsziele.',
    source: 'Kapitel 3.1, PDF S. 11', conceptIds: ['mc-komm-ziele', 'mc-kategoriebeduerfnis'],
  },
  {
    id: 'qm3-12', chapterId: 'm3', type: 'transfer', goal: 'application', difficulty: 2,
    prompt: 'Ein Start-up bringt ein völlig neuartiges Produkt auf den Markt, das ein Problem löst, dessen sich die Konsumenten bisher nicht aktiv bewusst sind. Welches reine Kommunikationsziel steht im Vordergrund? Erläutern Sie den Begriff.',
    rubric: [
      { point: 'Kategoriebedürfnis', keywords: ['kategoriebedürfnis', 'kategorie'] },
      { point: 'Schaffung einer neuen Kategorie', keywords: ['neue kategorie', 'schaffung', 'neuer kategorien'] },
      { point: 'Problem nicht bewusst → noch keine Nachfrage; Bedürfnis muss erst etabliert werden', keywords: ['nicht bewusst', 'keine nachfrage', 'etabliert', 'erst'] },
    ],
    modelAnswer: 'Im Vordergrund steht das Kategoriebedürfnis. Es bezieht sich auf die Schaffung neuer Kategorien: Völlig neue, innovative Produkte lösen oft Probleme, denen sich Konsumenten nicht aktiv bewusst sind – es gibt also noch keine Nachfrage nach der Lösung. Die Kommunikation muss das Bedürfnis deshalb erst etablieren.',
    explanation: 'Neue Produktkategorie = Kategoriebedürfnis schaffen.',
    source: 'Kapitel 3.1, PDF S. 11', conceptIds: ['mc-kategoriebeduerfnis', 'mc-komm-ziele'],
  },
  {
    id: 'qm3-13', chapterId: 'm3', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Beschreiben Sie die acht Schritte zur Entwicklung eines Kommunikationsprogramms nach Kotler/Keller/Opresnik (2015).',
    rubric: [
      { point: '1. Zielgruppe auswählen, 2. Kommunikationsziele festlegen', keywords: ['zielgruppe', 'kommunikationsziele', 'ziele festlegen'] },
      { point: '3. Botschaft bestimmen, 4. Kanäle auswählen', keywords: ['botschaft', 'kanäle', 'kanal'] },
      { point: '5. Budget festlegen, 6. Kommunikationsmix gestalten', keywords: ['budget', 'kommunikationsmix', 'mix'] },
      { point: '7. Ergebnisse messen, 8. Prozess steuern', keywords: ['messen', 'ergebnisse', 'steuern', 'überwach'] },
    ],
    modelAnswer: '1. Zielgruppe auswählen: An wen richtet sich die Kommunikation (ganzes Marktsegment oder Teilmenge)? 2. Kommunikationsziele festlegen: Welche konkreten Ziele in welchem Zeitraum? 3. Kommunikationsbotschaft bestimmen: Was soll wie und von wem gesagt werden? 4. Kommunikationskanäle auswählen: persönliche Kanäle oder Massenkanäle (Grenzen verwischen durch soziale Medien, programmatische Werbung, KI). 5. Budget festlegen: z. B. nach finanziellen Möglichkeiten, Prozent vom Umsatz, an Mitbewerbern orientiert oder – empfohlen – auf Basis von Zielen und Aufgaben. 6. Kommunikationsmix gestalten: Medien und Kanäle unter Berücksichtigung von Merkmalen und Kosten durchdacht kombinieren. 7. Kommunikationsergebnisse messen: Konsumentenbefragungen, CTR, Conversion Rate, Engagement Rate. 8. Marketingkommunikationsprozess steuern: Instrumente kontinuierlich überwachen, koordinieren und anpassen, zunehmend per Marketing-Automatisierung.',
    explanation: 'Reihenfolge + Kerninhalt je Schritt.',
    source: 'Kapitel 3.1, PDF S. 11–12', conceptIds: ['mc-8schritte-komm', 'mc-zielgruppe', 'mc-botschaft', 'mc-kanaele', 'mc-budget', 'mc-ergebnismessung', 'mc-prozesssteuerung'],
  },
  {
    id: 'qm3-14', chapterId: 'm3', type: 'open', goal: 'fact', difficulty: 2,
    prompt: 'Welche Möglichkeiten nennt das Skript, um das Kommunikationsbudget festzulegen, und welche davon wird empfohlen?',
    rubric: [
      { point: 'Nach finanziellen Möglichkeiten', keywords: ['finanziellen möglichkeiten', 'finanziell'] },
      { point: 'Als Prozentsatz des Umsatzes', keywords: ['prozentsatz', 'umsatz'] },
      { point: 'Orientiert an den Mitbewerbern', keywords: ['mitbewerber', 'wettbewerber', 'konkurrenz'] },
      { point: 'Auf Basis von Zielen und Aufgaben – empfohlen', keywords: ['ziele und aufgaben', 'zielen und aufgaben', 'aufgaben', 'empfohlen', 'empfehlenswert'] },
    ],
    modelAnswer: 'Das Budget kann nach den finanziellen Möglichkeiten, als Prozentsatz des Umsatzes, orientiert an den Mitbewerbern oder auf Basis von Zielen und Aufgaben festgelegt werden. Empfehlenswert ist laut Skript der Weg auf Basis von Zielen und Aufgaben.',
    explanation: 'Schritt 5 der Kommunikationsplanung.',
    source: 'Kapitel 3.1, PDF S. 11', conceptIds: ['mc-budget'],
  },
  {
    id: 'qm3-15', chapterId: 'm3', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erklären Sie Retargeting und programmatische Werbung und zeigen Sie, warum laut Skript die Grenzen zwischen persönlichen Kanälen und Massenkanälen verwischen.',
    rubric: [
      { point: 'Retargeting: ehemalige Besucher gezielt erneut ansprechen (z. B. Instagram-Anzeige für angesehene Produkte)', keywords: ['ehemalige besucher', 'erneut', 'zuvor angesehen', 'retargeting'] },
      { point: 'Programmatische Werbung: automatisierter Anzeigenhandel, Algorithmen ersteigern Werbeflächen in Echtzeit', keywords: ['automatisiert', 'algorithm', 'echtzeit', 'ersteigern'] },
      { point: 'Grenzen verwischen durch soziale Medien, programmatische Werbung und KI', keywords: ['verwisch', 'soziale medien', 'ki', 'künstliche intelligenz'] },
      { point: 'Beispiel: KI-personalisierte Coupons in Retail-Apps (Lidl, REWE, dm)', keywords: ['coupon', 'lidl', 'rewe', 'dm', 'personalisiert'], weight: 0.5 },
    ],
    modelAnswer: 'Retargeting ist eine Onlinestrategie, bei der ehemalige Besucher gezielt erneut angesprochen werden – z. B. mit einer Instagram-Anzeige für zuvor angesehene Produkte. Programmatische Werbung ist automatisierter Anzeigenhandel über Algorithmen, die Werbeflächen in Echtzeit ersteigern. Bei der Kanalwahl (Schritt 4) unterscheidet man grob persönliche Kanäle und Massenkanäle; diese Grenzen verwischen jedoch durch soziale Medien, programmatische Werbung und KI, die massenhaft und zugleich personalisiert ansprechen – etwa KI-personalisierte Coupons in den Retail-Apps von Lidl, REWE oder dm.',
    explanation: 'Zwei digitale Begriffe + Einordnung in Schritt 4.',
    source: 'Kapitel 3.1, PDF S. 11–12', conceptIds: ['mc-retargeting', 'mc-programmatic', 'mc-kanaele'],
  },
  {
    id: 'qm3-16', chapterId: 'm3', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erläutern Sie die Click-Through-Rate, die Conversion Rate und die Engagement Rate jeweils mit einem Beispiel und ordnen Sie sie in den Planungsprozess ein.',
    rubric: [
      { point: 'CTR: Klickhäufigkeit von Anzeigen (Banner gesehen, 1 % klickt)', keywords: ['klickhäufigkeit', 'klick', 'banner'] },
      { point: 'Conversion Rate: Anteil der Besucher mit Zielhandlung (100 Besucher, 5 Käufe = 5 %)', keywords: ['zielhandlung', 'anteil der besucher', '5 %', 'käufe'] },
      { point: 'Engagement Rate: Aktivität der Nutzer (Kommentare, Shares, Likes pro Post)', keywords: ['aktiv', 'kommentare', 'shares', 'likes'] },
      { point: 'Einordnung: Schritt 7 – Kommunikationsergebnisse messen', keywords: ['schritt 7', 'ergebnisse messen', 'wirkung', 'messen'] },
    ],
    modelAnswer: 'Die Click-Through-Rate misst die Klickhäufigkeit von Anzeigen – z. B. ein Banner wird gesehen, 1 % klickt. Die Conversion Rate ist der Anteil der Besucher, die eine Zielhandlung ausführen – 100 Besucher, 5 Käufe = 5 %. Die Engagement Rate misst, wie aktiv Nutzer reagieren, etwa Kommentare, Shares und Likes pro Post. Alle drei sind digitale Messgrößen für Schritt 7 „Kommunikationsergebnisse messen“ (neben Konsumentenbefragungen).',
    explanation: 'Drei Kennzahlen + Einordnung.',
    source: 'Kapitel 3.1, PDF S. 12', conceptIds: ['mc-ctr', 'mc-conversion', 'mc-engagement', 'mc-ergebnismessung'],
  },
  {
    id: 'qm3-17', chapterId: 'm3', type: 'open', goal: 'fact', difficulty: 2,
    prompt: 'Jedes Kommunikationswerkzeug hat Vor- und Nachteile. Wovon hängen Auswahl und Kombination der Werkzeuge laut Skript ab? Erläutern Sie in diesem Zusammenhang auch den Begriff Kaufentscheidung.',
    rubric: [
      { point: 'Marktstellung des Unternehmens; Art des Produktmarkts (Konsum oder Industrie)', keywords: ['marktstellung', 'produktmarkt', 'konsum', 'industrie'] },
      { point: 'Charakteristiken der Zielgruppe; Kaufbereitschaft/Art der Kaufentscheidung', keywords: ['zielgruppe', 'kaufbereitschaft', 'kaufentscheidung'] },
      { point: 'Phase im Lebenszyklus; verfügbares Budget', keywords: ['lebenszyklus', 'budget'] },
      { point: 'Kaufentscheidung: kognitiver/sonstiger Aufwand – impulsiv, habituell, limitiert, extensiv', keywords: ['aufwand', 'impulsiv', 'habituell', 'limitiert', 'extensiv'] },
    ],
    modelAnswer: 'Auswahl und Kombination hängen ab von (1) der Marktstellung des Unternehmens, (2) der Art des Produktmarkts (Konsum oder Industrie), (3) den Charakteristiken der Zielgruppe, (4) der Kaufbereitschaft der Konsumenten und der Art der Kaufentscheidung, (5) der Phase im Lebenszyklus und (6) dem zur Verfügung stehenden Budget. Die Kaufentscheidung bezieht sich darauf, mit welchem kognitiven und sonstigen Aufwand ein Kauf verbunden ist; man unterscheidet impulsive, habituelle, limitierte und extensive Kaufentscheidungen.',
    explanation: 'Sechs Faktoren + Kaufentscheidungstypen.',
    source: 'Kapitel 3.1, PDF S. 12', conceptIds: ['mc-medienkombination', 'mc-kaufentscheidung'],
  },
  {
    id: 'qm3-18', chapterId: 'm3', type: 'open', goal: 'understanding', difficulty: 3,
    prompt: 'Nennen und erläutern Sie die sechs Kriterien zur Einschätzung von Effektivität und Effizienz der integrierten Marketingkommunikation (Keller/Swaminathan 2019).',
    rubric: [
      { point: 'Reichweite: Wird die angestrebte Zielgruppe erreicht?', keywords: ['reichweite'] },
      { point: 'Mitwirkung: Auswirkung auf die Zielgruppe', keywords: ['mitwirkung', 'auswirkung'] },
      { point: 'Gemeinsamkeit: konsistente Botschaft über alle Wege', keywords: ['gemeinsamkeit', 'konsistent'] },
      { point: 'Komplementarität: Wege ergänzen sich gegenseitig', keywords: ['komplementarität', 'ergänzen'] },
      { point: 'Vielseitigkeit: wirkt bei Einfach- und Mehrfachkontakten', keywords: ['vielseitigkeit', 'mehreren kontakten', 'einem werkzeug'] },
      { point: 'Kosten', keywords: ['kosten'] },
    ],
    modelAnswer: 'Reichweite: Wird die angestrebte Zielgruppe erreicht? Mitwirkung: Welche Auswirkung hat die Kommunikation auf die Zielgruppe? Gemeinsamkeit: Vermitteln die verschiedenen Kommunikationswege eine konsistente Botschaft? Komplementarität: Ergänzen sich die Kommunikationswege gegenseitig? Vielseitigkeit: Wirkt die Kommunikation sowohl bei Konsumenten, die nur von einem Werkzeug erreicht werden, als auch bei denen mit mehreren Kontakten? Kosten: Welche Kosten fallen an?',
    explanation: 'Alle sechs mit Leitfrage – Gemeinsamkeit und Komplementarität sauber trennen.',
    source: 'Kapitel 3.1, PDF S. 12', conceptIds: ['mc-6kriterien', 'mc-integrierte-kommunikation'],
  },
  {
    id: 'qm3-19', chapterId: 'm3', type: 'open', goal: 'distinction', difficulty: 2,
    prompt: 'Grenzen Sie massenmediale und persönliche Kommunikation ab und erklären Sie, was Fragmentierung der Medienlandschaft bedeutet und welche Folgen sie hat.',
    rubric: [
      { point: 'Massenmedial: Botschaft an eine Masse, nicht individuell abgestimmt', keywords: ['masse', 'nicht individuell'] },
      { point: 'Persönlich: an individuelle Konsumenten, in Form und Inhalt anpassbar', keywords: ['individuell', 'angepasst', 'anpassbar', 'form und inhalt'] },
      { point: 'Fragmentierung: Mainstreammedien verlieren Reichweite, mehr Angebote mit spitzen Zielgruppensegmenten', keywords: ['mainstream', 'reichweite', 'spitze', 'zielgruppensegment'] },
      { point: 'Folge: definierte Zielgruppen leichter, viele Konsumenten über ein Medium schwerer erreichbar (Wetten, dass?)', keywords: ['einfacher', 'schwieriger', 'ein einziges medium', 'wetten'] },
    ],
    modelAnswer: 'Massenmediale Kommunikation richtet sich an eine Masse von Empfängern und ist nicht individuell auf Personen abgestimmt; persönliche Kommunikation richtet sich an individuelle Konsumenten und kann in Form und Inhalt angepasst werden. Fragmentierung bezeichnet die Änderung der Struktur der Medienlandschaft: Klassische Mainstreammedien verlieren an Reichweite, stattdessen gibt es immer mehr Angebote mit sehr spitzen Zielgruppensegmenten. Dadurch wird es einfacher, genau definierte Zielgruppen zu erreichen, aber schwieriger, viele Konsumenten über ein einziges Medium zu erreichen – „Wetten, dass?“ hatte in den 80ern 20 Mio. Zuschauer, vor der Einstellung 2014 nur noch 6–7 Mio.',
    explanation: 'Abgrenzung + Fragmentierung mit Beispiel.',
    source: 'Kapitel 3.2, PDF S. 12', conceptIds: ['mc-massenmedial', 'mc-persoenliche-komm', 'mc-fragmentierung'],
  },
  {
    id: 'qm3-20', chapterId: 'm3', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Definieren Sie Werbung, nennen Sie die vier Kanalgruppen und beurteilen Sie Werbung anhand von je drei Vor- und Nachteilen.',
    rubric: [
      { point: 'Definition: unpersönliche, von einem explizit genannten Auftraggeber bezahlte Präsentation von Produkten', keywords: ['unpersönlich', 'bezahlt', 'auftraggeber'] },
      { point: 'Kanäle: Print-, Übertragungs-, Display-, digitale Medien', keywords: ['print', 'übertragung', 'display', 'digital'] },
      { point: 'Vorteile: große Reichweite, Ausdruckskraft, wiederholbar, Image, volle Kontrolle', keywords: ['reichweite', 'große menge', 'ausdruckskraft', 'wiederholbar', 'kontrolle', 'image'] },
      { point: 'Nachteile: hohe Kosten, Werbemüdigkeit, Ausblenden, keine individuelle Ansprache, schwer messbar', keywords: ['kosten', 'werbemüdigkeit', 'ausblenden', 'individuelle ansprache', 'schwer messbar'] },
    ],
    modelAnswer: 'Werbung ist die unpersönliche, durch einen explizit genannten Auftraggeber bezahlte Präsentation von Produkten. Kanäle: Printmedien (Zeitungen, Flyer), Übertragungsmedien (Radio, TV, Kino), Displaymedien (Plakate, Schilder) und digitale Medien (soziale Netzwerke, Suchmaschinen, Websites, Apps). Vorteile: Erreichbarkeit einer großen Menge von Konsumenten, starke Ausdruckskraft durch Bild, Ton und Farbe, präsente und wiederholbare Botschaft, Aufbau eines positiven Images, volle Kontrolle über die Produktpräsentation. Nachteile: hohe Kosten, Werbemüdigkeit, mögliches Ausblenden durch neue Technologie, keine individuelle Ansprache, Effizienz und Effektivität schwer messbar.',
    explanation: 'Definition + Kanäle + Vor-/Nachteile.',
    source: 'Kapitel 3.2, PDF S. 13', conceptIds: ['mc-werbung', 'mc-werbemuedigkeit'],
  },
  {
    id: 'qm3-21', chapterId: 'm3', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Was ist Verkaufsförderung? Erläutern Sie, warum sie an Bedeutung gewonnen hat, wie sie sich von Wettbewerbsargumenten unterscheidet und welche Gefahr ein zu häufiger Einsatz birgt.',
    rubric: [
      { point: 'Kurzfristige Anregung von Verkauf durch gezielte Anreize (z. B. Coupons, Warenproben, Flash Sales)', keywords: ['kurzfristig', 'anreiz', 'coupon', 'warenprobe', 'flash'] },
      { point: 'Bedeutungsgewinn, weil die Wirkung klassischer Werbung nachlässt', keywords: ['wirkung klassischer werbung', 'nachlässt', 'klassische werbung'] },
      { point: 'Keine Wettbewerbsargumente, sondern greifbare, direkte Anreize; durch zeitliche Limitierung messbar', keywords: ['keine argumente', 'greifbar', 'direkte anreize', 'zeitliche limitierung', 'messbar'] },
      { point: 'Gefahr: Wirkungsnachlass, Schaden für den Markenwert', keywords: ['markenwert', 'wirkungsnachlass', 'schaden', 'nachlass'] },
    ],
    modelAnswer: 'Verkaufsförderung (Promotion) ist die kurzfristige Anregung von Verkauf durch gezielte Anreize wie Warenproben, Coupons, Preisnachlässe, Flash Sales oder Gamification. Sie hat an Bedeutung gewonnen, weil die Wirkung klassischer Werbung nachlässt. Sie liefert keine Argumente im Sinne von Wettbewerbsvorteilen, sondern greifbare, direkte Anreize zum Handeln (z. B. Black Friday); durch die zeitliche Limitierung lassen sich die Effekte messen. Zu starker oder zu häufiger Einsatz führt aber zu Wirkungsnachlass und kann dem Markenwert schaden.',
    explanation: 'Definition + Bedeutungsgewinn + Abgrenzung + Risiko.',
    source: 'Kapitel 3.2, PDF S. 13', conceptIds: ['mc-verkaufsfoerderung'],
  },
  {
    id: 'qm3-22', chapterId: 'm3', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erläutern Sie Sponsoring und Eventmarketing: Was tun Unternehmen dabei, wie wirkt es und welche Ziele werden verfolgt?',
    rubric: [
      { point: 'Organisieren/finanzieren Aktivitäten in Sport, Kunst, Unterhaltung, Wohltätigkeit (auch Festivals, Webinare, Firmenmuseen)', keywords: ['sport', 'kunst', 'unterhaltung', 'wohltätigkeit', 'festival', 'organisieren', 'unterstützen'] },
      { point: 'Markenaufbauender Kontakt, emotionale Bindung durch gemeinsame Erlebnisse', keywords: ['emotionale bindung', 'gemeinsame erlebnisse', 'erlebnis', 'markenaufbauend'] },
      { point: 'Ziele: Bekanntheit, Image, Kontaktpflege, gesellschaftliches Engagement (neben ökonomischen Größen)', keywords: ['bekanntheit', 'image', 'kontaktpflege', 'engagement', 'verantwortung'] },
      { point: 'Beispiele: Mercedes/Fashion Week Berlin, Red Bull Music Academy/Flugtage', keywords: ['mercedes', 'fashion week', 'red bull'], weight: 0.5 },
    ],
    modelAnswer: 'Unternehmen organisieren und/oder unterstützen finanziell Aktivitäten und Programme in Sport, Kunst, Unterhaltung oder Wohltätigkeit – auch Festivals, virtuelle Events, Webinare, Werksbesichtigungen, Firmenmuseen (Porschemuseum) oder Aktionen in Fußgängerzonen. Der Sponsor tritt in markenaufbauenden Kontakt und schafft durch gemeinsame Erlebnisse eine emotionale Bindung (z. B. Mercedes bei der Fashion Week Berlin, Red Bull mit Music Academy und Flugtagen). Neben ökonomischen Größen (Umsatz, Gewinn, Marktanteil) werden vor allem psychologische Ziele verfolgt: Steigerung der Bekanntheit, Imageverbesserung, Kontaktpflege und der Nachweis gesellschaftlichen Engagements und Verantwortung.',
    explanation: 'Definition + Wirkung + Ziele.',
    source: 'Kapitel 3.2, PDF S. 13–14', conceptIds: ['mc-sponsoring'],
  },
  {
    id: 'qm3-23', chapterId: 'm3', type: 'open', goal: 'fact', difficulty: 3,
    prompt: 'Nennen und erläutern Sie die sieben Funktionen der Public Relations nach Meffert et al. (2015).',
    rubric: [
      { point: 'Informationsfunktion: Informationen an die Öffentlichkeit', keywords: ['informationsfunktion', 'information'] },
      { point: 'Kontaktfunktion: Stakeholderverbindungen aufbauen/erhalten', keywords: ['kontaktfunktion', 'kontakt'] },
      { point: 'Imagefunktion: Unternehmensbild aufbauen, ändern, pflegen', keywords: ['imagefunktion', 'unternehmensbild', 'image'] },
      { point: 'Absatzförderungsfunktion: Verkaufsförderung durch Anerkennung und Vertrauen', keywords: ['absatzförderung', 'anerkennung'] },
      { point: 'Sozialfunktion: gesellschaftliche/soziale Leistungen aufzeigen', keywords: ['sozialfunktion', 'gesellschaftlich', 'sozial'] },
      { point: 'Balancefunktion (Anreiz-Beitrags-Gleichgewicht) und Stabilisierungsfunktion (Krisenfestigkeit)', keywords: ['balance', 'anreiz-beitrag', 'gleichgewicht', 'stabilisierung', 'krisenfest'] },
    ],
    modelAnswer: 'Informationsfunktion: Vermittlung von Informationen an die Öffentlichkeit. Kontaktfunktion: Aufbau und Aufrechterhaltung der Stakeholderverbindungen. Imagefunktion: Aufbau, Änderung und Pflege des Unternehmensbildes. Absatzförderungsfunktion: Verkaufsförderung durch Anerkennung und Vertrauen. Sozialfunktion: Aufzeigen der gesellschaftlichen und sozialen Unternehmensleistungen. Balancefunktion: Anreiz-Beitrags-Gleichgewicht der Unternehmensstakeholder. Stabilisierungsfunktion: Erhöhung der Krisenfestigkeit aufgrund stabiler Beziehungen zu den Anspruchsgruppen.',
    explanation: 'Typische Aufzählungsfrage – alle sieben mit Kurzerklärung.',
    source: 'Kapitel 3.2, PDF S. 14', conceptIds: ['mc-pr-funktionen', 'mc-pr'],
  },
  {
    id: 'qm3-24', chapterId: 'm3', type: 'open', goal: 'distinction', difficulty: 2,
    prompt: 'Grenzen Sie Direktmarketing und interaktives Marketing voneinander ab. Gehen Sie auf Beispiele, Ziele und die gemeinsamen Probleme ein.',
    rubric: [
      { point: 'Direktmarketing: Konsumenten direkt angesprochen (Kataloge, Telefon, E-Mail/SMS, TV-Shopping)', keywords: ['direkt angesprochen', 'katalog', 'telefon', 'e-mail', 'sms', 'tv-shopping'] },
      { point: 'Ziele: Neukundengewinnung, intensive Betreuung, Kundennähe/-bindung', keywords: ['neukunden', 'betreuung', 'kundennähe', 'kundenbindung'] },
      { point: 'Interaktiv: Weiterentwicklung mit Austausch Konsument–Unternehmen (E-Commerce, Chatbots, Social Media, Retargeting, suchgebundene Anzeigen)', keywords: ['weiterentwicklung', 'austausch', 'chatbot', 'e-commerce', 'social media', 'suchgebunden'] },
      { point: 'Probleme: ethische Probleme (Irreführung, Betrug, Ausnutzung, Privatsphäre), Ablehnung/Ausblenden', keywords: ['ethisch', 'irreführung', 'betrug', 'privatsphäre', 'ablehnung', 'ausblenden'] },
    ],
    modelAnswer: 'Direktmarketing umfasst Werbemaßnahmen, mit denen Konsumenten direkt angesprochen werden – z. B. Postwurfsendung von Katalogen, Telefonmarketing, E-Mail/SMS, TV-Shopping oder versandte Müsliproben. Ziele sind Neukundengewinnung und die intensive Betreuung bestehender Kunden (Kundennähe, Kundenbindung, effizientere Ansprache). Interaktives Marketing ist die Weiterentwicklung: Es findet ein Austausch zwischen Konsument und Unternehmen statt, heute über E-Commerce, Webseiten mit Chatbots und KI-Personalisierung, soziale Medien, Apps, Retargeting und suchgebundene Anzeigen; zusätzlich lassen sich über digitale Daten die Interessen ermitteln. Beide teilen ethische Probleme (Irreführung, Betrug, Ausnutzung, Verletzung der Privatsphäre); Direktmarketing wird von vielen abgelehnt und erfordert die Verwaltung von Kontaktdaten, beim interaktiven Marketing droht das Ausblenden der Botschaften.',
    explanation: 'Einbahnstraße vs. Austausch.',
    source: 'Kapitel 3.2, PDF S. 14–15', conceptIds: ['mc-direktmarketing', 'mc-interaktiv', 'mc-suchgebunden'],
  },
  {
    id: 'qm3-25', chapterId: 'm3', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Erklären Sie Mund-zu-Mund-Kommunikation und ihre drei Formen. Warum ist sie so einflussreich und wo liegen ihre Grenzen?',
    rubric: [
      { point: 'Persönliche Kommunikation von Konsumenten untereinander über Erfahrungen; zunehmend elektronisch', keywords: ['untereinander', 'erfahrungen', 'elektronisch', 'konsumenten'] },
      { point: 'Buzz (Foren, Bewertungsplattformen, Instagram/Reddit), Viral (Verbreitung multipliziert), Influencer (Kooperation mit reichweitenstarken Personen)', keywords: ['buzz', 'viral', 'influencer'] },
      { point: 'Sehr einflussreich durch persönliche Bindung, zeitnah, Dialog', keywords: ['persönliche bindung', 'einflussreich', 'zeitnah', 'dialog'] },
      { point: 'Grenzen: begrenzte Einflussmöglichkeiten der Unternehmen, Wirkung schwer messbar', keywords: ['begrenzte einfluss', 'schwer messbar', 'einflussmöglichkeit'] },
    ],
    modelAnswer: 'Mund-zu-Mund-Kommunikation (Word-of-Mouth) ist die persönliche Kommunikation von Konsumenten untereinander über ihre Erfahrungen mit Unternehmen und Produkten – zunehmend elektronisch über soziale Medien und Blogs. Formen: Buzz Marketing (Mundpropaganda in Foren, auf Bewertungsplattformen oder Plattformen wie Instagram oder Reddit), Viral Marketing (Verbreitung wird über Influencer oder Onlinemedien multipliziert) und Influencer-Marketing (strategische Kooperation mit reichweitenstarken Personen, deren authentische Stimme und Glaubwürdigkeit genutzt werden). Wegen der persönlichen Bindung ist WoM sehr einflussreich, dialogisch und zeitnah (Amazon nutzt Kundenbewertungen zur Verbesserung der Angebote). Grenzen: Unternehmen haben nur begrenzte Einflussmöglichkeiten, und die Wirkung ist schwer messbar.',
    explanation: 'Definition + drei Formen + Vor-/Nachteile.',
    source: 'Kapitel 3.2, PDF S. 15', conceptIds: ['mc-wom', 'mc-buzz', 'mc-viral', 'mc-influencer'],
  },
  {
    id: 'qm3-26', chapterId: 'm3', type: 'open', goal: 'understanding', difficulty: 2,
    prompt: 'Warum gilt der persönliche Verkauf als effektivstes Mittel zur Kaufbeeinflussung, wo ist er besonders verbreitet und was spricht gegen ihn?',
    rubric: [
      { point: 'Präsentation eines Angebots durch einen Verkäufer; besonders im B2B (Großgeräte an Kliniken, Pharmareferent)', keywords: ['verkäufer', 'b2b', 'großgerät', 'pharmareferent', 'krankenhaus'] },
      { point: 'Verkäufer reagiert unmittelbar auf den Konsumenten (direkte Interaktion)', keywords: ['unmittelbar', 'direkte interaktion', 'reaktion'] },
      { point: 'Kultivierung langfristiger Kundenbeziehungen', keywords: ['langfristig', 'kundenbeziehung', 'kultivier'] },
      { point: 'Nachteil: hohe Kosten (Verkäufer, Reisekosten)', keywords: ['hohe kosten', 'reisekosten', 'teuer'] },
    ],
    modelAnswer: 'Persönlicher Verkauf ist die Präsentation eines Angebots durch einen Verkäufer – besonders im B2B-Geschäft verbreitet, z. B. medizinische Großgeräte an Krankenhäuser oder der Pharmareferent beim Arzt; dazu Verkaufspräsentationen, Messen und Expos. Er gilt als effektivstes Mittel, weil der Verkäufer unmittelbar auf die Reaktion des Konsumenten eingehen und langfristige Kundenbeziehungen kultivieren kann. Dagegen sprechen die hohen Kosten für Verkäufer und Reisen.',
    explanation: 'Effektivität durch direkte Interaktion, aber teuer.',
    source: 'Kapitel 3.2, PDF S. 16', conceptIds: ['mc-persoenlicher-verkauf'],
  },
  {
    id: 'qm3-27', chapterId: 'm3', type: 'transfer', goal: 'application', difficulty: 2,
    prompt: 'Ein Hersteller hochpreisiger, erklärungsbedürftiger Laborgeräte will Universitätskliniken als Kunden gewinnen. Welches Kommunikationsinstrument steht im Mittelpunkt? Begründen Sie mit Vor- und Nachteilen.',
    rubric: [
      { point: 'Persönlicher Verkauf', keywords: ['persönlicher verkauf', 'verkäufer', 'außendienst'] },
      { point: 'Begründung: B2B, effektivstes Mittel, direkte Interaktion, unmittelbare Reaktion', keywords: ['b2b', 'effektiv', 'direkte interaktion', 'unmittelbar', 'reaktion'] },
      { point: 'Langfristige Kundenbeziehung kultivieren (z. B. Messen, Präsentationen)', keywords: ['langfristig', 'kundenbeziehung', 'messe', 'präsentation'] },
      { point: 'Nachteil hohe Kosten – gerechtfertigt durch hohen Auftragswert', keywords: ['kosten', 'teuer', 'reisekosten'] },
    ],
    modelAnswer: 'Im Mittelpunkt steht der persönliche Verkauf: Er ist besonders im B2B-Geschäft verbreitet (wie medizinische Großgeräte an Krankenhäuser) und das effektivste Mittel zur Kaufbeeinflussung, weil der Verkäufer in Präsentationen und auf Messen direkt mit den Entscheidern interagiert, unmittelbar auf Fragen reagieren und langfristige Kundenbeziehungen kultivieren kann. Der Nachteil – hohe Kosten für Verkäufer und Reisen – ist bei wenigen, hochpreisigen Aufträgen vertretbar.',
    explanation: 'B2B + erklärungsbedürftig + hoher Wert → persönlicher Verkauf.',
    source: 'Kapitel 3.2, PDF S. 16', conceptIds: ['mc-persoenlicher-verkauf', 'mc-b2b'],
  },
  {
    id: 'qm3-28', chapterId: 'm3', type: 'transfer', goal: 'application', difficulty: 3,
    prompt: 'Bei einem Getränkehersteller laufen TikTok-Kampagne, Plakatwerbung und Sponsoring unabhängig voneinander; jede Abteilung kommuniziert eine andere Kernbotschaft, und niemand überwacht die Kampagnen. Beurteilen Sie die Situation anhand der Kriterien und Schritte der integrierten Marketingkommunikation.',
    rubric: [
      { point: 'Kriterium Gemeinsamkeit verletzt: keine konsistente Botschaft', keywords: ['gemeinsamkeit', 'konsistent', 'einheitlich', 'stimmig'] },
      { point: 'Komplementarität fehlt: Wege ergänzen sich nicht', keywords: ['komplementarität', 'ergänzen'] },
      { point: 'Integration nötig: Aktivitäten aufeinander abstimmen, einheitliche Markenbotschaft', keywords: ['integriert', 'abstimm', 'markenbotschaft', 'kohärent'] },
      { point: 'Schritt 8: Prozess steuern – Instrumente nicht isoliert, überwachen, koordinieren, anpassen', keywords: ['steuern', 'isoliert', 'überwach', 'koordinier', 'anpass'] },
    ],
    modelAnswer: 'Die Kommunikation ist nicht integriert. Nach Keller/Swaminathan ist vor allem das Kriterium Gemeinsamkeit verletzt, weil die Wege keine konsistente Botschaft vermitteln; auch Komplementarität fehlt, da sich die Kanäle nicht gegenseitig ergänzen. Kommunikationsaktivitäten müssen integriert und aufeinander abgestimmt werden, damit eine einheitliche und stimmige Markenbotschaft entsteht. Zudem wird Schritt 8 vernachlässigt: Instrumente dürfen nicht isoliert laufen, sondern müssen kontinuierlich überwacht, koordiniert und bei Bedarf angepasst werden – zunehmend über Marketing-Automatisierungssysteme.',
    explanation: 'Anwendung der IMK-Kriterien auf einen Missstand.',
    source: 'Kapitel 3.1, PDF S. 11–12 und 16', conceptIds: ['mc-6kriterien', 'mc-integrierte-kommunikation', 'mc-prozesssteuerung', 'mc-kommmix'],
  },
  {
    id: 'qm3-29', chapterId: 'm3', type: 'transfer', goal: 'application', difficulty: 2,
    prompt: 'Ein Onlinehändler startet seit Monaten jede Woche eine neue Rabattaktion. Die Umsätze steigen kaum noch, Kunden kaufen nur noch mit Gutschein. Erklären Sie diese Entwicklung mithilfe des Skripts.',
    rubric: [
      { point: 'Verkaufsförderung: kurzfristige Anreize', keywords: ['verkaufsförderung', 'kurzfristig', 'anreiz'] },
      { point: 'Zu häufiger Einsatz → Wirkungsnachlass; Konsumenten blenden Maßnahmen wegen Überfrachtung aus', keywords: ['wirkungsnachlass', 'lässt nach', 'überfrachtung', 'ausblend'] },
      { point: 'Schaden für den Markenwert', keywords: ['markenwert', 'marke'] },
    ],
    modelAnswer: 'Rabattaktionen sind Verkaufsförderung – kurzfristige, direkte Kaufanreize. Laut Skript führt ein zu starker oder zu häufiger Einsatz zu Wirkungsnachlass: Die Wirkung lässt mit der Zeit nach, und Konsumenten blenden verkaufsfördernde Maßnahmen wegen Überfrachtung aus. Außerdem kann dies dem Markenwert schaden – Kunden gewöhnen sich an Rabatte und kaufen nur noch mit Gutschein.',
    explanation: 'Nachteile der Verkaufsförderung in der Praxis.',
    source: 'Kapitel 3.2, PDF S. 13', conceptIds: ['mc-verkaufsfoerderung', 'mc-konsistenter-mix'],
  },

  // ======================= neue geschlossene Fragen =======================
  {
    id: 'qm3-30', chapterId: 'm3', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Was versteht man unter medienneutraler Planung?',
    options: [
      'Alle Kommunikationsoptionen und -kanäle werden objektiv nach Effektivität (Nutzen) und Effizienz (Aufwand) bewertet.',
      'Es wird grundsätzlich auf Massenmedien verzichtet.',
      'Jedes Medium erhält das gleiche Budget.',
      'Die Botschaft wird für jedes Medium neu erfunden.',
    ],
    correctOptions: [0],
    explanation: 'Medienneutral = objektive Bewertung aller Optionen nach Nutzen und Aufwand.',
    source: 'Kapitel 3.1, PDF S. 11', conceptIds: ['mc-medienneutral'],
  },
  {
    id: 'qm3-31', chapterId: 'm3', type: 'assignment', goal: 'application', difficulty: 2,
    prompt: 'Ordnen Sie das Praxisbeispiel dem passenden Schritt der Kommunikationsplanung zu.',
    pairs: [
      { left: 'HelloFresh spricht abgesprungene Kunden mit E-Mails, Anrufen und Retargeting an', right: 'Zielgruppe auswählen' },
      { left: 'Nikes „Just Do It“ seit 1988', right: 'Kommunikationsbotschaft bestimmen' },
      { left: 'Zara setzt auf Standorte, Store-Design und Mund-zu-Mund statt Werbung', right: 'Kommunikationsmix gestalten' },
      { left: 'Duolingo „Duo is Dead“: +51 % täglich aktive Nutzer', right: 'Kommunikationsergebnisse messen' },
      { left: 'Merit Beauty verlagert 2025 kurzfristig Budget von TikTok', right: 'Marketingkommunikationsprozess steuern' },
    ],
    explanation: 'Alle Beispiele stammen aus der Acht-Schritte-Liste im Skript.',
    source: 'Kapitel 3.1, PDF S. 11–12', conceptIds: ['mc-8schritte-komm', 'mc-zielgruppe', 'mc-botschaft', 'mc-kommmix', 'mc-ergebnismessung', 'mc-prozesssteuerung'],
  },
  {
    id: 'qm3-32', chapterId: 'm3', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Welche Methode der Budgetfestlegung bezeichnet das Skript als empfehlenswert?',
    options: ['Auf Basis von Zielen und Aufgaben', 'Als Prozentsatz des Umsatzes', 'Nach den finanziellen Möglichkeiten', 'Orientiert an den Mitbewerbern'],
    correctOptions: [0],
    explanation: 'Die ziel- und aufgabenorientierte Budgetierung ist der empfehlenswerte Weg.',
    source: 'Kapitel 3.1, PDF S. 11', conceptIds: ['mc-budget'],
  },
  {
    id: 'qm3-33', chapterId: 'm3', type: 'cloze', goal: 'application', difficulty: 1,
    prompt: 'Ein Onlineshop hat 100 Besucher, von denen 5 kaufen. Die Conversion Rate beträgt damit ______ Prozent.',
    clozeAnswers: [['5', 'fünf', '5 %', '5%']],
    explanation: 'Conversion Rate = Anteil der Besucher mit Zielhandlung: 5 von 100 = 5 %.',
    source: 'Kapitel 3.1, PDF S. 12', conceptIds: ['mc-conversion'],
  },
  {
    id: 'qm3-34', chapterId: 'm3', type: 'true_false', goal: 'fact', difficulty: 1,
    prompt: 'Retargeting ist eine Onlinestrategie, bei der ehemalige Besucher gezielt erneut angesprochen werden.',
    correctBool: true,
    explanation: 'Richtig – z. B. eine Instagram-Anzeige für zuvor angesehene Produkte.',
    source: 'Kapitel 3.1, PDF S. 12', conceptIds: ['mc-retargeting'],
  },
  {
    id: 'qm3-35', chapterId: 'm3', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Was ist programmatische Werbung (Programmatic Advertising)?',
    options: [
      'Automatisierter Anzeigenhandel über Algorithmen, die Werbeflächen in Echtzeit ersteigern',
      'Werbung, die ein festes Fernsehprogramm unterbricht',
      'Die Planung von Werbung nach einem Jahresprogramm',
      'Werbung ausschließlich in Printmedien',
    ],
    correctOptions: [0],
    explanation: 'Programmatic Advertising: Algorithmen ersteigern Werbeflächen in Echtzeit.',
    source: 'Kapitel 3.1, PDF S. 12', conceptIds: ['mc-programmatic'],
  },
  {
    id: 'qm3-36', chapterId: 'm3', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Wovon hängen laut Skript Auswahl und Kombination der Kommunikationswerkzeuge ab? (Mehrfachauswahl)',
    options: ['Marktstellung des Unternehmens', 'Phase im Lebenszyklus', 'Zur Verfügung stehendes Budget', 'Geschlecht des Geschäftsführers', 'Art des Produktmarkts (Konsum oder Industrie)'],
    correctOptions: [0, 1, 2, 4],
    explanation: 'Sechs Faktoren: Marktstellung, Art des Produktmarkts, Zielgruppencharakteristiken, Kaufbereitschaft/Art der Kaufentscheidung, Lebenszyklusphase, Budget.',
    source: 'Kapitel 3.1, PDF S. 12', conceptIds: ['mc-medienkombination'],
  },
  {
    id: 'qm3-37', chapterId: 'm3', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie das Kriterium der integrierten Marketingkommunikation seiner Leitfrage zu.',
    pairs: [
      { left: 'Reichweite', right: 'Wird die angestrebte Zielgruppe erreicht?' },
      { left: 'Mitwirkung', right: 'Welche Auswirkung hat die Kommunikation auf die Zielgruppe?' },
      { left: 'Gemeinsamkeit', right: 'Vermitteln die Kommunikationswege eine konsistente Botschaft?' },
      { left: 'Komplementarität', right: 'Ergänzen sich die Kommunikationswege gegenseitig?' },
      { left: 'Vielseitigkeit', right: 'Wirkt die Kommunikation bei Konsumenten mit einem wie mit mehreren Kontakten?' },
    ],
    explanation: 'Sechstes Kriterium: Kosten (Keller/Swaminathan 2019).',
    source: 'Kapitel 3.1, PDF S. 12', conceptIds: ['mc-6kriterien'],
  },
  {
    id: 'qm3-38', chapterId: 'm3', type: 'cloze', goal: 'fact', difficulty: 2,
    prompt: 'Nach dem Aufwand unterscheidet man impulsive, ______, limitierte und ______ Kaufentscheidungen.',
    clozeAnswers: [['habituelle', 'habituell'], ['extensive', 'extensiv']],
    explanation: 'Impulsiv – habituell – limitiert – extensiv (steigender kognitiver Aufwand).',
    source: 'Kapitel 3.1, PDF S. 12', conceptIds: ['mc-kaufentscheidung'],
  },
  {
    id: 'qm3-39', chapterId: 'm3', type: 'single_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Wofür steht das Beispiel „Wetten, dass?“ (20 Mio. Zuschauer in den 80ern, 6–7 Mio. vor der Einstellung 2014) im Skript?',
    options: [
      'Für die Fragmentierung der Medienlandschaft',
      'Für erfolgreiches Product Placement',
      'Für Werbemüdigkeit durch Unterbrechungen',
      'Für virales Marketing',
    ],
    correctOptions: [0],
    explanation: 'Mainstreammedien verlieren an Reichweite – viele Konsumenten über ein einziges Medium zu erreichen wird schwieriger.',
    source: 'Kapitel 3.2, PDF S. 12', conceptIds: ['mc-fragmentierung'],
  },
  {
    id: 'qm3-40', chapterId: 'm3', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Was versteht man unter Product Placement?',
    options: [
      'Gezielte, in den Kontext eingebundene Darstellung von Markenprodukten in Medien wie Film, Fernsehen oder Videospielen',
      'Die Platzierung von Produkten im Supermarktregal',
      'Bezahlte Einblendungen in Suchmaschinen',
      'Die Verteilung von Warenproben',
    ],
    correctOptions: [0],
    explanation: 'Product Placement ist eine Werbemaßnahme in Medieninhalten.',
    source: 'Kapitel 3.2, PDF S. 13', conceptIds: ['mc-product-placement'],
  },
  {
    id: 'qm3-41', chapterId: 'm3', type: 'true_false', goal: 'distinction', difficulty: 2,
    prompt: 'Search Engine Advertising (SEA) bezeichnet bezahlte Einblendungen innerhalb von Suchmaschinen-Ergebnisseiten.',
    correctBool: true,
    explanation: 'Richtig – im Unterschied zu SEO (Optimierung der Webseite für ein besseres Ranking, Kapitel 5).',
    source: 'Kapitel 3.2, PDF S. 13', conceptIds: ['mc-sea'],
  },
  {
    id: 'qm3-42', chapterId: 'm3', type: 'single_choice', goal: 'fact', difficulty: 2,
    prompt: 'Was ist Verbundwerbung?',
    options: [
      'Unternehmen unterschiedlicher Branchen, die die gleichen Konsumenten ansprechen, schließen sich zu einer gemeinsamen Werbeaktion zusammen.',
      'Mehrere Filialen desselben Händlers werben gemeinsam.',
      'Werbung, die über mehrere Medien gleichzeitig läuft.',
      'Werbung eines Herstellers gemeinsam mit seinen Konkurrenten derselben Branche.',
    ],
    correctOptions: [0],
    explanation: 'Verbundwerbung ist ein Instrument der Verkaufsförderung.',
    source: 'Kapitel 3.2, PDF S. 13', conceptIds: ['mc-verbundwerbung'],
  },
  {
    id: 'qm3-43', chapterId: 'm3', type: 'multiple_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche der folgenden Maßnahmen zählen laut Skript zur Verkaufsförderung? (Mehrfachauswahl)',
    options: ['Coupons als QR-Code', 'Flash Sales', 'Gamification-Elemente in Apps', 'Pressemitteilungen', 'Inzahlungnahme'],
    correctOptions: [0, 1, 2, 4],
    explanation: 'Pressemitteilungen gehören zur Public Relations.',
    source: 'Kapitel 3.2, PDF S. 13–14', conceptIds: ['mc-verkaufsfoerderung', 'mc-pr'],
  },
  {
    id: 'qm3-44', chapterId: 'm3', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Welches Sponsoring-Beispiel nennt das Skript?',
    options: ['Mercedes sponsert die Fashion Week Berlin', 'Nike sponsert „Wetten, dass?“', 'Apple sponsert die Fußball-WM', 'Zara sponsert ein Musikfestival'],
    correctOptions: [0],
    explanation: 'Weitere Skript-Beispiele: Red Bull Music Academy und Flugtage, Porschemuseum.',
    source: 'Kapitel 3.2, PDF S. 14', conceptIds: ['mc-sponsoring'],
  },
  {
    id: 'qm3-45', chapterId: 'm3', type: 'assignment', goal: 'fact', difficulty: 3,
    prompt: 'Ordnen Sie die PR-Funktion ihrer Bedeutung zu (Meffert et al. 2015).',
    pairs: [
      { left: 'Informationsfunktion', right: 'Vermittlung von Informationen an die Öffentlichkeit' },
      { left: 'Kontaktfunktion', right: 'Aufbau und Aufrechterhaltung der Stakeholderverbindungen' },
      { left: 'Imagefunktion', right: 'Aufbau, Änderung und Pflege des Unternehmensbildes' },
      { left: 'Absatzförderungsfunktion', right: 'Verkaufsförderung durch Anerkennung und Vertrauen' },
      { left: 'Sozialfunktion', right: 'Aufzeigen der gesellschaftlichen und sozialen Unternehmensleistungen' },
      { left: 'Balancefunktion', right: 'Anreiz-Beitrags-Gleichgewicht der Unternehmensstakeholder' },
      { left: 'Stabilisierungsfunktion', right: 'Erhöhung der Krisenfestigkeit durch stabile Beziehungen' },
    ],
    explanation: 'Die sieben Funktionen der PR.',
    source: 'Kapitel 3.2, PDF S. 14', conceptIds: ['mc-pr-funktionen'],
  },
  {
    id: 'qm3-46', chapterId: 'm3', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Wer sind Anspruchsgruppen (Stakeholders)?',
    options: [
      'Personen oder Gruppen, die von der Tätigkeit eines Unternehmens auf irgendeine Weise betroffen sind',
      'Ausschließlich die Aktionäre eines Unternehmens',
      'Nur die Kunden eines Unternehmens',
      'Die Vertriebspartner im indirekten Vertrieb',
    ],
    correctOptions: [0],
    explanation: 'Stakeholder sind alle in irgendeiner Weise Betroffenen – die PR sucht den Dialog mit allen Anspruchsgruppen.',
    source: 'Kapitel 3.2, PDF S. 14', conceptIds: ['mc-stakeholder'],
  },
  {
    id: 'qm3-47', chapterId: 'm3', type: 'true_false', goal: 'understanding', difficulty: 2,
    prompt: 'Bei der PR hat das Unternehmen volle Kontrolle darüber, ob und wie seine Botschaft dargestellt wird.',
    correctBool: false,
    explanation: 'Falsch – genau das ist ein Nachteil der PR: wenig Kontrolle über die Darstellung. Volle Kontrolle bietet die Werbung.',
    source: 'Kapitel 3.2, PDF S. 13–14', conceptIds: ['mc-pr', 'mc-werbung'],
  },
  {
    id: 'qm3-48', chapterId: 'm3', type: 'multiple_choice', goal: 'fact', difficulty: 1,
    prompt: 'Welche Maßnahmen nennt das Skript als Beispiele für Direktmarketing? (Mehrfachauswahl)',
    options: ['Postwurfsendung von Katalogen', 'Telefonmarketing', 'TV-Shopping', 'Plakatwerbung', 'Versenden von Müsliproben'],
    correctOptions: [0, 1, 2, 4],
    explanation: 'Plakate sind Displaymedien der (massenmedialen) Werbung.',
    source: 'Kapitel 3.2, PDF S. 14', conceptIds: ['mc-direktmarketing'],
  },
  {
    id: 'qm3-49', chapterId: 'm3', type: 'single_choice', goal: 'understanding', difficulty: 2,
    prompt: 'Welchen besonderen Vorteil haben suchgebundene Anzeigen?',
    options: [
      'Sie erleichtern die gezielte Ansprache von Kunden, die sich gerade in der Suchphase des Kaufentscheidungsprozesses befinden.',
      'Sie sind immer kostenlos.',
      'Sie erreichen garantiert alle Konsumenten eines Landes.',
      'Sie ersetzen den persönlichen Verkauf.',
    ],
    correctOptions: [0],
    explanation: 'Suchgebundene Anzeigen erscheinen neben den eigentlichen Suchergebnissen.',
    source: 'Kapitel 3.2, PDF S. 15', conceptIds: ['mc-suchgebunden', 'mc-interaktiv'],
  },
  {
    id: 'qm3-50', chapterId: 'm3', type: 'assignment', goal: 'distinction', difficulty: 2,
    prompt: 'Ordnen Sie die Form der Mund-zu-Mund-Kommunikation ihrer Beschreibung zu.',
    pairs: [
      { left: 'Buzz Marketing', right: 'Mundpropaganda in Foren, auf Bewertungsplattformen oder Plattformen wie Instagram/Reddit' },
      { left: 'Viral Marketing', right: 'Die Verbreitung von Inhalten wird über Influencer oder Onlinemedien multipliziert' },
      { left: 'Influencer-Marketing', right: 'Kooperation mit reichweitenstarken Personen, deren authentische Stimme genutzt wird' },
    ],
    explanation: 'Influencer-Marketing ist die gezielte strategische Nutzung des viralen Effekts.',
    source: 'Kapitel 3.2, PDF S. 15', conceptIds: ['mc-buzz', 'mc-viral', 'mc-influencer'],
  },
  {
    id: 'qm3-51', chapterId: 'm3', type: 'single_choice', goal: 'fact', difficulty: 1,
    prompt: 'Welchen Nachteil nennt das Skript für den persönlichen Verkauf?',
    options: ['Hohe Kosten (Verkäufer und Reisekosten)', 'Geringe Glaubwürdigkeit', 'Keine direkte Interaktion', 'Nur im B2C einsetzbar'],
    correctOptions: [0],
    explanation: 'Ansonsten gilt er als effektivstes Mittel zur Kaufbeeinflussung.',
    source: 'Kapitel 3.2, PDF S. 16', conceptIds: ['mc-persoenlicher-verkauf'],
  },
  {
    id: 'qm3-52', chapterId: 'm3', type: 'multiple_choice', goal: 'fact', difficulty: 1,
    prompt: 'Welche Instrumente zählen zu den massenmedialen Kommunikationsinstrumenten? (Mehrfachauswahl)',
    options: ['Werbung', 'Verkaufsförderung', 'Sponsoring & Eventmarketing', 'Public Relations', 'Direktmarketing'],
    correctOptions: [0, 1, 2, 3],
    explanation: 'Direktmarketing ist ein persönliches Instrument.',
    source: 'Kapitel 3.2, PDF S. 13', conceptIds: ['mc-massenmedial', 'mc-kommmix'],
  },
  {
    id: 'qm3-53', chapterId: 'm3', type: 'single_choice', goal: 'application', difficulty: 1,
    prompt: 'Amazon nutzt Kundenbewertungen gezielt zur Verbesserung seiner Angebote. Zu welchem Instrument gehört dieses Skript-Beispiel?',
    options: ['Mund-zu-Mund-Kommunikation', 'Persönlicher Verkauf', 'Sponsoring', 'Verbundwerbung'],
    correctOptions: [0],
    explanation: 'Kundenbewertungen sind (elektronische) Mund-zu-Mund-Kommunikation – zeitnah und einflussreich.',
    source: 'Kapitel 3.2, PDF S. 15', conceptIds: ['mc-wom'],
  },
  {
    id: 'qm3-54', chapterId: 'm3', type: 'single_choice', goal: 'fact', difficulty: 2,
    prompt: 'Welche Coca-Cola-Kampagne nennt das Skript als Beispiel für das Festlegen von Kommunikationszielen?',
    options: ['„New Guy“ – das gesamte Portfolio emotional erlebbar machen', '„Just Do It“', '„Duo is Dead“', '„Mission Mini“'],
    correctOptions: [0],
    explanation: '„Just Do It“ = Nike (Botschaft), „Duo is Dead“ = Duolingo (Messung), „Mission Mini“ = BMW Mini (PR).',
    source: 'Kapitel 3.1, PDF S. 11', conceptIds: ['mc-komm-ziele'],
  },
];
